### ISSUE TITLE
Doc - outdated from sparknlp.eval import *

### ISSUE THREAD

**Issue by jdobes-cz** [JohnSnowLabs/spark-nlp#1009]
On https://nlp.johnsnowlabs.com/docs/en/evaluation there is statement 
from sparknlp.eval import *
It is outdated (module sparknlp.eval does not exists). Should be updated.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version:
* Apache NLP version:
* Java version (java -version):
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
The `eval` module is under licensed products.
