### ISSUE TITLE
Will Sparknlp Supports Universal Sentence Encoder v4?

### ISSUE THREAD

**Issue by yx1201** [JohnSnowLabs/spark-nlp#1010]
I noticed that TensorFlow Hub released Universal Sentence Encoder v4. Will Sparknlp support the new version in the nearest future?

**Comment by maziyarpanahi** [comment]
Unfortunately, after V3 those are only for TF 2.x and may not work properly on TF 1.x like ours (1.15.0). That's being said, we'll try but there aren't any fixes that change the results of the predictions. They are mostly for those who fin-tune which it happens outside Spark NLP.

**Comment by yx1201** [comment]
Thanks!
