### ISSUE TITLE
Add portuguese-bert models to BertEmbeddings and BertSentenceEmbeddings

### ISSUE THREAD

**Issue by maziyarpanahi** [JohnSnowLabs/spark-nlp#1026]
https://github.com/neuralmind-ai/portuguese-bert

**Comment by rafaelsandroni** [comment]
Hi! I'm high interested in this feature, how can I contribute?

**Comment by samvygupta** [comment]
I will be highly interested in this notebook. (#904). Please let me know if I can provide any inputs.
I tried to find loadSavedModel in Bert Embeddings annotator https://nlp.johnsnowlabs.com/docs/en/annotators but no luck.

**Comment by maziyarpanahi** [comment]
Here is the [notebook](https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/training/portuguese/Export_BERT_model_to_Spark_NLP_BertEmbeddings.ipynb)

@rafaelsandroni @samvygupta Could you please take a look and see if it's being exported correctly? We normally do TF Hub models, the code, and the first tests looked fine but I appreciate your inputs.
