### ISSUE TITLE
 An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.

### ISSUE THREAD

**Issue by Prasannasai3698** [JohnSnowLabs/spark-nlp#1027]
explain_document_dl download started this may take some time.

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-3-7c534aa46310> in <module>
     19 
     20 # Download a pre-trained pipeline
---> 21 pipeline = PretrainedPipeline('explain_document_dl', lang='en')

~\Anaconda3\lib\site-packages\sparknlp\pretrained.py in __init__(self, name, lang, remote_loc, parse_embeddings, disk_location)
     89     def __init__(self, name, lang='en', remote_loc=None, parse_embeddings=False, disk_location=None):
     90         if not disk_location:
---> 91             self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
     92         else:
     93             self.model = PipelineModel.load(disk_location)

~\Anaconda3\lib\site-packages\sparknlp\pretrained.py in downloadPipeline(name, language, remote_loc)
     49     def downloadPipeline(name, language, remote_loc=None):
     50         print(name + " download started this may take some time.")
---> 51         file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
     52         if file_size == "-1":
     53             print("Can not find the model to download please check the name!")

~\Anaconda3\lib\site-packages\sparknlp\internal.py in __init__(self, name, language, remote_loc)
    189 class _GetResourceSize(ExtendedJavaWrapper):
    190     def __init__(self, name, language, remote_loc):
--> 191         super(_GetResourceSize, self).__init__(
    192             "com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize", name, language, remote_loc)
    193 

~\Anaconda3\lib\site-packages\sparknlp\internal.py in __init__(self, java_obj, *args)
    127         super(ExtendedJavaWrapper, self).__init__(java_obj)
    128         self.sc = SparkContext._active_spark_context
--> 129         self._java_obj = self.new_java_obj(java_obj, *args)
    130         self.java_obj = self._java_obj
    131 

~\Anaconda3\lib\site-packages\sparknlp\internal.py in new_java_obj(self, java_class, *args)
    137 
    138     def new_java_obj(self, java_class, *args):
--> 139         return self._new_java_obj(java_class, *args)
    140 
    141     def new_java_array(self, pylist, java_class):

~\Anaconda3\lib\site-packages\pyspark\ml\wrapper.py in _new_java_obj(java_class, *args)
     67             java_obj = getattr(java_obj, name)
     68         java_args = [_py2java(sc, arg) for arg in args]
---> 69         return java_obj(*java_args)
     70 
     71     @staticmethod

~\Anaconda3\lib\site-packages\py4j\java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

~\Anaconda3\lib\site-packages\pyspark\sql\utils.py in deco(*a, **kw)
    129     def deco(*a, **kw):
    130         try:
--> 131             return f(*a, **kw)
    132         except py4j.protocol.Py4JJavaError as e:
    133             converted = convert_exception(e.java_exception)

~\Anaconda3\lib\site-packages\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoClassDefFoundError: org/apache/spark/ml/util/MLReadable$class
	at com.johnsnowlabs.nlp.DocumentAssembler$.<init>(DocumentAssembler.scala:178)
	at com.johnsnowlabs.nlp.DocumentAssembler$.<clinit>(DocumentAssembler.scala)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.<init>(ResourceDownloader.scala:431)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.<clinit>(ResourceDownloader.scala)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.ml.util.MLReadable$class
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

**Comment by Prasannasai3698** [comment]
code:

# Import Spark NLP
from sparknlp.base import *
from sparknlp.annotator import *
from pyspark.sql import SparkSession

from sparknlp.pretrained import PretrainedPipeline
import sparknlp

# Start Spark Session with Spark NLP
spark = SparkSession.builder \
    .appName("Spark NLP")\
    .master("local[4]")\
    .config("spark.driver.memory","16G")\
    .config("spark.driver.maxResultSize", "2G") \
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.5.5")\
    .config("spark.kryoserializer.buffer.max", "1000M")\
    .getOrCreate()
spark

**Comment by maziyarpanahi** [comment]
Could you please complete the template as well?

**Comment by Prasannasai3698** [comment]
Description- started server using below code

from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .appName("Spark NLP")\
    .master("local[4]")\
    .config("spark.driver.memory","16G")\
    .config("spark.driver.maxResultSize", "2G") \
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.5.5")\
    .config("spark.kryoserializer.buffer.max", "1000M")\
    .getOrCreate()
spark

from the below line I f=got module Not Found Error
from com.johnsnowlabs.nlp.pretrained.pipeline.en import BasicPipeline as bp

ModuleNotFoundError: No module named 'com.johnsnowlabs.nlp.pretrained.pipeline'; 'com.johnsnowlabs.nlp.pretrained' is not a package

**My Environment**
Windows
spark-nlp==2.6.0

**Comment by maziyarpanahi** [comment]
I am sorry I cannot follow the actual error and the actual code. One says no module exist one says cannot find the model. Could you please follow the template, step by step with the full code and full error? I need the full code cause I see imports we never mentioned anywhere. And actual steps as you say 2.6.0 but I see you are using packages from 2.5.5, the template helps us to narrow down the issue especially on Windows.

PS: you are on Windows and Apache Spark on Windows requires these steps, please make sure you follow them: https://github.com/JohnSnowLabs/spark-nlp/issues/1022

**Comment by Prasannasai3698** [comment]
**I'm following steps as in :  ([(https://github.com/kennycontreras/Jupyter-Notebooks/blob/master/NLP_Analytics.ipynb)])**

With the below code, I got error
In [33]:

# As we can see, our aproache is not working very well... That's why we are going to use a library 
## called NLP (Natural Languague Processing) who recognize every single word ans classified like nouns, pronouns, verbs, etc.

from com.johnsnowlabs.nlp.pretrained.pipeline.en import BasicPipeline as bp

dfAnnotated = bp.annotate(df, 'Comment')

As you said above I have all the steps to setup environment variables and still I'm getting the same error.

**---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-020cf56bc8f0> in <module>
      1 #NLP
      2 
----> 3 from com.johnsnowlabs.nlp.pretrained.pipeline.en import BasicPipeline as bp
      4 
      5 dfAnnotated = bp.annotate(df, 'Logs')

ModuleNotFoundError: No module named 'com.johnsnowlabs.nlp.pretrained.pipeline'; 'com.johnsnowlabs.nlp.pretrained' is not a package**

**Comment by maziyarpanahi** [comment]
You can see that example was for 1.8.2 release which means it's at least more than 2 years old. 
Please follow our instructions in the README for installations and our examples. (There is no such thing as BasicPipeline)

PS: i am closing this issue as you are using a very old code on a very mew release, but please next time respect the template to save us time or it will be ignored.
