### ISSUE TITLE
Road Map for Other Languages

### ISSUE THREAD

**Issue by toddleo** [JohnSnowLabs/spark-nlp#103]
Hi,

I understand it's non-trivial work, but, still wonder if other languages (say, Chinese) are already on your road map. Or is the model plug-able so that developers can easily attach Chinese models in spark-nlp?

---
BR,
Todd

**Comment by saifjsl** [comment]
Hi @toddleo thanks for you interest in the library.

Currently the library works as language-agnostic for occidental languages only. There is no other language support plans in the short term, but we are willing to accept contributions or help to get it prioritized further.
