### ISSUE TITLE
Request to provide a brief description, purpose , assumptions and usage example for the pretrained models

### ISSUE THREAD

**Issue by kaniska** [JohnSnowLabs/spark-nlp#1048]
**Link to doc page in question (if any):**

https://github.com/JohnSnowLabs/spark-nlp-models

**Name of the Spark NLP feature whose docs need improvement:**

pretrained models

**What you think the docs should say:**

Currently the documentation specifies the names of the model e.g. electra_xyz, biobert_xyz elmo , albert_xyz, xlnet_xyz, multiclassifierd_xyz etc.

It would be great if the documentation also provides a brief description (**What**) , purpose (**Why**) , usage domain (**Where**) and sample code using model output attributes (**How**) along with the implicit **assumptions**, requirements (if any) and tuning params - for each type of the model.

**Comment by maziyarpanahi** [comment]
Hi,

We are developing a Model Hub which comes with all this information. We will announce it once it's done and we will deprecate the use of one long-page markdown as it is really hard to manage 330+ models/pipelines.

**Comment by maziyarpanahi** [comment]
Forgot to leave a link, we are slowly updating it and adding more models/pipelines: https://nlp.johnsnowlabs.com/models

**Comment by kaniska** [comment]
Thanks so much for offering this amazing set of models 👍 👍 👍

**Comment by maziyarpanahi** [comment]
It is under development, so please do share your feedback or if you think something is missing so we can add them while we continue adding more models/pipelines.

**Comment by maziyarpanahi** [comment]
I think the Models Hub is in a good shape in terms of example, demo, results, code, benchmarks, etc.
https://nlp.johnsnowlabs.com/models
