### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.rocksdb.LRUCache.newLRUCache(JIZD)J when trying to do NER using NerCrf 

### ISSUE THREAD

**Issue by eoinlane** [JohnSnowLabs/spark-nlp#105]
Issue with NER in version 1.4

## Description
I am using a Databricks notebook to run the latest version of Spark NLP and trying to do NER using NerCrf. I get an error below and this takes a long time to run.

## Expected Behavior
I get the following error when i run the NerCrf

java.lang.UnsatisfiedLinkError: org.rocksdb.LRUCache.newLRUCache(JIZD)J
	at org.rocksdb.LRUCache.newLRUCache(Native Method)
	at org.rocksdb.LRUCache.<init>(LRUCache.java:74)
	at org.rocksdb.LRUCache.<init>(LRUCache.java:19)
	at com.johnsnowlabs.nlp.embeddings.WordEmbeddings.<init>(WordEmbeddings.scala:13)
	at com.johnsnowlabs.nlp.embeddings.ApproachWithWordEmbeddings.beforeTraining(ApproachWithWordEmbeddings.scala:55)
	at com.johnsnowlabs.nlp.AnnotatorApproach.fit(AnnotatorApproach.scala:32)

## Possible Solution
I believe the wrong version of rocksdb is packaged with Spark NLP
## Steps to Reproduce

1. I am using a Databricks Notebook and latest Spark runtime 3.4 (includes Apache Spark 2.2.0, Scala 2.11)
2. I have installed Spark NLP 1.4 from Maven 
3. Here is the link to the Databricks Notebook that shows the error

https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/5276288487867556/871609068453572/3684151997220649/latest.html

**Comment by aleksei-ai** [comment]
@eoinlane It seems that RocksDB 5.2.1 is already used by DataBricks https://docs.databricks.com/release-notes/runtime/3.3.html

Probably shading we can do shading or release special version for DataBricks

**Comment by eoinlane** [comment]
Thanks aleksei-ai, a release special version for DataBricks would be great.

**Comment by albertoandreottiATgmail** [comment]
hi @eoinlane, until a special release for Databricks comes along, you can use the following image to create your cluster in Databricks platform,
Spark 2.1 (Auto-updating, Scala2.11)

I tried that image and was able to run your code without problems.

**Comment by albertoandreottiATgmail** [comment]
I created a jar that uses older 5.2.1 rocksdb library, that will enable the use of the latest 3.5 Databricks images, take a look here,
https://drive.google.com/open?id=1WwNDDjPXBo3LDxYtbsADscwnDFLXKkNv

@saifjsl, @aleksei-ai, A PR for this can be found ([here](https://github.com/JohnSnowLabs/spark-nlp/pull/109)).

**Comment by eoinlane** [comment]
I can confirm that both of those options are working and look forward to a supported Databricks release going forward. Thanks for all your help.

**Comment by saifjsl** [comment]
Going with this downgrade fix for now https://github.com/JohnSnowLabs/spark-nlp/pull/109
We should consider longer term solution though.
