### ISSUE TITLE
Unable to load `t5_grammar_error_corrector`

### ISSUE THREAD

**Issue by gadde5300** [JohnSnowLabs/spark-nlp#10561]
Unable to load `t5_grammar_error_corrector` model.
## Current Behavior

While downloading the model it throws an `IllegalArgumentException` error.
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version `sparknlp.version()`: `4.0.1`
* Apache NLP version `spark.version`: `3.3.0`
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.): colab
* Operating System and version:
* Link to your project (if any): https://colab.research.google.com/drive/1ZEf3BubOX-f-4YKI-CupzFBBtDZ57bZO?usp=sharing

**Comment by maziyarpanahi** [comment]
Following up here: https://github.com/JohnSnowLabs/spark-nlp/issues/13155
