### ISSUE TITLE
SentenceDetector() not working

### ISSUE THREAD

**Issue by kkotarac** [JohnSnowLabs/spark-nlp#10581]
I am not able to use SentenceDetector() as a part of a pipeline.
## Description

Yesterday my code was working but today I keep getting error:
java.util.NoSuchElementException: Param customBoundsStrategy does not exist.

If I remove the SentenceDetector step from my pipeline everything is ok.

## Expected Behavior

Earlier everything was working as it should.
## Steps to Reproduce

Example from nlp.johnsnowlabs.com results with the same error https://nlp.johnsnowlabs.com/api/python/reference/autosummary/sparknlp/annotator/embeddings/universal_sentence_encoder/index.html#sparknlp.annotator.embeddings.universal_sentence_encoder.UniversalSentenceEncoder

```
import sparknlp
from sparknlp.base import *
from sparknlp.annotator import *
from pyspark.ml import Pipeline
documentAssembler = DocumentAssembler() \
    .setInputCol("text") \
    .setOutputCol("document")
sentence = SentenceDetector() \
    .setInputCols(["document"]) \
    .setOutputCol("sentence")
embeddings = UniversalSentenceEncoder.pretrained() \
    .setInputCols(["sentence"]) \
    .setOutputCol("sentence_embeddings")
embeddingsFinisher = EmbeddingsFinisher() \
    .setInputCols(["sentence_embeddings"]) \
    .setOutputCols("finished_embeddings") \
    .setOutputAsVector(True) \
    .setCleanAnnotations(False)
pipeline = Pipeline() \
    .setStages([
      documentAssembler,
      sentence,
      embeddings,
      embeddingsFinisher
    ])
data = spark.createDataFrame([["This is a sentence."]]).toDF("text")
result = pipeline.fit(data).transform(data)
result.selectExpr("explode(finished_embeddings) as result").show(5, 80)
```

## Your Environment

*  `sparknlp.version()`: 4.0.2
* `spark.version`: 3.2.1

**Comment by maziyarpanahi** [comment]
Please make sure both `spark-nlp` PyPI and the `spark-nlp` Maven package are `4.0.2`. (this indicates your PyPI version is 4.0.2 but the Maven package inside your SparkSession is not 4.0.2)

`pip install --upgrade spark-nlp==4.0.2`
`com.johnsnowlabs.nlp:spark-nlp_2.12:4.0.2`

**Comment by kkotarac** [comment]
Upgrading the `spark-nlp` Maven package to version 4.0.2 solved my problem. 
Thank you and best regards,
Karlo
