### ISSUE TITLE
Not sure if this is intended behaviour of the SentenceEmbeddings Annotator

### ISSUE THREAD

**Issue by M4lF3s** [JohnSnowLabs/spark-nlp#1063]
## Description

I was using the SentenceEmbeddings Annotator to get an Embedding for each Sentence (based on the set Pooling-Strategy). But what I noticed was, that after that Pipeline-Step every Sentence had the same Embedding-Vector. 

## Expected Behavior

I would expect that the SentenceEmbeddings Annotator actually assigns only the respective Sentence-Embedding-Vector to each Sentence

## Current Behavior

The SentenceEmbeddings Annotator actually calculates the Embeddings for each Sentence (as expected) but then concatenates these Vectors and assigns that concatenated Vector to all Sentences. But as the Title says I´m not sure if this is actually intended behaviour? I had a look at the Unit-Tests and those are also not really clarifying this.

## Possible Solution

[Here](https://gist.github.com/M4lF3s/7ba26be8b0225a40e7bb9b01f20f83e0#file-sentenceembeddings-scala) is a gist for the `annotate()` method for the SentenceEmbeddings Annotator that actually returns the Embeddings as I would expect them

## Steps to Reproduce

I created a Repo containing a [Unit-Test](https://github.com/M4lF3s/spark-nlp-sentence-embeddings/blob/master/src/test/scala/EmbeddingPipelineSpec.scala) that illustrates the issue I have

Basically for the following Document 

> It was the White Rabbit, trotting slowly back again. Oh my dear paws! Oh my fur and whiskers!

and the [pre-trained BERT Model (v2.4)](https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/models/bert_base_uncased_en_2.4.0_2.4_1580579889322.zip)

I was getting these feature-Vectors using the SentenceEmbeddings Annotator with [this Pipeline](https://github.com/M4lF3s/spark-nlp-sentence-embeddings/blob/master/src/main/scala/PipelineWithSentenceEmbeddingsAnnotator.scala):

```
+--------------------+
|            features|
+--------------------+
|[-0.2708099186420...|
|[-0.2708099186420...|
|[-0.2708099186420...|
+--------------------+
```

But I expected these(Using the exploded Sentences from SentenceDetector and averaging the Word-Embeddings manually with [this Pipeline](https://github.com/M4lF3s/spark-nlp-sentence-embeddings/blob/master/src/main/scala/PipelineWithExplodedSentences.scala)):
```
+--------------------+
|            features|
+--------------------+
|[-0.2708099186420...|
|[0.32363849878311...|
|[0.33493545651435...|
+--------------------+
```

(see my Repo for non-truncated output)

Sorry, I hope it´s clear what my Problem is :sweat_smile: (sometimes it´s hard to explain such issues)
Would be nice to get some Feedback if this is actually intended behaviour or not (since I´m using this for my thesis) :blush:

## Your Environment

* Spark NLP version: 2.5.5
* Apache NLP version: 2.4.6
* Java version (java -version): 1.8.0_252
* SBT version: 1.3.13
* Setup and installation (Pypi, Conda, Maven, etc.): SBT using IntelliJ
* Operating System and version: OpenSUSE Tumbleweed
* Link to your project (if any): https://github.com/M4lF3s/spark-nlp-sentence-embeddings

**Comment by maziyarpanahi** [comment]
Many thanks @M4lF3s 

The intention behind SentenceEmbeddings is to get to vectors for each token and average them into 1 vector. The boundary for those tokens is based on the inputCols for Tokenizer, BertEmbeddings (in your case), and SentenceEmbeddings. Having the same vector for all the sentences in the same document is definitely not the intention. 

Could you please share your code so I can reproduce this, this might be a mismatch between inputCols or a param somewhere set in SentenceDetector, but I would like to be sure and fix it if it's a bug. 


PS: Just as an FYI for BERT models, there is a new annotator called BertSentenceEmbeddings released in 2.6.x with its own set of models that generates Sentence Embeddings similar to UniversalSentenceEncoder. https://github.com/JohnSnowLabs/spark-nlp-models#embeddings

**Comment by M4lF3s** [comment]
Thanks for the quick reply :) maybe you want to also check out my [gist](https://gist.github.com/M4lF3s/7ba26be8b0225a40e7bb9b01f20f83e0#file-sentenceembeddings-scala), which would actually fix the annotation (I think)

I will also definitely check out the new Annotator, many thanks for the hint :+1:

**Comment by maziyarpanahi** [comment]
Yes, I did, we don't have to explode inside the annotate, I am sure we missed something inside `calculateSentenceEmbeddings` and consider everything as Document instead of Sentence. I'll debug this soon and get back to you.
