### ISSUE TITLE
BERT fine tuning in spark NLP

### ISSUE THREAD

**Issue by NeverInAsh** [JohnSnowLabs/spark-nlp#1068]
**Is your feature request related to a problem? Please describe.**
I see that sparkNLP has pre-trained BERT, elmo embeddings but I haven't been able to figure out if there's a way to fine tune the embeddings.

I see there are downstream tasks, but I'm not sure if the BERT embeddings are just extracted and then plugged into these new downstream tasks, or if the downstream tasks are built on top of the transformer architecture for BERT (therefore allowing us to fine-tune the embeddings).

Can someone explain this, and also if it's possible to fine-tune how can I extract the new weights after training on down stream tasks. Thank you.

**Describe the solution you'd like**
With the NERDL can there be a parameter available to allow training of the underlying language model ? and also the freedom to freeze and unfreeze certain layers.

**Describe alternatives you've considered**

**Additional context**
Originally posted on SO.

**Comment by maziyarpanahi** [comment]
Hi,

All the embeddings models are pretrained and won't be fine-tuned separately or in any other downstream. Maybe in future, we provide another annotator just or BERT to be fine-tuned based on a specific task but today this part happens outside of Spark NLP. 
Once you fine-tune your BERT model or trained it from scratch, you can use this notebook to import it to Spark NLP for distributed prediction.

https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/training/portuguese/Export_BERT_model_to_Spark_NLP_BertEmbeddings.ipynb
