### ISSUE TITLE
Azure Synapse Notebook TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by jenghub** [JohnSnowLabs/spark-nlp#10720]
Trying to get Spark NLP to work in Azure Synapse notebook and having trouble loading the model jar packages for the pretrained pipelines. Spark NLP seems to start up fine but models can't be downloaded and/or loaded. Couldn't find many Synapse-specific installation instructions.

## Description
Developing in an Microsoft Azure Synapse workspace notebook and have installed Spark NLP as a pool dependency in environment.yaml (- spark-nlp==4.0.2)

## Current Behavior
```
pipeline = PretrainedPipeline('recognize_entities_dl', 'en')
result = pipeline.annotate('The Mona Lisa is a 16th century oil painting created by Leonardo')
print(result)
```
The download seems to start:
`recognize_entities_dl download started this may take some time.`

But then type error:
`TypeError: 'JavaPackage' object is not callable`

## Possible Solution

Does it have something to do with pyspark initialization, similar to:
[https://stackoverflow.com/questions/65713299/javapackage-object-is-not-callable-error-executing-explain-in-pyspark-3-0](https://stackoverflow.com/questions/65713299/javapackage-object-is-not-callable-error-executing-explain-in-pyspark-3-0)

## Steps to Reproduce

1. 
```
sc = spark.sparkContext

spark = SparkSession.builder.appName(f"App Name {mssparkutils.runtime.context}")\
                            .master("local[*]")\
                            .config("spark.driver.memory","16G")\
                            .config("spark.driver.maxResultSize", "0") \
                            .config("spark.kryoserializer.buffer.max", "2000M")\
                            .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.12:4.0.2")\
                            .getOrCreate()
```

Have also tried:

```
spark= sparknlp.start()
```
2. 
```
pipeline = PretrainedPipeline('recognize_entities_dl', 'en')
result = pipeline.annotate('The Mona Lisa is a 16th century oil painting created by Leonardo')
print(result)
```
3.
`recognize_entities_dl download started this may take some time.`
`TypeError: 'JavaPackage' object is not callable`

## Your Environment

* Spark NLP version `sparknlp.version()`: 4.0.2
* Apache NLP version `spark.version`: 3.1.2.5.0-66290225
* Java version `java -version`: 1.8.0_282
* Setup and installation (Pypi, Conda, Maven, etc.): Pypi

**Comment by jenghub** [comment]
I have also tried downloading the fat jar file offline and downloaded pre-trained model from path:

```
...
.config("spark.jars", "https://minteddataqetde.blob.core.windows.net/synapse/jars/spark-nlp-assembly-4.0.2.jar")\
...
```
```
pipeline = PipelineModel.load("https://path/explain_document_ml_en_4.0.0_3.0_1656066222624/")
```

This raises:
```
# Hide where the exception came from that shows a non-Pythonic
# JVM exception message.
IllegalArgumentException: Invalid start or len parameter`
```

**Comment by maziyarpanahi** [comment]
Hi @jenghub 

Yes, that error means you have the PyPI package installed so you have access to the Python APIs, but the actual core/logic of the software (either a Maven package or a fat JAR) is missing from the SparkSession.

Azure synapse is like Databricks/EMR/Zeppelin, it comes with an already created SparkSession. Your first line `sc = spark.sparkContext` is the evidence of that. Unfortunately, once the SparkSession is created you cannot add/remove any `spark.jars` or `spark.jars.packages` from that session.

That is why you have configurations like this in those platforms: https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-manage-session-packages#session-scoped-java-or-scala-packages
So you can say what needs to be downloaded/installed for both Python and Scala/Java and included in the SparkSession when it is created for the first time.

PS: You cannot use `HTTP(s)` when you are using `.load()`. This native Spark ML function only supports `file:///` for local setup and `hdfs, dbfs, and s3` for clusters. So you can use `%%configure` before the session is created to include either the `spark.jars` or `spark.jars.packages` and install the `spark-nlp` PyPI package on all the machines. (I think it has a place to do that inside manage dependencies)

**Comment by jenghub** [comment]
Amazing, loading the offline jar in a %%config block did the trick. Thanks so much! BTW it looks like I can mix and match loading a fat jar file offline and also downloading a model pipeline from the web? 
`pipeline = PretrainedPipeline('recognize_entities_dl', 'en')` seemed to work just fine even when I initialized using the offline jar file.

**Comment by maziyarpanahi** [comment]
Glad to hear that. Having the library installed offline (via Wheel file for PyPI and Fat JAR for Maven) is different than having the models/pipelines offline. You can have one without the other, or you can have them both offline to achieve a 100% offline solution which is required in sensitive environments like Healthcare: https://github.com/JohnSnowLabs/spark-nlp#offline

If you want to share your steps to make Spark NLP work on Azure Synapse I can add it to the docs like the others.

**Comment by jenghub** [comment]
Here are the main steps for Microsoft's Azure Synapse. (Feel free to adapt this as needed to your readme):

1. Specify the PyPi installation in the pool level .yml configuration file:
<img width="1135" alt="install pool dependency" src="https://user-images.githubusercontent.com/63479299/181068071-1a877b31-6cb1-4e64-b25c-3f676ec3c3fb.png">

2. At the top of your notebook, specify a config block that includes a spark.jars key pointing to the jar file. In the below example I have downloaded the fat jar file and stored it in Azure Blob Storage account linked to the Synapse workspace for offline access:

```
%%configure -f
{
"conf": {
      "spark.jars": "abfss://synapse@path/spark-nlp-assembly-4.0.2.jar",
   }
}
```

Skip session initialization methods such as:
```
sparknlp.start()
```
or
```
spark = SparkSession.builder.appName().config()...
```

See here for more details: [https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-manage-session-packages#session-scoped-java-or-scala-packages](https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-manage-session-packages#session-scoped-java-or-scala-packages)
