### ISSUE TITLE
Pretrained Models fail to load when running Spark on Kubernetes

### ISSUE THREAD

**Issue by clayms** [JohnSnowLabs/spark-nlp#10755]
## Description

I am running Spark on Kubernetes as implemented by Dataiku.  For Spark to work, Dataiku needs the Spark driver to run from the same cloud instance Dataiku is installed. The workers are spun up in the attached Kubernetes cluster.  

When I download a pretrained model, SparkNLP puts the model in a `cache_pretrained` folder on the driver, but then the executors don't have access to that folder. 

```
java.io.FileNotFoundException: File 
file:/home/dssuser/cache_pretrained/spellcheck_dl_en_3.4.1_3.0_1648457196011/metadata/part-00000
```
I can check that folder on the driver, and it is there.

## Expected Behavior

For Spark run on Kubernetes where the driver is not in the same Kubernetes cluster, Models should download to a location that all the executors have access to.

## Current Behavior

Models download to a location that only the driver has access to.

## Possible Solution

The ability to set a flag that indicates this type of set up (Spark run on Kubernetes where the driver is not in the same Kubernetes cluster), which will have the pretrained models download directly to an Object Store (blob, S3) that all the executors have access to.

## Steps to Reproduce

1. run Spark on Kubernetes where the driver is not in the same Kubernetes cluster
2. download and use pretrained models 

## Your Environment

* Spark NLP version `sparknlp.version()`: 4.0.2
* Apache NLP version `spark.version`: 3.2.1
* Java version `java -version`:  openjdk version "1.8.0_332"
* Setup and installation (Pypi, Conda, Maven, etc.): Pypi, Maven
* Operating System and version:  CentOS-7 (driver and Kubernetes containers)

**Comment by maziyarpanahi** [comment]
Suppose your Apache Spark is in a cluster mode (client or cluster), meaning the Driver and Executors are on different machines. In that case, the models/pipelines will be downloaded automatically on a configured distributed file system. (EMR will be S3, Databricks will be DBFS, Cloudera/YARN will be HDFS, no extra config or code, it will just automatically do it)

The issue with k8 is that most of them don't have any distributed file system configured for Apache Spark. They are mostly used to just pull/push data from/to. In any case, the models/pipelines must be downloaded/extracted/loaded on a shared file system that all the machines (driver/executors) have access to, or else it won't work.

You can set that address here if the automatic home_directory detection doesn't work: https://github.com/JohnSnowLabs/spark-nlp#spark-nlp-configuration

**Comment by clayms** [comment]
@maziyarpanahi Thanks, sounds like you are getting sick of answering this question.  It would be best to put some warnings in several places scattered throughout the documentation.  Including fixes, and which models can still work and which cannot.

I created my sparkSession as follows:
```python
spark = ( SparkSession.builder.appName("spark nlp")
    .config("spark.jars.packages",  "com.johnsnowlabs.nlp:spark-nlp-spark32_2.12:3.4.4")
    .config("spark.jsl.settings.pretrained.cache_folder","s3://my-bucket/spark-nlp/cache_pretrained")
    .config("spark.jsl.settings.aws.credentials.access_key_id", AWS_KEY)
    .config("spark.jsl.settings.aws.credentials.secret_access_key", AWS_SECRET_KEY)
    .getOrCreate()
)
```

However, when running the code below:

```python
checker = NorvigSweetingModel.pretrained().setInputCols(['token']).setOutputCol('checked')
```
I get the same error as posted in https://github.com/JohnSnowLabs/spark-nlp/issues/8079#issue-1213491341 :

```
An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.:
 java.lang.ExceptionInInitializerError at 
com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$
.$anonfun$getDownloadSize$1(ResourceDownloader.scala:713)
...
Caused by: java.lang.IllegalArgumentException: Wrong FS: s3://my-bucket/spark_nlp/cache_pretrained, expected: file:///
```
##

So, the `NorvigSweetingModel` also cannot be used when the model is saved in S3?

I agree with @salil-at 's comment https://github.com/JohnSnowLabs/spark-nlp/issues/8079#issuecomment-1108290971 
> Is there a list I can refer that suggests which models/pipelines can work with s3?

**Comment by maziyarpanahi** [comment]
> @maziyarpanahi Thanks, sounds like you are getting sick of answering this question. It would be best to put some warnings in several places scattered throughout the documentation. Including fixes, and which models can still work and which cannot.

Not really, we don't have that many users using Kubernetes, even though the issues may sound the same but when it comes to k8 they are harder to debug since other low lever setups are involved. (even S3 support on K8 is not the same as the EMR or Databricks when the services are managed)

S3 support:

All the models and pipelines work without any issue on HDFS, DBFS, and S3. The issue here is when a user adds another layer of complexity which is outside our skills scope.  The k8 cluster and storage (PV, PVC, Spark pods, etc.) are not something we can support here, we expect users know what they are doing when it comes to K8.

Solution: 

I would recommend asking the admin of your K8 (or the support) to setup the driver/executor volumes correctly, have upload fs also setup correctly, etc. (these all can be pointed to your S3 and Spark NLP will detect them automatically)

**Comment by maziyarpanahi** [comment]
@danilojsl (just in case `cache_folder` doesn't support S3 or it requires more config for auth)

**Comment by maziyarpanahi** [comment]
FYI: https://github.com/JohnSnowLabs/spark-nlp/issues/10786

**Comment by clayms** [comment]
@maziyarpanahi 
Can  the NorvigSweetingModel.pretrained()  model even be downloaded?
