### ISSUE TITLE
Starting a SparkSession for spark-nlp

### ISSUE THREAD

**Issue by clayms** [JohnSnowLabs/spark-nlp#10752]
Starting a SparkSession for spark-nlp

https://nlp.johnsnowlabs.com/docs/en/install#start-spark-nlp-session-from-python

The existing documentation says:
> If you need to manually start SparkSession because you have other configurations and `sparknlp.start()` is not including them, you can manually start the SparkSession:

However, what if I need to specify other parameters in `sparknlp.start`, 
e.g. `spark = sparknlp.start("cache_folder"="/home/user1/nlp_cache/")`

How do I add that to my typical pyspark SparkSession builder statement: `spark.local.dir` ?

Something like:

```python
SparkSession.builder \
    .appName("Spark NLP")\
    .config("spark.local.dir", "/home/user1/nlp_cache/")
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.12:4.0.2")\
    .getOrCreate()
```

What other parameters are available for `sparknlp.start()` ?

**Comment by maziyarpanahi** [comment]
https://github.com/JohnSnowLabs/spark-nlp#spark-nlp-configuration
