### ISSUE TITLE
How to I save BERTEmbeddings to local file.

### ISSUE THREAD

**Issue by Harish202** [JohnSnowLabs/spark-nlp#1077]
While loading Bert Embeddings as below

bert = BertEmbeddings.pretrained('bert_base_cased', 'en') \
 .setInputCols(["sentence",'token'])\
 .setOutputCol("bert")\
 .setCaseSensitive(False)\
 .setPoolingLayer(-2)

For some reason cased is taking forever to load and where as uncased is loading in few minutes. I am wondering if once loaded is there a way to save these embeddings into local file. So that I need not re download it every time. Appreciate your help.

**Comment by maziyarpanahi** [comment]
Hi,
Please complete the template and details about your machine/env. in order for us to help. (once a model/pipeline downloaded it never downloads it again unless there is a newer version)

**Comment by Harish202** [comment]
Oh so once download is done it will not download again!! I was thinking it is downloading every time I run the code:

bert = BertEmbeddings.pretrained('bert_base_cased', 'en')
.setInputCols(["sentence",'token'])
.setOutputCol("bert")
.setCaseSensitive(False)
.setPoolingLayer(-2)

Perhaps that is the reason bert_base_uncased is loading quickly as I have already used it many times before(already downloaded). This is the first time I am downloading bert_base_cased hence may be taking more time. Now it makes sense. Thanks a lot for your input. Closing the ticket.

**Comment by maziyarpanahi** [comment]
@Harish202 
Yes, you are correct. It will always download all the pretrained models/pipelines inside your `~/cache_pretrained` directory. (~ is usually HOME_DIRECTY)
If the model/pipeline exists, right after saying start downloading you see it changes to `done` and loading. (it skips the download)
