### ISSUE TITLE
SentenceDetector replaces "ö" with "?"

### ISSUE THREAD

**Issue by lorenz-nlp** [JohnSnowLabs/spark-nlp#108]
The SentenceDetector is applied on German texts. If an "ö" occurs, it is replaced by "?".  However, if other German special characters (such as ä,ü,ß) occur, the SentenceDetector performs as it should, and does not replace them by a question mark.

## Expected Behavior
The SentenceDetector should not change the text within its annotation.

## Current Behavior
The SentenceDetector replaces "ö" by "?".

## Steps to Reproduce
1. Run the test-case:
[sentenceDetector.txt](https://github.com/JohnSnowLabs/spark-nlp/files/1741113/sentenceDetector.txt)

2. Show the transformed dataframe:
[output.txt](https://github.com/JohnSnowLabs/spark-nlp/files/1741105/output.txt)
The token of question is the second one within the second row.

## Context
Subsequent annotators perform worse, for example a lemma cannot be found if the token was changed.

## Your Environment
* Version used: 1.4.0

**Comment by saifjsl** [comment]
I believe this was fixed in 1.4.0 after tokenizer became language agnostic. This is implicitly solved. Added test in PR to make sure this is so: https://github.com/JohnSnowLabs/spark-nlp/pull/165

**Comment by saifjsl** [comment]
Reopening issue. I just found by chance the mysterious reason for this issue, which implicitly caused other issues in some scenarios. Will be fixing in 1.5.5

**Comment by saifjsl** [comment]
Fixed in https://github.com/JohnSnowLabs/spark-nlp/pull/221
