### ISSUE TITLE
Input format examples in DateMatcher()

### ISSUE THREAD

**Issue by sofianeh** [JohnSnowLabs/spark-nlp#110]
Could you please include some examples of accepted input date formats that would be automatically detected by the DateMatcher? I have a corpus using multiple formats that are not detected, here are some examples:
```
06JAN2018
June 30, 2021
MAY 2018
```
Is it be possible to add our own custom input formats?

Also, it is not clear what are the accepted InputCols as well. Having tried Tokens and Sentences crashes the pipeline execution.

**Comment by saifjsl** [comment]
hi @sofianeh 

The datematcher says to require DOCUMENT type, meaning either DocumentAssembler's output or SentenceDetector's output. Tokens won't work but sentences should.

Regarding the supported formats, the unit test coverage checks on the following formats:

```
Array(
    ("1978-01-28", new Calendar.Builder().setDate(1978, 1-1, 28).build),
    ("1984/04/02", new Calendar.Builder().setDate(1984, 4-1, 2).build),
    ("1/02/1980", new Calendar.Builder().setDate(1980, 1-1, 2).build),
    ("2/28/79", new Calendar.Builder().setDate(1979, 2-1, 28).build),
    ("The 31st of April in the year 2008", new Calendar.Builder().setDate(2008, 4-1, 31).build),
    ("Fri, 21 Nov 1997", new Calendar.Builder().setDate(1997, 11-1, 21).build),
    ("Jan 21, '97", new Calendar.Builder().setDate(1997, 1-1, 21).build),
    ("Sun, Nov 21", new Calendar.Builder().setDate(currentYear, 11-1, 21).build),
    ("jan 1st", new Calendar.Builder().setDate(currentYear, 1-1, 1).build),
    //NS: "february twenty-eighth",
    ("next thursday", nextThursdayCalendar),
    ("last wednesday", lastWednesdayCalendar),
    ("today", Calendar.getInstance),
    ("tomorrow", tomorrowCalendar),
    ("yesterday", yesterdayCalendar),
    ("next week", nextCalendar(Calendar.WEEK_OF_MONTH)),
    ("next month", nextCalendar(Calendar.MONTH)),
    ("next year", nextCalendar(Calendar.YEAR)),
    //NS: "3 days from now",
    //NS: "three weeks ago",
    ("day after", tomorrowCalendar),
    ("the day before", yesterdayCalendar),
    //"the monday after",
    //"the monday before"
    //NS: "2 fridays before",
    //NS: "4 tuesdays after"
    ("0600h", setTimeTo(Calendar.getInstance, 6,0,0)),
    ("06:00 hours", setTimeTo(Calendar.getInstance, 6,0,0)),
    ("6pm", setTimeTo(Calendar.getInstance, 18,0,0)),
    ("5:30 a.m.", setTimeTo(Calendar.getInstance, 5,30,0)),
    ("at 5", setTimeTo(Calendar.getInstance, 17,0,0)),
    ("12:59", setTimeTo(Calendar.getInstance, 12,59,0)),
    ("23:59", setTimeTo(Calendar.getInstance, 23,59,0)),
    ("1988/11/23 6pm", setTimeTo(new Calendar.Builder().setDate(1988, 11-1, 23).build, 18, 0, 0)),
    ("next week at 7.30", setTimeTo(nextCalendar(Calendar.WEEK_OF_MONTH), 19, 0, 0)),
    ("5 am tomorrow", setTimeTo(tomorrowCalendar, 5, 0, 0))
  )
```

Anything outside these example's format is probably not covered. I am surprised 'June 30, 2021' doesn't work though, i'll take a look. The others don't appear on the list or any similar.

I will mark this as feature request for improvement, maybe add custom regular expressions or a completely new machine learning based date matcher. 

Thanks

**Comment by saifjsl** [comment]
Hello @Rachana-Baldania Thank you for trying out the DateMatcher!

Unfortunately, we're a small team and our current priorities are not on this annotator. You are more than welcome to debug it / fix it / make a new one and we are more than willing to help you in the process.

Feel free to join slack, we can discuss details over there.

Once I get free time I'll take a look at this one
