### ISSUE TITLE
Question: What [approach] annotators are trainable with user-provided datasets and how to train them?

### ISSUE THREAD

**Issue by ali-abz** [JohnSnowLabs/spark-nlp#1105]
Hi there.
I really like this project and I was wondering if I could somehow make this project available for Persian language. I don't know much about the whole project but I understand that some annotators (like NerDLApproach) can be trained on a user-provided dataset with proper format (like CoNLL).

So I was wondering:
1. Can I use a dataset with Persian/Arabic characters (and in proper format like CoNLL) to train an annotator like NerDLApproach?
2. Can I train **ANY** Approach annotator (like PerceptronApproach for POSTagger) on any user-provided dataset? In case of NerDLApproach, the documentation explicitly mention this is possible but for (most of) other annotators there is no information I could find. If it is possible, how can I know what is the proper training process?

And also, sorry if my questions are naive. I'm pretty new to NLP.

**Comment by maziyarpanahi** [comment]
Hi @ali-abz 

You are correct. Any annotator that has either `Approach` in their name or they are trainable can be trained by custom datasets (following the compatible format). 

In the case of NerDLApproach, as long as the dataset is in CoNLL2003 format you can train it on any dataset. The quality of the NER will eventually fall under whether it is domain-specific such as law, healthcare, etc. or the language. This will affect the transfer learning via the Embeddings. I would suggest using WordEmbeddings models such as `glove_100d` or even `glove_840B_300`. The list of all models is available here: https://github.com/JohnSnowLabs/spark-nlp-models

We do have some very good public courses for getting started with Spark NLP:
- https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/tutorials/1hr_workshop
- https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/tutorials/Certification_Trainings/Public

On a side note, the library can be more compatible with right-to-left languages such as Persian, Arabic, or Hebrew which we have on the roadmap especially for POS and Lemmatization. (in these two annotators, the delimiter will change the position of the `TOKEN_LABEL` like `VERB_هست` which we will fix it.
