### ISSUE TITLE
Access Denied error when opening SentenceDetectorDL download link

### ISSUE THREAD

**Issue by michaeltimblin** [JohnSnowLabs/spark-nlp#1106]
## Description

The download button on [this webpage](https://nlp.johnsnowlabs.com/2020/09/13/sentence_detector_dl_en.html) references [this url](https://s3.amazonaws.com/auxdata.johnsnowlabs.com/models/sentence_detector_dl_en_2.6.0_2.4_1600002888450.zip). An "Access Denied" error is returned when opening the link.

## Expected Behavior

The file should be publicly accessible, and no errors should be returned.

## Current Behavior

The link returns an error. I included an example error below.
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>40CE251A345C3887</RequestId>
<HostId>iy5P9NMTNm6Pl01jlDtJbwwgYBJHm1U44fz1G/b+YQQ4edvdTujJKDC4l+SKtcnC7dr00GJXxqM=</HostId>
</Error>
```

## Possible Solution

Most likely the file was replaced, and the download link just needs to be updated.

## Steps to Reproduce

1. Navigate to [this webpage](https://nlp.johnsnowlabs.com/2020/09/13/sentence_detector_dl_en.html)
2. Click the download button

## Context

I was just trying to download SentenceDetectorDLModel

## Your Environment

* Spark NLP version: N/A
* Apache NLP version: N/A
* Java version (java -version) N/A:
* Setup and installation (Pypi, Conda, Maven, etc.): N/A
* Operating System and version: N/A
* Link to your project (if any): N/A

**Comment by michaeltimblin** [comment]
The README in the spark-nlp-models repo [here](https://github.com/JohnSnowLabs/spark-nlp-models#english---models) includes a working [download link](https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/models/sentence_detector_dl_en_2.6.2_2.4_1600002888450.zip)

**Comment by maziyarpanahi** [comment]
Thanks @michaeltimblin 

It's been fixed.
