### ISSUE TITLE
 TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by breakcards** [JohnSnowLabs/spark-nlp#11215]
"TypeError: 'JavaPackage' object is not callable " error

Platform: Azure Databricks
Pyspark: 3.1.2
Java Version : 1.8.0_302 (Azul Systems, Inc.)
Scala Version: version 2.12.10
Python: version 3.8.10

Tried running the followings, but returned with the same "TypeError: 'JavaPackage' object is not callable " error. 
spark = SparkSession.builder \
    .appName("ner")\
    .master("local[4]")\
    .config("spark.driver.memory","16G")\
    .config("spark.driver.maxResultSize", "2G") \
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.5.2")\
    .config("spark.kryoserializer.buffer.max", "1000m")\
    .getOrCreate()

document_assembler = DocumentAssembler()\
    .setInputCol("text")\
    .setOutputCol("documents")

t5 = T5Transformer() \
    .pretrained(MODEL_NAME) \
    .setTask(task_prefix[TASK])\
    .setMaxOutputLength(200)\
    .setInputCols(["documents"]) \
    .setOutputCol("T5")

pipeline = Pipeline(stages=[document_assembler,t5])

****Here is the error**:**

TypeError                                 Traceback (most recent call last)
<command-901177939515733> in <module>
----> 1 document_assembler = DocumentAssembler()\
      2     .setInputCol("text")\
      3     .setOutputCol("documents")
      4 
      5 t5 = T5Transformer() \

/databricks/spark/python/pyspark/__init__.py in wrapper(self, *args, **kwargs)
    112             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    113         self._input_kwargs = kwargs
--> 114         return func(self, **kwargs)
    115     return wrapper
    116 

/local_disk0/.ephemeral_nfs/envs/pythonEnv-30cc6283-d040-48d5-aff1-a696d90c2867/lib/python3.8/site-packages/sparknlp/base/document_assembler.py in __init__(self)
     90     @keyword_only
     91     def __init__(self):
---> 92         super(DocumentAssembler, self).__init__(classname="com.johnsnowlabs.nlp.DocumentAssembler")
     93         self._setDefault(outputCol="document", cleanupMode='disabled')
     94 

/databricks/spark/python/pyspark/__init__.py in wrapper(self, *args, **kwargs)
    112             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    113         self._input_kwargs = kwargs
--> 114         return func(self, **kwargs)
    115     return wrapper
    116 

/local_disk0/.ephemeral_nfs/envs/pythonEnv-30cc6283-d040-48d5-aff1-a696d90c2867/lib/python3.8/site-packages/sparknlp/internal/annotator_transformer.py in __init__(self, classname)
     31         self.setParams(**kwargs)
     32         self.__class__._java_class_name = classname
---> 33         self._java_obj = self._new_java_obj(classname, self.uid)
     34 

/databricks/spark/python/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     64             java_obj = getattr(java_obj, name)
     65         java_args = [_py2java(sc, arg) for arg in args]
---> 66         return java_obj(*java_args)
     67 
     68     @staticmethod

TypeError: 'JavaPackage' object is not callable

**Comment by maziyarpanahi** [comment]
- you cannot create a SparkSession inside Databricks notebooks. They come with SparkSession once the cluster was created. Therefore, the spark-nlp package is not included
- spark-nlp 2.5 is deprecated and very old, it doesn't support Spark 3.x
- Pease follow these steps without missing any of them by using the latest release: https://github.com/JohnSnowLabs/spark-nlp#databricks-cluster
