### ISSUE TITLE
NerDLApproach outputs the logs for the first epoch and then no detailed logs (or no logs at all)

### ISSUE THREAD

**Issue by vkocaman** [JohnSnowLabs/spark-nlp#1133]
After 2.6.3 (introducing memoryOptimization), the loggings could only output the results for the first epoch. Sometimes we can only the logs for the first epoch and then summary logs for the following epochs. 

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version:
* Apache NLP version:
* Java version (java -version):
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by vkocaman** [comment]
The problem still exists.. I tried this with val split and it is fine.. so the problem is logging with test data that set in .setTestDataSet() param.

**Comment by albertoandreottiATgmail** [comment]
Hello @vkocaman , thanks for the additional info, will look into it.

**Comment by albertoandreottiATgmail** [comment]
@vkocaman , @maziyarpanahi please take a look here, and give it a try,

https://github.com/JohnSnowLabs/spark-nlp/pull/1146/files

**Comment by vkocaman** [comment]
thanks @albertoandreottiATgmail

**Comment by maziyarpanahi** [comment]
This should be fixed in the 2.7.0 release. 

```sh
pip install spark-nlp==2.7.0 --upgrade
```
