### ISSUE TITLE
Trying to download `ner_jsl_enriched` from the models hub on the browser but I get a 403

### ISSUE THREAD

**Issue by sreeprasannar** [JohnSnowLabs/spark-nlp#11530]
**Link to doc page in question (if any):**
https://nlp.johnsnowlabs.com/2021/10/22/ner_jsl_enriched_en.html

**Name of the Spark NLP feature whose docs need improvement:**
Downloading

**What you think the docs should say:**
How to download without getting a 403

**Comment by maziyarpanahi** [comment]
This is a licensed model, we only support open-source related issues here. (We don't have any knowledge of licensed products)

You can ask your questions on Slack (#healthcare channel)
