### ISSUE TITLE
An error in running spark nlp document Assembler...

### ISSUE THREAD

**Issue by lewisshkang** [JohnSnowLabs/spark-nlp#11531]
With sparknlp.version() 3.4.0 and spark version 3.1.3., I tried running document Assembler with the following and continued to see an error... Do you know what is the issue??

**I run below**
documentAssembler = DocumentAssembler().\
                    setInputCol("title").\
                    setOutputCol("document").\
                    setCleanupMode("shrink")     

Error:
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
Input In [28], in <cell line: 2>()
      1 # Defining document assembler
----> 2 documentAssembler = DocumentAssembler().\
      3                     setInputCol("title").\
      4                     setOutputCol("document").\
      5                     setCleanupMode("shrink")

File /usr/lib/spark/python/pyspark/__init__.py:114, in keyword_only.<locals>.wrapper(self, *args, **kwargs)
    112     raise TypeError("Method %s forces keyword arguments." % func.__name__)
    113 self._input_kwargs = kwargs
--> 114 return func(self, **kwargs)

File /opt/conda/miniconda3/lib/python3.8/site-packages/sparknlp/base.py:387, in DocumentAssembler.__init__(self)
    385 @keyword_only
    386 def __init__(self):
--> 387     super(DocumentAssembler, self).__init__(classname="com.johnsnowlabs.nlp.DocumentAssembler")
    388     self._setDefault(outputCol="document", cleanupMode='disabled')

File /usr/lib/spark/python/pyspark/__init__.py:114, in keyword_only.<locals>.wrapper(self, *args, **kwargs)
    112     raise TypeError("Method %s forces keyword arguments." % func.__name__)
    113 self._input_kwargs = kwargs
--> 114 return func(self, **kwargs)

File /opt/conda/miniconda3/lib/python3.8/site-packages/sparknlp/internal.py:107, in AnnotatorTransformer.__init__(self, classname)
    105 self.setParams(**kwargs)
    106 self.__class__._java_class_name = classname
--> 107 self._java_obj = self._new_java_obj(classname, self.uid)

File /usr/lib/spark/python/pyspark/ml/wrapper.py:66, in JavaWrapper._new_java_obj(java_class, *args)
     64     java_obj = getattr(java_obj, name)
     65 java_args = [_py2java(sc, arg) for arg in args]
---> 66 return java_obj(*java_args)

File /opt/conda/miniconda3/lib/python3.8/site-packages/py4j/java_gateway.py:1568, in JavaClass.__call__(self, *args)
   1562 command = proto.CONSTRUCTOR_COMMAND_NAME +\
   1563     self._command_header +\
   1564     args_command +\
   1565     proto.END_COMMAND_PART
   1567 answer = self._gateway_client.send_command(command)
-> 1568 return_value = get_return_value(
   1569     answer, self._gateway_client, None, self._fqn)
   1571 for temp_arg in temp_args:
   1572     temp_arg._detach()

File /usr/lib/spark/python/pyspark/sql/utils.py:111, in capture_sql_exception.<locals>.deco(*a, **kw)
    109 def deco(*a, **kw):
    110     try:
--> 111         return f(*a, **kw)
    112     except py4j.protocol.Py4JJavaError as e:
    113         converted = convert_exception(e.java_exception)

File /opt/conda/miniconda3/lib/python3.8/site-packages/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling None.com.johnsnowlabs.nlp.DocumentAssembler.
: java.lang.NoClassDefFoundError: org/apache/spark/ml/util/MLWritable$class
	at com.johnsnowlabs.nlp.DocumentAssembler.<init>(DocumentAssembler.scala:16)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)

**Comment by maziyarpanahi** [comment]
Could you please fill the template for better answer? (short answer, your Spark NLP and PySpark version is not matched. `MLWritable` happens when you have loaded a Spark NLP that is not compatible with your PySpakr, so if you fill the template we can see where can be the issue)






## Description


## Expected Behavior


## Current Behavior


## Possible Solution


## Steps to Reproduce


1.
2.
3.
4.

## Context


## Your Environment

* Spark NLP version `sparknlp.version()`:
* Apache NLP version `spark.version`:
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by lewisshkang** [comment]
Thank you! That does sound like a culprit as the first time I ran it, the version was:
Spark NLP version:  2.5.5
Spark version:  2.4.7

Do you know which versions should I adopt for the Spark NLP and Spark will not clash with each other? For example, should I downgrade SparkNLP to 3.x.x ?

**Comment by maziyarpanahi** [comment]
It depends on your Spark/PySpark version.

- if you are on Spark/PySpark 2.4 then the latest Spark NLP 3.4.4 (which is called spark-nlp-spark24)
- if you are on Spark/PySpark 3.x, then you should use Spark NLP 4.0.2 to enjoy all the new features. 

In any case, you have no reason to stay on Spark NLP 2.x, it's  very old and docs/examples/features are deprecated and hard to find.
