### ISSUE TITLE
An error in running spark nlp document Assembler

### ISSUE THREAD

**Issue by lewisshkang** [JohnSnowLabs/spark-nlp#11555]
## Steps to Reproduce

1.
2.
3.
4.

## Context
 I am simply trying run the document assembler. And an error keeps occurring with "TypeError: 'JavaPackage' object is not callable".  The park the error occurs is the following:

documentAssembler = DocumentAssembler().\
                    setInputCol("title").\
                    setOutputCol("document").\
                    setCleanupMode("shrink")   

And the full error is 
"---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [6], in <cell line: 2>()
      1 # Defining document assembler
----> 2 documentAssembler = DocumentAssembler().\
      3                     setInputCol("title").\
      4                     setOutputCol("document").\
      5                     setCleanupMode("shrink")

File /usr/lib/spark/python/pyspark/__init__.py:114, in keyword_only.<locals>.wrapper(self, *args, **kwargs)
    112     raise TypeError("Method %s forces keyword arguments." % func.__name__)
    113 self._input_kwargs = kwargs
--> 114 return func(self, **kwargs)

File /opt/conda/miniconda3/lib/python3.8/site-packages/sparknlp/base/document_assembler.py:92, in DocumentAssembler.__init__(self)
     90 @keyword_only
     91 def __init__(self):
---> 92     super(DocumentAssembler, self).__init__(classname="com.johnsnowlabs.nlp.DocumentAssembler")
     93     self._setDefault(outputCol="document", cleanupMode='disabled')

File /usr/lib/spark/python/pyspark/__init__.py:114, in keyword_only.<locals>.wrapper(self, *args, **kwargs)
    112     raise TypeError("Method %s forces keyword arguments." % func.__name__)
    113 self._input_kwargs = kwargs
--> 114 return func(self, **kwargs)

File /opt/conda/miniconda3/lib/python3.8/site-packages/sparknlp/internal/annotator_transformer.py:33, in AnnotatorTransformer.__init__(self, classname)
     31 self.setParams(**kwargs)
     32 self.__class__._java_class_name = classname
---> 33 self._java_obj = self._new_java_obj(classname, self.uid)

File /usr/lib/spark/python/pyspark/ml/wrapper.py:66, in JavaWrapper._new_java_obj(java_class, *args)
     64     java_obj = getattr(java_obj, name)
     65 java_args = [_py2java(sc, arg) for arg in args]
---> 66 return java_obj(*java_args)

TypeError: 'JavaPackage' object is not callable
"

## Your Environment

* Spark NLP version `sparknlp.version()`:  4.0.2
* Apache NLP version `spark.version`:   3.1.3
* Java version `java -version`: openjdk version "1.8.0_332"
* Setup and installation (Pypi, Conda, Maven, etc.):  Pypi
* Operating System and version: Windows GCP Jupyterlab
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
`TypeError: 'JavaPackage' object is not callable` error indicates you have installed the PyPI package of Spark NLP `spark-nlp==4.0.2` however, the JAR/Maven package is not included in the SparkSession:
https://github.com/JohnSnowLabs/spark-nlp#gcp-dataproc
