### ISSUE TITLE
How to train word embeddings (Glove/Word2Vec) on custom dataset?

### ISSUE THREAD

**Issue by akjindal53244** [JohnSnowLabs/spark-nlp#1166]
Thanks for creating this awesome library!

I have a question regarding training word embeddings (`Glove`) on a custom dataset. Is this currently supported?
It would be helpful if you could provide me an example (preferably both in `python` and `scala`) on this. TIA!

**Comment by maziyarpanahi** [comment]
Hi,
Unfortunately, you cannot train Word2Vec or GloVe inside Spark NLP. However, you can use Spark ML or Gensim to train your own embeddings on your custom dataset, save it as TEXT or BINARY and simply loading it via WordEmbeddings.

**Comment by mattivi** [comment]
Do you have any example where you load via WordEmbeddings? I am facing some issues and can not load a WordEmbeddingsModel with already pre-trained vectors. thanks a lot

**Comment by mattivi** [comment]
I have found, for reference [here an example ](https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/3.SparkNLP_Pretrained_Models.ipynb#scrollTo=ZgJ6xShAdbFo)with custom embeddings.
