### ISSUE TITLE
Incompatible Jackson version: 2.10.0

### ISSUE THREAD

**Issue by ImSanjayChintha** [JohnSnowLabs/spark-nlp#1201]
I am using python 3.7.3 version with anaconda package. I have installed

`pip install spark-nlp==2.6.4 pyspark==2.4.4`

This is my code:

```
from sparknlp.base import *
from sparknlp.annotator import *
from sparknlp.pretrained import PretrainedPipeline 
import sparknlp
spark = sparknlp.start()
pipeline = PretrainedPipeline('analyze_sentiment', lang='en') #Throwing error as Incompatible Jackson version: 2.10.0
```

I understand this is compatible versions issue. But I want to know which python version is compatible for sparknlp package?

![image](https://user-images.githubusercontent.com/19264696/100428410-ee4c6880-30b9-11eb-8ba6-fd1caf21077c.png)

**Comment by maziyarpanahi** [comment]
Please complete the template with all the questions asked and a full stack of errors, not screenshots.

**Comment by ImSanjayChintha** [comment]
Do you mean, code to reproduce the error? If it is, use python 3.7.3 and install spark packages. Run above code, you can see the same error.

**Comment by maziyarpanahi** [comment]
When you create a new issue there is a pre-made template which you need to fill in all the required questions. We need all of the details asked in that template. Without those, we cannot answer. Please make sure you complete the template next time and always provide the stack error in a full text not a select part in the screenshot.
