### ISSUE TITLE
java.lang.ClassNotFoundException: com.johnsnowlabs.nlp.util.regex.RuleFactory

### ISSUE THREAD

**Issue by maxifom** [JohnSnowLabs/spark-nlp#1214]
## Description
Trying to setup Scala with local cluster using Python example and got the following error: 
java.lang.ClassNotFoundException: com.johnsnowlabs.nlp.util.regex.RuleFactory
## Expected Behavior
Pipeline working correctly

## Current Behavior
java.lang.ClassNotFoundException: com.johnsnowlabs.nlp.util.regex.RuleFactory

## Possible Solution
???

## Steps to Reproduce
1. Set up local cluster with apache spark 2.4.7 (start-master+start-slave) -> this [Apache spark version](https://apache-mirror.rbc.ru/pub/apache/spark/spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz)
2. Using following project https://github.com/maxifom/test-spark-nlp
3. Tried to execute main script (sbt run)
4. Got the error

## Your Environment

* Spark NLP version: 2.6.4
* Apache NLP version: 2.4.7
* Java version (java -version): 
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
```
* Setup and installation (Pypi, Conda, Maven, etc.): IDEA sbt
* Operating System and version: Ubuntu 20.04.1 
* Link to your project (if any): https://github.com/maxifom/test-spark-nlp

P.S Using local[*] as master works

Stack trace of an error: https://gist.github.com/maxifom/548fde34d06ea00de6e25ea326f3dc94

**Comment by maxifom** [comment]
Using spark-shell --packages com.johnsnowlabs.nlp:spark-nlp_2.11:2.6.4 and inserting code from my repo works, don't understand why code doesn't work when I try to build in Scala

**Comment by maziyarpanahi** [comment]
This depends on how the cluster is being started. Usually, I build the application by using Spark NLP sbt packages, this helps me to develop my code and test inside Intellij. (there are env or configs involve to make the master local[*] for stand-alone testings and YARN/etc. for the production)

However, no matter what you do, you still need to have Spark NLP maven package or Fat JAR included in your cluster (spark-shell, spark-submit, YARN, EMR, Databricks, etc.)

**Comment by maxifom** [comment]
> This depends on how the cluster is being started. Usually, I build the application by using Spark NLP sbt packages, this helps me to develop my code and test inside Intellij. (there are env or configs involve to make the master local[*] for stand-alone testings and YARN/etc. for the production)
> 
> However, no matter what you do, you still need to have Spark NLP maven package or Fat JAR included in your cluster (spark-shell, spark-submit, YARN, EMR, Databricks, etc.)

I guessed if I used cluster like spark://localhost:7077 as master, the config of spark.jars.packages with spark-nlp should do the job and I should not receive class not found exceptions?

**Comment by maziyarpanahi** [comment]
I personally never tried using IntelliJ to directly be connected to any cluster or even another master, so I can't tell for that. But `ClassNotFoundException` usually a sign that wherever the code is being executed it doesn't have the full codebase (package or the fat JAR of Spark NLP). 
Maybe there is a way for me to reproduce this, what exactly is at `spark://localhost:7077`? How is that Apache Spark node setup?

**Comment by maxifom** [comment]
> I personally never tried using IntelliJ to directly be connected to any cluster or even another master, so I can't tell for that. But `ClassNotFoundException` usually a sign that wherever the code is being executed it doesn't have the full codebase (package or the fat JAR of Spark NLP). 
> 
> Maybe there is a way for me to reproduce this, what exactly is at `spark://localhost:7077`? How is that Apache Spark node setup?

So the way I set up my local cluster is the following: 
1. wget on apache spark description
2. untarred it
3. Started master and slave with following commands: `sbin/start-master.sh` and `sbin/start-slave.sh spark://max-pc:7077`. max-pc being hostname of my PC. You can check what's yours after going to localhost:8080, which is the default web ui address for spark master. You will see spark:// url. 
spark://max-pc:7077 is the spark master url, which I use to connect as master parameter in the code instead of local[*]

**Comment by maxifom** [comment]
Fixed by following steps:
1. Started Spark with JVM 11
2. Copied spark-nlp jar to jars/ folder in spark
3. Started my Scala application with JVM 8

**Comment by maziyarpanahi** [comment]
Thanks for the update. Step 1 is really strange, only Apache Spark 3.x supports JVM 11, anything released before only accepts JVM 8. (Spark NLP doesn't support Apache Spark 3.x)

But I am glad this got resolved.
