### ISSUE TITLE
Cannot join by slack invite link

### ISSUE THREAD

**Issue by maxifom** [JohnSnowLabs/spark-nlp#1215]
**Link to doc page in question (if any):**
README.md
**Name of the Spark NLP feature whose docs need improvement:**
Slack invite link
**What you think the docs should say:**
Correct link to join chat

Was it intentional to disable slack link or by accident? I cannot join chat as I need to have bitscopic.com or va.gov or mednet.ucla.edu email

**Comment by maziyarpanahi** [comment]
The invitation link is open to everyone, that must be a mistake. Thanks for reporting and we will look into it ASAP.

**Comment by maziyarpanahi** [comment]
This should be the invitation link before it expires and it has been updated in the README. 
https://spark-nlp.slack.com/join/shared_invite/zt-j5ttxh0z-Fn3lQSG1Z0KpOs_SRxjdyw#/

Please let us know if the link works correctly.

**Comment by maziyarpanahi** [comment]
new invitation link: https://github.com/JohnSnowLabs/spark-nlp/issues/13963
