### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by chandramohanreddyab** [JohnSnowLabs/spark-nlp#1220]
We have the Hadoop file system where we placed our sparkNLP pretrained model are placed and sparkNLP jar files in a folder on both driver node and data nodes. We are successful in initializing the spark session on driver node, which uses 'yarn as master'. Even though we are adding the sparkNLP jar files while initializing the spark session, executors are unable to reach these jar files.
Could you please help me  where exactly We need to place the jars to make executors reach ?  I have tried the different ways mentioned in issue [#232](https://github.com/JohnSnowLabs/spark-nlp/issues/232) but nothing worked out.

## Expected Behavior

Jars files should be loaded and executed

## Current Behavior

TypeError: 'JavaPackage' object is not callable

os.environ['PYSPARK_PYTHON']='/opt/anaconda/3.7.1/bin/python3'
os.environ['PYSPARK_DRIVER_PYTHON']='/opt/anaconda/3.7.1/bin/python3'
local_path='/data/dataiku/dataiku-dss-6.0.1/dss_data/code-envs/python/Python37_TEXTAnalytics/sparknlpjars/'
from pyspark.sql import SparkSession
nodes_path='/opt/sparknlp/'
spark = SparkSession.builder\
        .appName("Spark NLP") \
        .master("yarn") \
        .config("spark.driver.memory", "8G") \
        .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer") \
        .config("spark.kryoserializer.buffer.max", "500M") \
        .config("spark.driver.maxResultSize", "0")\
        .config("spark.jars", "/data/dataiku/dataiku-dss-6.0.1/dss_data/code-envs/python/Python37_TEXTAnalytics/sparknlpjars/spark-nlp-spark23-assembly-2.6.3.jar")\
        .getOrCreate()

## Possible Solution

Making sure jars are reachable to executors
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version: 2.6.3
* Apache NLP version: 2.3.0
* Java version (java -version): 1.8
* Setup and installation (Pypi, Conda, Maven, etc.): Conda
* Operating System and version: Linux
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,

Where do you run this SparkSession? And what is your cluster-mode? Depending on the answers, your external JAR has to be either on local fileSystem of the Driver and it will be uploaded on HDFS (you'll see it in the logs when the session is being started) or the jar must be on HDFS where every executor can access it. This is the Apache Spark rule.

The error is clearly about not having the JAR with the session:

- Having a look into your cluster-mode
- Try having the Fat JAR on HDFS and then point to that hdfs:///
- I would also suggest looking into the Spark UI environment to see where the JAR is exactly. 
- Try using packages just for testing: `("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp-spark23_2.11:2.6.3")`

**Comment by chandramohanreddyab** [comment]
We are running spark session on DataIKU DSS application and the cluster mode is 'client'. 
- Try using packages just for testing: ("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp-spark23_2.11:2.6.3")---> As we do not have internet connection on servers, I think this option will not work.
- We have fat jars in local fileSystem on DataIKU DSS and as well as in a folder which is accessible by all cluster nodes (not in HDFS file system)

which path folder we need to give while initializing the part session ? Local fileSystem on DSS or folder path on Cluster?

**Comment by maziyarpanahi** [comment]
The best thing to test now will be a path that is accessible by the entire Apache Spark cluster. Meaning if you do `spark.read.csv(YOUR_DISTRIBUTED_FS:///file.csv)` it can read it and distribute it to all executors.
After that, you should also check the Spark UI right after to see where is that JAR or whether it is in the cluster at all. (this must be just how you start your app in a cluster if you just pull spark-shell with --jars in YARN client mode you won't be having a problem. 

PS: You just need to find the right way to lunch that app in a cluster with an external JAR. I myself don't have any experience with DataIKU DSS so I can't say but I've tried all the other clusters including Databricks on AWS/Azure, EMR, GCP, Cloudera, Hortonwork, etc. with the same situation as yours (offline, Fat JAR, and in a cluster)

**Comment by chandramohanreddyab** [comment]
Thank you @maziyarpanahi I have updated the spark configuration on DSS at admin level. Now spark executor is able to reach the jars.. :) 👍

**Comment by maziyarpanahi** [comment]
Gald to hear that! Thanks for the update 👍🏼
