### ISSUE TITLE
NerDLApproach : How can I get all the scores computed for each token ?

### ISSUE THREAD

**Issue by emontarsoloamf** [JohnSnowLabs/spark-nlp#1225]
I trained an NER using NerDLApproach; and I would like to get for each token the score corresponding to each label.
For instance, if my categories are : PERS, ORG; I would like to know for each token in a document, the 5 probabilities corresponding to "B-PERS" /  "I-PERS" / "B-ORG" / "I-ORG" / "O".

Here is my pipeline (my train and test  data are CONLL data) : 
```
# PARAMETERS
max_epochs = 50
batch_size = 5
po = 0.003
validation_ratio = 0.0
lr = 0.01

# NER PIPELINE
## Word Embedding
embeddings = WordEmbeddingsModel.load("/glove/model/path")\
                .setInputCols("document", "token")\
                .setOutputCol("embeddings")

## NER Model            
ner = NerDLApproach().setInputCols("document", "token", "embeddings")\
                               .setOutputCol("ner")\
                               .setVerbose(2)\
                               .setLabelColumn("label")\
                               .setMaxEpochs(max_epochs).setLr(lr).setPo(po)\
                               .setBatchSize(batch_size).setValidationSplit(validation_ratio)\
                               .setRandomSeed(1)\
                               .setIncludeConfidence(True)\
                               .setOutputLogsPath("/output/path")
                        
## Get full entity
ner_converter = NerConverter()\
      .setInputCols(["sentence", "token", "ner"])\
      .setOutputCol("ner_chunk")
         
# BUILD THE PIPELINE
ner_pipeline_retrain = Pipeline(stages = [embeddings, ner, ner_converter])

# FIT ON TRAIN DATA
new_model = ner_pipeline_retrain.fit(train_data)

# APPLY MODEL ON TEST DATA
result = new_model.transform(test_data)
```

IncludeConfidence parameter being True, I was able to get a confidence value. But it's only one score, wich I guess corresponds to the predicted tag (i.e. the most likely one). However, I need to know the other scores, to analyse situations where the model could have hesitated with an other tag.

Can I do that ? I couldn't find anything in the docs, except info on the "IncludeConfidence " parameter.

SparkNLP version : 2.5.2
Spark version: 2.3

**Comment by maziyarpanahi** [comment]
As you found out correctly, the `IncludeConfidence` only displays the confident score of the predicted label which is the result. We don't have the probabilities of the other possible labels in our architecture. (we do for other tasks such as multi-class classification or multi-label classification in annotators like ClassifierDL, MultiClassifierDL, or LanguageDetectorDL but in NerDLModel we don't have access to that information)
