### ISSUE TITLE
Incompatible Jackson version: 2.10.0

### ISSUE THREAD

**Issue by ImSanjayChintha** [JohnSnowLabs/spark-nlp#1227]
I am using python 3.7.3 version with anaconda package. I have installed 
pip install spark-nlp==2.6.4 pyspark==2.4.4

And I am trying spark nlp package just like given in documentation, its not letting use pipeline packages.

## Description
```
This is my code:
from sparknlp.base import *
from sparknlp.annotator import *
from sparknlp.pretrained import PretrainedPipeline 
import sparknlp
spark = sparknlp.start()
pipeline = PretrainedPipeline('analyze_sentiment', lang='en') #Throwing error as Incompatible Jackson version: 2.10.0

I understand this is compatible versions issue. But I want to know which python version is compatible for sparknlp package?
```

## Expected Behavior
```
pipeline = PretrainedPipeline('analyze_sentiment', lang='en')
Approximate size to download 4.9 MB
Download done! Loading the resource.
```

## Current Behavior
Throwing error as :
```
An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline.
: java.lang.ExceptionInInitializerError:
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.10.0

```
## Possible Solution
Please make latest python spark nlp version to be compatible with python 7 and 8 versions 
## Steps to Reproduce
1. Install Python and Anaconda with jupyter 
2. Run below code in jupyter notebook

```
from sparknlp.base import *
from sparknlp.annotator import *
from sparknlp.pretrained import PretrainedPipeline
import sparknlp
import pandas as pd
from collections import Counter
spark = sparknlp.start()
pipeline = PretrainedPipeline('analyze_sentiment', lang='en') //Throws error
```

## Context
I am actually analyzing a statement is positive or negative using spark nlp with pipeline module 

## Your Environment

* Spark NLP version: 2.6.4
* Apache NLP version: 2.4.4
* Java version (java -version): Java 8
* Setup and installation (Pypi, Conda, Maven, etc.): Python 7 with Anaconda
* Operating System and version: Windows 10
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
It seems you are not using the correct/compatible PySpark version. Could you please run these two lines and paste the results back:

```python
from sparknlp.base import *
from sparknlp.annotator import *
from sparknlp.pretrained import PretrainedPipeline 
import sparknlp
spark = sparknlp.start()

print("Spark NLP version: ", sparknlp.version())
print("Apache Spark version: ", spark.version)
```

**Comment by ImSanjayChintha** [comment]
![image](https://user-images.githubusercontent.com/19264696/101041727-7fcc4680-35a2-11eb-89e3-b8c46a606824.png)

**Comment by maziyarpanahi** [comment]
Thanks. There is definitely not correctly set up in your Windows. Since this is a Windows, there are lots of other configs that need to be set for Java, Hadoop, and Apache Spark.
The only way to resolve this issue is to follow every single step of the following instruction without missing anything and removing anything that already is there as a leftover:

https://github.com/JohnSnowLabs/spark-nlp/issues/1022
