### ISSUE TITLE
Where is the scala API documentation，

### ISSUE THREAD

**Issue by shyoulala** [JohnSnowLabs/spark-nlp#12596]
https://nlp.johnsnowlabs.com/api/. there is nothing,please,thanks

**Comment by maziyarpanahi** [comment]
Hi,

- This is how ScalaDoc format/template works. You can either search what you are looking for and the results will appear in real-time and you can click on it for the actual doc like: https://nlp.johnsnowlabs.com/api/com/johnsnowlabs/nlp/annotators/ner/dl/NerDLModel.html
- Or you can get to them from our documentations where each feature has a direct link to the Scala API like: https://nlp.johnsnowlabs.com/docs/en/annotators#classifierdl
