### ISSUE TITLE
java fail with 'Mapping error' on model load or download

### ISSUE THREAD

**Issue by vpisanoVH** [JohnSnowLabs/spark-nlp#12612]
## Description
Trying to any model to run locally. Docker, local python, all fail. Tried python 3.5/6/7/8/10, jdks 8 and 11, miniforge, venv, a half dozen different sets of install instructions you have littered around various websites and githubs

## Expected Behavior
Model should be loaded.

## Current Behavior
Fail with cryptic error:  y4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoClassDefFoundError: org/json4s/MappingException

## Steps to Reproduce
1. start JSL docker (johnsnowlabs/sparknlp:sparknlp_for_healthcare_jupyter)
2. run code:
import sparknlp
spark = sparknlp.start()

print("Spark NLP version: {}".format(sparknlp.version()))
print("Apache Spark version: {}".format(spark.version))
from sparknlp.pretrained import PretrainedPipeline 
pipeline = PretrainedPipeline('recognize_entities_dl', 'en')

## Your Environment

* Spark NLP version `sparknlp.version()`:'4.0.2'
* Apache NLP version `spark.version`: pyspark 3.2.1
* Java version `java -version`: openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
* Setup and installation (Pypi, Conda, Maven, etc.): literally just docker
* Operating System and version: docker running on OSX M1

Full error message: 
---------------------------------------------------------------------------
Py4JError                                 Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 pipeline = PretrainedPipeline('recognize_entities_dl', 'en')

File /usr/local/lib/python3.8/dist-packages/sparknlp/pretrained/pretrained_pipeline.py:54, in PretrainedPipeline.__init__(self, name, lang, remote_loc, parse_embeddings, disk_location)
     52 def __init__(self, name, lang='en', remote_loc=None, parse_embeddings=False, disk_location=None):
     53     if not disk_location:
---> 54         self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
     55     else:
     56         self.model = PipelineModel.load(disk_location)

File /usr/local/lib/python3.8/dist-packages/sparknlp/pretrained/resource_downloader.py:65, in ResourceDownloader.downloadPipeline(name, language, remote_loc)
     63 t1.start()
     64 try:
---> 65     j_obj = _internal._DownloadPipeline(name, language, remote_loc).apply()
     66     jmodel = PipelineModel._from_java(j_obj)
     67 finally:

File /usr/local/lib/python3.8/dist-packages/sparknlp/internal/__init__.py:323, in _DownloadPipeline.__init__(self, name, language, remote_loc)
    322 def __init__(self, name, language, remote_loc):
--> 323     super(_DownloadPipeline, self).__init__(
    324         "com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline", name, language, remote_loc)

File /usr/local/lib/python3.8/dist-packages/sparknlp/internal/extended_java_wrapper.py:26, in ExtendedJavaWrapper.__init__(self, java_obj, *args)
     24 super(ExtendedJavaWrapper, self).__init__(java_obj)
     25 self.sc = SparkContext._active_spark_context
---> 26 self._java_obj = self.new_java_obj(java_obj, *args)
     27 self.java_obj = self._java_obj

File /usr/local/lib/python3.8/dist-packages/sparknlp/internal/extended_java_wrapper.py:36, in ExtendedJavaWrapper.new_java_obj(self, java_class, *args)
     35 def new_java_obj(self, java_class, *args):
---> 36     return self._new_java_obj(java_class, *args)

File /usr/local/lib/python3.8/dist-packages/pyspark/ml/wrapper.py:66, in JavaWrapper._new_java_obj(java_class, *args)
     64     java_obj = getattr(java_obj, name)
     65 java_args = [_py2java(sc, arg) for arg in args]
---> 66 return java_obj(*java_args)

File /usr/local/lib/python3.8/dist-packages/py4j/java_gateway.py:1321, in JavaMember.__call__(self, *args)
   1315 command = proto.CALL_COMMAND_NAME +\
   1316     self.command_header +\
   1317     args_command +\
   1318     proto.END_COMMAND_PART
   1320 answer = self.gateway_client.send_command(command)
-> 1321 return_value = get_return_value(
   1322     answer, self.gateway_client, self.target_id, self.name)
   1324 for temp_arg in temp_args:
   1325     temp_arg._detach()

File /usr/local/lib/python3.8/dist-packages/pyspark/sql/utils.py:111, in capture_sql_exception.<locals>.deco(*a, **kw)
    109 def deco(*a, **kw):
    110     try:
--> 111         return f(*a, **kw)
    112     except py4j.protocol.Py4JJavaError as e:
    113         converted = convert_exception(e.java_exception)

File /usr/local/lib/python3.8/dist-packages/py4j/protocol.py:334, in get_return_value(answer, gateway_client, target_id, name)
    330             raise Py4JError(
    331                 "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332                 format(target_id, ".", name, value))
    333     else:
--> 334         raise Py4JError(
    335             "An error occurred while calling {0}{1}{2}".
    336             format(target_id, ".", name))
    337 else:
    338     type = answer[1]

Py4JError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline

**Comment by maziyarpanahi** [comment]
Could you please use `spark = sparknlp.start(m1=True)` to see what happens?
https://github.com/JohnSnowLabs/spark-nlp#packages-cheatsheet

**Comment by vpisanoVH** [comment]
the docker image fails before that part. First cell of your docker_notebook examples: 

import os
jsl_secret = os.getenv('SECRET')
import sparknlp
sparknlp_version = sparknlp.version()
import sparknlp_jsl
jsl_version = sparknlp_jsl.version()
print (jsl_secret)

ModuleNotFoundError: No module named 'sparknlp_jsl'

isn't the whole point of docker to have all these requirements and environment issues solved from the get go?

**Comment by maziyarpanahi** [comment]
@vpisanoVH 

It depends where that Docker image is running, the hardware has an impact on how it should be used. That's being said, I made a mistake by not seeing this line:

```
start JSL docker (johnsnowlabs/sparknlp:sparknlp_for_healthcare_jupyter)
```

This repo is only for the public/open-source library. We do not offer any Docker image nor have any knowledge of licensed products. I highly recommend sharing this on Slack (#healthcare channel) or reaching out via email. 

If the hardware/virtualization was supported they will help you quickly. (keep in mind, some M1 chips like M1 Pro are not supported)
