### ISSUE TITLE
Exception in Chunker annotator

### ISSUE THREAD

**Issue by ChristophDE** [JohnSnowLabs/spark-nlp#12677]
This text input raises an exception in the Chunker annotator. This is the smallest string that I could cut out which showed the error. 
(sorry, this text looks like garbage, but so does text from OCR sometimes). 

Please note the html tags (encoded and decoded) which get removed during the normalization. Adding "\\","\n" as additional cleanup patterns helped me in this case. 
```
text = """
'<p id="p0001" num="1">\n12 \nABSTRACT \nThe present disclosure relates to a gutter fixture assembly. In a particular form the present disclosure \nrelates to a gutter hanger or bracket assembly. In one aspect, the rain gutter hanger assembly \ncomprises a base for securement with respect to a supporting structure, and a connector adapted for \n5 securement with respect to a portion of a rain gutter, and to bridge the base and the rain gutter, and \nwherein at least one of either of the base or the connector is adapted to interconnect with the other.  \n0\n\'N"\' \nN N \n\'~ N N&gt; \nN\'\' \nN \n""N \\ NN \n\\ N NNWNN \nN \n\\\\ ~ N ~\' N\' \nN N N N\' \nNA\' ~ \nAt " NV N\' \\ NNA N \nit ~4\\ ~ \nN\\ &gt;\\? N N\\N\' ~\\ ~/ N \nN NN N\' \nNN N NNN \nN" \'N A\' j\'~~ NN itkN N NNN " \nN N\\ N N\' ji\' i\' N *N,\'N \'N NN N *~A NiN~i\' ~ NN\' NN \nN NN / ~\' N N ~N\' \\N N~ \nNN A\' N" N NN ~N \'N~ \'&lt; NN N \nN\'N\' N \n"N"" C" ""\'s \n\'N ir\'\\N"\\ NN~., NN NNN N\'\' ~\' N \n~ \\ N~QN4 N\' N\\ V N\' N\\ *NN~ N \nNN N N NN N ~\' NN ~N N ""\'~\' N \nNN N\\ N N NNN \nN N N N \nNN N N A, \\N N\' \nNN NN N \nNN NTh \nNN \'K \nNN NN N &lt;N \n\'N N N NN \nNN N N NN N N \nN NN \n\'N N\' Ni NN \nN N NN N N \nN N N N N \nNN N N N" \nNN NN \nN N NN NN N N \nNN N\\ N N \nNN N N N \n\\N N N\' \nNN NN N N \nNN N N N\\ N iN N \nNN N NN \nN NN N N 1, \n\'N \nNN /\n</p>'
"""
text_df = spark.createDataFrame(new_rows).toDF("text")

from sparknlp.annotator import *
from sparknlp.base import *

documentAssembler = DocumentAssembler()\
    .setInputCol("text")\
    .setOutputCol("document")

cleanUpPatterns = ["<.*?>","&lt;.*?&gt;"]

documentNormalizer = DocumentNormalizer() \
    .setInputCols("document") \
    .setOutputCol("normalizedDocument") \
    .setAction("clean") \
    .setPatterns(cleanUpPatterns) \
    .setReplacement(" ") \
    .setPolicy("pretty_all") \
    .setLowercase(True)

sentenceDetector = SentenceDetector()\
    .setInputCols(['normalizedDocument'])\
    .setOutputCol('sentences')

tokenizer = Tokenizer() \
    .setInputCols(["sentences"]) \
    .setOutputCol("token")

pos_tagger = PerceptronModel.pretrained('pos_anc') \
     .setInputCols(['sentences', 'token']) \
     .setOutputCol('pos')

allowed_tags = [
                "<JJ.?>?<NN.?>+", 
                "<VB.?>", 
                "<JJ.?>", 
                "<NN.?>+<IN><JJ.?>?<NN.?>+"
               ]

chunker = Chunker() \
    .setInputCols(["sentences", "pos"]) \
    .setOutputCol("chunk") \
    .setRegexParsers(allowed_tags)

chunk_pipeline = Pipeline(stages=[documentAssembler,
                               documentNormalizer,
                               sentenceDetector,
                               tokenizer,
                               pos_tagger,
                               chunker
                               ])

chunk_pipeline.fit(text_df).transform(text_df).collect()
```

...
Caused by: org.apache.spark.SparkException: Failed to execute user defined function (HasSimpleAnnotate$$Lambda$6616/1539018399: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>)
...
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -10
	at java.lang.String.substring(String.java:1967)
	at com.johnsnowlabs.nlp.annotators.Chunker.$anonfun$annotate$7(Chunker.scala:242)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
...

**Comment by maziyarpanahi** [comment]
Hi @ChristophDE 

Could you please fill in the following template?

## Your Environment

* Spark NLP version `sparknlp.version()`:
* Apache NLP version `spark.version`:
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by ChristophDE** [comment]
sure: 

Spark NLP version sparknlp.version(): 4.1.0
Apache NLP version spark.version: 3.2.1

Java version java -version:
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Zulu 8.56.0.21-CA-linux64) (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Zulu 8.56.0.21-CA-linux64) (build 25.302-b08, mixed mode)

Setup and installation (Pypi, Conda, Maven, etc.): Maven com.johnsnowlabs.nlp:spark-nlp_2.12:4.1.0
Operating System and version: running on Azure Databricks
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Link to your project (if any): sorry, it is proprietary

**Comment by maziyarpanahi** [comment]
Thanks @ChristophDE 
I just wanted to make sure I am looking at the right line's number from the error trace.
