### ISSUE TITLE
Entity Recognizer Colab Setup

### ISSUE THREAD

**Issue by Taghreed7878** [JohnSnowLabs/spark-nlp#12733]
Code:

import os

# Install java
! apt-get update -qq
! apt-get install -y openjdk-8-jdk-headless -qq > /dev/null

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]
! java -version

# Install pyspark
! pip install --ignore-installed pyspark==2.4.4

# Install Spark NLP
! pip install --ignore-installed spark-nlp

import sys
import time

#Spark NLP
import sparknlp
from sparknlp.pretrained import PretrainedPipeline
from sparknlp.annotator import *
from sparknlp.common import RegexRule
from sparknlp.base import *

spark = sparknlp.start()

print("Spark NLP version: ", sparknlp.version())
print("Apache Spark version: ", spark.version)

pipeline = PretrainedPipeline('recognize_entities_dl', lang='en')

Error:

recognize_entities_dl download started this may take some time.
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
[<ipython-input-4-9b16b2503bec>](https://localhost:8080/#) in <module>
----> 1 pipeline = PretrainedPipeline('recognize_entities_dl', lang='en')

8 frames
[/usr/local/lib/python3.7/dist-packages/sparknlp/pretrained/pretrained_pipeline.py](https://localhost:8080/#) in __init__(self, name, lang, remote_loc, parse_embeddings, disk_location)
     52     def __init__(self, name, lang='en', remote_loc=None, parse_embeddings=False, disk_location=None):
     53         if not disk_location:
---> 54             self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
     55         else:
     56             self.model = PipelineModel.load(disk_location)

[/usr/local/lib/python3.7/dist-packages/sparknlp/pretrained/resource_downloader.py](https://localhost:8080/#) in downloadPipeline(name, language, remote_loc)
     54     def downloadPipeline(name, language, remote_loc=None):
     55         print(name + " download started this may take some time.")
---> 56         file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
     57         if file_size == "-1":
     58             print("Can not find the model to download please check the name!")

[/usr/local/lib/python3.7/dist-packages/sparknlp/internal/__init__.py](https://localhost:8080/#) in __init__(self, name, language, remote_loc)
    357     def __init__(self, name, language, remote_loc):
    358         super(_GetResourceSize, self).__init__(
--> 359             "com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize", name, language, remote_loc)
    360 
    361 

[/usr/local/lib/python3.7/dist-packages/sparknlp/internal/extended_java_wrapper.py](https://localhost:8080/#) in __init__(self, java_obj, *args)
     24         super(ExtendedJavaWrapper, self).__init__(java_obj)
     25         self.sc = SparkContext._active_spark_context
---> 26         self._java_obj = self.new_java_obj(java_obj, *args)
     27         self.java_obj = self._java_obj
     28 

[/usr/local/lib/python3.7/dist-packages/sparknlp/internal/extended_java_wrapper.py](https://localhost:8080/#) in new_java_obj(self, java_class, *args)
     34 
     35     def new_java_obj(self, java_class, *args):
---> 36         return self._new_java_obj(java_class, *args)
     37 
     38     def new_java_array(self, pylist, java_class):

[/usr/local/lib/python3.7/dist-packages/pyspark/ml/wrapper.py](https://localhost:8080/#) in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

[/usr/local/lib/python3.7/dist-packages/py4j/java_gateway.py](https://localhost:8080/#) in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

[/usr/local/lib/python3.7/dist-packages/pyspark/sql/utils.py](https://localhost:8080/#) in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

[/usr/local/lib/python3.7/dist-packages/py4j/protocol.py](https://localhost:8080/#) in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoSuchMethodError: org.apache.spark.ml.util.MLReadable.$init$(Lorg/apache/spark/ml/util/MLReadable;)V
	at com.johnsnowlabs.nlp.DocumentAssembler$.<init>(DocumentAssembler.scala:310)
	at com.johnsnowlabs.nlp.DocumentAssembler$.<clinit>(DocumentAssembler.scala)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.<init>(ResourceDownloader.scala:578)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.<clinit>(ResourceDownloader.scala)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)

**Comment by maziyarpanahi** [comment]
You are using a very old `pyspark`. You don't need to install anything yourself, all you need is to follow a simple script to setup Colab notebook for Spark NLP:

```
# This is only to setup PySpark and Spark NLP on Colab
!wget https://setup.johnsnowlabs.com/colab.sh -O - | bash
```

- reference: https://github.com/JohnSnowLabs/spark-nlp#google-colab-notebook

(this is equivalent of `! pip install pyspark==3.3.0 spark-nlp=4.1.0` and that's all you need. But it's best to use the official script to set up Colab just in case there are other steps require in the future)
