### ISSUE TITLE
Java 17 support

### ISSUE THREAD

**Issue by BaselAriqat** [JohnSnowLabs/spark-nlp#12732]
**Is your feature request related to a problem? Please describe.**
not related to a problem

**Describe the solution you'd like**
Official support for java 17

**Describe alternatives you've considered**
Using java 11 till java 17 is officially supported

**Comment by gulldan** [comment]
Any plan to support java 17?

**Comment by maziyarpanahi** [comment]
Unfortunately, we are having a tough time deprecating Java 8 so we can go Java 11! The enterprise (EMR, Databricks, etc.) are still by default Java 8 and forcing you to take extra streps to have Java 11 instead.

Let's hope by the end of this year we can move to Java 11 and in addition support newer Java releases.

**Comment by izogfif** [comment]
Any news on this issue? Maybe consider reopening it, if it's not implemented?

**Comment by maziyarpanahi** [comment]
Hi,
It's pretty much the same situation as before. The enterprise has not moved away from Java 8. In fact, you have to take extra steps to get any Runtime on Databricks that comes with Java 11 let alone with 17!

Spark NLP is being used in production and we cannot ask our users to take extra steps everytime they need to install it. Until Java 8 is deprecated in most Cloud providers we have to support and that means we cannot support other Java.
