### ISSUE TITLE
Add support for MinIO file system (bucket) in Spark NLP

### ISSUE THREAD

**Issue by chems-eddin** [JohnSnowLabs/spark-nlp#12906]
## Description

Hi, i setup a MinIO cluster, and i try to run this example:

`
 import` sparknlp
from sparknlp.base import *
from sparknlp.annotator import *
from pyspark.ml import Pipeline
from sparknlp.pretrained import PretrainedPipeline

data = spark.createDataFrame([[1, "New York and New Jersey aren't that far apart actually."]]).toDF("id", "text")
pipeline = PretrainedPipeline("explain_document_dl")
chunkToDoc = Chunk2Doc().setInputCols("entities").setOutputCol("chunkConverted")
explainResult = pipeline.transform(data)
result = `chunkToDoc.transform(explainResult) 
`

with this configuration of spark:
`
spark =SparkSession.builder.appName("PythonPi").\
master("spark://192.168.1.102:7077").\
config("spark.jars.packages", "io.delta:delta-core_2.12:1.2.1,org.apache.hadoop:hadoop-aws:3.3.1,com.johnsnowlabs.nlp:spark-nlp-aarch64_2.12:4.2.0").\
config("spark.hadoop.fs.s3a.access.key", 'LOGIN').\
config("spark.hadoop.fs.s3a.secret.key", 'PASSWORD').\
config("spark.hadoop.fs.s3a.endpoint", 'IP:9000').\
config("spark.hadoop.fs.s3a.endpoint.region", 'us-east-1').\
config("spark.databricks.delta.retentionDurationCheck.enabled","false").\
config("spark.sql.extensions","io.delta.sql.DeltaSparkSessionExtension").\
config("spark.executor.memory", "6g").\
config("spark.sql.debug.maxToStringFields", "100").\
config("spark.hadoop.fs.s3a.path.style.access", "true").\
config("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem").\
config("spark.sql.autoBroadcastJoinThreshold","-1").\
config("num-executors","10").\
config("spark.hadoop.fs.s3a.connection.ssl.enabled", "false").\
config("spark.sql.execution.arrow.pyspark.enabled", "true").\
config("spark.kryoserializer.buffer.max", "2000M").\
config("spark.jsl.settings.pretrained.credentials.access_key_id", "minioadmin").\
config("spark.jsl.settings.pretrained.credentials.secret_access_key", "minioadmin").\
config("spark.jsl.settings.storage.cluster_tmp_dir", "s3a://sparknlp/cluster_tmp_dir/").\
config("spark.jsl.settings.annotator.log_folder", "s3a://sparknlp/log_folder/").\
config("spark.jsl.settings.pretrained.cache_folder", "s3a://sparknlp/cache_folder/").\
config("spark.sql.catalog.spark_catalog","org.apache.spark.sql.delta.catalog.DeltaCatalog").getOrCreate()
`

and i get this error:

 `
explain_document_dl download started this may take some time.
Approx size to download 169.4 MB
[ / ]Uploading model explain_document_dl_en_3.1.3_3.0_1631046343759 to S3URI: s3a://sparknlp/cache_folder
22/10/11 12:45:20 WARN AmazonS3Client: No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.
[ \ ]explain_document_dl download started this may take some time.
Approximate size to download 169.4 MB
Error: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: XX9AM5TMYADM7955; S3 Extended Request ID: Nmx92jUca4muOerMwgIDbrOgpgdL7PJGQ4KIDezLum/gy+4d4h8BzpX9wyfXcVP5x753Q5Q1k6I=; Proxy: null)
22/10/11 12:45:24 ERROR ResourceDownloader$: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: XX9AM5TMYADM7955; S3 Extended Request ID: Nmx92jUca4muOerMwgIDbrOgpgdL7PJGQ4KIDezLum/gy+4d4h8BzpX9wyfXcVP5x753Q5Q1k6I=; Proxy: null)
`
i check the code source and it seem when the path start with s3a, it try to connect to aws service but i when it to connect to my Minio cluster,

can anyone help me?

## Your Environment

* Spark NLP version `4.2.0`:
* Apache NLP version `3.3.0`:
* Java version `jopenjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 11.0.16+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 11.0.16+8-jvmci-22.2-b06, mixed mode)`:
* Operating System and version 'ubuntu 22.04 arm64':

**Comment by maziyarpanahi** [comment]
Hi @chems-eddin 

I use MinIO for other tasks, never tried it with Spark NLP. Even thought it is similar to S3, it is not supported in Spark NLP. I will change this into a feature request.
