### ISSUE TITLE
Tesnsorflow model for ClassifierDLApproach

### ISSUE THREAD

**Issue by amir1m** [JohnSnowLabs/spark-nlp#12905]
Hello, 
Where can we find the Tesnsorflow code defining layers, etc. for ClassifierDLApproach model? I can see the model being loaded from this location line # 248 but don’t see any code that is used to create and write/save the model https://github.com/JohnSnowLabs/spark-nlp/blob/5bf8c61ee11acaa46f589b6c757c191e7dc094c4/src/main/scala/com/johnsnowlabs/nlp/annotators/classifier/dl/ClassifierDLApproach.scala

**Comment by maziyarpanahi** [comment]
Hi,

The code to create that model along with the other 2 classifiers is not disclosed since there is no need to re-create those models unlike NerDL and other DL-baed models. This one is just a simple end-to-end DNNs model.
