### ISSUE TITLE
Annotation python - Incorrect schema

### ISSUE THREAD

**Issue by xyutech** [JohnSnowLabs/spark-nlp#12934]
## Description
When we fill annotations from python we get NullPointerException For instance code like this produced it
```
            entries = []
            tree = ET.parse(xmlfile)
            root = tree.getroot()
            for m in root.findall("object"):
                m_dict = {t.tag : t.text for t in list(m.find("bbox"))}
                m_dict['label'] = m.find("name").text
                new_ann = Annotation(annotator_type = "ENTITY",
                                     begin = 0,
                                     end = 1,
                                     result = m_dict['label'],
                                     metadata = {'x' : int(m_dict['xmin']),
                                                 'y' : int(m_dict['ymin']),
                                                 'width' : (int(m_dict['width'])),
                                                 'height' : (int(m_dict['height'])),
                                                 'confidence' : 1,
                                                 'word' : m_dict['label']
                                                 },
                                     embeddings = [])
                entries.append(new_ann)
            return entries
        df = df.withColumn('annotation',
                           udf(getAnnotations, Annotation.dataType())
                           (df['filename']))
```
If we change 
```
Annotation.dataType()
```
to
```
ArrayType(StructType([
                               StructField('annotator_type', StringType(), False),
                               StructField('begin', IntegerType(), False),
                               StructField('end', IntegerType(), False),
                               StructField('result', StringType(), False),
                               StructField('metadata', MapType(StringType(), StringType()), False),
                               StructField('embeddings', ArrayType(FloatType()), False)
                               ]))
```
Everything works OK
So actually change is StructField('annotatorType', StringType(), False) -> StructField('annotator_type', StringType(), False)

## Possible Solution
Indeed Scala's Annotation class has 'annotatorType' field but at python it is renamed to 'annotator_type'. Update names accordingly.

## Your Environment
Spark NLP version: 4.1.0

**Comment by maziyarpanahi** [comment]
Thanks @xyutech for this issue

@danilojsl can we do this safely? It's not the first time a user noticed the difference between these two naming conventions, but I wasn't sure we can rename it without breaking things.

Could you please check and see what and where we can have issues if we rename it?

**Comment by fernandrez** [comment]
My take is the correct name should be the same both in scala and python, so I would change Annotation constructor parameter to be annotatorType everywhere, both in the Annotation class, and the dataType. In this way an annotation made in python is compatible with scala; personally Ive never used the Annotation class in python to create annotations because a simple tuple plus the correct dataType does the trick in a withColumn udf. 
I think this is a very old bug, following snake-case variable naming convention in python blindly.

**Comment by fernandrez** [comment]
> ## Description
> When we fill annotations from python we get NullPointerException For instance code like this produced it
> 
> ```
>             entries = []
>             tree = ET.parse(xmlfile)
>             root = tree.getroot()
>             for m in root.findall("object"):
>                 m_dict = {t.tag : t.text for t in list(m.find("bbox"))}
>                 m_dict['label'] = m.find("name").text
>                 new_ann = Annotation(annotator_type = "ENTITY",
>                                      begin = 0,
>                                      end = 1,
>                                      result = m_dict['label'],
>                                      metadata = {'x' : int(m_dict['xmin']),
>                                                  'y' : int(m_dict['ymin']),
>                                                  'width' : (int(m_dict['width'])),
>                                                  'height' : (int(m_dict['height'])),
>                                                  'confidence' : 1,
>                                                  'word' : m_dict['label']
>                                                  },
>                                      embeddings = [])
>                 entries.append(new_ann)
>             return entries
>         df = df.withColumn('annotation',
>                            udf(getAnnotations, Annotation.dataType())
>                            (df['filename']))
> ```
> 
> If we change
> 
> ```
> Annotation.dataType()
> ```
> 
> to
> 
> ```
> ArrayType(StructType([
>                                StructField('annotator_type', StringType(), False),
>                                StructField('begin', IntegerType(), False),
>                                StructField('end', IntegerType(), False),
>                                StructField('result', StringType(), False),
>                                StructField('metadata', MapType(StringType(), StringType()), False),
>                                StructField('embeddings', ArrayType(FloatType()), False)
>                                ]))
> ```
> 
> Everything works OK So actually change is StructField('annotatorType', StringType(), False) -> StructField('annotator_type', StringType(), False)
> 
> ## Possible Solution
> Indeed Scala's Annotation class has 'annotatorType' field but at python it is renamed to 'annotator_type'. Update names accordingly.
> 
> ## Your Environment
> Spark NLP version: 4.1.0

From the tests I ran a while ago, this annotation would make any downstream annotator fail given they require annotatorType property in the Struct in Scala.
