### ISSUE TITLE
Online demo hangs with no rendering...

### ISSUE THREAD

**Issue by weisisheng** [JohnSnowLabs/spark-nlp#12944]
Text boxes present themselves for testing

## Current Behavior
Website shows loading activity but no GUI.

## Possible Solution
Move off of streamlight?

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version `sparknlp.version()`:
* Apache NLP version `spark.version`:
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi @weisisheng 

Could you please provide the link to the exact demo? Also, is it the same behavior on different browsers?

**Comment by weisisheng** [comment]
Hello-- Tried this demo--> https://demo.johnsnowlabs.com/ocr/PDF_TO_TEXT/ on firefox 106 and google chrome 106, ubuntu 22.04.  Not in any rush as I was just experimenting.
