### ISSUE TITLE
Identical GPU and CPU performance for NER Pretrained Pipeline

### ISSUE THREAD

**Issue by vlreinier** [JohnSnowLabs/spark-nlp#1295]
## Current Behavior
I am getting identical performance for sparknlp.start(gpu=False) and sparknlp.start(gpu=True). Is this normal behaviour? Also, only 164MB GPU memory is being utilized when using sparknlp.start(gpu=True). Maybe someone can point me in the right direction?

Thanks in advance!

## Installed from Jupyter Notebook in Ubuntu docker:
import os
!apt-get update -qq
!apt-get install -y openjdk-8-jdk-headless -qq > /dev/null
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]
!java -version
!pip install --ignore-installed pyspark==2.4.4
!pip install --ignore-installed spark-nlp
!pip install sklearn

## Run code:
import sparknlp
import time
from sparknlp.annotator import *
from sparknlp.common import *
from sparknlp.base import *
from sparknlp.pretrained import PretrainedPipeline

spark = sparknlp.start(gpu=False)
pipeline = PretrainedPipeline('entity_recognizer_lg', lang='nl')
text = open("data/test_sentences.txt", 'r').read() # txt file containing 3k sentences
num_sentences = len(text.splitlines())

start_time = time.time()
result = pipeline.annotate(text)
print("{:.2f} milliseconds per sentence on average".format((time.time() - start_time) * 1000 / num_sentences))

## Your Environment
* Spark NLP version: 2.6.4
* Apache NLP version: 2.4.4
* Java version (java -version): 8
* Setup and installation (Pypi, Conda, Maven, etc.): Running from Jupyter Notebook, installed in Ubuntu docker
* Operating System and version: Ubuntu 2004
* GPU: RTX 2080TI 11GB
* RAM: 125GB

**Comment by maziyarpanahi** [comment]
Hi,

You are not definitely using the GPU. Please have a look at your logs to find out why. (usually, it's the wrong Cuda version, you can refer to this issue: https://github.com/JohnSnowLabs/spark-nlp/issues/1234)

The memory of the GPU starts with what it needs and then grow. (it quickly utilizes the entire available memory)
