### ISSUE TITLE
Multiple Documents Do Not Get Chunked Properly

### ISSUE THREAD

**Issue by dataanalyst4lyfe** [JohnSnowLabs/spark-nlp#12981]
## Description

If I load in multiple documents, and attempt to chunk them, I get really strange results.
Here is a [diagram of pipeline](https://i.imgur.com/tb9WRQQ.png) that I have created.
Here is the code that I am attempting to run that gives the issue:
```
data = spark.createDataFrame([["Neopets - The gaming website for all your needs.", "Peter Pipers employees are picking pecks of pickled peppers"]]).toDF("title", "description")
data.show()

# Create pipeline

# Document Assembler
# Title
title_document_assembler = DocumentAssembler()
title_document_assembler.setInputCol('title')
title_document_assembler.setOutputCol('title_document')
# Description
description_document_assembler = DocumentAssembler()
description_document_assembler.setInputCol('description')
description_document_assembler.setOutputCol('description_document')

# Sentence Detector - Combining both [Title] & [Description]
sentence_detector = SentenceDetector()
sentence_detector.setInputCols(['title_document', 'description_document'])
sentence_detector.setOutputCol('title_description_sentences')

# Tokenizer
tokenizer = Tokenizer()
tokenizer.setInputCols(['title_description_sentences'])
tokenizer.setSplitChars(['|'])
tokenizer.setOutputCol('title_description_tokens')

# Normalizer
if False:
    normalizer = Normalizer()
    normalizer.setInputCols(['title_description_tokens'])
    normalizer.setCleanupPatterns(['[^\w\d\s]'])
    normalizer.setOutputCol('title_description_normalized')

# POS Tagger
pos_tagger = PerceptronModel.pretrained("pos_anc", "en")

pos_tagger.setInputCols(['title_description_tokens', 'title_description_sentences'])
pos_tagger.setOutputCol('title_description_pos')    
    
# Chunker
chunker = Chunker()
chunker.setInputCols(['title_description_sentences', 'title_description_pos'])
chunker.setRegexParsers([
    '<JJ>*<NNP>+',
])
chunker.setOutputCol('title_description_chunks')

# Finisher
finisher = Finisher()
finisher.setInputCols(['title_document',
                       'description_document',
                       'title_description_sentences',
                       'title_description_tokens',
                       'title_description_pos', 
                       'title_description_chunks'])
finisher.setCleanAnnotations(False)

recursive_pipeline_stages = [
    title_document_assembler,
    description_document_assembler,
    sentence_detector,
    tokenizer,
    pos_tagger,
    chunker,
    finisher
]

pipeline = Pipeline().setStages(recursive_pipeline_stages)

result_df = pipeline.fit(data).transform(data)
result_pdf = result_df.toPandas()
display(result_pdf)

for row in result_pdf:
    print(f'\n{row}')
    display(result_pdf.iloc[0][row])
```

## Expected Behavior
For multiple documents, the chunker should return the result of the individual documents. i.e.
```
['Peter Pipers']
and
['Neopets']
```

## Current Behavior
When I run it with the 2 documents, I get the following outputs:
```
['Neopets',
 'Neopets - Th',
 'Neopets',
 'Neopets - Th',
 'Peter P',
 'Peter Pipers',
 'Peter P',
 'Peter Pipers']
```

## Steps to Reproduce
You can run the code I pasted in the [Description] section, or here's a [Google Colab notebook](https://colab.research.google.com/drive/1l2Y4R0LDBPiYrQWRJzdBU4ZJZOtIAJtr?usp=sharing).

## Context
I was trying to figure out the keywords from 2 columns of text, without having to create 2 separate pipelines, or merging the 2 texts together.

## Your Environment

* Spark NLP version `sparknlp.version()`:  4.2.1
* Pyspark version `spark.version`: 3.2.1
* Link to your project (if any): https://colab.research.google.com/drive/1l2Y4R0LDBPiYrQWRJzdBU4ZJZOtIAJtr?usp=sharing

**Comment by dataanalyst4lyfe** [comment]
@danilojsl - I am not sure if this is related to #12958 , but it is somewhat similar.

**Comment by maziyarpanahi** [comment]
Thanks @dataanalyst4lyfe this is very complete and easy to follow code. @danilojsl  will reproduce this and see what goes wrong in this pipeline

**Comment by dataanalyst4lyfe** [comment]
> Thanks @dataanalyst4lyfe this is very complete and easy to follow code. @danilojsl will reproduce this and see what goes wrong in this pipeline

Thanks for the quick response. Also, let me know if my [diagram of the pipeline](https://i.imgur.com/tb9WRQQ.png) does/doesn't make sense to you.

**Comment by maziyarpanahi** [comment]
Your pipeline makes sense. I would merge the `title` and `description` from the beginning by concat the cols before Spark NLP. But the way you do it, you can have different weights/scores for keywords extracted from the title or description later. (I did this too by giving higher value to keywords from title in co-occurrence matrix for instance)

**Comment by maziyarpanahi** [comment]
@dataanalyst4lyfe We will dig in more, however, you can only feed 1 column into SentenceDetector and expect 1 outputCol. 


This is wrong (unfortunately, in Python we cannot control there is an extra inputCols so it will allow you to set anything)
```
sentence_detector.setInputCols(['title_document', 'description_document'])
```
The Python API shows it expects 1 col type `DOCUMENT`: https://nlp.johnsnowlabs.com/api/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.html#inputAnnotatorTypes:Array[SentenceDetector.this.AnnotatorType]

I would use this code for the last example before DocumentAssembler and SentenceDetector:

```python
from pyspark.sql.functions import concat_ws

df.select(concat_ws(' ', df.title, df.description).alias("title_description"))
```

We are still looking to see why wrong number of cols results in bad output in POS (it has wrong sentence index) and will come back with the result. But in the meantime, the code and the explanation here should unlock you while we look for an expiation as why. (even though this is not a bug, but it's an interesting issue one might face)

**Comment by dataanalyst4lyfe** [comment]
@maziyarpanahi - Much appreciated for your response. I think I misunderstood what the API meant for this line:
```
defsetInputCols(value: Array[String]): [SentenceDetector](https://nlp.johnsnowlabs.com/api/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.html).this.type
Overrides required annotators column if different than default
```
[(Source)](https://nlp.johnsnowlabs.com/api/com/johnsnowlabs/nlp/annotators/sbd/pragmatic/SentenceDetector.html#setInputCols(value:Array[String]):HasInputAnnotationCols.this.type)
^ I interpreted the `String`-part of `Array[String]`, as the name of multiple `Document`-columns.

I will attempt to use the workaround you gave. Thanks!

**Comment by maziyarpanahi** [comment]
You are welcome @dataanalyst4lyfe . We will figure out what really happens with the wrong number of cols. 

PS: I appreciate that you always providing a complete reproducible example in your issues 👍🏼
