### ISSUE TITLE
Question - BertSentenceEmbeddings Methodology?

### ISSUE THREAD

**Issue by AllardJM** [JohnSnowLabs/spark-nlp#13009]
Hello. I am using a pipeline like the following. I am taking the normalized embeddings with LSH and looking at a Euclidean distance. 
I could not find a description of BertSentenceEmbeddings that described if this was the mean pooling of the tokens from a Bert model or the approach of sentence bert (sBert)? Thanks!

```
document = DocumentAssembler()\
              .setInputCol("text")\
              .setOutputCol("document")

bert_sent = BertSentenceEmbeddings.pretrained('sent_small_bert_L2_768')\
              .setInputCols(["document"])\
              .setOutputCol("sentence_embedding")

embeddingsFinisher = sparknlp.base.EmbeddingsFinisher() \
                      .setInputCols("sentence_embedding")\
                      .setOutputCols("finished_embedding")\
                      .setOutputAsVector(True)

SQL = SQLTransformer(statement = "SELECT url, desc_plug_title, explode(finished_embedding) as result FROM __THIS__")

norm = pyspark.ml.feature.Normalizer() \
        .setInputCol("result") \
      .setOutputCol("normalized_embedding") \
      .setP(1.0)


nlpPipeline = Pipeline(stages=[
                                document,
                                bert_sent,
                                embeddingsFinisher,
                                SQL,norm
                               ])
```

**Comment by maziyarpanahi** [comment]
Hi,

The `BertSentenceEmbeddings` fetches the `pooler_output` layer. If the model is not fine-tuned for next-sentence prediction (NSP) this layer may not produce meaningful embeddings.

You can also combine `BertEmbeddings` (last_hidden_layer for word embeddings) with `SentenceEmbeddings` which takes all the embeddings (words) inside the document/sentence and average them all into 1 embedding (like BertSentenceEmbeddings, so you can compare the quality of both). (it has average and sum strategies)

**Comment by AllardJM** [comment]
Thanks for the reply. If I am using sent_small_bert_L2_768 is this suitable for the task of sentence embeddings for downstream similarity? Is there a better one available for longer sentences?

Also, I just noticed a couple examples of importing a model from hugging face. Is it correct that we could use a model from sentence-transformers (sbert) in spark nlp exactly in a pipeline above?

**Comment by maziyarpanahi** [comment]
Yes, that is a model that was trained for both Word and Sentence embeddings, how accurate it can be depends on the content of your corpus. So you should test a couple of them and pick the best one. (you should also try `glove` models and not just transformers to be sure)

sbert is not Hugging Face, it comes from the Sentence Transformer library. Everything compatible with Spark NLP is listed here with a notebook to show step-by-step. (you can fine-tune your own BERT on your own corpus with NSP and import that model to Spark NLP too) https://github.com/JohnSnowLabs/spark-nlp/discussions/5669

**Comment by AllardJM** [comment]
Great thanks. (It appears you can use hugging face without sentence transformers library if you pool the output yourself.  https://www.sbert.net/docs/hugging_face.html). Thanks for the info!
