### ISSUE TITLE
exportConllFiles from CoNLLGenerator failes when the token has non-int metadata

### ISSUE THREAD

**Issue by jfernandrezj** [JohnSnowLabs/spark-nlp#13044]
## Description
exportConllFiles function uses token metadata mainly to extract the sentence index and be able to reproduce sentence information with proper double-new-lines. From what I read in [here](https://github.com/JohnSnowLabs/spark-nlp/blob/master/src/main/scala/com/johnsnowlabs/util/CoNLLGenerator.scala#L96), it's kind of expecting the only metadata field to be a single key with an int value. Sometimes we have more metadata keys (not only one), and diverse metadata value types (not only int like values).

## Expected Behavior

When we have this situation, many keys with diverse value types in the token metadata, the function should work with just one key from the metadata.

## Current Behavior
Even when no non-int values are present, the functions uses all metadata fields (which seems incorrect).
When there is a metadata field with non-int values it just throws an exception saying there is a non-int value in the metadata.

## Possible Solution
Using just the right metadata key ("sentence"). This can be achieved in the code most probably by adding a filter like this: 
```(row._1 zip row._2, row._3.filter(_._1=="sentence").map(_._2.toInt), row._4).zipped```
to the mentioned line. As shown [here](https://github.com/jfernandrezj/spark-nlp/blob/conll-token-nonint-meta-fixed/src/main/scala/com/johnsnowlabs/util/CoNLLGenerator.scala#L96).

## Steps to Reproduce
Just running the test on this branch from the updated [forked repo](https://github.com/jfernandrezj/spark-nlp/blob/conll-token-nonint-meta/src/test/scala/com/johnsnowlabs/nlp/util/CoNLLGeneratorTestSpec.scala#L219).

## Context
Customer project while running NER + Relex

## Your Environment

* Spark NLP version `sparknlp.version()`: 4.0.0
* Apache Spark version `spark.version`: 3.0.2
* Java version `java -version`: 8
* Setup and installation (Pypi, Conda, Maven, etc.): Built from source
* Operating System and version: Ubuntu 22.02

**Comment by maziyarpanahi** [comment]
Hi @jfernandrezj 

Do you have a simple example within a pipeline that causes this issue? Just to be sure I am not breaking something else to fix this. (a simple end-to-end example would be great to show what it is expected instead of the current results)

**Comment by jfernandrezj** [comment]
I provided the test using a DataFrame from Healthcare Library (pipeline + udf), where tokens have the following metadata fields:
sentence
section
section_name

Test is here:
[Token with more than one key in the metadata](https://github.com/jfernandrezj/spark-nlp/blob/conll-token-nonint-meta/src/test/scala/com/johnsnowlabs/nlp/util/CoNLLGeneratorTestSpec.scala#L219).

Please reach out if we can have a quick chat where I can show the internal code.
