### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable on Google DataProc

### ISSUE THREAD

**Issue by clayyoo-mendel** [JohnSnowLabs/spark-nlp#13046]
## Description

`TypeError: 'JavaPackage' object is not callable` when calling `DocumentAssembler()`.

## Expected Behavior

No error should be raised.

## Current Behavior

```
Traceback (most recent call last):
  File "/tmp/8c05504aa5ee4928b29b20c0e809bb6e/etl_job.py", line 68, in <module>
    main()
  File "/tmp/8c05504aa5ee4928b29b20c0e809bb6e/etl_job.py", line 56, in main
    DocumentAssembler()
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/__init__.py", line 114, in wrapper
  File "/opt/conda/default/lib/python3.8/site-packages/sparknlp/base/document_assembler.py", line 92, in __init__
    super(DocumentAssembler, self).__init__(classname="com.johnsnowlabs.nlp.DocumentAssembler")
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/__init__.py", line 114, in wrapper
  File "/opt/conda/default/lib/python3.8/site-packages/sparknlp/internal/annotator_transformer.py", line 33, in __init__
    self._java_obj = self._new_java_obj(classname, self.uid)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 66, in _new_java_obj
TypeError: 'JavaPackage' object is not callable
22/11/07 22:38:05 INFO org.sparkproject.jetty.server.AbstractConnector: Stopped Spark@3bea9b00{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
 ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [8c05504aa5ee4928b29b20c0e809bb6e] failed with error:
```

## Steps to Reproduce

1. Initialize Spark Session
2. Call document assembler
```
# test.py
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("tmp")\
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.12:4.2.2")\
    .getOrCreate()

from sparknlp.base import DocumentAssembler
DocumentAssembler()

print("Done")
```
3. Submit to DataProc
`gcloud dataproc jobs submit pyspark test.py --cluster CLUSTER_NAME`

**However**, if I ssh into the master node 
```
python test.py
```
This works fine.

## Context

I am using this to compute Transformers embeddings.

## Your Environment

* Spark NLP version `sparknlp.version()`: 4.2.2
* Apache NLP version `spark.version`:  3.1.3
* Java version `java -version`: openjdk version "1.8.0_345"
* Setup and installation (Pypi, Conda, Maven, etc.): Pip
* Operating System and version: Ubuntu 18.04 lts
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,

Have you followed the instructions for GCP Dataproc? https://github.com/JohnSnowLabs/spark-nlp#gcp-dataproc

There are more steps than just using Maven inside the Python script. I believe you also need --pacakges with your `pyspark` submit, you need to have `pip install spark-nlp==4.2.2` installed on all the machines in the cluster, etc.

PS: `JavaPackage' object is not callable` which means your Apache Spark application doesn't have Spark NLP Maven. (I would suggest to also add `--packages com.johnsnowlabs.nlp:spark-nlp_2.12:4.2.2` to your `spark-submit` command line for a quick test before following the instructions.

**Comment by clayyoo-mendel** [comment]
Thanks for the quick follow-up and apology for missing the instruction. Creating a cluster with `--properties spark:spark.jars.packages=com.johnsnowlabs.nlp:spark-nlp_2.12:4.2.2` fixed this issue.
