### ISSUE TITLE
Number of languages supported in sentence detector

### ISSUE THREAD

**Issue by Rhtyme** [JohnSnowLabs/spark-nlp#13080]
**Link to doc page in question (if any):**
https://github.com/JohnSnowLabs/spark-nlp/blob/master/docs/_posts/2020-09-14-sentence_detector_dl_xx.md

**Name of the Spark NLP feature whose docs need improvement:**
Sentence detector

**What you think the docs should say:**
Thanks for this library. I need to do sentence segmentation (i.e. split text into sentences), and multi-lingual sentence detector shown [here](https://github.com/JohnSnowLabs/spark-nlp/blob/master/docs/_posts/2020-09-14-sentence_detector_dl_xx.md) doing great. 

However, I could not find information about what languages it supports. Can you please add information about the number of supported languages? I tried Chinese and Hindi, and it turns out that this model can not perform sentence detection in these languages.

Moreover, could you please add information how someone can enrich this model by adding more languages?

**Comment by maziyarpanahi** [comment]
Hi,

This is a very good point, it seems we forgot to leave the benchmark in the model's card. (also there is this notebook that shows a demo)

https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/9.SentenceDetectorDL.ipynb

```
bg Bulgarian
bs Bosnian
da Danish
de German
el Greek
en English
es Spanish
fi Finnish
fr French
hr Croatian
it Italian
mk Macedonian
nl Dutch
pt Portuguese
ro Romania
sq Albanian
sr Serbian
sv Swedish
tr Turkish
```

@ahmedlone127 could you please update the model's card with a link to the `demo` notebook and add these lnauges to the description?

**Comment by ahmedlone127** [comment]
Hey @maziyarpanahi @Rhtyme  the notebook is already present in the open in colab colab button and I have added the languages to the description
