### ISSUE TITLE
rocksdb support on Mac M1

### ISSUE THREAD

**Issue by rwoodard-prog** [JohnSnowLabs/spark-nlp#13106]
Cannot load `librocksdbjni` with simple starter code on Mac M1.

I know @DevinTDHa and @maziyarpanahi have have worked on the `librocksdbjni` issue [here](https://github.com/JohnSnowLabs/spark-nlp/pull/8533).  Facebook  rocksdb team says it should be working [here](https://github.com/facebook/rocksdb/issues/7720).  However, I still get a crash.

Please see https://github.com/maziyarpanahi/spark-nlp-starter/issues/1#issuecomment-1317566310 for full details of the problem.

```
pos_anc download started this may take some time.
Approximate size to download 3.9 MB
Download done! Loading the resource.
glove_100d download started this may take some time.
Approximate size to download 145.3 MB
Download done! Loading the resource.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/jj/v8v5hy3d22ndmxj58b_736kw0000gp/T/librocksdbjni2717270241799440176.jnilib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2633)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:69)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:38)
	at com.johnsnowlabs.storage.RocksDBConnection.<init>(RocksDBConnection.scala:27)
```

## Steps to Reproduce

1. https://github.com/maziyarpanahi/spark-nlp-starter/issues/1#issuecomment-1317566310

## Your Environment

See https://github.com/JohnSnowLabs/spark-nlp/issues/13079 for my env.

**Comment by DevinTDHa** [comment]
Hello again @rwoodard-prog,

Also thanks again for reporting this.

I was able to reproduce and resolve the issue on my machine.

The problem seems to be a **dependency problem between Spark version > 3.1.x and rocksdb**. 

Why exactly I still have to find out, but in the meantime the issue can be resolved by using a lower version of Spark. In my case I used version 3.1.3 which can be downloaded at the [Spark release archives](https://archive.apache.org/dist/spark/spark-3.1.3/).

Let me know if this resolves the issue you are having.

**Comment by rwoodard-prog** [comment]
@DevinTDHa Yes, good solution.  I downgraded to Spark 3.1.3 and successfully ran the `spark-nlp-starter` code.  Thank you!  Closing the issue.

**Comment by maziyarpanahi** [comment]
If @DevinTDHa you don't mind I am gonna leave this open. I think Apache Spark started using RocksDB itself at some point, so let's make sure we can make 3.2/3.3 releases also compatible.

**Comment by DevinTDHa** [comment]
I agree, we will need to do some changes regarding this!

And you are right, Spark version 3.2.0 added a StateStore implementation based on RocksDB.

For future reference:
https://spark.apache.org/releases/spark-release-3-2-0.html
https://issues.apache.org/jira/browse/SPARK-34198
