### ISSUE TITLE
Wrong Example code provided for LemmatizerModel

### ISSUE THREAD

**Issue by maziyarpanahi** [JohnSnowLabs/spark-nlp#13125]
In the example code (both Python and Scala) the setInputCols wrongly has 2 inputs. It should be only `token`:

- example: https://nlp.johnsnowlabs.com/2022/03/31/lemma_taiga_ru_3_0.html
- https://nlp.johnsnowlabs.com/api/python/reference/autosummary/python/sparknlp/annotator/lemmatizer/index.html#python.sparknlp.annotator.lemmatizer.LemmatizerModel
- https://colab.research.google.com/drive/1q_PS_IeDTVIEVabnbquk3cLXpoJgFwXy?usp=sharing

Reference issue: https://github.com/JohnSnowLabs/spark-nlp/issues/13124

**Comment by ahmedlone127** [comment]
https://github.com/JohnSnowLabs/spark-nlp/pull/13126
