### ISSUE TITLE
java.util.NoSuchElementException: Param customBoundsStrategy does not exist.

### ISSUE THREAD

**Issue by britt-emm** [JohnSnowLabs/spark-nlp#13135]
## Description
I am trying to use spark-nlp with SentenceDetector as one of my annotators in an Azure Databricks Jupyter Notebook using Python. Last month the notebook was running fine. But today I'm getting the error in the title. I even tried eliminating use of the setCustomBounds parameter (which you will see in my screenshot) and it's still giving me the error.
![Screen Shot 2022-11-23 at 1 12 05 PM](https://user-images.githubusercontent.com/76189601/203632257-d9038aaf-c9a9-476d-93c2-e618632cc6c3.png)
![Screen Shot 2022-11-23 at 1 12 25 PM](https://user-images.githubusercontent.com/76189601/203632312-f7c79199-43f3-431a-91d8-c99068666be8.png)
![Screen Shot 2022-11-23 at 1 12 34 PM](https://user-images.githubusercontent.com/76189601/203632380-311a5671-b416-4759-8d87-99920f258dcb.png)

![Screen Shot 2022-11-23 at 1 12 51 PM](https://user-images.githubusercontent.com/76189601/203632387-322ee18c-8613-4d03-8ed7-ea5e086c3c13.png)

## Expected Behavior
I was expecting that I would run the code without errors.

## Current Behavior
Current behavior is when I run the code I get the listed error.

## Possible Solution
I don't have a solution. Is the setCustomBounds parameter still valid?

## Steps to Reproduce

1. Create a dataframe called pt_df with the following columns: 'PAT_MRN_ID', 'PAT_ENC_CSN_ID', 'CONTACT_DATE', 'NOTE_ID', 'NOTE_TEXT'
2. Make sure to populate the columns, especially important is the NOTE_TEXT column
3. Replace the setEntities in my code with your own entities. 
4. run the code

## Context
I have an entire notebook that doesn't work because all of the NLP that I'm doing is dependent on the SentenceDetector Annotator working.

## Your Environment
* Spark NLP version `sparknlp.version()`: 4.2.3
* Apache NLP version `spark.version`:3.3.0
* Java version `java -version`:  1.8.0_302 (Azul Systems, Inc.)
* Setup and installation (Pypi, Conda, Maven, etc.): Azure Databricks Jupyter Notebook using cluster Python version 3
* Operating System and version: MacOs Monterey 12.5.1
* Link to your project (if any): I can't link to my project

**Comment by maziyarpanahi** [comment]
Hi @britt-emm 

When usually this happens in Databricks your Spark NLP Python is not the same version as your Maven. Some users just use `spark-nlp` in side the Libraries->PyPI and then they have to use Maven coordinates which must have a version. So next time you run/start your cluster it will download the latest for PyPI (automatically), but still uses the older version of the Maven.

`customBoundsStrategy` was introduced in `4.0.2` so your Maven must be on older versions. If you just follow these steps to be sure you are using the same versions for both PyPI and Maven everything should be fine: https://github.com/JohnSnowLabs/spark-nlp#databricks-cluster

```
3. In Libraries tab inside your cluster you need to follow these steps:

    3.1. Install New -> PyPI -> spark-nlp==4.2.3 -> Install

    3.2. Install New -> Maven -> Coordinates -> com.johnsnowlabs.nlp:spark-nlp_2.12:4.2.3 -> Install
```

**Comment by britt-emm** [comment]
> 

Thank you for your help! That solved the issue.
