### ISSUE TITLE
Bug in Big text matcher unable to extract substring (complete word) is superstring is present

### ISSUE THREAD

**Issue by lijinchungapalli** [JohnSnowLabs/spark-nlp#13168]
Bug in Big text matcher
## Description
Big text matcher unable to extract substring (complete word) is superstring is present, example if vocab file has lung and lung cancer, lung wont be extracted even if lung cancer is not present in text.
## Expected Behavior
Both entities should be present
## Current Behavior
substring is never extracted even if superstring is not present.
## Steps to Reproduce
```
sample.txt
lung
lung cancer
sle
sle lupus
lupus
```

```
import sparknlp
from sparknlp.base import *
from sparknlp.annotator import *
from pyspark.ml import Pipeline

documentAssembler = DocumentAssembler() \
    .setInputCol("text") \
    .setOutputCol("document")

tokenizer = Tokenizer() \
    .setInputCols("document") \
    .setOutputCol("token")

data = spark.createDataFrame([["patient has Lung Cancer with sle"], 
                              ["patient Lung and Kidney Cancer with sle"],
                             ["patient bad lung and sle and good lung lupus"]]).toDF("text")
entityExtractor = BigTextMatcher() \
    .setInputCols("document", "token") \
    .setStoragePath("sample.txt", ReadAs.TEXT) \
    .setOutputCol("entity") \
    .setCaseSensitive(False) \
    .setMergeOverlapping(True)


pipeline = Pipeline().setStages([documentAssembler, tokenizer, entityExtractor,])
results = pipeline.fit(data).transform(data)
results.selectExpr("entity").show(truncate=False)
```

Result:
+---------------------------------------------------------------+
|entity                                                         |
+---------------------------------------------------------------+
|[{chunk, 12, 22, Lung Cancer, {sentence -> 0, chunk -> 0}, []}]|
|[]                                                             |
|[{chunk, 39, 43, lupus, {sentence -> 0, chunk -> 0}, []}]      |
+---------------------------------------------------------------+
note that here " patient Lung and Kidney Cancer with sle" we havent extraceted anything.

## Context
extract entities

## Your Environment

* Spark NLP version `4.2.4`:
* Apache NLP version `3.2.1`:
* Java version `java -version`: 8
* Setup and installation (Pypi, Conda, Maven, etc.): Pypi
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Fixed in 4.2.5 release
