### ISSUE TITLE
WARN DocumentNormalizer: Requested encoding parameter is different from the default charset

### ISSUE THREAD

**Issue by dev590t** [JohnSnowLabs/spark-nlp#13179]
## Description

`DocumentNormalizer().setLowercase(True)` can't convert correctly for some french char.
## Expected Behavior

For the input text "Aimé", I expect the output is "aimé"
## Current Behavior

Hovewer, spark-nlp give "aim?":
```
22/12/01 15:51:37 WARN DocumentNormalizer: Requested encoding parameter is different from the default charset.
+------+
|result|
+------+
|[aim?]|
+------+
```
## Steps to Reproduce

Run this code:
```
import sparknlp
from sparknlp.base import *
from sparknlp.annotator import *
from pyspark.ml import Pipeline
documentAssembler = DocumentAssembler() \
    .setInputCol("text") \
    .setOutputCol("document")
documentNormalizer = DocumentNormalizer() \
    .setInputCols("document") \
    .setOutputCol("normalizedDocument") \
    .setLowercase(True)
pipeline = Pipeline().setStages([
    documentAssembler,
    documentNormalizer
])
text = """Aimé"""
data = spark.createDataFrame([[text]]).toDF("text")
pipelineModel = pipeline.fit(data)
result = pipelineModel.transform(data)
result.selectExpr("normalizedDocument.result").show(truncate=False)
```
## Context

I'm trying to use `RegexMatcher` on the input text. As RegexMatcher doesn't support case insensitive regex option expression like `"aimé"i` or `/aimé/i`, et doesn't have a function `setCaseInsensitive()` to configurate case insensitive behavior. I need normalize the input text to low case in first.
## Your Environment

* Spark NLP version `sparknlp.version()`: '4.2.3'
* Apache NLP version `spark.version`: '3.3.1'
* Java version `java -version`: 
```
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+0-adhoc..jdk-11.0.1510)
OpenJDK 64-Bit Server VM (build 11.0.15+0-adhoc..jdk-11.0.1510, mixed mode)
```
* Setup and installation (Pypi, Conda, Maven, etc.): `pdm`

**Comment by wolliq** [comment]
Hello @dev590t I have been trying to reproduce but I could not find a scenario using the supported encodings.

Analysing the WARN, the message you get 

`Requested encoding parameter is different from the default charset.`

shows that you are running a JVM with a default encoding other than UTF-8 .

My setting is JDK temurin-1.8.0_302 with UTF and I could run lowercase succesfully.
```
+---+-----------------+
| id|             text|
+---+-----------------+
|  1|             Aimé|
|  2|C'EST-à-dire Noël|
+---+-----------------+

+---+-----------------+-----------------------------------------------------------+-----------------------------------------------------------+
|id |text             |document                                                   |normalizedDocument                                         |
+---+-----------------+-----------------------------------------------------------+-----------------------------------------------------------+
|1  |Aimé             |[{document, 0, 3, Aimé, {sentence -> 0}, []}]              |[{document, 0, 3, aimé, {sentence -> 0}, []}]              |
|2  |C'EST-à-dire Noël|[{document, 0, 16, C'EST-à-dire Noël, {sentence -> 0}, []}]|[{document, 0, 16, c'est-à-dire noël, {sentence -> 0}, []}]|
+---+-----------------+-----------------------------------------------------------+-----------------------------------------------------------+
```

You could check the following command response in your terminal to identify the encoding you have set on the JVM:
`java -XshowSettings`

There should be a setting like:
...
file.encoding = UTF-8
...

we should expect a different value, other than UTF-8, related to the warning you see.

You could also explicitly set encoding value to UTF-8 in your test to see if it solves the issue.

```
...
    documentNormalizer = DocumentNormalizer() \
      .setInputCols("document") \
      .setOutputCol("normalizedDocument") \
      .setLowercase(True) \
      .setEncoding("UTF-8")
...
```

Thanks

**Comment by dev590t** [comment]
` java -XshowSettings` show `file.encoding = ANSI_X3.4-1968`

I have tested `.setEncoding("UTF-8")`, but that give the same result.
I tested also other encoding
`.setEncoding("ANSI_X3.4-1968")` remove the warning and give:
```
+------+
|result|
+------+
|[]    |
+------+
```
`.setEncoding("UTF-16")` ` give:
```
22/12/08 11:33:28 WARN DocumentNormalizer: Requested encoding parameter is different from the default charset.
+------+
|result|
+------+
|[慩洿]|
+------+
```

`.setEncoding("UnicodeLittle")` remove the warning and give:
```
+------+
|result|
+------+
|[]    |
+------+
```

Do you think I should try to change java 's property file.encoding to UTF-8 and try again, or that will change any thing as `.setEncoding("UTF-8")` fails?

**Comment by wolliq** [comment]
Hi @dev590t,

thanks for the info, in fact ANSI_X3.4-1968 is not currently supported, this is why you get the incorrect encoding. 
Let me check if we can extend the support.

**Comment by dev590t** [comment]
Thank you @wolliq , that runs.

I have run this code before launch the python interpreter:
```
JAVA_TOOL_OPTIONS="$JAVA_OPTS -Dfile.encoding=UTF-8"
export JAVA_TOOL_OPTIONS
```
This command change the default charset used in JVM to utf-8.
