### ISSUE TITLE
Loading EmbeddingsFinisher in Pipeline not working in python.

### ISSUE THREAD

**Issue by Thijsvandepoll** [JohnSnowLabs/spark-nlp#1320]
When saving and loading a pipeline including `EmbeddingsFinisher` in python, the following exception is thrown:

```
AttributeError: module 'sparknlp' has no attribute 'EmbeddingsFinisher'
```

## Description
It should be possible to save the pipeline to disk and reload the entire `Pipeline` into memory. This is now not possible when using `EmbeddingsFinisher`. Would be great if this is fixed such that no workaround is necessary.

## Expected Behavior
Loading an entire pipeline including the transformer `EmbeddingsFinisher` should be available.

## Current Behavior
The line

```
PipelineModel.load("./path/to/saved/pipeline")
```
results in

```
AttributeError: module 'sparknlp' has no attribute 'EmbeddingsFinisher'
```

## Possible Solution
Import of sparknlp.base is missing.

## Steps to Reproduce

```
import sparknlp
from sparknlp.base import *
from sparknlp.annotator import *
# Start spark session
spark = sparknlp.start()

# Create sample dataframe
data = spark.createDataFrame([
    (1, "This is the first example sentence."),
    (2, "This is another example sentence.")
], schema=["id", "text"])

# Create document assembler
document_assembler = DocumentAssembler(). \
    setInputCol("text"). \
    setOutputCol("document")

# Create universal sentence decoder
use = UniversalSentenceEncoder.pretrained(). \
    setInputCols("document"). \
    setOutputCol("embedding")

# Create embedding finisher
finisher = EmbeddingsFinisher(). \
    setInputCols(["embedding"]). \
    setOutputCols("finished"). \
    setOutputAsVector(True). \
    setCleanAnnotations(True)

# Create pipeline
pipe = Pipeline(stages=[
    document_assembler,
    use,
    finisher
])

# Create pipeline model
model = pipe.fit(data)

# Save model
model.write().overwrite().save("./test_model")

# Load model
loaded_model = PipelineModel.load("./test_model")
```

## Context
Now I have to use a workaround, i.e. create a PySpark ML custom transformer.

## Your Environment
* Spark NLP version: 2.6.4
* Java version (java -version): 1.8.0_202
* Setup and installation (Pypi, Conda, Maven, etc.): `pip install pyspark==2.4.4 sparknlp==2.6.4`
* Operating System and version: macOS Catalina 10.15.7

**Comment by maziyarpanahi** [comment]
`AttributeError: module 'sparknlp' has no attribute 'EmbeddingsFinisher` is fixed in 2.6.5 release. Please re-open if there is still an issue.
