### ISSUE TITLE
Doc2Chunk not included in Spark NLP Lightpipelines

### ISSUE THREAD

**Issue by josejuanmartinez** [JohnSnowLabs/spark-nlp#13220]
Doc2Chunk is not supported inside LightPipelines. See description below.

## Description

When trying to create the foillowing pipeline:

```
documentAssembler = nlp.DocumentAssembler()\
        .setInputCol("text")\
        .setOutputCol("document")

chunkAssembler = nlp.Doc2Chunk() \
    .setInputCols("document") \
    .setOutputCol("chunk") \
    .setIsArray(False)

      
cm_pipeline = nlp.Pipeline(stages=[documentAssembler, chunkAssembler])
fit_cm_pipeline = cm_pipeline.fit(empty_data)

cm_lp = LightPipeline(fit_cm_pipeline)
```

... LightPipeline fails with:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/36634572/207142342-159f4a44-9a8d-4c1a-bda0-8f83b0369d7a.png">

## Expected Behavior

It should run the model within the Lightpipeline.

## Current Behavior

<img width="809" alt="image" src="https://user-images.githubusercontent.com/36634572/207142342-159f4a44-9a8d-4c1a-bda0-8f83b0369d7a.png">

## Possible Solution

I think NLP Components implement some interface to be served using LP. Maybe something is missing?

## Steps to Reproduce

1. Create the pipeline as above
2. Create a LP using that pipeline
3. Try to infer any text
4.

## Context

Sometimes when you are interested in quick inference, it forces you to go to fit/transform.

## Your Environment

* Spark NLP version `sparknlp.version()`: 4.2.4
* Apache NLP version `spark.version`: 3.1.2
* Java version `java -version`: 1.8.0
* Setup and installation (Pypi, Conda, Maven, etc.): Databricks johnsnowlabs cluster
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
I can look over this one more time just to be 100% sure, but Doc2Chunk is not compatible with LightPipeline as we checked this before. There are some annotators that won't be compatible with LP due to their nature.
There is a param that you can set in LP which will ignore none-compatible features as it is instructed in the error message.

**Comment by maziyarpanahi** [comment]
@josejuanmartinez Just had a look again, some annotators are not supported. However, they are none-blocking tasks, so the end result of that LP pipeline is fine as long as you add `.setIgnoreUnsupported(True)`

If you don't mind I'll keep this open to do one more round of test on `RawAnnotator` to see what happens.

**Comment by josejuanmartinez** [comment]
@maziyarpanahi  It turns out `ChunkMappers` from licensed libraries now accept `document` annotation type, not only `chunk`, so I'm good without it. Feel free to change this to `wontfix` if it's not compatible.

**Comment by maziyarpanahi** [comment]
Glad to hear that. I will ask someone to give this another shot in the next release and then I'll close it if it's a `wontfix` situation.
