### ISSUE TITLE
Generating all the word embeddings in the w2v_cc_300d model

### ISSUE THREAD

**Issue by martina-dev-11** [JohnSnowLabs/spark-nlp#13278]
Hi. 

I am using the Word2Vec Embeddings in Maltese (300d) model (w2v_cc_300d) to generate all the word embeddings for this model. 

I have tried using `getVectors()` however, I am getting an AttributeError: `AttributeError: 'WordEmbeddingsModel' object has no attribute 'getVectors'`

Is there an alternative to generating all the word embeddings?

**Comment by maziyarpanahi** [comment]
The `WordEmbeddingsModel` annotator doesn't have that function. In this specific annotator you cannot export all the existing vocabulary with their vectors.

Could you please provide the full code just to be sure you are using `WordEmbeddingsModel` annotator and not `Wav2VecModel` annotator?

**Comment by martina-dev-11** [comment]
Sure, here is the code: 

```
import sparknlp
from sparknlp.pretrained import PretrainedPipeline 
from sparknlp.base import *
from sparknlp.annotator import *

spark = sparknlp.start()
print("Spark NLP version: {}".format(sparknlp.version()))
print("Apache Spark version: {}".format(spark.version))

documentAssembler = DocumentAssembler().setInputCol("text").setOutputCol("document")
tokenizer = Tokenizer().setInputCols("document").setOutputCol("token")
embeddings = WordEmbeddingsModel.pretrained("w2v_cc_300d","mt").setInputCols(["document", "token"]).setOutputCol("embeddings")
pipeline = Pipeline(stages=[documentAssembler, tokenizer, embeddings])

#testing with a word 'tessera'
data = spark.createDataFrame([["tessera"]]).toDF("text")
result = pipeline.fit(data).transform(data)
result
```

Is there no way of getting the vocabulary used or the word embeddings used?

**Comment by maziyarpanahi** [comment]
OK so you are using `WordEmbeddingsModel` annotator, this one doesn't have any option to export all the vectors.

**Comment by martina-dev-11** [comment]
Ok thanks for the information.

**Comment by aidahalitaj** [comment]
Since WordEmbeddingsModel doesn't have the option to export all the vectors, is there any other way to create the embedding matrix from embeddings generated by  WordEmbeddingsModel? I want to use that matrix as an input for RNN model using Keras and TensorFlow?

The matrix should be initialized by something like:
embedding_matrix = np.zeros((num_tokens, embedding_dim))

But without the num_tokens how is it possible to create the matrix?
@maziyarpanahi @martina-dev-11
