### ISSUE TITLE
Which Corpora are being used to train Word2Vec Embeddings in Maltese (300d) ? 

### ISSUE THREAD

**Issue by martina-dev-11** [JohnSnowLabs/spark-nlp#13275]
Hello. 

I came across the Word2Vec Embeddings in Maltese (300d) using w2v_cc_300d. I found code on how to implement this using this [documentation](https://nlp.johnsnowlabs.com/2022/03/16/w2v_cc_300d_mt_3_0.html#how-to-use). 

What corpus is being used to train this Word2Vec? I have tried searching for this but could not find any mention of corpora listed.

Thanks in advance!

**Comment by maziyarpanahi** [comment]
Hi,

These are imported from fastText. You can find more info about it here: https://fasttext.cc/docs/en/crawl-vectors.html

**Comment by martina-dev-11** [comment]
Thanks!
