### ISSUE TITLE
Need guidance to finetune BertSentenceEmbedding using  domain specific pair of sentences 

### ISSUE THREAD

**Issue by srimantacse** [JohnSnowLabs/spark-nlp#13300]
This is not a proper feature request; rather I need the guidance to build our customized model using BertSentenceEmbedding  which would be built on top of pretrained model for ex: small_bert_L2_128; I will use some domain specific dataset to finetune the mentioned model. Request to share the approach in spark-nlp perspective.

**Comment by srimantacse** [comment]
@maziyarpanahi Request to give input on the above query.

**Comment by maziyarpanahi** [comment]
Hi,

The fine-tuning of any transformer models must happen outside Spark NLP. The Java APIs for TensorFlow (or any other DL framework) don't have the feature to fine-tune, only Python has.
So you pick a model in HuggingFace, let's say BERT Small (or Tiny, or any size), you will fine-tune it for the next sentence prediction over your own domain-specific dataset (they have examples of how to do NSP and there are many online tutorials), and once you are done you will import that model into `BertSentenceEmbeddings` annotator which you can use for training classifiers or any other tasks but at scale with zero-code change when you go from 1 machine to N machines.
