### ISSUE TITLE
Pipeline with Sentence detector always gives sentence index as 0 in the metadata

### ISSUE THREAD

**Issue by hchugani** [JohnSnowLabs/spark-nlp#13311]
## Description
Running NLPPipeline using Spark 
Stages in pipeline, 
1. com.johnsnowlabs.nlp.DocumentAssembler:
        setInputCol("content");
        setOuputCol("document")
2. com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector:
   setInputCol("document");
   setOutputCol("sentence");
   setExplodeSentence(true);
3. com.johnsnowlabs.nlp.annotators.Tokenizer;
  setInputCol("sentence");
  setOutputCol("token");

## Expected Behavior
Valid sentence index in the token metadata 

## Current Behavior
result.select("sentence", "token").collect()
Attached current output with sentence index coming as 0 for all the different tokens in a multiline input document .

|[[document, 1, 53, SSN gender birthdate maiden name last name first name, [sentence -> 0], []]]            |[[token, 1, 3, SSN, [sentence -> 0], []], [token, 5, 10, gender, [sentence -> 0], []], [token, 12, 20, birthdate, [sentence -> 0], []], [token, 22, 27, maiden, [sentence -> 0], []], [token, 29, 32, name, [sentence -> 0], []], [token, 34, 37, last, [sentence -> 0], []], [token, 39, 42, name, [sentence -> 0], []], [token, 44, 48, first, [sentence -> 0], []], [token, 50, 53, name, [sentence -> 0], []]]                                                                             |
|[[document, 55, 97, 172-32-1176 m 4/21/1958 Smith White Johnson, [sentence -> 1], []]]                     |[[token, 55, 65, 172-32-1176, [sentence -> 0], []], [token, 67, 67, m, [sentence -> 0], []], [token, 69, 77, 4/21/1958, [sentence -> 0], []], [token, 79, 83, Smith, [sentence -> 0], []], [token, 85, 89, White, [sentence -> 0], []], [token, 91, 97, Johnson, [sentence -> 0], []]] 

## Steps to Reproduce
1. Take any multiline  document as input
2. As mentioned in the description, create NLPPipeline using Spark.
3. output dataset: result.select("sentence", "token").collect()

## Context
Please refer to slack channel thread :  https://spark-nlp.slack.com/archives/C032JJ2UAR2/p1671003969986109 

## Your Environment
* Spark NLP version `sparknlp.version()`: Spark NLP version-4.0.2 and Spark NLP JSL version-4.1.0
* Apache NLP version `spark.version`: Spark 3.0.2
* Java version `java -version`:  1.8.0_333
* Setup and installation : mvn 
* Operating System and version: Linux

**Comment by maziyarpanahi** [comment]
Could you please provide the full pipeline including the input (`text`) for us to reproduce this?

**Comment by hchugani** [comment]
## Java code snippet
import org.apache.spark.ml.Pipeline;
import com.johnsnowlabs.nlp.DocumentAssembler;
import com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector;
import com.johnsnowlabs.nlp.annotators.Tokenizer;
import org.apache.spark.ml.PipelineModel;

DocumentAssembler documentAssembler = new DocumentAssembler();
documentAssembler.setInputCol("content");
documentAssembler.setOutputCol("document");

SentenceDetector sentenceDetector = new SentenceDetector();
sentenceDetector.setInputCols("document");
sentenceDetector.setOutputCol("sentence");
sentenceDetector.setCustomBounds(new String[] {System.lineSeparator()});
sentenceDetector.setExplodeSentences(true);

Tokenizer tokenizer = new Tokenizer();
tokenizer.setInputCols("sentence");
tokenizer.setOutputCol("token");


final List<PipelineStage> pipelineStagesList = new LinkedList<>();
pipelineStagesList.add(documentAssembler);
pipelineStagesList.add(sentenceDetector);
pipelineStagesList.add(tokenizer);

Pipeline pipeline = new Pipeline().setStages(pipelineStagesList.toArray(new PipelineStage[0]));

PipelineModel pipelineModel =
                    pipeline.fit(
                            sparkSession
                                    .emptyDataset(Encoders.STRING())
                                    .toDF("content"));
result = pipelineModel.transform(inputDataset);


## Input
inputDataset (Columns: fileName, content)
["test.pdf", "
SSN gender birthdate maiden name last name first name
172-32-1176 m 4/21/1958 Smith White Johnson
514-14-8905 f 12/22/1944 Amaker Borden Ashley
213-46-8915 f 4/21/1958 Pinson Green Marjorie
524-02-7657 m 3/25/1962 Hall Munsch Jerome
489-36-8350 m 1964/09/06 Porter Aragon Robert
514-30-2668 f 1986/05/27 Nicholson Russell Jacki
505-88-5714 f 1963/09/23 Mcclain Venson Lillian
690-05-5315 m 1969/10/02 Kings Conley Thomas
646-44-9061 M 1978/01/12 Kurtz Jackson Charles
421-37-1396 f 1980/04/09 Linden Davis Susan
461-97-5660 f 1975/01/04 Kingdon Watson Gail
660-03-8360 f 1953/07/11 Onwunli Garrison Lisa
751-01-2327 f 1968/02/16 Simpson Renfro Julie
559-81-1301 m 1952/01/20 Mcafee Heard James
624-84-9181 m 1980/01/16 Frazier Reyes Danny
449-48-3135 m 1982/06/14 Feusier Hall Mark
477-36-0282 m 1961/03/10 Vasquez Mceachern Monte
458-02-6124 m 1955/09/20 Pennebaker Diaz Christopher
044-34-6954 m 1967/05/28 Simpson Lowe Tim
587-03-2682 f 1958/10/24 Dickerson Oyola Lynette
421-90-3440 f 1953/07/17 Kroeger Morrison Adriane
451-80-3526 m 1950/06/09 Parmer Santos Thomas
300-62-3266 m 1965/02/10 Spain Faulkner Victor
322-84-2281 m 1977/08/19 Miley Iorio Albert
465-73-5022 f 1964/06/20 Summers Kaminski Teresa
612-20-6832 m 1979/08/18 Banas Edwards Rick
687-05-8365 f 1976/05/24 Robbins Peacock Stacey
205-52-0027 f 1950/03/26 Sanford Nelson Agnes
404-12-2154 f 1984/09/21 Garcia Townsend Mireille
151-32-2558 f 1952/11/19 Stockdale Zwick Rebecca
"
]

**Comment by danilojsl** [comment]
@maziyarpanahi  it looks like there is a bug with `explodeSentence`. I reproduced the error by setting `setExplodeSentences` to false. I will take a look at it.
