### ISSUE TITLE
Bug in .setDimension() from SentenceEmbeddings

### ISSUE THREAD

**Issue by mauro-nievoff** [JohnSnowLabs/spark-nlp#13322]
## Description
The dimension of the sentence embeddings is not affected by the value introduced in `.setDimension()`. For example, if you use `.setDimension(200)`, the length of the embeddings is 100 (default value) instead of 200. In this example, if `getDimension()` is used, it returns 200. 

## Expected Behavior
When a new value is introduced in `.setDimension()`, the length of the sentence embeddings should be the same as that value.

## Current Behavior
The length of the sentence embeddings is always 100 (default value for dimension) disregarding the value introduced using `.setDimension()`.

## Possible Solution
\-

## Steps to Reproduce
```
document_assembler = DocumentAssembler() \
      .setInputCol("text") \
      .setOutputCol("document")
    
tokenizer = Tokenizer() \
      .setInputCols(["document"]) \
      .setOutputCol("token")

glove_embeddings = WordEmbeddingsModel().pretrained() \
      .setInputCols(["document",'token'])\
      .setOutputCol("embeddings")\
      .setCaseSensitive(False)

default_sentence_embeddings = SentenceEmbeddings() \
      .setInputCols(["document", "embeddings"]) \
      .setOutputCol("default_sentence_embeddings")

customized_sentence_embeddings = SentenceEmbeddings() \
      .setInputCols(["document", "embeddings"]) \
      .setOutputCol("customized_sentence_embeddings")\
      .setDimension(200)

nlp_pipeline = Pipeline(
    stages=[document_assembler, 
            tokenizer,
            glove_embeddings,
            default_sentence_embeddings,
            customized_sentence_embeddings])

text_df = spark.createDataFrame([["Sentence embeddings can be used for text classification, semantic similarity, clustering, and other natural language tasks."]]).toDF("text")

nlp_model = nlp_pipeline.fit(text_df)

results = nlp_model.transform(text_df)

```

The length of the embeddings is the same in both cases:
```
len(results.select('default_sentence_embeddings').take(1)[0]['default_sentence_embeddings'][0]['embeddings'])

```
```
100
```

```
len(results.select('customized_sentence_embeddings').take(1)[0]['customized_sentence_embeddings'][0]['embeddings'])
```
```
100
```

## Context
I was trying to get sentence embeddings with different dimensions.

## Your Environment
I'm using Google Colab.
* Spark NLP version `sparknlp.version()`: 4.2.4
* Apache NLP version `spark.version`: 3.1.2

**Comment by maziyarpanahi** [comment]
Hi @mauro-nievoff 

The `setDimension` cannot be set after the embeddings model are saved. It is only used when we are importing those models and it is purely informative. (it is impossible to change embeddings dimensions like this, if you download a model from any embeddings and it says `768` for dimensions, it means it is 768 and it will stay like that forever)

We added this so people use `setDimension()` when they are importing and know what they are downloading via `getDimension()` param
