### ISSUE TITLE
Wav2Vec does not work on Apple M1

### ISSUE THREAD

**Issue by pds2208** [JohnSnowLabs/spark-nlp#13366]
### Description

I can't get any Wav2Vec models or pipelines working on Apple M1. Error is:

2023-01-19 08:53:19.502205: W external/org_tensorflow/tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-01-19 08:53:21.915776: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:171] XLA service 0x10dfbbb50 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-01-19 08:53:21.915790: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (0): Host, Default Version
'cyclone' is not a recognized processor for this target (ignoring processor)
'cyclone' is not a recognized processor for this target (ignoring processor)
'cyclone' is not a recognized processor for this target (ignoring processor)
'cyclone' is not a recognized processor for this target (ignoring processor)
'cyclone' is not a recognized processor for this target (ignoring processor)
'cyclone' is not a recognized processor for this target (ignoring processor)
'cyclone' is not a recognized processor for this target (ignoring processor)
'cyclone' is not a recognized processor for this target (ignoring processor)
LLVM ERROR: 64-bit code requested on a subtarget that doesn't support it!

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

I've tried with both Python and Scala  - same error and the same code is fine on X86. 

I'm using the code in the example here:. 
https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/annotation/english/asr-wav2vec2/Automatic_Speech_Recognition_Wav2Vec2_(Wav2Vec2ForCTC).ipynb

Here's a Python version that fails: 

```python
import librosa
import pandas as pd
import sparknlp
from pyspark.ml import Pipeline
from pyspark.sql.types import *
from sparknlp import AudioAssembler
from sparknlp.annotator import Wav2Vec2ForCTC

spark = sparknlp.start(m1=True)

print(sparknlp.version())

data, sampleing_rate = librosa.load("data/ngm_12484_01067234848.wav", sr=16000)
data = [float(x) for x in data]

schema = StructType([StructField("audio_content", ArrayType(FloatType())),
                     StructField("sampling_rate", LongType())])

df = pd.DataFrame({
    "audio_content": [data],
    "sampling_rate": [sampleing_rate]
})

spark_df = spark.createDataFrame(df, schema)

audio_assembler = AudioAssembler() \
    .setInputCol("audio_content") \
    .setOutputCol("audio_assembler")

speech_to_text = Wav2Vec2ForCTC \
    .pretrained() \
    .setInputCols("audio_assembler") \
    .setOutputCol("text")

pipeline = Pipeline(stages=[
    audio_assembler,
    speech_to_text,
])

pipelineDF = pipeline.fit(spark_df).transform(spark_df)
pipelineDF = pipeline.transform(spark_df)

pipelineDF.select("text.result").show(1, False)
```

###  Your Environment

- Spark NLP version sparknlp.version(): 4.2.7
- Apache NLP version spark.version: 3.3.1
- Java version java -version: OpenJDK 64-Bit Server VM Zulu11.60+19-CA (build 11.0.17+8-LTS, mixed mode)
- Setup and installation (Pypi, Conda, Maven, etc.): Conda / Maven same issue
- Operating System and version: MacOS Ventura 13.1 on Apple M1 Max

**Comment by DevinTDHa** [comment]
Hi @pds2208 ,

The Wav2Vec Annotators are not supported for M1 processors. Unfortunately XLA is not supported on M1 yet. This only affects the Wav2Vec type annotators at the moment.

There is a note on the official documentation for it:
https://nlp.johnsnowlabs.com/docs/en/transformers#wav2vec2forctc

I will update the notebook you referred to, so that it is consistent. Thanks for reporting!

**Comment by jlindsay** [comment]
Has this issue been resolved yet? I was trying wav2lip on mac m1 recently, and I can't get it to work with the CPU or metal.
