### ISSUE TITLE
SPARK NER with Bert embedding for custom annotated dataset returning the output as out of entity tag

### ISSUE THREAD

**Issue by Covedis** [JohnSnowLabs/spark-nlp#13404]
## Steps to Reproduce

1.

2.

3.

4.

 

## Your Environment

* Spark NLP version `sparknlp.version()`:

* Apache NLP version `spark.version`:

* Java version `java -version`:

* Setup and installation (Pypi, Conda, Maven, etc.):

* Operating System and version:

* Link to your project (if any):

 Hi Team,
I am facing issue in training the spark ner with bert embedding or elmo embedding when trying to train the ner model with custom dataset, I have here attached both dataset and code ( Both are open source only ).

Issue : Testing the model with eval or testing or even trained dataset getting the output as 'O' ( out of entity) not sure where it going wrong, but i have done as mentioned in the article, correct me if i a wrong.

Process:
**Data source** : Extracted opensource from internet and had annotated in the label studio ( ref : gitconll.conll)
**reading file** : using CONNll class have read the file and generated the sentence , token ,pos for the text in the above reference file
**Training process** : Bert embedding and Nerapproach  and pipeline executed for fitting the model with training dataset
**volume of the dataset** : training has 10 rows , each rows has 50-70 words and 5-9 are annotated words among them.
**model inferencing:** : loaded the saved model with nermodel and passed with nerconverter pipeline

Output : getting all output as O out of entity in the ner label column

not sure why its happening even for CONNll dataset has happens too.

Please correct me if i am wrong.

**Comment by maziyarpanahi** [comment]
@Covedis 

Short answer: There is absolutely nothing in this issue that we can help with. 

Long answer. You are missing every single required information we asked in the template, this is not a common issue and we need an end-to-end notebook that helps us to reproduce this problem. Could be a simple `input conll has a bad schema`, or it could be a feature request, but either way we need to reproduce it and there is nothing here that helps us doing that.

**Comment by Covedis** [comment]
Thanks @maziyarpanahi  for the reply and inputs for the NER training material, It helps me lot in last week.
I had gone through the both notebooks referred in the link of how CONll dataset to be created and all.
 
Here I have one question , assume i have trained the SPARK NER with balanced amount of dataset in weights of class equally and got good F1 score , precision & Recall as well, hence further I tried to test the model with some more relevant datasets by loading the model.
Here I can extract only when i am giving long sentences or full form of labeled entities. but when in case of short / sentences are unable to spot the text.
 
For eg: **Annotated txt** : I have **BMW G 310R 2022 BS VI** in India
My Input while testing the model :  **BMW G**
 
Output : I can get the Extraction of BMW G 310R 2022 BS VI only when i giving full Annotated text , not when trying with mentioned **My Inputs**.

This is the just sample mostly long sentences are only extracting
 
Do you have any suggestion for this.

**Comment by maziyarpanahi** [comment]
You are welcome. When it comes to extracting entities (not just labels), your IOB/IOB2 schema helps you a lot. You must annotate enough labels where the begins and middle/end are helping to extract different parts.

Is `BMW G 310R 2022 BS VI` annotated as 1 entity like `CAR_MODEL`. Or was it annotated as (`BMW`, `B-CAR_MODEL`), (`G`, `I-CAR_MODEL`) (`310R`, `I-CAR_MODEL`) (`2022`, `I-CAR_MODEL`) (`BS`, `I-CAR_MODEL`) (`VI`, `I-CAR_MODEL`)

You get the idea from this short example. And the more you have detailed annotated examples the better. Unfortunately, this mostly falls under text annotations rather than Spark NLP as we don't offer any annotation tools. I would recommend searching `best practices to annotate text for named entity recognition` online for better examples.

**Comment by Covedis** [comment]
Hi @maziyarpanahi 
It's exactly as like below I mentioned

its annotated as (BMW, B-CAR_MODEL), (G, I-CAR_MODEL) (310R, I-CAR_MODEL) (2022, B-CAR_YEAR) (BS, B-CAR_ENGINE_MODEL) (VI, I-CAR_ENGINE_MODEL)

Like this in very detailed way have annotated and trained still found some short fall on extracting from small sentences

**Comment by maziyarpanahi** [comment]
Very nice, I would also search for `data augmentation` to generate more data from the already annotated dataset to create much bigger dataset that has shorter/longer/etc. to cover most use cases. (I saw people using ChatGPT now to create annotated examples!)

Any way you can add more examples especially with length the better. (we are not looking for 30k, the CoNLL 2003 has 12k sentences, but they cover lots of use cases, repeating the same entities within the same sentence, etc.) - I would also try different word embeddings with case-sensitivity for comparisons.

Best of luck

**Comment by Covedis** [comment]
Thanks @maziyarpanahi for the suggestion , can you please share a notebook or Py file which use Streamlit with Ner work related.

Specifically it would be helpful if that it can run on vs tool.
