### ISSUE TITLE
TypeError: setInputCols in ClassifierDLModel_067520557d6d expecting 1 columns. Provided column amount: 2. Which should be columns from the following annotators: ['sentence_embeddings']

### ISSUE THREAD

**Issue by Adesoji1** [JohnSnowLabs/spark-nlp#13438]
<!
![Screenshot from 2023-01-30 23-47-19](https://user-images.githubusercontent.com/20457308/215613704-adf7405c-817d-4918-8457-e28e8b196304.png)
  !-->

<!-
![in running the line called   document_classifier = ClassifierDLModel.pretrained(model_name)\
  .setInputCols(['document', 'sentence_embeddings']).setOutputCol("class")
 -->
it gives an error attaced in the screenshot

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version `sparknlp.version()`:
* Apache NLP version `spark.version`:
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi @Adesoji1 

ClassifierDLModel only requires 1 column, you should only use `['sentence_embeddings']` and remove the other column as the error stating.

Is this one our notebooks? If yes, please let me know and I will fix the extra column.

**Comment by Adesoji1** [comment]
Hi @maziyarpanahi  yes it is one of your notebooks, kindly fix it on google colab. in addition , i want to ask, how do i use my personal csv file to train a fake news classifer using johnsnow's lab fake news classification using nlu.load('mypersonalorcustomcsvfile')?

**Comment by maziyarpanahi** [comment]
- Thanks, if you provide the link I can fix it. (we have many examples)
- You are using NLU library, you can ask here if you have any questions: https://github.com/JohnSnowLabs/nlu
- There is a full example of how to train a classifier in Spark NLP just in case you want to use Spark NLP: https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/5.Text_Classification_with_ClassifierDL.ipynb

There are many other examples for training NLP tasks and how the data must look like in this repository https://github.com/JohnSnowLabs/spark-nlp-workshop

**Comment by Adesoji1** [comment]
https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/streamlit_notebooks/CLASSIFICATION_EN_FAKENEWS.ipynb , this is the link, I feel that your answer should be seen in the codes so that another person won't make the same mistake I made previously

**Comment by maziyarpanahi** [comment]
thanks, I'll reported that directory to be updated with the new changes in our latest releases.

**Comment by C-K-Loan** [comment]
Hi @Adesoji1  take a look at the docs & tutorials for training classifiers with NLU https://nlu.johnsnowlabs.com/docs/en/training

The entire Spark Notebook you shared can be condensed into 1 line with NLU: 

`nlp.load('train.sentiment').fit(pd.read_csv('datasets/train.csv')).predict('Super haxx in 1 line')`


You just need to make sure the CSV has 2 columns, one named `text` and one named `y` for the label. 
NLU expects pandas data frame, so you just use `pd.read_csv()` and nlu handles the rest
The rest is handled automagically

Thanks for contributing to making <3

**Comment by C-K-Loan** [comment]
@Adesoji1 

```python
pretraiend_pipe = nlp.load('train.sentiment').fit(pd.read_csv('datasets/train.csv'))

pretraiend_pipe.predict('Super haxx in 1 line')
```
will return you a new pandas DF with the labels predicted. 
For how to work with CSV files, see pandas tutorials please
