### ISSUE TITLE
AnnotationToolJsonReader version 2.7.2

### ISSUE THREAD

**Issue by aydinmyilmaz** [JohnSnowLabs/spark-nlp#1343]
AnnotationToolJsonReader module (version 2.7.1 and 2.7.2) doesn't convert json files from Annotation Tool. 
Version 2.7.0 works properly.
## Description

Py4JJavaError: An error occurred while calling o79.readDataset.
: java.util.NoSuchElementException: key not found: T2QXy5kw_u

![image](https://user-images.githubusercontent.com/29075537/103106406-93188200-4635-11eb-85a1-9828a70c576a.png)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version:
* Apache NLP version:
* Java version (java -version):
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,
This repo is only for supporting the open-source Spark NLP. We don’t have the knowledge of what other products are.
Please use the Slack channel for the healthcare products or ask the person who gave you the license key. They’ll get back to you quickly.
