### ISSUE TITLE
Aws Access Denied when trying to download any model

### ISSUE THREAD

**Issue by thekevshow** [JohnSnowLabs/spark-nlp#13453]
## Expected Behavior

That the model should download. 

## Current Behavior

Access denied when trying to download the model in anyway available. 

## Steps to Reproduce

1. try using from code new PretrainedPipeline( with an acceptable model (will fail in code)
2. second option would be to just place the [https://](https://s3.amazonaws.com/) prefix for any model/ file. You will see access denied in browser.
3.
4.

## Context

Started playing with this today so since today. 

## Your Environment

* Spark NLP version `sparknlp.version(4.2.8)`:
* Apache NLP version `spark.version`:
* Java version `java -version`: 17
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version: Windows 11
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Cloud you please provide the steps and the code to reproduce this issue? Unless what you are trying to download is `licensed`, every `open source` model/pipeline is easily downloadable from Models Hub: https://nlp.johnsnowlabs.com/models?edition=Spark+NLP

**Comment by thekevshow** [comment]
I'm sorry we can close this I think I realized that these have since become private. Thank you.
