### ISSUE TITLE
GPU support on mac m1

### ISSUE THREAD

**Issue by nemesis00sam** [JohnSnowLabs/spark-nlp#13540]
### How could the documentation be improved?

I'm trying to run the model on MacBook m1. Thanks to the documentation, I can run it. But when I follow the logs, it looks like it is utilizing CPU source not GPU. As I also have Tensorflow on my computer, I can see that it can use GPU. Do you support GPU? My version is 4.2.8. 

Thanks in advance.

**Comment by maziyarpanahi** [comment]
Hi,
We can only support what the official TensorFlow supports. To be honest, they are not even supporting M1/M2 in the same package, you have to install something else for Apple Silicon.
But we managed to make it work for Apple Silicon, however, we need the official support from Google when it comes to GPU on M1/M2 and I have the feeling that it's not a priority for them considering the M1 has been out for a while and there is no simple and straightforward forward to do pip install tensorflow-gpu on macOS today.
Unfortunately, at the moment the GPU on macOS cannot be supported unless it's an external NVidia.
