### ISSUE TITLE
Param engine does not exist.

### ISSUE THREAD

**Issue by LukeArrigoni** [JohnSnowLabs/spark-nlp#13562]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### What are you working on?

I’m working on a SparkNLP project on Azure Databricks, trying to do inference.

### Current Behavior

 and we’ve hit a bug we’ve been struggling with and Google is of no help on.
We convert out hugging face model to a sparknlp model
We setup and call the following line:
```
encoder = BertSentenceEmbeddings.load('/tmp/models/' + bert_model_name)\
 .setInputCols("document")\
 .setOutputCol("sentence_embeddings")
```
3. We get this error: `Param engine does not exist.`
Has anyone come across this? It’s just vague enough that it’s hard for us to understand where its coming from.

### Expected Behavior

We expect that the inference should take place.

### Steps To Reproduce

Convert this model:
https://huggingface.co/sentence-transformers/multi-qa-mpnet-base-dot-v1
into a Spark NLP model and run it on Azure Databricks.

### Spark NLP version and Apache Spark

Azure Databricks
Python 3
Spark NLP version 4.2.2
Apache Spark version: 3.3.0

**Comment by maziyarpanahi** [comment]
Hi,

Could you please update your Spark NLP from `4.2.2` to  `4.3.1`?

**Comment by LukeArrigoni** [comment]
That fixed the issue. 

Thanks!

**Comment by KhanjanD** [comment]
Hello, I am getting the same error

**Model**: `t5_base`
**Apache Spark**: `2.4.3`
**Spark NLP**: `3.3.4`
**Model URL**: https://sparknlp.org/2021/01/08/t5_base_en.html

Can you please help?

**Comment by maziyarpanahi** [comment]
The solution is to update to the latest for both spark-nlp and pyspark (you are on very old versions)

just in case, could you please copy and paste the full error trace here? Maybe there is something to do if you cannot update your spark version
