### ISSUE TITLE
Could not download the SBERT embedding while I can download universal sentence embeddings 

### ISSUE THREAD

**Issue by rajamed** [JohnSnowLabs/spark-nlp#13578]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### Who can help?

@mz

### What are you working on?

Hello mazi, thanks for the resolving previous issues, am reporting an issue, SBERT(PUBMED) embedding is not getting downloaded. But i can download SBERT large (1.2 GB) and try to train a model, but it did not start the training. Whereas I can easily download the Universal sentence encoder and i can finish the training in 2 hrs. Please help me out in resolving this issue.

### Current Behavior

Embedding above mentioned is not getting downloaded and cannot train the model.

### Expected Behavior

It must train as like universal sentence embedding. 

### Steps To Reproduce

bio = BertSentenceEmbeddings.pretrained("sent_biobert_pubmed_base_cased", "en") \
.setInputCols("sentence") \
.setOutputCol("sentence_embeddings")

### Spark NLP version and Apache Spark

spark-nlp==4.3.0
pyspark==3.2.1

**Comment by maziyarpanahi** [comment]
Please provide a link to a Colab notebook where we can see the code and the error.

**Comment by rajamed** [comment]
@maziyarpanahi hello mazi am sorry i cant upload the error and data into colab due to compliance. let me share the code snippet which the model got trained in Universal Sentence Embedding and model does not even start training in sbert. 

`document = DocumentAssembler()\
  .setInputCol("text")\
  .setOutputCol("document")\
  .setCleanupMode("shrink")

sentence_detector=SentenceDetector() \
    .setInputCols(["document"]) \
    .setOutputCol("sentence") 

bio = BertSentenceEmbeddings.pretrained("sent_biobert_pubmed_base_cased", "en") \
.setInputCols("sentence") \
.setOutputCol("sentence_embeddings")

multiClassifier = MultiClassifierDLApproach()\
  .setInputCols("sentence_embeddings")\
  .setOutputCol("category")\
  .setLabelColumn("labels")\
  .setBatchSize(128)\
  .setMaxEpochs(40)\
  .setLr(1e-3)\
  .setThreshold(0.3)\
  .setEnableOutputLogs(True)\
.setOutputLogsPath('logs')\
.setShufflePerEpoch(True)\

  

pipeline = Pipeline(
    stages = [
        document,
        sentence_detector,bio,
        multiClassifier
    ])

pipelineModel = pipeline.fit(train)`

Please help me out in resolving this issue.

**Comment by maziyarpanahi** [comment]
There is no bug with `BertSentenceEmbeddings` annotator nor their models, compare to USE the models in BERT are 10x slower because BERT is computational. 

- you can test this by using a very small dataset just to see it's working
- you just need increase your resources or use a smaller model

These series of questions seem to be just discussion, please ask them on Slack if they are not actually bugs.
