### ISSUE TITLE
IllegalArgumentException: requirement failed: Found input column with storage metadata. But such ref does not match to the ref this annotator requires. Make sure you are loading the annotator with ref: tfhub_use

### ISSUE THREAD

**Issue by rajamed** [JohnSnowLabs/spark-nlp#13572]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### Who can help?

Hello @maziyarpanahi  need your help and support I just trained the multi label text classifier, using Bert  sentence encoder. When I tried to load the model after saving that in a folder i get this error. Pls check out the code i have used. 

`pipelineModel.stages[-1].write().overwrite().save('/home/dswuser/workspace/kirubr1_personal/wsb40')`
`multiClassifier = MultiClassifierDLModel.load("/home/dswuser/workspace/kirubr1_personal/wsb40") \
  .setInputCols(["sentence_embeddings"])\
  .setOutputCol("category")\
  .setThreshold(0.2)`
`pipeline = Pipeline(
    stages = [
        document,
       sentence_detector,bert_embeddings,
        multiClassifier
    ])`

`pipeline.fit(test).transform(test)` when I try to fit and transform at this step am getting this error.  can you help me out.

### What are you working on?

Am trying to a build my own custom multi label classifier and facing this issue when I try to load the model. 

### Current Behavior

IllegalArgumentException: requirement failed: Found input column with storage metadata. But such ref does not match to the ref this annotator requires. Make sure you are loading the annotator with ref: tfhub_use

### Expected Behavior

Proper inference 

### Steps To Reproduce

I have shared the code in the above form

### Spark NLP version and Apache Spark

spark==3.2.1
Spark-nlp=4.3.0

**Comment by maziyarpanahi** [comment]
you trained your model by using a specific Embeddings' model, you must use the exact same Embeddings' model for prediction. `tfhub_use`

Please use the exact same annotator/model you used for training, the model and embeddings go hand in hand.
