### ISSUE TITLE
Models compatible with Spark NLP

### ISSUE THREAD

**Issue by LiJianGuo2333** [JohnSnowLabs/spark-nlp#13599]
### Link to the documentation pages (if available)

Hi there,

I am confused about the use of the annotation platform NLP Lab. I have noticed that only **Spark NLP-compatible** custom models can be uploaded. It seems a little bit unclear to me. If I want to use a custom pretrained LLM model which cannot be accessed directly from one line code API calling like `model = AutoModel.from_pretrained("bert-base-uncased")`, do I need another processing? More specifically, the deep learning framework I use is [paddlepaddle](https://github.com/PaddlePaddle/Paddle), if pretrained models are transformed into TF, can these models be uploaded and used to pre-annotation in NLP Lab?

Best regards

### How could the documentation be improved?

The introduction about uploading custom models in NLP Lab for pre-annotation seems a little bit unclear, so it would be better if more details can be explained.

**Comment by maziyarpanahi** [comment]
Hi,

The documentation is only hosted in the repo, but the maintainers of this repository are only supporting Spark NLP. For any questions regarding other libraries you can use Slack (there is a channel dedicated for each library): 
https://join.slack.com/t/spark-nlp/shared_invite/zt-198dipu77-L3UWNe_AJ8xqDk0ivmih5Q

I close this as we just don't know anything about NLP Lab, but you can use the link for a reference when you are asking your question on Slack.

PS: You can import models from HF into Spark NLP and this is the list of all compatible models/architecture with notebooks showing how to: https://github.com/JohnSnowLabs/spark-nlp/discussions/5669
