### ISSUE TITLE
Low GPU utilisation on NerDLModel prediction

### ISSUE THREAD

**Issue by Tasos1** [JohnSnowLabs/spark-nlp#13665]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### Who can help?

Maziyar Panahi

### What are you working on?

I followed the Spark NLP workshop on NerDLApproach to train a Ner model:
https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/4.NERDL_Training.ipynb

I trained the model successfully and I'm able to use the prediction pipeline to predict new documents. 

I'm interested to understand how Spark NLP utilizes the GPU on prediction as I'm observing low GPU utilization compared to the GPU utilization during training.

This is somewhat of a more detailed follow-up to #13602 .  As you suggested in #13602 I was able to predict many times faster on CPU with more workers and partitioning but still want to understand if this can be optimized further on GPU.

### Current Behavior

The prediction takes around 15 minutes for 50K documents. When monitoring the metrics I observe the following:

 Prediction for this run starts at **18:17**

Left = worker1, middle = driver, Right = worker2

### GPU util
![image](https://user-images.githubusercontent.com/10477529/225410620-8bf9c05d-91f8-465b-bfed-7a2322e1a8a7.png)

### GPU mem util
![image](https://user-images.githubusercontent.com/10477529/225410986-bedba418-75ef-42dc-ade2-8becfab71745.png)

### Mem report
![image](https://user-images.githubusercontent.com/10477529/225411149-1c4d477b-5175-41e0-8328-6052c6e5f45a.png)

### CPU report
![image](https://user-images.githubusercontent.com/10477529/225411251-cdbfa5e0-eb99-4a2a-9cdc-c6df69ecebf8.png)

### Expected Behavior

I was expecting to see GPU behaviour similar to the training of the model - see utilization during training

Left = worker, Right = driver

### GPU util
![image](https://user-images.githubusercontent.com/10477529/225406858-1a90d3a4-1af6-46ce-82f4-2cf5f5cc4649.png)

### GPU mem util
![image](https://user-images.githubusercontent.com/10477529/225410158-e8aeca18-c4ca-4303-9fab-b1ff5b94fe12.png)

### Steps To Reproduce

# Infrastructure
Databricks Runtime: 12.1 ML (includes Apache Spark 3.3.1, GPU, Scala 2.12)
GPU: Standard_NC4as_T4_v3 (1 Driver (28GB) + 2 workers (28GB each) )

# Train Model
```
# Load Libraries
import sparknlp
from sparknlp.base import *
from sparknlp.annotator import *
from sparknlp.training import CoNLL
import pyspark.sql.functions as F

# Load training data
training_data = CoNLL().readDataset(spark, '/xxxxxx/xxxxx/eng.train').limit(5000)
training_data.cache()


# Training Pipeline
glove_embeddings = WordEmbeddingsModel.pretrained('glove_100d')\
                      .setInputCols(["document", "token"])\
                      .setOutputCol("embeddings")

nerTagger = NerDLApproach()\
              .setInputCols(["sentence", "token", "embeddings"])\
              .setLabelColumn("label")\
              .setOutputCol("ner")\
              .setMaxEpochs(3)\
              .setLr(0.003)\
              .setBatchSize(32)\
              .setRandomSeed(0)\
              .setVerbose(1)\
              .setValidationSplit(0.2)\
              .setEvaluationLogExtended(True) \
              .setEnableOutputLogs(True)\
              .setIncludeConfidence(True)\
              .setEnableMemoryOptimizer(True)

    
ner_pipeline = Pipeline(stages=[glove_embeddings,
                                nerTagger])

# Train model
ner_model = ner_pipeline.fit(training_data)

# Save model
ner_model.stages[1].write().overwrite().save("/xxxxxx/xxxxxxx/spark_nlp_workshop_test_model")


```

# Pre-process new data

```
# Pre-process pipeline
document = DocumentAssembler()\
            .setInputCol("text")\
            .setOutputCol("document")

sentence = SentenceDetector()\
            .setInputCols(['document'])\
            .setOutputCol('sentence')

token = Tokenizer()\
            .setInputCols(['sentence'])\
            .setOutputCol('token')

glove_embeddings = WordEmbeddingsModel.pretrained('glove_100d')\
            .setInputCols(["document", "token"])\
            .setOutputCol("embeddings")
  
ner_preprocess_pipeline = Pipeline(
    stages = [
        document,
        sentence,
        token,
        glove_embeddings
        ])

# Set up pipeline
empty_data = spark.createDataFrame([['']]).toDF("text")
preprocess_model = ner_preprocess_pipeline.fit(empty_data)


# Create dummy data for prediction
text = """Peter Parker is a nice guy who lives in New York. In his spare time he dresses up as Spiderman and fights
against the bad guys, whether they are in New York or in another city such as Chicago. His arch enemy is Norman Osborn, also know as the Green Goblin.
Norman Osborn's favourite phone is the iPhone by Apple. Once he tried to use an Android phone but got so confused that not even his super powers could help
him. He got so angry that he decided that all humanity should use iPhones and devised an evil plan to replace all Androids with iPhones. Peter Parker, an iPhone man himself,
could see why the Green Goblin got so upset but the kindness in his heart could not let all the Android users suffer. And so he defeated the Green Goblin once more and saved the humanity from a monopoly, although he thought that maybe a duopoly or oligopoly was still not enough choice for people. He then used his spidey senses to create a new smartphone called the
SpiderPhone. He built millions of them. All he has to do now is set up a marketing team and a launch event to convince people to use his product."""

sample_data = spark.createDataFrame([[text]] * 50000).toDF("text")


# Transform prediction data
df_preprocessed = preprocess_model.transform(sample_data)


# Save transformed data
df_preprocessed \
  .write \
  .format("delta") \
  .mode("overwrite") \
  .option("overwriteSchema", "true") \
  .saveAsTable("database.sparknlp_workshop_test_preprocessed_50K") 

```

# Predict Transformed data

```
# Load back transformed data
df_preprocessed = spark.sql("""
                               select *
                               from database.sparknlp_workshop_test_preprocessed_50K
                              """)


#Set up prediction pipeline
loaded_ner_model = NerDLModel.load("/xxxxx/xxxxxx/spark_nlp_workshop_test_model")\
            .setInputCols(["sentence", "token", "embeddings"])\
            .setOutputCol("ner")

converter = NerConverter()\
            .setInputCols(["document", "token", "ner"])\
            .setOutputCol("ner_span")

ner_prediction_pipeline = Pipeline(
    stages = [
        loaded_ner_model,
        converter
        ])


# Predict 
df_preds = ner_prediction_pipeline.fit(df_preprocessed).transform(df_preprocessed)


# Save predictions
df_preds \
  .write \
  .format("delta") \
  .mode("overwrite") \
  .option("overwriteSchema", "true") \
  .saveAsTable("database.sparknlp_workshop_test_predictions") 

```

### Spark NLP version and Apache Spark

Spark NLP: 4.3.2
Spark: 3.3.1

**Comment by maziyarpanahi** [comment]
Hi,

NerDL is a very light and small DL model in TensorFlow. Maybe for training GPU can be beneficial especially with transformers, but for inference with GloVe you won't see much activity. 

If you are using BERT or other Transformer-based models then GPU can be very useful. I would say you would see more speed if you partition your DataFrame to the number of cores in your cluster and parallelize it on CPUs. (GPU is only good if you have transformers in your pipeline)

Here is a great zero to hero guide for CPU vs. GPU and partition: https://www.johnsnowlabs.com/watch-webinar-speed-optimization-benchmarks-in-spark-nlp-3-making-the-most-of-modern-hardware/

**Comment by maziyarpanahi** [comment]
PS: I forgot to mention partitioning is really important for both CPU and GPU. This right here, you need to make sure it's not 1 partition:

```
# Create dummy data for prediction
text = """Peter Parker is a nice guy who lives in New York. In his spare time he dresses up as Spiderman and fights
against the bad guys, whether they are in New York or in another city such as Chicago. His arch enemy is Norman Osborn, also know as the Green Goblin.
Norman Osborn's favourite phone is the iPhone by Apple. Once he tried to use an Android phone but got so confused that not even his super powers could help
him. He got so angry that he decided that all humanity should use iPhones and devised an evil plan to replace all Androids with iPhones. Peter Parker, an iPhone man himself,
could see why the Green Goblin got so upset but the kindness in his heart could not let all the Android users suffer. And so he defeated the Green Goblin once more and saved the humanity from a monopoly, although he thought that maybe a duopoly or oligopoly was still not enough choice for people. He then used his spidey senses to create a new smartphone called the
SpiderPhone. He built millions of them. All he has to do now is set up a marketing team and a launch event to convince people to use his product."""

sample_data = spark.createDataFrame([[text]] * 50000).toDF("text")
```

You have to use .repartition(N) and making sure it is distributed via Spark UI over executors

**Comment by Tasos1** [comment]
Thank you for the quick reply.

**CPU Performance**
I have followed the tutorial and your suggestions. Definitely seeing major improvement on speed with CPU and .repartition(N), where N = number of total cores. 

I have also seen that the improvement is linear so 2 workers with 8 cores each (16 partitions) vs 10 workers with 8 cores each (80 partitions) is about 5 times faster.

**GPU Performance - Standard_NC4as_T4_v3  with 2 workers -  4 vCPUs per worker**
For GPU, .repartition(N) does not seem to make much difference in speed. I have tried  .repartition(4) and .repartition(8), .repartition(32) and getting about the same speed and the same GPU utilization. 

Also, the actual partitioning looks fragmented on the GPUs (compared to the CPU where it was one non-stop green line per core like in the tutorial you shared).

**GPU cluster: df.repartition(1)**
![image](https://user-images.githubusercontent.com/10477529/225688226-3464a6fa-fe67-44e7-a4f2-3b90c0839ec0.png)


**GPU cluster: df.repartition(4)**
![image](https://user-images.githubusercontent.com/10477529/225688307-9fa75997-9086-4913-b884-97db0342ba8a.png)


**GPU cluster: df.repartition(8)**
![image](https://user-images.githubusercontent.com/10477529/225688341-52908eeb-b854-46a7-9bd7-a104129a0943.png)


**GPU cluster: df.repartition(32)**
![image](https://user-images.githubusercontent.com/10477529/225688377-2847d8ea-4b93-4d40-af3e-5beedf04c8e1.png)


**Or is it that for GPUs each worker is considered one core? so actually the best number of partitions is 2 if I have 2 workers?**

**Comment by maziyarpanahi** [comment]
- Glad you got the improvements with a correct level of parallelism. 
- GPU is different. Unlike CPU where each core can handle 1 task, here 1 GPU can handle 1 task. So the level of parallelism is a bit different and much harder to tune.
- If you try to use BERT in the pipeline for inference, you would see improvements by using GPU vs. CPU
- I suggest these articles (especially the provided code) to see how I change the parallelism and other confits on Databricks to tune GPU. (but again, my pipeline/tasks benefit greatly from GPU, NER is really light and CPUs would do better)

- https://blog.devgenius.io/scale-vision-transformers-vit-beyond-hugging-face-part-1-e09318cab588
- https://blog.devgenius.io/scale-vision-transformers-vit-beyond-hugging-face-part-2-b7b296d548b7
- https://blog.devgenius.io/scale-vision-transformers-vit-beyond-hugging-face-part-3-5b8c13ef6477
- Code: https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/tutorials/blogposts/medium/scale-vision-transformers-vit-beyond-hugging-face
