### ISSUE TITLE
Is there support to load models/pipelines from a custom s3 endpoint?

### ISSUE THREAD

**Issue by flowy0** [JohnSnowLabs/spark-nlp#13670]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### What are you working on?

I was looking at this notebook https://github.com/JohnSnowLabs/spark-nlp/blob/master/examples/util/Load_Model_From_S3.ipynb.

I'm running sparknlp on Spark on Kubernetes with an on-premise ECS server(AWS compatible)

Can i check if there is support for the filesystem s3a:// using the spark config `spark.hadoop.fs.s3a.endpoint` ?

### Current Behavior

I get this error
```
Error: Region argument is mandatory to create Amazon S3 client. (Service: null; Status Code: 0; Error Code: null; Request ID: null; Proxy: null)
```

My spark config looks like this:
```
builder = pyspark.sql.SparkSession.builder \
    .appName("Spark NLP") \
    .config("spark.sql.warehouse.dir", "/tmp/temp_warehouse") \
    .config("spark.driver.memory","16G")\
    .config("spark.driver.maxResultSize", "0") \
    .config("spark.kryoserializer.buffer.max", "2000M") \
    .config("spark.jsl.settings.pretrained.cache_folder", "s3a://mybucketname/tmp") 
```

### Expected Behavior

Would be great if i can load a model/pipeline from a remote location (S3 custom endpoint) 

### Steps To Reproduce

```python
from sparknlp.pretrained import PretrainedPipeline
from delta.pip_utils import configure_spark_with_delta_pip
import pyspark
import sparknlp

builder = pyspark.sql.SparkSession.builder \
    .appName("Spark NLP") \
    .config("spark.sql.warehouse.dir", "/tmp/temp_warehouse") \
    .config("spark.driver.memory","16G")\
    .config("spark.driver.maxResultSize", "0") \
    .config("spark.kryoserializer.buffer.max", "2000M") \
    .config("spark.jsl.settings.pretrained.cache_folder", "s3a://mybucket/tmp") 

   
spark = configure_spark_with_delta_pip(builder).enableHiveSupport().getOrCreate()
spark.sparkContext.setLogLevel("WARN")

logger = spark.sparkContext._jvm.org.apache.log4j.LogManager.getLogger(
    __name__
)

#download, load, and annotate a text by pre-trained pipeline
pipeline = PretrainedPipeline('recognize_entities_dl', 'en')
result = pipeline.annotate('Harry Potter is a great movie')
```

### Spark NLP version and Apache Spark

sparknlp version: 4.3.2
spark version: 3.3.1

### Type of Spark Application

Python Appliation

### Setup and installation

Pypi

**Comment by maziyarpanahi** [comment]
I use `s3:` which should be pretty much the same as `s3a:`. But you are missing all the required configs in order to access private S3 bucket. (the error will keep telling you what's missing, like this time the Region, next time something else until you have them all)


You need all these configs (they are mandatory):
https://github.com/JohnSnowLabs/spark-nlp/blob/master/examples/util/Load_Model_From_S3.ipynb

```python
    .config("spark.hadoop.fs.s3a.access.key", MY_ACCESS_KEY) \
    .config("spark.hadoop.fs.s3a.secret.key", MY_SECRET_KEY) \
    .config("spark.hadoop.fs.s3a.session.token", MY_SESSION_KEY) \
    .config("spark.hadoop.fs.s3a.aws.credentials.provider", "org.apache.hadoop.fs.s3a.TemporaryAWSCredentialsProvider") \
    .config("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem") \
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.12:4.1.0,org.apache.hadoop:hadoop-aws:3.3.1,com.amazonaws:aws-java-sdk:1.11.901") \
    .config("spark.hadoop.fs.s3a.path.style.access", "true") \
    .config("spark.jsl.settings.pretrained.cache_folder", "s3://my_bucket/my/models/") \
    .config("spark.jsl.settings.aws.region", "us-east-1") \
```

**Comment by maziyarpanahi** [comment]
PS: I forgot to mention I am using loading models/pipelines from S3 on both K8s cluster (since I don't have HDFS) and AWS Glue 4.0/5.0 cluster (again, no HDFS). I also use AWS ECS (FARGATE) via S3 since my models are private and I don't want to bundle those large models inside the Docker image.

The private S3 bucket works great (specially in the latest `4.3.2`)
