### ISSUE TITLE
Where can I see in the documentation what the token input limit is for transformer models?

### ISSUE THREAD

**Issue by Tasos1** [JohnSnowLabs/spark-nlp#13685]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### Who can help?

Maziyar Panahi

### What are you working on?

I'm creating embeddings for medium sized documents (100 - 1000 words) and trying various pre-trained models such as  "tfhub_use_lg". 

However, I can't see in the documentation any information about whether the model cuts off tokens after a limit (e.g. 512) and so I don't know whether I need to process the input data differently.

### Current Behavior

Cannot find any information in the documentation on the max number of input tokens for "tfhub_use_lg".

### Expected Behavior

Expecting clear information in the documentation of the max number of input tokens.

### Steps To Reproduce

I found the below info from the documentation but it's not explicit enough:

**Spark NLP model hub:** https://nlp.johnsnowlabs.com/2020/04/17/tfhub_use_lg.html

- "The input is variable length English text and the output is a 512 dimensional vector".

**TensorFlow Hub:** https://tfhub.dev/google/universal-sentence-encoder-large/5
- "The module performs best effort text input preprocessing, therefore it is not required to preprocess the data before applying the module."

### Spark NLP version and Apache Spark

sparknlp.version: 4.3.2
spark.version: 3.3.1

**Comment by maziyarpanahi** [comment]
the original models are the best reference. For instance, there is no limit for USE as the original URL has no mention of it, BERT and other similar transformers have 512 hard-coded limits.

- Always have a look at the reference of the model
- if there is a `setMaxSentenceLength` then the maximum is documented in the APIs
- if there is no `setMaxSentenceLength`, then there is no limit for length
