### ISSUE TITLE
MultiDateMatcher doesn't return more than one date

### ISSUE THREAD

**Issue by bunyamin-polat** [JohnSnowLabs/spark-nlp#13780]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### What are you working on?

I am using the MultiDateMatcher on the Agreement texts to get all the different date formats

https://sparknlp.org/docs/en/annotators#multidatematcher

### Current Behavior

There is more than one date in the texts, but only 1 date is being returned for MultiDateMatcher.

### Expected Behavior

I would like to get dates in all different formats

### Steps To Reproduce

https://colab.research.google.com/drive/1fG6yah-DLv49ByGX_GZnkpYJ5RlW7GZ8#scrollTo=b7f2c545-14d6-41da-a4cc-0dc8a6ea3180

### Spark NLP version and Apache Spark

`spark.version` = 3.3.1
`sparknlp.version()` = 4.4.1

**Comment by maziyarpanahi** [comment]
This should be fixed in 4.4.2 release: https://github.com/JohnSnowLabs/spark-nlp/pull/13783
