### ISSUE TITLE
The "get started with colab" notebook link is broken

### ISSUE THREAD

**Issue by AayushSameerShah** [JohnSnowLabs/spark-nlp#13840]
### Link to the documentation pages (if available)

1. Please reach on this section of this page: https://sparknlp.org/docs/en/install#google-colab-notebook
2. Try clicking on: [Spark NLP quick start on Google Colab](https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/quick_start_google_colab.ipynb)
3. The link doesn't open.

Preview:
![image](https://github.com/JohnSnowLabs/spark-nlp/assets/83115948/b4d80516-6cfc-4f78-be05-e0bbbc7e7495)

### How could the documentation be improved?

The link can be fixed.

**Comment by maziyarpanahi** [comment]
Hi @AayushSameerShah 

Many thanks for reporting this, I have fix the broken links and in 10-15 minutes the new changes will be reflected in the Website:

https://github.com/JohnSnowLabs/spark-nlp/commit/9f47bfe05a96385d4ca42c8ef56ba6d479b5e9af

**Comment by AayushSameerShah** [comment]
Done, thanks. Closing this issue 🤗
