### ISSUE TITLE
aws list read write commands not working when we start spark_nlp session

### ISSUE THREAD

**Issue by omkar-joshi-zs** [JohnSnowLabs/spark-nlp#13893]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### What are you working on?

running jsl model along with aws s3 read write operations which doesnot include jsl usage.

### Current Behavior

I am working on jupyter notebook hosted on aws service. 
aws s3 list,read,write commands not working when we start spark_nlp session.
If we restart the notebook and spark_nlp session is not started yet then i am able to perform aws s3 read, list,write operations.
I couldn't find spark nlp  stop session anywhere in the documentation.

### Expected Behavior

aws s3 commands should be working even if spark session is active.
spark nlp stop to be added in documentation

### Steps To Reproduce

import sparknlp

spark = sparknlp.start("secret key")

!aws s3 ls "s3 path."

### Spark NLP version and Apache Spark

3.4.0

**Comment by maziyarpanahi** [comment]
I am afraid this is incomplete

> I am working on jupyter notebook hosted on aws service. 

What service? How are you using Spark NLP in that service?

> spark = sparknlp.start("secret key")

There is no `secret key` in Spark NLP, what's this `secret key`?
