### ISSUE TITLE
Can we build custom langugage models?

### ISSUE THREAD

**Issue by vishalovercome** [JohnSnowLabs/spark-nlp#13892]
### Link to the documentation pages (if available)

I'm evaluating this project for some internal use case in company. I can see that this project supports a wide range of language models but what if I had a large corpus of documents that aren't necessarily English but structured documents where fields and values resemble various commonly spoken languages? How, if even possible, can we build a language model on Spark using this project? 

### How could the documentation be improved?

Perhaps have a section on the scope of the project and what it will and will not do.

**Comment by maziyarpanahi** [comment]
Hi,

The page dedicated to all available `transformers` / `LLMs` is here: https://sparknlp.org/docs/en/transformers

Each comes with an example of how one can import a LLM model and use it for inference. You cannot create a new LLM nor fine-tune one in Spark NLP, you can import them into this library to scale even on a single machine at it uses all the cores. (Also, all embeddings can be used to train other models we have)

Here is also a page to show how to import LLM models into Spark NLP: https://github.com/JohnSnowLabs/spark-nlp/discussions/5669
