### ISSUE TITLE
Assertion Error with PretrainedPipeline

### ISSUE THREAD

**Issue by kara-liu** [JohnSnowLabs/spark-nlp#13904]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### Who can help?

Hello. I am having the following error when I just try to run

`from sparknlp.pretrained import PretrainedPipeline  
pipeline = PretrainedPipeline( "icd10cm_umls_mapping","en","clinical/models")`

I get the following traceback.
I have java 8> installed. 
![Screen Shot 2023-07-27 at 10 17 32 PM](https://github.com/JohnSnowLabs/spark-nlp/assets/113812160/d7d72251-7589-455c-b3ee-c8526d77458e)

### What are you working on?

I am just trying to use the ICD10 to UMLs mapping.

### Current Behavior

Assertion Error related to Java (I think ?)

### Expected Behavior

No assertionerror, prediction of UMLs codes. 

### Steps To Reproduce

`from sparknlp.pretrained import PretrainedPipeline  
pipeline = PretrainedPipeline( "icd10cm_umls_mapping","en","clinical/models")`

### Spark NLP version and Apache Spark

5.0.1
NameError: name spark is not defined

### Type of Spark Application

Python Application

### Java Version

java version "1.8.0_381" Java(TM) SE Runtime Environment (build 1.8.0_381-b09) Java HotSpot(TM) 64-Bit Server VM (build 25.381-b09, mixed mode)

### Java Home Directory

/oak/stanford/groups/rbaltman/karaliu/jre1.8.0_381/

### Setup and installation

pip install 

### Operating System and Version

Linux 64

**Comment by maziyarpanahi** [comment]
Hi @kara-liu 

Your pipeline is licensed and is coming from another library. (it requires a licensed library) We don't have any knowledge nor access to that kind of information, you can either ask your question on [Slack](https://join.slack.com/t/spark-nlp/shared_invite/zt-198dipu77-L3UWNe_AJ8xqDk0ivmih5Q) (#healthcare channel) or maybe here: https://github.com/JohnSnowLabs/johnsnowlabs

**Comment by kara-liu** [comment]
Do I need a special license from you all to run this? I also don't have access to the slack because I don't have the proper domain.

**Comment by maziyarpanahi** [comment]
Everything in this repository and on this website is 100% free and open-source: http://sparknlp.org

We don't have any information about any commercial products, please refer to their Website and contact them directly
