### ISSUE TITLE
Doc2VecModel obtain vocabulary

### ISSUE THREAD

**Issue by wgeul** [JohnSnowLabs/spark-nlp#13930]
Before I ask the question, the key principle of using embedding encoders is that they should be, approximately, representative representations of the initial information (e.g. a string). The current implementation seems to not allow a user to verify this principle, because the vocabulary is inaccessible. Due to the missing vocabulary, I cannot run the embedding output through a decoder model to assess the accuracy of the representation relative to the ground truth.

I think this is a major issue. How am I to trust the embeddings without the ability to verify them?

The documentation of Doc2VecApproach contains this sentence:
_The algorithm first constructs a vocabulary from the corpus and then learns vector representation of words in the vocabulary. The vector representation can be used as features in natural language processing and machine learning algorithms._

I would like to retrieve the vocabulary of the Doc2VecApproach object. Is this possible?

Example:
```
import sparknlp

from sparknlp.base import *

from sparknlp.annotator import *

from pyspark.ml import Pipeline

documentAssembler = DocumentAssembler() \

    .setInputCol("text") \

    .setOutputCol("document")

tokenizer = Tokenizer() \

    .setInputCols(["document"]) \

    .setOutputCol("token")

embeddings = Doc2VecApproach() \

    .setInputCols(["token"]) \

    .setOutputCol("embeddings")

pipeline = Pipeline() \

    .setStages([

      documentAssembler,

      tokenizer,

      embeddings

    ])

path = "sherlockholmes.txt"

dataset = spark.read.text(path).toDF("text")

pipelineModel = pipeline.fit(dataset)
```

**Comment by maziyarpanahi** [comment]
The algorithm comes from Spark ML Word2Vec: https://spark.apache.org/docs/2.2.0/ml-features.html#word2vec

Unfortunately, the method that makes the final vocab-vector list is not implemented in Doc2VecModel nor in Word2VecModel.

This could be a feature request to make those methods available.

**Comment by wgeul** [comment]
Hi @maziyarpanahi.

Thank you for your message. I believe indeed the `getVectors()` function is what is missing in the implementation.
_Returns the vector representation of the words as a dataframe with two fields, word and vector._

https://spark.apache.org/docs/2.2.0/api/python/_modules/pyspark/ml/feature.html#Word2VecModel.getVectors
  
Thanks for adding it as feature request.

**Comment by maziyarpanahi** [comment]
You are welcome. I added this to our roadmap for `Word2VecModel`, `Doc2VecModel` and `WordEmbeddingsModel` since they all have the full `vocab` and `vector` statically.
