### ISSUE TITLE
spark-nlp 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by naydin2** [JohnSnowLabs/spark-nlp#13962]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### What are you working on?

internal data set

### Current Behavior

I'm using Zeppelin + EMR, inside zeppelin

```
%pyspark
import sparknlp
from sparknlp.base import LightPipeline, Pipeline, ReadAs, Finisher
from sparknlp.annotator import SentenceDetector, Tokenizer, DocumentAssembler, TextMatcher, BigTextMatcher
from pyspark.sql import functions as F
import pandas as pd

spark = sparknlp.start()


document_assembler = DocumentAssembler().setInputCol("text").setOutputCol("document")
```
it fails at `DocumentAssembler` line with

```
Fail to execute line 8: document_assembler = DocumentAssembler().setInputCol("text").setOutputCol("document")
Traceback (most recent call last):
  File "/tmp/python6933359071221497541/zeppelin_python.py", line 162, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 8, in <module>
  File "/usr/lib/spark/python/pyspark/__init__.py", line 139, in wrapper
    return func(self, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sparknlp/base/document_assembler.py", line 96, in __init__
    super(DocumentAssembler, self).__init__(classname="com.johnsnowlabs.nlp.DocumentAssembler")
  File "/usr/lib/spark/python/pyspark/__init__.py", line 139, in wrapper
    return func(self, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sparknlp/internal/annotator_transformer.py", line 36, in __init__
    self._java_obj = self._new_java_obj(classname, self.uid)
  File "/usr/lib/spark/python/pyspark/ml/wrapper.py", line 86, in _new_java_obj
    return java_obj(*java_args)
TypeError: 'JavaPackage' object is not callable
```

I set `spark.jars.packages` as `com.johnsnowlabs.nlp:spark-nlp_2.12:5.1.0`  still no luck. 

### Expected Behavior

Working fine without error.

### Steps To Reproduce

```
%pyspark
import sparknlp
from sparknlp.base import LightPipeline, Pipeline, ReadAs, Finisher
from sparknlp.annotator import SentenceDetector, Tokenizer, DocumentAssembler, TextMatcher, BigTextMatcher
from pyspark.sql import functions as F
import pandas as pd

spark = sparknlp.start()

# Create a dataframe from the sample_text
data = spark.createDataFrame([
["""As she traveled across the world, Emma visited many different places
and met many fascinating people. She walked the busy streets of Tokyo,
hiked the rugged mountains of Nepal, and swam in the crystal-clear waters
of the Caribbean. Along the way, she befriended locals like Akira, Rajesh,
and Maria, each with their own unique stories to tell. Emma's travels took her
to many cities, including New York, Paris, and Hong Kong, where she savored
delicious foods and explored vibrant cultures. No matter where she went,
Emma always found new wonders to discover and memories to cherish."""]
]).toDF("text")

%pyspark
# PERSON
person_matches = """
Emma
Akira
Rajesh
Maria
"""

with open('person_matches.txt', 'w') as f:
    f.write(person_matches)

# LOCATION
location_matches = """
Tokyo
Nepal
Caribbean
New York
Paris
Hong Kong
"""

with open('location_matches.txt', 'w') as f:
    f.write(location_matches)
    

%pyspark

from py4j.java_gateway import java_import
java_import(spark._sc._jvm, "org.apache.spark.sql.api.python.*")


# Step 1: Transforms raw texts to `document` annotation
document_assembler = DocumentAssembler().setInputCol("text").setOutputCol("document")

# Step 2: Gets the tokens of the text
tokenizer = Tokenizer().setInputCols("document").setOutputCol("token")

# Step 3: PERSON matcher
person_extractor = TextMatcher().setInputCols("document", "token").setEntities("person_matches.txt", ReadAs.TEXT).setOutputCol("person_entity")

# Step 4: LOCATION matcher
location_extractor = TextMatcher().setInputCols("document", "token").setEntities("location_matches.txt", ReadAs.TEXT).setOutputCol("location_entity")


# pipeline = Pipeline().setStages([document_assembler,
                                #  tokenizer,
                                #  person_extractor,
                                #  location_extractor
                                #  ])

```

### Spark NLP version and Apache Spark

spar version = '3.4.0-amzn-0'

spark nlp version = '5.1.0'

**Comment by maziyarpanahi** [comment]
In managed services like EMR, Glue, or Databricks you already have a SparkSession so `sparknlp.start()` doesn't really do anything. The session has started and any required packages/configs are not set. (SparkSession doesn't allow changing anything after it is started)

I never used Zeppelin inside EMR, but you do need 100% of all these steps to have an EMR setup correctly. (once you ssh to your Driver, you should be able to use a simple pyspark shell to test everything is working and from there you can probably set other required configs for Zeppelin. But these steps are mandatory)
https://github.com/JohnSnowLabs/spark-nlp#emr-cluster

**Comment by naydin2** [comment]
Hello Maziyar, I think you're talking about `spark.jars.packages`, but I set that inside Zeppelin config file, which is supposed to configure before Spark Context creation.

**Comment by naydin2** [comment]
@maziyarpanahi how can i validate if actually Maven is downloading the package? Also is there any spark configuration that might be disabling Maven?
Thanks.

**Comment by maziyarpanahi** [comment]
> @maziyarpanahi how can i validate if actually Maven is downloading the package? Also is there any spark configuration that might be disabling Maven?
> Thanks.

Zeppelin on local and YARN is different than the one on EMR. I am not sure they respect all the configurations, it definitely doesn't install `spark-nlp` PyPI on all the machines, etc.

If you follow those steps, you are 100% sure your EMR cluster has all the required spark configs. (then you can try to find out why that config is note working inside Zeppelin interpreters. We have Fat JARs as well, you can use `spark.jars` and point to [spark-nlp-assembly-5.1.0.jar](https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/jars/spark-nlp-assembly-5.1.0.jar) pointed at the end of each release notes: https://github.com/JohnSnowLabs/spark-nlp/releases/tag/5.1.0

PS: I can have a look at the Zeppelin, but I remember the Jupyter on EMR has lots of Magics to set Spark Configs for EMR. (not sure if it's the same for Zeppelin)

**Comment by naydin2** [comment]
Thanks Maziyar, Much appreciated :)

**Comment by naydin2** [comment]
@maziyarpanahi  Btw I tried to sign up for slack community channel but i think it's not allowing people to join from gmail addresses?

**Comment by maziyarpanahi** [comment]
I'll put new link here when they get expired: https://github.com/JohnSnowLabs/spark-nlp/issues/13963

**Comment by naydin2** [comment]
@maziyarpanahi I'm in thanks much :) I hope you have a great rest of your day.

**Comment by naydin2** [comment]
I just created a new cluster with above steps https://github.com/JohnSnowLabs/spark-nlp#emr-cluster 
But issue persists, I think somehow Zeppelin not installing Maven packages.
