### ISSUE TITLE
xlm roberta self defined data processing

### ISSUE THREAD

**Issue by yc0619** [JohnSnowLabs/spark-nlp#13976]
### Description

Hi,

i would like to ask, if the following task could be accomplished by sparknlp
1. extract the output of last 4 layers size (768, ) and concatenate to one (3072, )
2. get sentence embedding by do average to all (3072, ) tensors （1 tensor is 1 word）

best Regards.

### Preferred Solution

```
spark = SparkSession.builder \
    .appName("xlmRobertaSentenceEmbedding") \
    ...
    .getOrCreate()

df = spark.read.format("mongo").load()

document_assembler = ...
tokenizer =  ...

xlm_roberta_offline = XlmRobertaEmbeddings().load("str/to/model/dir") \
    .setInputCols(["doc_assembler", "token"]) \
    .setOutputCol("embeddings")

embedding_finisher = ...

processing_ppl = Pipeline(stages=[document_assembler, ..., embedding_finisher])
result = processing_ppl.fit(df).transform(df)
```

### Additional Context

I have already implemented UDF to do the processing. Since the UDF are most not optimized. So i want to try the processing directly with sparknlp. Is there any way to do the processing (take last 4 + concat + averaging) with the sparknlp.

**Comment by maziyarpanahi** [comment]
That's not possible regardless of where the model is coming from. There will be only 1 layer used to fetch the results in `XlmRobertaEmbeddings` which is called `last_hidden_state`. We don't have access to any other layers, there are no other layers when it comes to models on Hugging Face (not by default at least)

We also experimented with output layers way back in 2018 when BERT came out, there wasn't enough to implement multi-layer feature. 

We won't be implementing this feature, however, on the Python side if you can do this within the TensorFlow or ONNX where it takes the layers and sum/pool/concatenate and then output it as `last_hidden_state` then that could work. (we just feed some layers, and fetch this layer by name. as long as it exists and it is the same dtype and all the ops happen within TensorFlow or ONNX, it should be fine.)

**Comment by yc0619** [comment]
> That's not possible regardless of where the model is coming from. There will be only 1 layer used to fetch the results in `XlmRobertaEmbeddings` which is called `last_hidden_state`. We don't have access to any other layers, there are no other layers when it comes to models on Hugging Face (not by default at least)
> 
> We also experimented with output layers way back in 2018 when BERT came out, there wasn't enough to implement multi-layer feature.
> 
> We won't be implementing this feature, however, on the Python side if you can do this within the TensorFlow or ONNX where it takes the layers and sum/pool/concatenate and then output it as `last_hidden_state` then that could work. (we just feed some layers, and fetch this layer by name. as long as it exists and it is the same dtype and all the ops happen within TensorFlow or ONNX, it should be fine.)

Hi, thanks for the reply!
