### ISSUE TITLE
Support for multilingual-e5-large

### ISSUE THREAD

**Issue by davisuga** [JohnSnowLabs/spark-nlp#13978]
e5-large is already available in spark nlp, but I need to create multilingual embeddings. How can I do that?

**Comment by maziyarpanahi** [comment]
We have been looking into the multilingual offered model called e5 by the same author. However, the multilingual is not the same architecture, all the others are based on BERT, but the multilingual e5 is actually based on XLM-RoBERTa.

We will do our bests to to import and support multilingual e5 model soon

**Comment by davisuga** [comment]
Supported in spark-nlp 5.1.2+
https://sparknlp.org/2023/09/21/multilingual_e5_large_xx.html
