### ISSUE TITLE
Model downloader not working in databricks platform

### ISSUE THREAD

**Issue by saifjsl** [JohnSnowLabs/spark-nlp#140]
#Description 
It throws an error regarding the local cache directory missing (Since it doesn't have a local path really, it all handles DBFS filesystem

**Comment by jkabrg** [comment]
I think I'm experiencing the same problem. This is the exception:

`org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: /cache_pretrained/pos_fast_en_1.5_2_1522180653497/metadata`
