### ISSUE TITLE
Problems when exporting or transforming result after pipeline with Spark NLP

### ISSUE THREAD

**Issue by Criscas05** [JohnSnowLabs/spark-nlp#14011]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### Who can help?

@maziyarpanahi @DevinTDHa @danilojsl 

### What are you working on?

I am working on the implementation of a model to classify texts by emotions.

### Current Behavior

I import a Dataframe using Spark of 12700 rows and two columns which is quite small but I am using it as a test to take it over 100k data. When I try to export it (csv or parquet) or transform it to pandas it is fast and easy. 
When this Dataframe I enter it to the pipeline using Spark NLP to tokenize, use the BertForSequenceClassification emotion model and finally finisher, this pipeline result I try to export or transform it and it is not as easy as it was initially, it takes about an hour. I do not understand why this happens, if like before the pipeline is a Dataframe Spark.
If you are so kind you could help me with the solution to this problem, please.

### Expected Behavior

I expect the output of the Spark NLP pipeline to be easy to manipulate, as the Spark DataFrame that it is.

### Steps To Reproduce

Below I show the code I am using and explain the problem I am having:

spark = SparkSession.builder \
    .appName("Spark NLP")\
    .master("local[*]")\
    .config("spark.driver.memory","16G")\
    .config("spark.executor.memory","16G")\
    .config("spark.executor.cores", 3) \
    .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer")\
    .config("spark.driver.maxResultSize", "0") \
    .config("spark.kryoserializer.buffer.max", "2000M")\
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.12:5.1.1")\
    .getOrCreate()

df = spark.read.csv(path, header=True, sep=';', multiLine=True,encoding='UTF-8',escape="\"", inferSchema=True)\
df.show()

pand = df.toPandas() #I did it to test and it ran the transformation in 0.3 seconds.

document_assembler = DocumentAssembler() \
    .setInputCol('content') \
    .setOutputCol('document')

tokenizer = Tokenizer() \
    .setInputCols(['document']) \
    .setOutputCol('token')

sequenceClassifier = BertForSequenceClassification \
      .pretrained('bert_sequence_classifier_beto_emotion_analysis', 'es') \
      .setInputCols(['token', 'document']) \
      .setOutputCol('emotion') \
      .setCaseSensitive(True) \
      .setMaxSentenceLength(512)

finisher = Finisher() \
    .setInputCols('emotion') \
    .setOutputCols('emotion')

pipeline = Pipeline(stages=[
    document_assembler,
    tokenizer,
    sequenceClassifier,
    finisher])

result = pipeline.fit(df).transform(df)

result = result.withColumn("emotion", concat_ws(",", col("emotion"))) #I do this so that the columns are of String type
result = result.toPandas() #This process takes about an hour, which is not logical considering the small amount of data compared to what Spark supports.
result.write.parquet('Result_Emotion.parquet') # I tried exporting and it is the same, it takes a long time even using coalesce().

### Spark NLP version and Apache Spark

Spark NLP version 5.1.1
Apache Spark version: 3.2.4

### Type of Spark Application

Python Application, Java Application

### Java Version

java version "11.0.20" 2023-07-18 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.20+9-LTS-256) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.20+9-LTS-256, mixed mode)

### Java Home Directory

JAVA_HOME

### Setup and installation

Spark NLP I downloaded it from conda

### Operating System and Version

Windows 11 Enterprise, 21H2

### Additional Information

I understand that the Spark NLP process consumes resources, but after the Pipeline execution finishes these resources should be released. Thank you for your help, thank you very much.
Another thing is that every process I want to do with the result variable coming from the pipeline consumes 100% of the CPU.

**Comment by maziyarpanahi** [comment]
- as long as the SparkSession is active, it will use/reuse the allocate resources as it see it fit. You cannot tell it to release that 16G, it will loads all kinds of objects into the memory and it keeps reusing them. (you can keep starting and killing the SparkSession if you want to be released, but this will take time to keep restart it. Once it is allocated, it will consume the resources like any other application)
- You are using an BERT which is an large language model with at leat 300+ million parameters. It is fine-tuned for a Sequence Classification which you are using it for emotion analysis. This is a heavy task and a computationally expensive model. Using LLM will never be like simply loading and saving a CSV file, there are actual computations involved and even to this day,  using BERT is recommended on accelerated hardware like modern CPUs or GPUs. 
 
You can use Colab that has GPU and it's free, or provide more resources if it is too long on your machine, but the resources you have provided are very low. 3 cores of CPUs is really nothing for an LLM like BERT, I suggest just do a quick search regarding LLMs like BERT and see the idle required resources especially for the 100k. (even a none-LLM solution with static embeddings will require computations)
