### ISSUE TITLE
Error Token2Chunk: module 'sparknlp.annotator' has no attribute 'Token2Chunk'

### ISSUE THREAD

**Issue by hsaglamlar** [JohnSnowLabs/spark-nlp#14017]
https://github.com/JohnSnowLabs/spark-nlp/blob/74b8f230bc1547ee1b1152fbd19c111e8610f13c/python/sparknlp/base/token2_chunk.py#L75

While loading a PP which contains a Token2Chunk stage, the below failure occurs:

`AttributeError: module 'sparknlp.annotator' has no attribute 'Token2Chunk'`

Most probably the below change solve the problem:

`super(Token2Chunk, self).__init__(classname="com.johnsnowlabs.nlp.Token2Chunk") `

**Comment by maziyarpanahi** [comment]
Hi @hsaglamlar 

I saw a similar issue before and I think we fix it, could you please provide a small notebook to reproduce this? Might be something small we missed or a bug, we'll take it from there and fix it.

Thank you

**Comment by hsaglamlar** [comment]
Hi @maziyarpanahi , 

A similar problem exists with ChunkConverter, too. I prepared a NB for both. 

Thank you.

https://colab.research.google.com/drive/1yxU4Qb01zvPZIW8IUiDNBbkYej0vb9h6?usp=sharing

**Comment by maziyarpanahi** [comment]
Thanks @hsaglamlar 
Would you mind removing all the license parts and just have the open-source code remain? (it's easier to debug it this way).

Thank you

**Comment by hsaglamlar** [comment]
@maziyarpanahi, I removed the licensed part. BTW ChunkConverter is not an open-source annotator, so I removed it, too.

**Comment by maziyarpanahi** [comment]
Many thanks @hsaglamlar I'll take it from here and come back to you
