### ISSUE TITLE
can spark-nlp load tensorflow model?

### ISSUE THREAD

**Issue by zengshansong** [JohnSnowLabs/spark-nlp#141]
## Description

I want to use spark-nlp to load tensorflow model,  is there any method to do this?
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by saifjsl** [comment]
Hello, we are currently on development of TensorFlow based models that may be able to do this. Although our first use cases will be specific NER and Assertion Status models.

**Comment by saifjsl** [comment]
NerDLApproach and AssertionDLApproach are capable of training tensorflow models through provided graphs, and predict with Tensorflow. Closing this.
