### ISSUE TITLE
SparkSession should only be created and accessed on the driver

### ISSUE THREAD

**Issue by mahmoudaymo** [JohnSnowLabs/spark-nlp#14101]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### Who can help?

I am working on Databricks and using BertEmbeddings to embed a text that will later be used for a classification problem. The model name is "bert_base_cased",  But I keep getting this error:

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 20.0 failed 4 times, most recent failure: Lost task 0.3 in stage 20.0 (TID 26) (10.0.1.4 executor 0): java.lang.IllegalStateException: SparkSession should only be created and accessed on the driver.

### What are you working on?

```python
documentAssembler = DocumentAssembler().setInputCol("text").setOutputCol("document")
sentence = SentenceDetector().setInputCols("document").setOutputCol("sentence")
tokenizer = Tokenizer().setInputCols("sentence").setOutputCol("token")
bert_loaded = BertEmbeddings.pretrained("bert_base_cased", "en") \
    .setInputCols(["sentence", "token"]) \
    .setOutputCol("embeddings") \
    .setCaseSensitive(True)

embeddings_finisher = EmbeddingsFinisher() \
    .setInputCols(["embeddings"]) \
    .setOutputCols("embeddings") \
    .setOutputAsVector(True) \
    .setCleanAnnotations(False)

pipeline = Pipeline(stages=[documentAssembler, sentence, tokenizer, bert_loaded, embeddings_finisher])
data = spark.createDataFrame([["I love Spark NLP"]], schema=["text"])
result = pipeline.fit(data).transform(data)
result

```

### Current Behavior

org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 3.0 failed 4 times, most recent failure: Lost task 2.3 in stage 3.0 (TID 9) (10.0.1.4 executor 0): java.lang.IllegalStateException: SparkSession should only be created and accessed on the driver.

### Expected Behavior

```
Results

	token	en_embed_bert_base_cased_embeddings

	I	[0.43879568576812744, -0.40160006284713745, 0....
	love	[0.21737590432167053, -0.3865768313407898, -0....
	NLP	[-0.16226479411125183, -0.053727392107248306, ...

```

### Steps To Reproduce

```python
from sparknlp.base import *
from sparknlp.annotator import *
from pyspark.ml import Pipeline


documentAssembler = DocumentAssembler().setInputCol("text").setOutputCol("document")
sentence = SentenceDetector().setInputCols("document").setOutputCol("sentence")
tokenizer = Tokenizer().setInputCols("sentence").setOutputCol("token")
bert_loaded = BertEmbeddings.pretrained("bert_base_cased", "en") \
    .setInputCols(["sentence", "token"]) \
    .setOutputCol("embeddings") \
    .setCaseSensitive(True)

embeddings_finisher = EmbeddingsFinisher() \
    .setInputCols(["embeddings"]) \
    .setOutputCols("embeddings") \
    .setOutputAsVector(True) \
    .setCleanAnnotations(False)

pipeline = Pipeline(stages=[documentAssembler, sentence, tokenizer, bert_loaded, embeddings_finisher])
data = spark.createDataFrame([["I love Spark NLP"]], schema=["text"])
result = pipeline.fit(data).transform(data)
result

```

### Spark NLP version and Apache Spark

spark-nlp==5.1.4
spark==3.4.1
com.johnsnowlabs.nlp:spark-nlp_2.12:5.1.4

Working on Databricks

### Type of Spark Application

Python Application

### Java Version

8

### Java Home Directory

/usr/lib/jvm/zulu8-ca-amd64/jre/

### Setup and installation

Pypi

**Comment by maziyarpanahi** [comment]
Hi,

Could you please test the 5.2.0 release?

**Comment by mahmoudaymo** [comment]
I will, thanks.
