### ISSUE TITLE
Import Whisper large v3 into Spark NLP

### ISSUE THREAD

**Issue by minhduc210196** [JohnSnowLabs/spark-nlp#14150]
### Link to the documentation pages (if available)

I use instructions at the link

https://github.com/JohnSnowLabs/spark-nlp/discussions/5669

for whisper loud v3 but got the following error. Please help me solve it
![1231](https://github.com/JohnSnowLabs/spark-nlp/assets/147492971/e3511939-320d-4b83-aed6-645671b79e22)

### How could the documentation be improved?

Please help me solve it

**Comment by minhduc210196** [comment]
from sparknlp.annotator import *

whisper = (
    WhisperForCTC.loadSavedModel(f"/content/export_onnx/openai/whisper-large", spark)
    .setInputCols("audio_assembler")
    .setOutputCol("text")
    
 IllegalArgumentException: Size cannot be greater than Integer max value: 2547138560

**Comment by maziyarpanahi** [comment]
Hi @DevinTDHa 
Is this a limitation on Java or we hard-coded a dimension somewhere?

**Comment by DevinTDHa** [comment]
Hmm this is a very curious error, I don't think anything is hard coded that would cause this. I will update this thread, once I have found the underlying issue!

**Comment by DevinTDHa** [comment]
Hi @minhduc210196,

I am trying to reproduce it, but I don't get quite the same error. It also fails on my side, because the large model is split into a graph file (`*model.onnx`) and a file with the weights (`*model.onnx_data`).

Could you share your environment, so I could try to reproduce it?

**Comment by maziyarpanahi** [comment]
It seems ONNX models above 2G will be exported into `*model.onnx` and `*model.onnx_data` files. Similar to other models we have, we should also adapt Whisper to use that feature since it can go above 2G and not assume there will be 1 file. (we support `model.onnx_data`)
