### ISSUE TITLE
EntityRuler fails two basic tests

### ISSUE THREAD

**Issue by jfernandrezj** [JohnSnowLabs/spark-nlp#14187]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### Who can help?

@danilojsl @maziyarpanahi 

### What are you working on?

Matching Keyword Patterns from a list of known keywords

### Current Behavior

Both current behavior and desired behavior is documented in the branch with the failing tests:
https://github.com/JohnSnowLabs/spark-nlp/tree/issues/aho-corasick-failing-tests

### Expected Behavior

Both current behavior and desired behavior is documented in the branch with the failing tests:
https://github.com/JohnSnowLabs/spark-nlp/tree/issues/aho-corasick-failing-tests

### Steps To Reproduce

Just run the added tests in the branch:
https://github.com/JohnSnowLabs/spark-nlp/tree/issues/aho-corasick-failing-tests

### Spark NLP version and Apache Spark

Spark 3.4
Spark NLP 5.2.2

### Java Version

Java 11

**Comment by maziyarpanahi** [comment]
@jfernandrezj do you have a PR/fix for this issue?

**Comment by jfernandrezj** [comment]
A branch containing a potential fix for this issue is in:
https://github.com/JohnSnowLabs/spark-nlp/tree/issues/aho-corasick-failing-tests-fix-for-discussion
Please check it out and I can create a PR once we are ok

**Comment by danilojsl** [comment]
Hi @jfernandrezj 

LGFM I think you can create a PR for this
