### ISSUE TITLE
Can not find the model to download bge-m3

### ISSUE THREAD

**Issue by avivshafir** [JohnSnowLabs/spark-nlp#14243]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### What are you working on?

Sentence embedding in pyspark

### Current Behavior

The model is not being found

### Expected Behavior

Model should be found

### Steps To Reproduce

```
document_assembler = DocumentAssembler().setInputCol("text").setOutputCol("document")

sentencerDL = (
    SentenceDetectorDLModel.pretrained("sentence_detector_dl", "xx")
    .setInputCols(["document"])
    .setOutputCol("sentence")
)

embeddings = (
    XlmRoBertaSentenceEmbeddings.pretrained("bge_m3 ","xx")
    .setInputCols(["sentence"])
    .setOutputCol("embeddings")
)

pipeline = Pipeline().setStages([document_assembler, sentencerDL, embeddings])


df = spark.createDataFrame([["John Doe", "Jane Doe"]]).toDF("text")
```

### Spark NLP version and Apache Spark

sparknlp=='5.3.3'
jar version=5.3.3
spark_version='3.5.0'

databricks runtime version: 14.3.x-gpu-ml-scala2.12

### Type of Spark Application

spark-submit

**Comment by maziyarpanahi** [comment]
This is our fault, the code snippet has an extra `space` in the name. Thanks for reporting it, I'll fix the model's card.
