### ISSUE TITLE
allow configurable M2Resolvers

### ISSUE THREAD

**Issue by jianlins** [JohnSnowLabs/spark-nlp#14252]
### Description

In air-gap environment, the default maven repos are not accessible.  

### Preferred Solution

Can you set the M2Resolvers to read default ~/.m2/settings.xml to get the repo settings? or parameterize the repo URL?

### Additional Context

running some configurations fails when it trying to reach out to maven repo.

**Comment by jianlins** [comment]
sorry, miss click the assignment. not sure how to correct it.

**Comment by maziyarpanahi** [comment]
Hi @jianlins 

Isn't this possible to proxy the Maven from outside to any location you need without changing anything in the library? We have many users using it in air-gap env. 

Also, it would be best if you can use our official fat Jars that come with everything to avoid pulling any dependencies from anywhere. (it's the official recommendation for 100% offline support) - we list these jars in each release notes: https://github.com/JohnSnowLabs/spark-nlp/releases/tag/5.3.3
