### ISSUE TITLE
It's to slow to download a model

### ISSUE THREAD

**Issue by xueyuan1990** [JohnSnowLabs/spark-nlp#14251]
### Link to the documentation pages (if available)

It cost too mush time when I want to download the model in this link : https://sparknlp.org/2022/04/11/bert_embeddings_chinese_roberta_wwm_ext_zh_3_0.html
![11](https://github.com/JohnSnowLabs/spark-nlp/assets/8858328/4cda687a-5bca-4179-9240-b71804fe964f)

### How could the documentation be improved?

Please don't limit download speed

**Comment by maziyarpanahi** [comment]
All the models and pipelines are hosted on AWS S3, it has the highest bandwidth and it's impossible to control it. Where you are must be throttling the speed to access AWS S3 service.

You can test it on Google Colab to see how fast it downloads.
