### ISSUE TITLE
Py4JJavaError: An error occurred while calling o145.fit. : java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by NSManogna** [JohnSnowLabs/spark-nlp#14367]
I am training NerDLApproach with dataset attached but not able to train successfully. Could you please suggest any solution
[pii_dataset.csv.zip](https://github.com/user-attachments/files/16594940/pii_dataset.csv.zip)

**Comment by maziyarpanahi** [comment]
please provide your full code and specs of your machine. the error suggest you don't have enough memory. 

If you provide a complete info and code we can help you further.

**Comment by maziyarpanahi** [comment]
Please avoid sharing any dataset here, it won't help us finding out what's wrong. You MUST fill in the entire form in a new issue otherwise we can' help you: https://github.com/JohnSnowLabs/spark-nlp/issues/new?assignees=maziyarpanahi&labels=question&projects=&template=bug_report.yml
