### ISSUE TITLE
RuntimeError: Java gateway process exited before sending its port number

### ISSUE THREAD

**Issue by ska-ibees** [JohnSnowLabs/spark-nlp#14443]
### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find a match.

### Who can help?

@maziyarpana

### What are you working on?

https://github.com/JohnSnowLabs/spark-nlp/blob/master/examples/python/llama.cpp/PromptAssember_with_AutoGGUFModel.ipynb

### Current Behavior

With latest 5.5.1 version unable to start spark session. Seems spark package for v 5.5.1 hasn't published yet.

### Expected Behavior

Spark session should be started.

### Steps To Reproduce

Run this colab: https://github.com/JohnSnowLabs/spark-nlp/blob/master/examples/python/llama.cpp/PromptAssember_with_AutoGGUFModel.ipynb

### Spark NLP version and Apache Spark

SPARKNLP="5.5.1"
PYSPARK="3.2.3"

### Type of Spark Application

Python Application

### Additional Information

error:

RuntimeError                              Traceback (most recent call last)
[<ipython-input-2-7295da100991>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 # let's start Spark with Spark NLP with GPU enabled. If you don't have GPUs available remove this parameter.
----> 4 spark = sparknlp.start()
      5 print(sparknlp.version())

6 frames
[/usr/local/lib/python3.10/dist-packages/pyspark/java_gateway.py](https://localhost:8080/#) in launch_gateway(conf, popen_kwargs)
    106 
    107             if not os.path.isfile(conn_info_file):
--> 108                 raise RuntimeError("Java gateway process exited before sending its port number")
    109 
    110             with open(conn_info_file, "rb") as info:

RuntimeError: Java gateway process exited before sending its port number

![image](https://github.com/user-attachments/assets/25576b4e-dbcf-4689-ba96-97a4584b09f0)

**Comment by maziyarpanahi** [comment]
Hi @ska-ibees 

The command to publish the Maven artifacts failed unfortunately. The package is now available and published successfully on the Maven.

Could you please try agagin?

**Comment by ska-ibees** [comment]
Hi @maziyarpanahi Issue has been resolved. Thanks

**Comment by maziyarpanahi** [comment]
Hi @ska-ibees 
Thanks for confirming! 👍🏼
