### ISSUE TITLE
Can’t load library into databricks from maven 

### ISSUE THREAD

**Issue by lamastex** [JohnSnowLabs/spark-nlp#145]
## Description

I am unable to load library in databricks shard.
See attached image for:
com.johnsnowlabs.nlp:spark-nlp_2.11:1.4.2

## Expected Behavior

One should be able to load the library from maven coordinates 

## Current Behavior

Error that it is not available 
## Possible Solution

Try to load Library from databricks community edition 

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by karan-joshi** [comment]
I ran into same issue with the latest Spark NLP 1.4.2 release. I am also unable to import it into Azure Databricks. A quick solution was to use an older release. I was able to get the version 1.3.0 imported in Databricks. (Versions 1.4.0 and 1.4.1 also did not work)

However, there are a few things that are not available in older release, for example the ability to add infix patterns to tokenizer. 

It would be great to get the latest version working with databricks.

**Comment by eoinlane** [comment]
I am having the same import error trying to import Spark NLP 1.4.2 /1.4.1 as a Spark Package in Datbricks

Error: Your maven coordinate did not return any artifacts. Are you trying to import any Spark or Scala Dependencies?

**Comment by showy** [comment]
The error:

`Error: Your maven coordinate did not return any artifacts. Are you trying to import any Spark or Scala Dependencies?`

Actually comes from the fact that the we have sdk-bom as a dependency in build.sbt

"com.amazonaws" % "aws-java-sdk-bom" % awsVer

For the already released packages (including the 1.5.0) please just make sure to exclude the sdk-bom.
![screenshot from 2018-03-30 14-36-32](https://user-images.githubusercontent.com/2026148/38137877-cacd03f6-3427-11e8-900d-f848cbaf42ae.png)

**Comment by showy** [comment]
Previous answer has proven effective. We will look into sdk-bom issue to prevent the users from adding this exclusion.

**Comment by showy** [comment]
As a side note: it's a fact that we are removing the sdk-boom dependency for future releases.

**Comment by MohammadHeydari** [comment]
I also have the same error and unable to install` com.johnsnowlabs.nlp:spark-nlp_2.12:3.0.1` on `Databricks` env.

**Comment by maziyarpanahi** [comment]
@MohammadHeydari 
Please make sure you follow every step from our instructions: https://github.com/JohnSnowLabs/spark-nlp#databricks-cluster

If there is still an issue, please open a new issue with steps and all the information we need to reproduce. (right now, I don't know if you are choosing the right runtime with the right scala for that artifacts, etc.)
