### ISSUE TITLE
Pretrained model manual download

### ISSUE THREAD

**Issue by rdelbel** [JohnSnowLabs/spark-nlp#146]
I am using spark-nlp on a cluster without internet access.

I got spark-nlp working by downloading the jar file locally, sending it to the cluster and including it in my spark-submit.

I went through the github repo and documentation but i cant find where i can manually download the pretrained models that are normally downloaded by the downloadModel method.

 

Can you please point me to the location?

Thanks!

**Comment by aleksei-ai** [comment]
Hi @rdelbel. 
1. You can run com.johnsnowlabs.downloader.en.pipelines.CloudPOSPipeline.write.overwrite.save("your_folder")
2. Then you can upload folder to your cluster. 
3. And in cluster run PipelineModel.read.load("your_cluber_folder").

You can do the same with models (not only with pipelines) if you need.

If it doesn't work, please reopen the issue.
