### ISSUE TITLE
 java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by zengshansong** [JohnSnowLabs/spark-nlp#147]
When I train the spark-nlp　CRF model, emerged  java.lang.OutOfMemoryError: GC overhead limit exceeded  error
## Description

I found the training process only run on driver, and the executor was killed, so the driver take most of training works , and the driver's memory and cpu resources limit the training speed, and emerged above error " java.lang.OutOfMemoryError: GC overhead limit exceeded", is this right? is there any methods to sovle this problem? except to add the driver memeory
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by aleksei-ai** [comment]
Now there is no other solution. By design our algorithm is driver-based.
We can try to optimize memory usage.

**Comment by showy** [comment]
Closing this issue. We should open a new issue to discuss about the specifics regarding distributed training .
