### ISSUE TITLE
Building fat jars of scala projects with application.conf gives raise to build errors

### ISSUE THREAD

**Issue by avenka11** [JohnSnowLabs/spark-nlp#153]
Building fat jars of scala projects with `application.conf` gives raise to build errors

## Description
When including spark-nlp in a fat jar (using sbt-assembly) with existing `application.conf`, merge errors similar to the below error get raised
```
[error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] application.conf
```

## Possible Solution
According to https://github.com/lightbend/config#standard-behavior , it is correct to rename the file `reference.conf`

## Steps to Reproduce
1. Create a project dependent on `spark-nlp` with its own `application.conf`
2. Use `sbt-assembly` to create a fat jar

## Your Environment
* Version used: spark-nlp 1.4.2, sbt 1.0.2, sbt-assembly 0.14.5

**Comment by showy** [comment]
@avenka11 although I agree that we should be using reference.conf for the library settings, you can also specify the merge strategy for the application.conf files:

```
assemblyMergeStrategy in assembly := {
  case "application.conf" => MergeStrategy.concat
  ...
}
```

Let me know how that works for you.

**Comment by avenka11** [comment]
@showy yes, that does work. Thank you so much!
