### ISSUE TITLE
Does adding dependency in scala maven project works?

### ISSUE THREAD

**Issue by Mahesha999** [JohnSnowLabs/spark-nlp#163]
I added the dependency 

```
<!-- https://mvnrepository.com/artifact/com.johnsnowlabs.nlp/spark-nlp -->
<dependency>
    <groupId>com.johnsnowlabs.nlp</groupId>
    <artifactId>spark-nlp_2.11</artifactId>
    <version>1.5.0</version>
</dependency>
```

to scala-maven project in eclipse and ran maven install. It gave me following error:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building scalaspark 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.435 s
[INFO] Finished at: 2018-04-02T14:31:42+05:30
[INFO] Final Memory: 16M/222M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project scalaspark: Could not resolve dependencies for project com.mahesha999.datasci:scalaspark:jar:0.0.1-SNAPSHOT: Failure to find com.amazonaws:aws-java-sdk-bom:jar:1.11.272 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```
Their is no jar present at the following location: 
http://central.maven.org/maven2/com/amazonaws/aws-java-sdk-bom/1.11.306/
or here:
https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-bom/1.11.306
But their is only pom.

What  I am missing?

**Comment by lorenz-nlp** [comment]
I face the same problem with my maven-based project. Actually till spark-nlp version 1.4.0 I have no problems, but since then then (spark-nlp 1.4.1, 1.4.2, 1.5.0) the unresolved dependency of com.amazonaws:aws-java-sdk-bom prevents me from updating.

However, in my case the version of aws-java-sdk-bom somehow is 1.11.272.

**Comment by Mahesha999** [comment]
For me too the version is 1.11.272.
Also I added exclusion for this dependency. The error is gone, but am afraid if it will break in the future.

**Comment by showy** [comment]
@lorenz-nlp @Mahesha999 For now, excluding the dependency is the way to work.

We are looking into the sdk-bom issue. It shouldn't break and I do believe we can remove the bom dependency from our build.sbt. We will pay attention to this issue in the following releases.

**Comment by aleksei-ai** [comment]
@showy I think we can fix it adding correct sbt and pom.

**Comment by showy** [comment]
@aleksei-ai the sdk-bom seems to be only really necessary when using more that one aws sdk module. Do you know we need it for a fact in the build.sbt?

**Comment by aleksei-ai** [comment]
@showy Probably you are right. We can simply remove it so far.

**Comment by aleksei-ai** [comment]
@showy I've tested that we really don't need it in dependency.
So I removed it from our sbt, thank you!
