### ISSUE TITLE
Is API doc available online?

### ISSUE THREAD

**Issue by Mahesha999** [JohnSnowLabs/spark-nlp#164]
I was trying to translate sentiment analysis example given in [this python notebook](https://github.com/JohnSnowLabs/spark-nlp/blob/1.5.0/python/example/dictionary-sentiment/sentiment.ipynb) in Scala.

I translated this:

```
sentiment_detector = SentimentDetector() \
    .setInputCols(["lemma", "sentence"]) \
    .setOutputCol("sentiment_score") \
    .setDictionary("../../../src/test/resources/sentiment-corpus/default-sentiment-dict.txt", ",")
```
to this:

```
var sentimentDetector = (new SentimentDetector())
    .setInputCols(Array("lemma","sentence"))
    .setOutputCol("sentiment_score")
    .setDictionary("../../../src/test/resources/sentiment-corpus/default-sentiment-dict.txt", ",")
```

But getting error 
```
overloaded method value setDictionary with alternatives:   (path: String,delimiter: String,readAs: com.johnsnowlabs.nlp.util.io.ReadAs.Value,options: scala.collection.immutable.Map[String,String])com.johnsnowlabs.nlp.annotators.sda.pragmatic.SentimentDetector <and>   (value: com.johnsnowlabs.nlp.util.io.ExternalResource)com.johnsnowlabs.nlp.annotators.sda.pragmatic.SentimentDetector  cannot be applied to (String, String)
```
Hence, I tried to find scaladocs of the library, so that I can find signatures of different overloads of setDictionary method (something like this: https://spark.apache.org/docs/latest/api/scala/index.html of apache spark scaladoc). But I didnt found any doc online. Is scaladoc of the library present somewhere online?

After referencing [python code](https://github.com/JohnSnowLabs/spark-nlp/blob/1.5.0/python/sparknlp/annotator.py), I came to know about the default values ` read_as=ReadAs.LINE_BY_LINE, options={'format':'text'}` of `setDictionary`. But I still want to know if scala docs are available online.

**Comment by albertoandreottiATgmail** [comment]
Hi Mahesha999,

I think the closest to Scaladoc that is available is this list,

http://nlp.johnsnowlabs.com/components.html#scala

That's a list of common usages for all the annotators. It doesn't contain an exhaustive list of every possible method but it's a good starting point.
Also, you can directly look at the code for each annotator, for example, the one you're using is here,

https://github.com/JohnSnowLabs/spark-nlp/blob/master/src/main/scala/com/johnsnowlabs/nlp/annotators/sda/pragmatic/SentimentDetector.scala

hope that helps!,
Alberto.

**Comment by aleksei-ai** [comment]
@Mahesha999 
One of options in your case is:
`var sentimentDetector = new SentimentDetector()
    .setInputCols(Array("lemma","sentence"))
    .setOutputCol("sentiment_score")
    .setDictionary(ExternalResource("../../../src/test/resources/sentiment-corpus/default-sentiment-dict.txt", ReadAs.LINE_BY_LINE, Map("delimiter"->",")))`

Please, reopen the issue if doesn't help.
