### ISSUE TITLE
Aspect Based Sentiment Analysis 

### ISSUE THREAD

**Issue by programmeddeath1** [JohnSnowLabs/spark-nlp#1691]
The aspect Based Sentiment analysis for restaurants model is shown in the open source models but the ABSA_inference colab is asking for the json file with licence keys. Does this model come in the proprietary licensed subscription? Its showing under the open source tab of demos.

**Comment by maziyarpanahi** [comment]
Could you please provide both link to the Colab and the name of that model?

**Comment by programmeddeath1** [comment]
https://nlp.johnsnowlabs.com/demo On this page the last row first demo is Aspect Based Sentiment for restaurants. On clicking the colab it redirects to https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/streamlit_notebooks/ABSA_Inference.ipynb. Which asks for the licence json. 
Thanks!

**Comment by maziyarpanahi** [comment]
Updated : https://nlp.johnsnowlabs.com/2020/12/29/ner_aspect_based_sentiment_en.html
