### ISSUE TITLE
Using Spark ML NGram after Stemmer

### ISSUE THREAD

**Issue by elielhojman** [JohnSnowLabs/spark-nlp#176]
I am new at Spark and I looked all over your notebook examples and I didn't find an example which combines the JohnSnow's NLP library with the spark.ml feature extractors. Are those supposed to work together? 
A similar issue was raised in #59, but no solution specific to my problem was offered. 

Thanks

**Comment by maziyarpanahi** [comment]
@elielhojman It's actually very easy. You need to use `Finisher` in your Pipeline to output a column with arrays of string (either tokens, filtered tokens by removing stop words, or as you said stemmed tokens). 
Then you can point your NGram extraction input column to the output of `Finisher` column. You can use all the Spark ML functions alongside with spark-nlp as long as the input is an array of strings and you use `Finisher`.

> Once we have our NLP pipeline ready to go, we might want to use our annotation results somewhere else where it is easy to use. The Finisher outputs annotation(s) values into string. 

```scala
val finisher = new Finisher()
  .setInputCols("token")
```

> Settable parameters are:
> 
> - setInputCols()
> - setOutputCols()
> - setCleanAnnotations(true) -> Whether to remove intermediate annotations
> - setValueSplitSymbol("#") -> split values within an annotation character
> - setAnnotationSplitSymbol("@") -> split values between annotations character
> - setIncludeKeys(false) -> Whether to include metadata keys. Sometimes useful in some annotations
> - setOutputAsArray(false) -> Whether to output as Array. Useful as input for other Spark transformers.
> 
> 
Source: http://nlp.johnsnowlabs.com/components.html

**Comment by elielhojman** [comment]
Thanks for the quick response! 
Apparently I missed that part of the documentation :/.

**Comment by boris-mtdv** [comment]
How exactly can you use the output from finisher as input for word2vec? would you mind posting some code?

**Comment by maziyarpanahi** [comment]
@boris-mtdv The results of Finisher is an array of string which you pass it to your hashing function and the rest is the same as the examples on Spark website.
You can open a new issue and I give you some snippets.

**Comment by boris-mtdv** [comment]
I opened and issue and I still haven't been able to figure it out. Can you just post a snippet here please?

**Comment by maziyarpanahi** [comment]
In the upcoming release of Spark NLP `2.3.0`, we will have a native `NGramGenerator` annotator.
