### ISSUE TITLE
spark-nlp can only run in scalar after installing on Apache Zeppelin notebook

### ISSUE THREAD

**Issue by Yushan-Liu** [JohnSnowLabs/spark-nlp#198]
## Description
I installed spark-nlp on Apacehe Zeppelin notebook following the instruction [here](http://nlp.johnsnowlabs.com/quickstart.html). 

However, it only works when I run the notebook in Spark. If I try to import with pyspark, the package cannot be found. Does anyone have similar experience before? How to make it also run on Pyspark.  Thank you for any thoughts and inputs. 

Below is the difference when I imported the packages by using spark (scalar) and pyspark (python)
![spark_vs_pyspark](https://user-images.githubusercontent.com/37341291/39544933-9c8b99ca-4e1d-11e8-9b02-7e152f3067ed.PNG)

## Your Environment
* Version used: Spark 2.2 and Spark-nlp 1.5.3
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by saifjsl** [comment]
Hi @Yushan-Liu 

Using Maven coordinates will only cover the Scala/Java side. To use the python side of the library you will need to inject it with --packages argument.

In Zeppelin, you can do the following https://zeppelin.apache.org/docs/0.7.3/interpreter/spark.html:
`export SPARK_SUBMIT_OPTIONS="--packages com.databricks:spark-csv_2.10:1.2.0 --jars /path/mylib1.jar,/path/mylib2.jar --files /path/mylib1.py,/path/mylib2.zip,/path/mylib3.egg"`

**Comment by Yushan-Liu** [comment]
Thank you. I will try tomorrow and update the status later.
