### ISSUE TITLE
Unable to import python libs: AttributeError: 'module' object has no attribute 'annotator'

### ISSUE THREAD

**Issue by arnold-jr** [JohnSnowLabs/spark-nlp#206]
Using Spark 2.1.0, I am Python is unable to locate the spark-nlp python files.

## Description

I'm trying to import sparknlp in a Jupyter notebook. 

## Expected Behavior

I should be able to load sparknlp python modules.

## Current Behavior

Cannot import.

## Possible Solution

Spark should be shipping out the Python code in the jars, but is not. I've seen other projects zip up the Python sources and distribute them through the `--py-files` option; I tried doing this, but I suspect the python sources in the jar are masking.

## Steps to Reproduce

1. 
```[foo@bar ~]$ env | grep SPARK
SPARK_HOME=/opt/spark
PYSPARK_DRIVER_PYTHON=jupyter
PYSPARK_DRIVER_PYTHON_OPTS=notebook --no-browser --ip='*' --port=9999
```
2. `[foo@bar ~]$ $SPARK_HOME/bin/pyspark --packages JohnSnowLabs:spark-nlp:1.5.3`
3. From the notebook, `import sparknlp.base`

Results
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-668d318c3350> in <module>()
----> 1 import sparknlp.base

/tmp/spark-64f1c261-e85d-44a5-a66c-f6e62890508c/userFiles-5c700fed-42cf-495a-a68b-e3a1c895fcbb/JohnSnowLabs_spark-nlp-1.5.3.jar/sparknlp/__init__.py in <module>()

/tmp/spark-64f1c261-e85d-44a5-a66c-f6e62890508c/userFiles-5c700fed-42cf-495a-a68b-e3a1c895fcbb/JohnSnowLabs_spark-nlp-1.5.3.jar/sparknlp/annotator.py in <module>()

/tmp/spark-64f1c261-e85d-44a5-a66c-f6e62890508c/userFiles-5c700fed-42cf-495a-a68b-e3a1c895fcbb/JohnSnowLabs_spark-nlp-1.5.3.jar/com/johnsnowlabs/nlp/__init__.py in <module>()

AttributeError: 'module' object has no attribute 'annotator'
```

## Context

One day. I've just been trying to use spark-nlp in a Python 2 jupyter notebook. I've had no issue using spark-nlp via `spark-submit` or Scala-Spark apps.

## Your Environment

* Version used: 1.5.3
* Browser Name and version: Firefox
* Operating System and version (desktop or mobile): ```CentOS Linux release 7.4.1708 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core)
CentOS Linux release 7.4.1708 (Core)```
* Python version: Python 2.7.14 :: Anaconda custom (64-bit)
* Spark version: 2.1.0 precompiled for Hadoop-2.7
* Link to your project:

**Comment by thesuperzapper** [comment]
fixed in #205
