### ISSUE TITLE
ContextualParser not found

### ISSUE THREAD

**Issue by nithanda** [JohnSnowLabs/spark-nlp#2064]
Looking at this notebook:
https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Healthcare/1.2.Contextual_Parser_Rule_Based_NER.ipynb

I am trying to use ContextualParserApproach class but its not found in the spark nlp library that we have.. is it in some other jar or a bug?

**Comment by maziyarpanahi** [comment]
Hi,

`ContextualParserApproach` and features mentioned in `Healthcare` are licensed products. (we don't have the knowledge about these features here in open source)
https://johnsnowlabs.com/
