### ISSUE TITLE
ContextualParser is not working as expected

### ISSUE THREAD

**Issue by nithanda** [JohnSnowLabs/spark-nlp#2067]
Followed this tutorial in collab: - **(i have a trial healthcare license)**
https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Healthcare/1.2.Contextual_Parser_Rule_Based_NER.ipynb

cell # 36 is just printing empty results:
[]
[]
[]

but expectation was that it will match and return results

I tried to change setContextMatch(True) to False for all 3 contextual parsers then it printed results for date and gender but nothing for age... even though age is in the first sentence itself.

It should work even with setContextMatch(True) but didn't work.

**Comment by maziyarpanahi** [comment]
Hi @nithanda 

Unfortunately, we don't have any information on the licensed features here in open-source. I recommend you to either ask on Slack under #healthcare channel or directly ask the person who is your contact via Email. Either way, they get back to you pretty quickly :) 

PS: I would also suggest here: https://github.com/JohnSnowLabs/spark-nlp-workshop/issues
