### ISSUE TITLE
Improve pre-processing for multi-sentence input tasks for T5

### ISSUE THREAD

**Issue by C-K-Loan** [JohnSnowLabs/spark-nlp#2099]
Right now the T5 model seems to handle pre-processing for multi-sentence tasks not correct. 
This causes the predictions to be somewhat off since it is not clear for the model where the beginning and end of an sentence is .

From Appendix D. in the [T5 Paper](https://arxiv.org/pdf/1910.10683.pdf) it follows that for multi-sentence tasks (i.e section D.4 MRPC) that the first sentence should be prefixed with a special tag and the second sentence should be prefixed with a different tag.    
This seems to not be properly reflected in the T5 implementation yet.       
When configuring a task property on the T5 model in Spark NLP, it will prefix the task to the input sentence.       
There needs to be special handling for multi-sentence input tasks like MRPC, MNLI, and others.    

The current implementation of T5 seems to not handle this yet properly. Whatever task is configured seems to be prefixed to the input string and then passed to the T5 model. Adding tags between the sentences does not seem to happen.

One potential solution would be to use 2 input columns for such tasks.

## Example input and task to showcase different behavior, based on whether a prefix is added to the second sentence or not : 
If manually adding a prefix to the second sentence, the T5 model will properly predict ```equivalent```, but if it is not added T5 will predict ```not_equivalent``` which is wrong.

Examples are taken from section D4. in the appendix.

The T5 model behaves differently, wether the Tag for the second Sentence is added or not.

- Correct  ```equivalent```  prediction for  : 'We acted because we saw the existing evidence in a new light , through the prism of our experience on 11 September , " Rumsfeld said . ***sentence2:*** Rather , the US acted because the administration saw " existing evidence in a new light , through the prism of our experience on September 11
- Incorrect  ```not_equivalent``` prediction for:  'We acted because we saw the existing evidence in a new light , through the prism of our experience on 11 September , " Rumsfeld said . Rather , the US acted because the administration saw " existing evidence in a new light , through the prism of our experience on September 11

If you look at section D.11 the MultiRC is a multiple-choice predictor where each choice needs to be tagged with a specific tag.
The number of multiple-choice answers given to the model can be arbitrarily large, thus  an equal amount of tags must be placed between the sentences.

***Potential Solution*** : For N input choices, N input columns should be defined

**Comment by maziyarpanahi** [comment]
Hi @C-K-Loan
The `setTask` in `T5Transformer` and `setLangId` in `MarianTransformer` are there to make it easier for users to use these models. In fact, the usage of these models is normally with an inline prefix such as `translate English to French: Hi my name is...`. Since we have sentence detection it is really hard/unstable to know for which tasks we have to assume we should take pairs of sentences. 
I would say we should complete the documentation of T5 tasks and their usage with or without `setTask` param and let users decide which method is easier and more suitable to their dataset.
