### ISSUE TITLE
 Param loadSP does not exist

### ISSUE THREAD

**Issue by DanielOX** [JohnSnowLabs/spark-nlp#2111]
This particular error about **param loadSP**, in my case only occurs when i try to use tf_hub models sentimentdl_use_twitter, sentimentdl_use_imdb.

**Spark (pyspark) Version:** 2.4.7
**SparkNlp Version:** com.johnsnowlabs.nlp:spark-nlp_2.11:2.7.1
## Description

Below is the complete error details

![Screenshot from 2021-01-13 09-39-59](https://user-images.githubusercontent.com/33195456/104407461-7233b480-5583-11eb-8db6-f49cf45f5bc0.png)

This is the code i am using

```
import os 
import pyspark.sql.functions as F
import sparknlp
from pyspark.ml import Pipeline
from pyspark.sql import SparkSession
from sparknlp.annotation import *
from sparknlp.annotator import *
from sparknlp.base import *
from sparknlp.common import *
from sparknlp.pretrained import PretrainedPipeline
from pyspark.ml import Pipeline
import json

sparknlp.start()
spark = SparkSession.builder\
    .master('local[*]')\
    .getOrCreate()


df = df.read.csv('./data.csv')
df.createOrReplaceTempView('normalize_posts')
df = spark.sql("""
    SELECT *, posts.text_c as text FROM normalize_posts 

""").drop('posts,_metadata')



MODEL_NAME = "sentimentdl_use_twitter"
documentAssembler = DocumentAssembler()\
    .setInputCol("text")\
    .setOutputCol("document")
    
use = UniversalSentenceEncoder.pretrained(name="tfhub_use", lang="en")\
 .setInputCols(["document"])\
 .setOutputCol("sentence_embeddings")


sentimentdl = SentimentDLModel.pretrained(name=MODEL_NAME, lang="en")\
    .setInputCols(["sentence_embeddings"])\
    .setOutputCol("sentiment")

nlpPipeline = Pipeline(
      stages = [
          documentAssembler,
          use,
          sentimentdl
      ])
pipeline_model = LightPipeline(nlpPipeline.fit(spark.createDataFrame([['']]).toDF("text")))



annotations = pipeline_model.transform(df)
annotations.select(F.explode(F.arrays_zip('document.result', 'sentiment.result')).alias("cols")) \
.select(F.expr("cols['0']").alias("document"),
        F.expr("cols['1']").alias("sentiment")).show(truncate=False)
```

## Expected Behavior
The model should be loaded and perform predictions on my dataframe

## Current Behavior
Upon loading the model it throws Param loadSP does not exists

**Comment by maziyarpanahi** [comment]
Hi,

In 2.7.1 in order to fix some of the issues with Classifiers in the cluster, we had to change the architecture of those models. That is why there is a backward compatibility issue with models being saved beforehand including pre-trained models:
https://github.com/JohnSnowLabs/spark-nlp/releases/tag/2.7.1

However, we are training new models for our classifiers everyday and adding them to our Models Hub. This specific model hasn't been updated for 2.7.1 yet. You can check the current list of new models here: https://nlp.johnsnowlabs.com/models

We will update this issue once this model is updated for 2.7.1

**Comment by DanielOX** [comment]
@maziyarpanahi Thanks for the response. I am looking forward to it. Should i close this issue or keep it open?

**Comment by maziyarpanahi** [comment]
The models should work in 2.6.5 if you are not in the cluster. Just make sure using pretrained() function so it downloads/loads the compatible models.

**Comment by maziyarpanahi** [comment]
Both models have been updated for the 2.7.1 release: https://nlp.johnsnowlabs.com/models?tag=sentiment

**Comment by ankurphutela** [comment]
@maziyarpanahi  I am encountering the same error - `Param loadSP does not exist` in below models.

`analyze_sentimentdl_use_twitter`
`analyze_sentimentdl_use_imdb`

Steps to reproduce it - 
1. Download model using link - [analyze_sentimentdl_use_twitter](https://nlp.johnsnowlabs.com/2021/01/18/analyze_sentimentdl_use_twitter_en.html)
2. Uncompress the ZIP file.
3. Execute below in pyspark.

```
from sparknlp.base import *
senti_model=PipelineModel.load("<directory-path>")
```


Environment details - 
OS - ubuntu
pyspark==2.4.3
spark-nlp==2.7.1
openjdk version "1.8.0_282"

**Comment by maziyarpanahi** [comment]
Hi @ankurphutela 

I've just tested those pipelines. You are either not on `2.7.1` both PyPI and Java or you have downloaded (or using) the old version of that pipeline.

Please make sure:

- `pip install spark-nlp --upgrade` in your Python/Conda environment
- Make sure you use `spark = sparknlp.start()` and `sparknlp.version()` is correct
- Use the following code and let Spark NLP download the right compatible pipeline for you:
```python
from sparknlp.pretrained import PretrainedPipeline 
pipeline = PretrainedPipeline("analyze_sentimentdl_use_twitter", lang = "en") 

result = pipeline.fullAnnotate(["im meeting up with one of my besties tonight! Cant wait!!  - GIRL TALK!!", "is upset that he can't update his Facebook by texting it... and might cry as a result  School today also. Blah!"])
```
If you are offline with no internet, please remove anything you have already downloaded, download the pipeline in a different place and use that path to be sure you are loading the new pipeline.

**Comment by DanielOX** [comment]
@maziyarpanahi Hi, I followed the steps which you told @ankurphutela 

> 
    - pip install spark-nlp --upgrade in your Python/Conda environment
    - Make sure you use spark = sparknlp.start() and sparknlp.version() is correct
    - Use the following code and let Spark NLP download the right compatible pipeline for you:

But i am still getting the same error, btw i am using jupyter notebook 

![Screenshot from 2021-02-23 17-20-28](https://user-images.githubusercontent.com/33195456/108843080-0883dd00-75fc-11eb-9708-806c26bbc476.png)
These are the errors, kindly let me know if you need anything else


Thanks

**Comment by maziyarpanahi** [comment]
Hi @DanielOX 

I cannot reproduce this, could you please create a new issue, **complete the template**, provide **step-by-step instructions** for us to reproduce this error? 

It's hard here to follow since we are testing blindly without setting the environment, code, etc. exactly as the users. it could be a leftover path to an old version somewhere, updating Spark NLP in a wrong Python/Conda path, launch Jupyter in an environment that has a lower version, or etc.

I lock this issue as any new comments don't help to fix it.
PS
