### ISSUE TITLE
Zeppelin NoClassDefFoundError when the JAR is used

### ISSUE THREAD

**Issue by maziyarpanahi** [JohnSnowLabs/spark-nlp#213]
Hi,
If I use --package in my Zeppelin everything is fine. But when I use the JAR in my Zeppelin I receive this error: (I use JAR because it's on HDFS and it has a faster session creation for users)
```
java.lang.NoClassDefFoundError: com/typesafe/config/ConfigMergeable
  at com.johnsnowlabs.nlp.serialization.Feature.<init>(Feature.scala:15)
  at com.johnsnowlabs.nlp.serialization.MapFeature.<init>(Feature.scala:142)
  at com.johnsnowlabs.nlp.annotators.NormalizerModel.<init>(NormalizerModel.scala:21)
  at com.johnsnowlabs.nlp.annotators.NormalizerModel.<init>(NormalizerModel.scala:23)
  at com.johnsnowlabs.nlp.annotators.Normalizer.train(Normalizer.scala:60)
  at com.johnsnowlabs.nlp.annotators.Normalizer.train(Normalizer.scala:16)
  at com.johnsnowlabs.nlp.AnnotatorApproach.fit(AnnotatorApproach.scala:33)
  at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:153)
  at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:149)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
  at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
  at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:149)
  ... 58 elided
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigMergeable
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 72 more
```

Many thanks,
Maziyar

**Comment by saifjsl** [comment]
This is very strange error, what does ConfigMergeable has to do with Spark-NLP jar I wonder, is it a Spark dependency or something else?

How did you add the jar into zeppelin? Through the interpreter dependency list (pointing to a path)? if the jar it self it is not failing, it is probable that it is something else, an incompatible problem.

@albertoandreottiATgmail ?

**Comment by maziyarpanahi** [comment]
I am adding the JAR in zeppelin-env.sh like this:

```
export SPARK_SUBMIT_OPTIONS="--jars hdfs:///user/maziyar/spark-nlp.jar"
```
I have many other jars which they all working. It seems there compiled spark-nlp.jar is missing something from typesafe dependency if I am not mistaken.

**Comment by saifjsl** [comment]
Why aren't you using --packages? this downloads all necessary dependencies automatically.

We have realized recently that to use --jars, we need to include the fat-jar (i.e. result of sbt assembly). We'll be updating the website with the fat-jar to download. but for now you'll have to clone and assembly yourself

**Comment by maziyarpanahi** [comment]
Hi @saifjsl 
Actually, I did that but this is a multi-user Zeppelin which some haven't logged in to the server. Therefore, there is no home directory and Zeppelin fails to start Spark interpreter if there is --package inside config cause it looks for .ivy2/cache. 
That is why I usually find the fat JAR and put them on HDFS to avoid waiting on starting new session and asking users to logged-in (auto home directory creation after LDAP first time login)

**Comment by saifjsl** [comment]
I see. So, the next hypothesis is that the jar is not being reached by the executor nodes. We had a discussion on that as well. We've got it working by making sure the jar is accessible from all nodes, and setting these settings (--conf) submit options.

```
spark.driver.extraClassPath
spark.executor.extraClassPath
```
or if yarn
```
spark.yarn.dist.jars
spark.yarn.jars
```
```

**Comment by maziyarpanahi** [comment]
Actually, it used to work only by assigning the JAR. I am guessing at some point it stopped being a fat JAR including every dependency. Hard to say cause the size dropped when everything moved to pre-trained downloadable models.
Is there a way to confirm that `ConfigMergeable` is indeed in the JAR? As you said it may be because it is not a fat JAR. But I am sure it worked with no problem for few versions before pre-train models.

**Comment by saifjsl** [comment]
Needs a little patience, I myself i'm not sure anymore into how Spark properly distributes stuff in a cluster when working with extra class paths.

All I know is that we solved a user's problem with a YARN cluster by carefully setting up SparkSession configurations, in order to be make sure executors were getting the *fat-jar* so yes, it only worked with distributed fat-jar in a distributed storage

**Comment by saifjsl** [comment]
A fat jar is about 60-70mb. I Also think you can open it with an archive manager to browse the jar contents.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by maziyarpanahi** [comment]
@saifjsl OK, the size is not reasonable to be downloaded. Is there any recipe for creating a fat JAR by using spark-nlp source code if someone needs a fat JAR?

**Comment by saifjsl** [comment]
Hi @maziyarpanahi , what do you mean the size is not reasonable?

Yes, to build it from source, simply clone the library and run `sbt assembly` from its root directory.

**Comment by maziyarpanahi** [comment]
@saifjsl I meant the size without including everything is between 2-5mb usually. So it is not reasonable to ask you for the fat JAR which is going to be around 6-70mb. That's why I asked how to do it ourselves.
However, having fat jar provided by you guys is much simpler and better :) 
We can close this issue and many thanks.

**Comment by saifjsl** [comment]
Thank you

**Comment by aburkov** [comment]
Where can I find the fat jar? I downloaded spark-nlp_2.11-2.6.3.jar from https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.11/2.6.3/ and still have this problem.

**Comment by maziyarpanahi** [comment]
@aburkov please have a look at the release notes, each release has all the fat jars listed at the bottom and hosted on S3.

**Comment by aburkov** [comment]
> @aburkov please have a look at the release notes, each release has all the fat jars listed at the bottom and hosted on S3.

Yes, I have found it, thank you. I have posted a different issue related to com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline could you please advise?
