### ISSUE TITLE
Enhancement of Aspect based analysis

### ISSUE THREAD

**Issue by programmeddeath1** [JohnSnowLabs/spark-nlp#2184]
Dear Team, is it possible to train your aspect based sentiment models to detect aspects for different industries and more aspect classes? Currently, the model is only detecting a single aspect from certain types of reviews.
![Screenshot from 2021-01-22 16-34-33](https://user-images.githubusercontent.com/44861370/105483379-c9e2c600-5ccf-11eb-9cab-f69c07c38ce8.png)
Can you guide me how I can expand its functionality to handle all kinds of reviews?
How can I train the NER to detect more aspects? Is there any documentation where I can understand the training method or input my own trained model.
Thanks for your help in advance!

**Comment by maziyarpanahi** [comment]
Hi,

This is how you use this model in the pipeline: 

https://github.com/HashamUlHaq/spark-nlp-workshop/blob/master/tutorials/streamlit_notebooks/ABSA_Inference.ipynb

And the tutorial to train a new NER model:

https://github.com/HashamUlHaq/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/4.NERDL_Training.ipynb

**Comment by maziyarpanahi** [comment]
@HashamUlHaq 
For the quality of the pretrained model, please send me a DM with the link to the dataset. Maybe I can find other contextualized embeddings to have a better coverage.

**Comment by HashamUlHaq** [comment]
Hi @maziyarpanahi , sure!

Hi @programmeddeath1 this model is trained on restaurant reviews dataset, so it is entirely possible it does not do that well on other examples.

Here is the description of the model on our official Models Hub https://nlp.johnsnowlabs.com/2020/12/29/ner_aspect_based_sentiment_en.html 

Here is the link to our models hub where you can find thousands of other models - some of which might help with your use-case.
https://nlp.johnsnowlabs.com/models

**Comment by ajay01994** [comment]
Hi @HashamUlHaq  , I also checked the models on model hub but unfortunately couldn't find new models on Aspect based , so  can this model be trained on custom dataset, Also  there is another repo as 
BERT ADA (https://github.com/deepopinion/domain-adapted-atsc) 

is  it possible to include this  it into  your pipeline  ?

**Comment by HashamUlHaq** [comment]
Hi @ajay01994 yes, it is fully possible to train a custom model. Here is the colab link to get you started right away. It explains the input data format, how to train, save and test an NER model.
https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/4.NERDL_Training.ipynb

**Comment by programmeddeath1** [comment]
Hi @maziyarpanahi @HashamUlHaq than you for your response!  Actually the model does quite well even on things it is not trained on / other than restaurant reviews. The problem was  sometimes it does not detect multiple aspects in longer sentences or multi-line comments but shows only one aspect. On splitting into smaller sentences and passing individually ( and after correcting grammar and phrases) it is able to detect the other aspects and works well. Of course there would be some training needed on other aspects. Thanks for your help I will try to train it for better results and see.
![2021-01-25](https://user-images.githubusercontent.com/44861370/105794706-90e97080-5fb1-11eb-9936-9353f1d35f69.png)
This example from your demo page was only picking one aspect staff members. But here even on splitting it did not show parking as positive.
![2021-01-25 (1)](https://user-images.githubusercontent.com/44861370/105794871-e32a9180-5fb1-11eb-816b-8d43de36559d.png)
This is what created a doubt in my mind, whether this is a training issue or do we need some preprocessing on the comments/reviews.

@maziyarpanahi I am still scraping and extracting the data for this, I will send once I complete creating the dataset.

Thank you guys for your help!
