### ISSUE TITLE
Passing EmbeddingsFinisher outputs to Spark ML MultilayerPerceptronClassifier fails

### ISSUE THREAD

**Issue by MeranaTona** [JohnSnowLabs/spark-nlp#2187]
Hi!

In PySpark passing outpus of EmbeddingsFinisher to Spark ML MultilayerPerceptronClassifier results in following error when calling mpc.fit(embedded_texts):
`java.lang.IllegalArgumentException: requirement failed: Column sentence_embeddings_vectors must be of type struct&lt;type:tinyint,size:int,indices:array&lt;int&gt;,values:array&lt;double&gt;&gt; but was actually array&lt;array&lt;float&gt;&gt;.`

I can't figure out how to transform the format correctly. Maybe because im new. Changing .setOutputAsVector() to false also doesn't solve it.

## Expected Behavior
From EmbeddingsFinisher  docs I thought outputs could be passed directly as 'feature' input for Spark ML classifiers.
https://nlp.johnsnowlabs.com/docs/en/transformers#embeddingsfinisher

## Steps to Reproduce
```
import sparknlp
from sparknlp.annotator import *
from sparknlp.common import *
from sparknlp.base import *

# Pipeline setup
document = DocumentAssembler()\
  .setInputCol('text')\
  .setOutputCol('document')

tokenizer = Tokenizer()\
  .setInputCols(['document'])\
  .setOutputCol('tokens')

normalizer = Normalizer()\
  .setInputCols(['tokens'])\
  .setOutputCol('normalized')

bert_embedder = BertEmbeddings.load(pretrained_models_folder + 'small_bert_L2_128_en_2.6.0_2.4_1598344320681/'
) \
  .setInputCols(['document', 'normalized']) \
  .setOutputCol('embedding')

sentence_embeddings = SentenceEmbeddings() \
  .setInputCols(['document', 'embedding']) \
  .setOutputCol('sentence_embeddings') \
  .setPoolingStrategy('AVERAGE')

embeddings_finisher = EmbeddingsFinisher() \
  .setInputCols('sentence_embeddings') \
  .setOutputCols('sentence_embeddings_vectors') \
  .setOutputAsVector(True)

bert_sentence_pipe = Pipeline(
  stages=[
    document,
    tokenizer,
    normalizer,
    bert_embedder,
    sentence_embeddings,
    embeddings_finisher
  ]
)
embedded_texts = bert_sentence_pipe.fit(texts).transform(texts)

mpc = MultilayerPerceptronClassifier(featuresCol='sentence_embeddings_vectors', labelCol='labels')
mpc.fit(embedded_texts)
```
## Your Environment

* Spark NLP version: 2.6.5
* Spark 2.4.5
* Operating System and version: Databricks runtime version 6.4

Thank you in advance.

**Comment by maziyarpanahi** [comment]
Even though you don’t have any sentence detector, the result will still be an array (in your case array of Vectors). You need to explode the sentence_embeddings_vectors column before feeding it into any Spark ML function.

You can see the explode either inside the pipeline or outside:
https://github.com/JohnSnowLabs/spark-nlp/blob/master/src/test/scala/com/johnsnowlabs/nlp/EmbeddingsFinisherTestSpec.scala
