### ISSUE TITLE
java.lang.IllegalArgumentException: requirement failed: Storage not found under given ref: EMBEDDINGS_glove_100d

### ISSUE THREAD

**Issue by leeivan** [JohnSnowLabs/spark-nlp#2205]
I am trying to run spark nlp on cluster, I didn't have this problem with BertEmbeddings, but WordEmbeddingsModel. I guess the point dose at the environment of spark cluster, but I didn't know how to fix this.
## Description

**_the error:_**
 This usually means:
1. You have not loaded any storage under such ref or one of your Storage based annotators has `includeStorage` set to false and must be loaded manually
2. You are trying to use cluster mode without a proper shared filesystem.
3. source was not provided to Storage creation
4. If you are trying to utilize Storage defined elsewhere, make sure it has the appropriate ref. 
	at scala.Predef$.require(Predef.scala:224)
	at com.johnsnowlabs.storage.RocksDBConnection.findLocalIndex(RocksDBConnection.scala:36)
	at com.johnsnowlabs.storage.RocksDBConnection.connectReadOnly(RocksDBConnection.scala:63)
	at com.johnsnowlabs.storage.HasConnection$class.$init$(HasConnection.scala:10)
**_the code:_**
def start(gpu=False):
    builder = SparkSession.builder \
        .appName("Spark NLP") \
    if gpu:
        builder.config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp-gpu_2.11:2.7.2")
    else:
        builder.config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.7.2")
    return builder.getOrCreate()

  
spark = start(gpu=False)
glove = WordEmbeddingsModel().pretrained() \
 .setInputCols(["sentence",'token'])\
 .setOutputCol("glove")\
 .setCaseSensitive(False)

test_data = CoNLL().readDataset(spark, 'hdfs://master:9000/root/sparknlp/eng.testa')
test_data = glove.transform(test_data)
test_data.show()

_**spark-defaults.conf:**_
spark.master                     spark://10.168.2.219:7077
spark.driver.host               10.168.2.219

spark.serializer                 org.apache.spark.serializer.KryoSerializer
spark.driver.memory              50g
spark.executor.memory           30g
spark.executor.cores            6
spark.cores.max                         32
spark.local.dir                  /nfs/cache/tmp
spark.kryoserializer.buffer.max  1000M
spark.jars.packages             com.johnsnowlabs.nlp:spark-nlp_2.11:2.7.2
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version:2.7.2
* Apache NLP version: NA
* Java version (java -version):java 8
* Setup and installation (Pypi, Conda, Maven, etc.): pip
* Operating System and version: ubuntu 20.04
* Link to your project (if any):
* Using Jupter Notebook to start spark application

**Comment by maziyarpanahi** [comment]
Please complete environment part, this happens because you don’t have your Apache Spark correctly co figured with the HDFS.

**Comment by leeivan** [comment]
I am trying to run spark nlp on cluster, I didn't have this problem with BertEmbeddings, but WordEmbeddingsModel. I guess the point dose at the environment of spark cluster, but I didn't know how to fix this.

**Comment by maziyarpanahi** [comment]
The WordEmbeddings annotator will use `/hadoop/tmp` to unpack some indexes. The fact you have to use a full URI for your HDFS means your Spark cluster doesn't have the correct config. Instead of `hdfs://master:9000/root/sparknlp/eng.testa` you should be able to use `hdfs://root/sparknlp/eng.testa` because Apache Spark knows where the HDFS master node is.

The BertEmbeddings don't require unpacking anything on the Hadoop file system. Even though it works, I highly recommend to setup those configs for your Apache Spark to have a better understanding of your HDFS setup. (Spark NLP reuses those configs)

**Comment by tawheedmanzoor** [comment]
@leeivan, were you able to solve this issue?
