### ISSUE TITLE
how to train a context-based spell checker (documentation or colab notebook)

### ISSUE THREAD

**Issue by mzeidhassan** [JohnSnowLabs/spark-nlp#2206]
Hi there,

I am new to SparkNLP, and I saw this [announcement](https://github.com/JohnSnowLabs/spark-nlp/releases/tag/2.7.2) today, and I am wondering if you can point me to where in the documentation I can find how to train a context-based spell checker. I searched it up, but no luck. Do you have a collab notebook or a guide on how to to this?

Thanks in advance for your support.

**Comment by maziyarpanahi** [comment]
We have all the examples here, you can just search the name of the annotator and see the notebooks: https://github.com/JohnSnowLabs/spark-nlp-workshop
