### ISSUE TITLE
training dataset format confusion

### ISSUE THREAD

**Issue by arcpool** [JohnSnowLabs/spark-nlp#2217]
https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp/master/src/test/resources/conll2003/eng.train

```
from sparknlp.training import CoNLL
training_data = CoNLL().readDataset(spark, 'eng.train')
```
The above lines do not work when I input my data instead of 'eng.train'
Currently, my data is in tsv format approximate size of 25MB whereas 'eng.train' used here is of size 3MB. 

Could you please let me know the format used or the type of file to be inputted so I can manipulate my data accordingly? 

Thankyou.

**Comment by maziyarpanahi** [comment]
As mentioned in documentation or by looking into that file, the format must be CoNLL 2003.
There are examples here:  https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/4.NERDL_Training.ipynb
