### ISSUE TITLE
2.7.2 Lemmatizers crash for input col token (Only PySpark ML Pipe, not Light)

### ISSUE THREAD

**Issue by C-K-Loan** [JohnSnowLabs/spark-nlp#2229]
The new Lemmatizers introduced in 2.7.2 seem to not be able to take in Tokenizer inputs when running Standard pipelines. It seems to only accept document columns.   
  This error does not occur in light pipelines, where running on token column works fine.

# Using Lightpipelines works fine
This works fine
```
spark = sparknlp.start()
document_assembler = DocumentAssembler() \
    .setInputCol("text") \
    .setOutputCol("document")

tokenizer = Tokenizer()\
    .setInputCols(["document"]) \
    .setOutputCol("token")

lemmatizer = LemmatizerModel.pretrained("lemma", "bh") \
        .setInputCols(["token"]) \
        .setOutputCol("lemma")

nlp_pipeline = Pipeline(stages=[document_assembler, tokenizer, lemmatizer])
light_pipeline = LightPipeline(nlp_pipeline.fit(spark.createDataFrame([[""]]).toDF("text")))
s
results = light_pipeline.fullAnnotate(["एह आयोजन में विश्व भोजपुरी सम्मेलन , पूर्वांचल एकता मंच , वीर कुँवर सिंह फाउन्डेशन , पूर्वांचल भोजपुरी महासभा , अउर हर्फ - मीडिया के सहभागिता बा ।"])


```

# Using classic pipeline crashes 
This reproduces the error for all 2.7.2 Lemmatizers
```
spark = sparknlp.start()
document_assembler = DocumentAssembler() \
    .setInputCol("text") \
    .setOutputCol("document")

tokenizer = Tokenizer()\
    .setInputCols(["document"]) \
    .setOutputCol("token")

lemmatizer = LemmatizerModel.pretrained("lemma", "bh") \
        .setInputCols(["token"]) \
        .setOutputCol("lemma")

nlp_pipeline = Pipeline(stages=[document_assembler, tokenizer, lemmatizer])
data = [ {"text": 'Some text hello world'}, ]
spark.createDataFrame(data)
nlp_pipeline.fit(df).transform(df).show()
```

## Resulting error  missing input columns)

```
pyspark.sql.utils.IllegalArgumentException: "requirement failed: Wrong or missing inputCols annotators in REGEX_TOKENIZER_464e65bbfb02.\n\nCurrent inputCols: token. Dataset's columns:\n(column_name=text,is_nlp_annotator=false)\n(column_name=origin_index,is_nlp_annotator=false)\n(column_name=document,is_nlp_annotator=true,type=document)\n(column_name=token,is_nlp_annotator=true,type=token).\nMake sure such annotators exist in your pipeline, with the right output names and that they have following annotator types: document"
```
Setting the Lemmatizers input to Document fixes this issue. But this makes running Lemmatizer on Tokenizers output impossible.

This *does not happen for English Lemmatizer* and any other model release pre-2020 
This error seems to occur for the latest Lemmatizers in 

When checking with the Modelshub, everything before 2020 (i.e. Hebrew and all before that) works fine. 
![image](https://user-images.githubusercontent.com/18140070/106677253-b92c2d00-65b8-11eb-9bc6-c1f2bb467347.png)

more precisely, Lemmatizers from Spark NLP 2.7.0 are fine, but the ones from the `2.7.2 release` seem to have this issue

**Comment by maziyarpanahi** [comment]
@dcecchini The models mentioned above (with the issue) are not LemmatizerModel. If you download them and look into the metadata, they are actually `TokenizerModel`. I think you might have saved that stage of the pipeline by mistake or something went wrong. 
Could you please give me the models for LemmatizerModel, I will set the same name and replace them on S3 manually?

**Comment by dcecchini** [comment]
@maziyarpanahi I re-trained the models and confirm that they are now correctly saved.

**Comment by maziyarpanahi** [comment]
@C-K-Loan 
I have replaced the models, could you please double-check to see if I fixed them all?

**Comment by C-K-Loan** [comment]
Confirmed all models work well now and will be available in the next NLU release
