### ISSUE TITLE
Getting typesafe config error while loading the model file

### ISSUE THREAD

**Issue by algoscale1** [JohnSnowLabs/spark-nlp#225]
I have a project in scala and spark, that also uses typesafe config. I have already created a trained pipeline and model using the default training data provided in the examples. Now In this project, I am trying to load these models for a prediction on test data. While trying to load the model this is what I am getting -
```
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'settings'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
	at com.johnsnowlabs.util.ConfigLoader$.<init>(ConfigLoader.scala:10)
	at com.johnsnowlabs.util.ConfigLoader$.<clinit>(ConfigLoader.scala)

```

## Description

This is how i am loading the model and pipeline in the code -
 ```
val config: Config = ConfigFactory.load.getConfig("application")
val pipeline = Pipeline.read.load(config.getString("nlp.pipeline.folder"))
val model = PipelineModel.read.load(config.getString("nlp.model.folder"))
```
And the error comes in the last line _PipelineModel.read.load(config.getString("nlp.model.folder"))_

**Some points to consider**
- If i print **config.getString("nlp.pipeline.folder")**, i get the correct path to the pipepline. So there is no issue in the path.
- I am able to load the pipeline so the error only comes while loading the model.
- And when i remove the typesafe library from my code completely, I am able to load both the pipeline and model. So the code is working fine when i don't use typesafe in my project.

It looks like the spark-nlp code is trying to find key 'settings' in the application.conf file that i created for my project instead of the library. 
I tried to exclude the typesafe from the library but it didn't work-

```
<dependency>
            <groupId>com.johnsnowlabs.nlp</groupId>
            <artifactId>spark-nlp_2.11</artifactId>
            <version>1.5.4</version>
            <exclusions>
                <exclusion>
                    <groupId>com.typesafe</groupId>
                    <artifactId>config</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

Is there anything that am i missing? 
Thanks

**Comment by saifjsl** [comment]
Hello @algoscale1 
Indeed, it may be a little bit confusing. We may need to explore a little bit this and see where the issue comes from.

settings {} is a configuration file provided by Spark-NLP, it could be the case that you are overriding Spark-NLP's setting with yours.

The content of our application.conf is the following:
```
settings {
  overrideConfigPath = "./application.conf"
  annotatorSerializationFormat = "object"
  useBroadcastForFeatures = true
}
```

So it may be required that you use typesafe config in a way that it does not override existing configuration files.

**ConfigFactory** is a static object and works universally across the JVM runtime. Spark-NLP calls `ConfigFactory.load()` so it is probable that it doesn't do anything if ConfigFactory is already loaded. So you're probably overriding Spark-NLP's configurations.

**Comment by haimco10** [comment]
I'm having the same issue

**Comment by haimco10** [comment]
BTW, I only had to add to my config file, the settings that @saifjsl posted and it solved my issue. Thanks.

**Comment by saifjsl** [comment]
Hi, please reopen if there is anything we can do to improve this use case.
