### ISSUE TITLE
Python Tokenizer addInfixPattern does not work properly

### ISSUE THREAD

**Issue by sethah** [JohnSnowLabs/spark-nlp#227]
## Description

Add infix pattern method is defined as:

```python
def addInfixPattern(self, value):
        infix_patterns = self.getInfixPatterns()
        infix_patterns.append(value)
        return self._set(infixPatterns=infix_patterns)
```

But I don't think these take effect since the rules are applied from start of list. In the Scala API, it is done differently:

```scala
def addInfixPattern(value: String): this.type = set(infixPatterns, value +: $(infixPatterns))
```

The new rule is added to the start of the list, so it takes effect ok. I more or less verified that changing the Python code to:

```python
def addInfixPattern(self, value):
        infix_patterns = self.getInfixPatterns()
        infix_patterns.insert(0, value)
        return self._set(infixPatterns=infix_patterns)
```

fixes the issue. I could submit a PR for it, but need to write unit tests, etc...

## Steps to Reproduce

Tokenize following "this is some/text I wrote"
```python
tokenizer = Tokenizer()\
  .setTargetPattern("\S+")\
  .addInfixPattern("(\\p{L}+)\\/(\\p{L}+\\b)")
```

That should separate "some" and "text" into separate tokens, but it doesn't.

## Context
Custom tokenization

## Your Environment
* Version used: 1.5.4
* Operating System and version (desktop or mobile): Ubuntu

**Comment by saifjsl** [comment]
Hello @sethah 

Sorry for the delay. Indeed that' s a very good catch. We should definitely fix the python implementation for addInfixPattern.

**Comment by saifjsl** [comment]
https://github.com/JohnSnowLabs/spark-nlp/pull/237
