### ISSUE TITLE
Question on how to use sparknlp with setting master to a remote spark instance

### ISSUE THREAD

**Issue by NixTheMan** [JohnSnowLabs/spark-nlp#2270]
Hi,
I instantiate manually my spark instance with something along the lines of:
```{python}
import pyspark.sql as spsq
spark_init = spsq.SparkSession.builder\
        .appName("nlpTEST")\
        .master("spark://myRemoteLivySparkInstance:7077")\
        .config("spark.ui.proxyBase", "/sparkui")\
        .config("spark.executor.memory", "2g")\
        .config("spark.jars.packages", "JohnSnowLabs:spark-nlp_2.11:2.7.2")\
        .config("spark.hadoop.fs.s3a.endpoint", endpoint_s3)\
        .config("spark.hadoop.fs.s3a.access.key", creds_s3["aws_access_key_id"])\
        .config("spark.hadoop.fs.s3a.secret.key", creds_s3["aws_secret_access_key"])\
        .getOrCreate()
```
Which instantiates fine. However, when I then run something along the lines of:
```
pipeline = PretrainedPipeline("explain_document_ml")
```
My spark throws errors saying that it can't find the file, as it was downloaded locally to my jupyter image, and not the spark server. Is there a way to get commands like these to execute on the spark server? Or download these files to an S3 instance and pass it to the remote spark instance that way?

**Comment by maziyarpanahi** [comment]
Hi,

Could you please provide the full code, full error stack, information about the versions of Spark NLP and Apache Spark, what is your cluster, version of Livy, etc.
