### ISSUE TITLE
required: org.apache.spark.sql.Dataset[_] 

### ISSUE THREAD

**Issue by deepakumarln** [JohnSnowLabs/spark-nlp#2274]
The document assembler transformer is expecting the input to be in format Dataset[_]
## Current Behavior

 found   : org.apache.spark.sql.DataFrame
    (which expands to)  org.apache.spark.sql.Dataset[org.apache.spark.sql.Row]
 required: org.apache.spark.sql.Dataset[_]
         val sparkPipeline = pipeline.fit(training)
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version:
* Apache NLP version:
* Java version (java -version):
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Please fill the template completely, snippet codes, full error, and steps to reproduce this. Issues like this cannot be resolved nor be helped.

**Comment by deepakumarln** [comment]
its solved, thank you.

**Comment by akurenkova** [comment]
I am having the same error, how to resolve it?
