### ISSUE TITLE
Parameters passed from AnnotatorApproach to AnnotatorModel

### ISSUE THREAD

**Issue by lorenz-nlp** [JohnSnowLabs/spark-nlp#231]
Creating a NormalizerModel by using Normalizer, parameters such as the patterns, slang dictionary or lower case are passed to the resulting NormalizerModel. However, the input and output columns defined in the Normalizer are not being passed to the model.

This behavior also applies to other annotators, such as the Lemmatizer and LemmatizerModel.

It is not exactly a bug, but very surprising to the user (principle of least astonishment). Also, the documentation doesn't seems to be inline with the actual behavior:

```
val normalizer = new Normalizer()
  .setInputCols(Array("token"))
  .setOutputCol("normalized")
```

## Expected Behavior
Defined input and output columns are passed from the AnnotatorApproch to the AnnotatorModel.

## Context
I updated SparkNLP from version 1.4.0 to 1.5.4. In 1.4.0, there only was a Normalizer (AnnotatorModel), which was changed to a Normalizer (AnnotatorApproach) and NormalizerModel (AnnotatorModel). After fixing all compile time errors, the pipeline blew up during runtime due to non-defined input- and output columns (they were only set for the Normalizer).

## Your Environment
* Version used: 1.5.4

**Comment by saifjsl** [comment]
Thank you @lorenz-nlp 

This is a strange, since if you put everything in a Pipeline, the input and output columns do get passed, since otherwise it wouldn't be able to call **transform()** (since the annotator next to the Normalizer wouldn't be using NormalizerModel's output on the pipeline), but that does happen.

Is this hapening when you load a NormalizerModel from disk? I'll check it out

**Comment by lorenz-nlp** [comment]
Thanks for checking the problem. I didn't use a pipeline here, but just called `train `with an empty dataset on the Normalizer in order to obtain the NormalizerModel.

**Comment by saifjsl** [comment]
@lorenz-nlp Could you please check whether this behavior is the same within SparkML in general? (i.e. using Spark ML transformers outside pipelines and see if you can load models and they keep their input/output cols)

**Comment by lorenz-nlp** [comment]
Sure, I just checked `org.apache.spark.ml.feature.{IDF,IDFModel}` and `org.apache.spark.ml.feature.{VectorIndexer,VectorIndexerModel}`: In both cases, the params are being passed to the resulting model by using the `copyValues`-method of the `Params`-trait in the `fit`-method of the estimator.

But seeing the code of `AnnotatorApproach`, the `fit`-method does copy the params as well (thats why it works in the pipeline). Hence, I believe I should use the `fit`-method instead of the `train`-method in order to obtain the model from an estimator.

**Comment by saifjsl** [comment]
ohh! I just realized you said you used train(). Indeed, I even believe 
train() should be protected. I'll give it some thought. Thank you.

If you believe there's no issue, feel free to close.

**Comment by lorenz-nlp** [comment]
Sure, thanks for your help, I happily close the issue.
