### ISSUE TITLE
Deep Learning Pretrained Pipelines Failing to Load

### ISSUE THREAD

**Issue by cfoleyie** [JohnSnowLabs/spark-nlp#2329]
Description
I have an issue that seems specifically related to the deep learning ("_dl") pretrained pipelines.

Specifically if I run the following:
pipeline = PretrainedPipeline('explain_document_ml', lang='en')
it runs fine, if however I run
pipeline = PretrainedPipeline('explain_document_dl', lang='en')

I get the following error:
```
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline.
: java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: linux, architecture: x86_64. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.
```
Any ideas why this is occurring just for the deep learning libraries?

Expected Behavior

Current Behavior

Possible Solution

Steps to Reproduce

```
from sparknlp.base import *
from sparknlp.annotator import *              
from sparknlp.pretrained import PretrainedPipeline
import sparknlp

spark = sparknlp.start()
pipeline = PretrainedPipeline('explain_document_dl', lang='en')
```

Context
Your Environment

Spark NLP version: 2.7.4

Apache NLP version:
Java version (java -version):
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

Setup and installation (Pypi, Conda, Maven, etc.):
Followed steps in:

java -version
conda create -n sparknlp python=3.6 -y
conda activate sparknlp
pip install spark-nlp==2.7.4 pyspark==2.4.7

Operating System and version:
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"

Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Thanks for reporting this. Our Deep Learning models/pipelines use TensorFlow (1.15.0) via JNI. It seems either the OS or the GCC on it is not compatible with TensorFlow 1.15.

I have personally tested RHEL 8 Enterprise successfully. Is there a way to upgrade your RHEL to some newer releases of 7.x for testings?

**Comment by cfoleyie** [comment]
Hi, no I cannot update the OS, is there something else I can try?

**Comment by maziyarpanahi** [comment]
Unfortunately, we don't control the TensorFlow compatibility on different Operating Systems. You can use any annotators, moels, and pipelines that don't use TensorFlow. 

I would also try to see if different ways of loading/using the library help. Like pyspark shell, Jupyter, even spark-shell in Scala. Just to be 100% sure there is no way to use TensorFlow 1.15 via JNI on RHEL 7.3 without upgrading it.

**Comment by cfoleyie** [comment]
Ok are you saying that it's not possible to update my tensorflow version on my current OS? Or should I try this.

**Comment by maziyarpanahi** [comment]
The TensorFlow comes with Spark NLP and the only version is for now 1.15. The upcoming release will be TensorFlow 2.x, but if 1.15 is not supported I doubt 2.x will support but maybe once it's out you can try. 

The issue is direct with your Operating System and its dependencies. I am suspecting 7.3 was out around 2016/2017 if I am not mistaken and TensorFlow 1.15 by default might not support it.

**Comment by cfoleyie** [comment]
Ok understood, thank you.

**Comment by maziyarpanahi** [comment]
You are welcome.
