### ISSUE TITLE
'JavaPackage' object is not callable @ document = DocumentAssembler().setInputCol("description").setOutputCol("document")

### ISSUE THREAD

**Issue by eedreamer** [JohnSnowLabs/spark-nlp#2340]
Launch the pyspark in WINDOWS with the command >"pyspark"
In the pyspark, run the following scripts, ...

from pyspark.sql import SparkSession
spark = SparkSession.builder\
        .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.7.4")\
        .getOrCreate()
...
from sparknlp.annotator import *
from sparknlp.common import *
from sparknlp.base import *    
document = DocumentAssembler().setInputCol("description").setOutputCol("document")

Error says 'JavaPackage' object is not callable @ document = DocumentAssembler().setInputCol("description").setOutputCol("document")

HOWEVER, if I launch the pyspark using the command "pyspark --packages com.johnsnowlabs.nlp:spark-nlp_2.11:2.7.4"
and run the same python scripts, it  works.
So my guess is the configure option for loading the jars.packages is not working when creating the spark session
 spark = SparkSession.builder\
        .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.0.1")\
        .getOrCreate()

Please advise. I am looking for a solution to load the sparknlp packages inside the python scripts rather than in the windows command. Thanks

**Comment by maziyarpanahi** [comment]
Hi,
When you are using `pyspark` it will start the SparkSession for you. So whatever you create after it will be ignored due to `getOrCreate` in SparkSession.

So if you are using `spark-shell`, `pyspark` shell, `spark-submit`, or any environment that creates the SparkSession for you, you must set the configs at the same time or none of the configs will take effect:

```
pyspark --driver-memory 16g --conf spark.kryoserializer.buffer.max=1000M --packages com.johnsnowlabs.nlp:spark-nlp_2.11:2.7.4
```

**Comment by eedreamer** [comment]
My question is If I construct my own SparkSession using 
spark = SparkSession.builder.config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.7.4").getOrCreate(), 
I found the packages defined in the config option are not auto-downloaded and loaded for me. I need to manually download the packages and saved in the %SPARK_HOME%/jars for use. Is that expected behavior or not?

**Comment by eedreamer** [comment]
Two more related questions about launching a spark session.
1. If I want to start the spark session using spark = sparknlp.start(), how to add the ".config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.7.4")" options into the sparknlp.start();
2. If I want to start the spark session with GPU support, what is the equivalence of sparknlp.start(gpu=true) using SparkSession.builder command?
Thanks

**Comment by maziyarpanahi** [comment]
- you don’t need to manually download any packages. I don’t what you are doing, but using Maven package will download everything needed in ~/.ivy
- sparknlp.start() construct a right SparkSession and starts it, no meed to add anything to it. (We know how to start SparkSession for Spark NLP)
- The name of the dependency for gpu is in the README

I think this matter is resolved unless you have any actual error. Best of luck.
