### ISSUE TITLE
'Finisher' object has no attribute 'setIncludeMetadata'

### ISSUE THREAD

**Issue by PinusSilvestris** [JohnSnowLabs/spark-nlp#235]
When working with PySpark Finisher does not seem to have this attribute implemented.

finisher = Finisher() \
  .setInputCols(["assembled"]) \
  .setCleanAnnotations(True) \
  .setOutputAsArray(False) \
  .setIncludeKeys(True) \
  .setIncludeMetadata(False)

This happens on machine with Apache Spark 2.3.1 and SparkNLP 1.5.4

**Comment by saifjsl** [comment]
Thank you, I confirm this bug exists and fix shall be released  this week

**Comment by saifjsl** [comment]
https://github.com/JohnSnowLabs/spark-nlp/pull/237
