### ISSUE TITLE
How exactly can you use the output from finisher as input for word2vec? would you mind posting some code?

### ISSUE THREAD

**Issue by boris-mtdv** [JohnSnowLabs/spark-nlp#239]
I have used Spark's native Tokenizer on a corpus, and have seen examples that use Spark nlp's finisher afterwards. My question is, how can you use the output from the finisher as input to the word2vec algorithm in mllib? here is an example of my code: 

val textDF = bigRdd.toDF("text")

    val tokenizer = new Tokenizer().setInputCol("text").setOutputCol("tokenized_text")

    val tokenized = tokenizer.transform(textDF)

    val res = tokenized.select("tokenized_text")

    val finisherR = new Finisher()
      .setInputCols("tokenized_text")
      .setOutputAsArray(true)

    val finishedd = finisher.transform(res)

I have no idea where to go from here, because the word2vec algorithm expects input of type JavaRDD[S], which I think is an RDD of a collection of strings (what kind of collection, I have no idea), and the finisher object is an RDD[Any]

**Comment by saifjsl** [comment]
Hi, please request access for Slack channel. We can help you there. Closing this since it is not an issue.

**Comment by maziyarpanahi** [comment]
End to end examples here:
https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/tutorials/jupyter
