### ISSUE TITLE
Feature request: setMaxLength for SentenceDetector

### ISSUE THREAD

**Issue by maziyarpanahi** [JohnSnowLabs/spark-nlp#243]
The Stanford CoreNLP has a global flag to improve performance where it avoids very long sentence from being parsed. I am not sure how this library is parsing for sentence detection, but I am sure the length of sentences and characters are impacting performance.

## Description
`setMaxLength`: Add option to avoid parsing any sentence more than `maxLength` to boost performance/memory especially in training stage.

```
val sentenceDetector = new SentenceDetector()
  .setInputCols("document")
  .setOutputCol("sentence")
  .setMaxLength("1000") // avoid parsing any sentence more than 1000 characters 
```

**Comment by maziyarpanahi** [comment]
Hi, @saifjsl

If there is already a way to avoid long sentences to avoid degrading performance automatically then my feature request for SentenceDetector is not relevant anymore. But to clarify, sometimes, some corpus has long sentences either by mistake (forgetting the `.` at the end) or intentionally due to either poor writing or other reasons. That is why the setMaxLength is to assure regardless of the length there will be a limit to how long can be a sentence.

Also, I would like to discuss this `setMinLength` and `setMaxLength` in other relevant annotators. Especially in Tokenizer, Regex, and Chunker. It would be nice to discard anything, for instance, less than 2 characters when we are tokenizing or anything more than 30 characters when we are Chunking. It helps to filter not desired outputs depending on the length. 

Do you think it's a good idea to have minimum and maximum in Tokenizer, Regex, or at least in Chunker?

Thanks again

**Comment by saifjsl** [comment]
We have discussed a little bit about this. We may include this plus a min-max limit on amount of sentences per row after sentence detection.

**Comment by maziyarpanahi** [comment]
This has been implemented in many releases ago in all SentenceDetector, SentenceDetectorDL, and even Tokenizer along with minLength to filter out unwanted lengths from the output.
