### ISSUE TITLE
java.util.NoSuchElementException: Param detectLists does not exist.

### ISSUE THREAD

**Issue by moussa7** [JohnSnowLabs/spark-nlp#2454]
## Description

I am using databricks cluster (spark version 2.4.5 & sparknlp version 2.7.1).

Here is my code:
---------------------------------
from sparknlp.base import *
from sparknlp.annotator import *
from sparknlp.embeddings import *
from sparknlp.pretrained import PretrainedPipeline
import sparknlp

spark = sparknlp.start()
pipeline = PretrainedPipeline('explain_document_dl', lang='en')
-----------------------------------

The error I got is: "java.util.NoSuchElementException: Param detectLists does not exist."

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version `sparknlp.version()`:
* Apache NLP version `spark.version`:
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Please complete the template, we need that information.
