### ISSUE TITLE
Scaladoc

### ISSUE THREAD

**Issue by kevinykuo** [JohnSnowLabs/spark-nlp#246]
Is this available somewhere? I'm working on the R API and it would be helpful to have documentation that's more details than http://nlp.johnsnowlabs.com/components.html.

**Comment by saifjsl** [comment]
Hello, unfortunately not! Welcome to help

**Comment by maziyarpanahi** [comment]
All the annotators have link to Scaladoc APIs above each example like Apache Spark documentation:
https://nlp.johnsnowlabs.com/docs/en/annotators
