### ISSUE TITLE
BertEmbeddings lacking setPoolingLayer attribute

### ISSUE THREAD

**Issue by AllardJM** [JohnSnowLabs/spark-nlp#2467]
My local version of BERT embeddings (2.7.5) throws an error when trying to set 
setPoolingLayer() with BertEmbeddings.pretrained(). I found this error exists on the same from your tutorials as well:

https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/blogposts/3.NER_with_BERT.ipynb?authuser=1#scrollTo=7TMzw75M-oge

bert_base_cased download started this may take some time.
Approximate size to download 389.1 MB
[OK!]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-af673ae4eec4> in <module>()
----> 1 bert_annotator = BertEmbeddings.pretrained('bert_base_cased', 'en')  .setInputCols(["sentence",'token']) .setOutputCol("bert") .setCaseSensitive(False) .setPoolingLayer(0)

AttributeError: 'BertEmbeddings' object has no attribute 'setPoolingLayer'

**Comment by maziyarpanahi** [comment]
Please complete the template for the next issues, really hard to make any decision without any of that information. 

You are using either an old model or an old version. Please use spark-nlp==2.7.5 for both PyPI and Maven and for offline models, download this one and extract it:

https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/models/bert_base_cased_en_2.6.0_2.4_1598340336670.zip

PS: poolLayer param was removed from BertEmbeddings way back in the 2.6.0 release, that notebook needs to be updated. (you can ask for an update here https://github.com/JohnSnowLabs/spark-nlp-workshop/issues)

reference: https://github.com/JohnSnowLabs/spark-nlp/releases/tag/2.6.0

**Comment by AllardJM** [comment]
Is the default (and only option) layer 0 now?

**Comment by maziyarpanahi** [comment]
The models are coming from TF Hub, they stopped providing access to other layers and we found no evidence the other layers perform better (although they might be more performant since they require fewer computations, but not more accurate)

https://tfhub.dev/google/collections/bert/1

We get what TF Hub outputs which is `sequence_output` (probably the last hidden layer)

**Comment by AllardJM** [comment]
Sorry one more related question on this output. So it seems that (inspecting the output) there is no "CLS" tag present. So, with Spark NLP for BERT a user is given the options for sentence classification type tasks to use the per token output and manually reduce (e.g. average) the tokens to a single embedding vector per sentence OR use the USE model. Is this correct about no CLS tag?

**Comment by maziyarpanahi** [comment]
The `CLS` is random and meaningless if it's not coming from a fine-tune BERT model. The models we provide are pretrained without any fine-tuning therefore that output has no meaning. That's being said, BertEmbeddings is word embeddings that output vectors for each token, CLS is an aggregated result for a sentence. We have BertSentencEmbeddings or UniversalSentenceEmbeddings or SentenceEmbeddings for document/sentence embeddings.

We have many tutorials and examples explaining everything for using embeddings in NER or Classification here: 

https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/tutorials/Certification_Trainings/Public

Best of luck
