### ISSUE TITLE
Spark-ML Pipeline freezes and never finishes with medium-sized dataset

### ISSUE THREAD

**Issue by jtrenkle** [JohnSnowLabs/spark-nlp#2478]
While trying to test spark-nlp out of the box I am running into a situation where the process stalls in some part of the pipeline with no further progress.  I made sure you wait a significant time, but the processes never terminated...

## Description

I am very interested in using Spark-NLP to generate embeddings for a medium-sized set of documents for the purposes of comparing queries to a set of sentences. In order to try it out and kick the tires a bit I have taken one of the stock examples from the python getting started page and simply inserted my dataframe (significantly undersampled) to test things.  I am working on Databricks.  

Here are the setups for my cluster based on what I've seen on your site and various tutorials
 • https://nlp.johnsnowlabs.com/docs/en/install#python
• https://medium.com/spark-nlp/spark-nlp-quickstart-tutorial-with-databricks-5df54853cf0a

![Databricks-Setup-JMT](https://user-images.githubusercontent.com/38893214/111942772-40623100-8a91-11eb-9034-ba3acbcdca5c.png)

Here are the libraries installed as described:

![Databricks-spark-nlp-libs](https://user-images.githubusercontent.com/38893214/111942832-6be51b80-8a91-11eb-884e-161a4e1b2474.png)

I was able to run the test process that uses a tiny dataframe.  Next, I swapped in my dataset and sampled 
• 100 records.  It worked.  
• 1000 records.  It worked.
• 10000 records.  it worked.

Above that it did not work and freezes each time in some stage of the pipeline

The cluster has good cluster memory (the cluster I sent here is much smaller than the original with the same behavior.  

I have looked into every possible diagnostic, log, stderr, stdout, etc. but nothing seems to indicate a problem.  It just never finishes or yields a result.

Here's the code: 

```
from pyspark.sql.functions import udf
from pyspark.sql.types import *
from pyspark.sql import functions as F

import sparknlp
from pyspark.ml import Pipeline
from sparknlp.pretrained import PretrainedPipeline
from sparknlp.annotator import *
from sparknlp.base import *

spark = sparknlp.start()   # I have tried it with this and without this.  I don't think it's required in DB, but it does not change the outcome
```

```
# Load my dataframe
HyperTextDF = spark.read.format("delta").load(fName)
print("There are {:,} records".format(HyperTextDF.count()))

HyperTextDF = (HyperTextDF
               .filter("textCat IN ('predicate')")
               .filter("numChars <= 128")

               # Undersample
               .limit(sc.defaultParallelism*10000)
               
               # We only need these fields
               .select("imdbId", "text")
               
               # make sure to take advantage of the cores we have
               .repartition(sc.defaultParallelism*10)
              ).cache()
print("There are {:,} records".format(HyperTextDF.count()))
```

There are 640k records in this test

The pipeline: 

```
# Basic Spark NLP Pipeline
document_assembler = (DocumentAssembler()
                      .setInputCol("text")
                      .setOutputCol("document")
                     )
                      
cleanUpPatterns = ["a-zA-Z"] # "[^\w\d\s]", "<[^>]*>", "\-\_"]
removalPolicy = "pretty_all"
document_normalizer = (DocumentNormalizer()
                      .setInputCols("document")
                      .setOutputCol("normalizedDocument")
                      .setAction("clean")
                      .setPatterns(cleanUpPatterns)
                      .setPolicy(removalPolicy)
                      .setLowercase(True)
                     )

sentence_detector = (SentenceDetector()
                     .setInputCols(["normalizedDocument"])
                     .setOutputCol("sentence")
                    )
                     
tokenizer = (Tokenizer()
             .setInputCols(["normalizedDocument"])
             .setOutputCol("token")
            )
                     
elmo = (ElmoEmbeddings
        .pretrained()
        .setInputCols(["token", "normalizedDocument"])
        .setOutputCol("elmo")
        .setPoolingLayer("elmo")
       )

nlpPipeline = Pipeline(stages=[
                                document_assembler,
                                document_normalizer,
                                sentence_detector, 
                                tokenizer,
                                elmo,
                            ])
```

Run it: 

```
nlp_model = nlpPipeline.fit(HyperTextDF)
processed = nlp_model.transform(HyperTextDF).cache()
print("There are {:,} records".format(processed.count()))
```

Then we see this...forever: 

![Stage 16 ad infinitum](https://user-images.githubusercontent.com/38893214/111944019-ee6eda80-8a93-11eb-9a0c-1da7c3e525da.png)

I appreciate any help or insight into this issue.  Thanks

## Expected Behavior

Process finished and yields annotated dataframe

## Current Behavior

Process freezes and never yield an outcome

## Steps to Reproduce

Run the stock example with a different, bigger dataset

## Context

Trying to process a large set of sentences to get embedding for an application where we need to finds nearest neighbors in embedding space for a query

## Your Environment

* Spark NLP version `sparknlp.version()`:  2.7.5
* Apache NLP version `spark.version`: 
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.): Maven, pypi
* Operating System and version:
* Link to your project (if any):

From Databricks: 

```
System environment
Operating System: Ubuntu 16.04.6 LTS
Java: 1.8.0_252
Scala: 2.11.12
Python: 3.7.3
R: R version 3.6.2 (2019-12-12)
Delta Lake: 0.5.0
```

**Comment by jtrenkle** [comment]
Details for Stage 16, if it might help: 

![Stage-16-details](https://user-images.githubusercontent.com/38893214/111944756-9b962280-8a95-11eb-8fc5-a1aebd23da1d.png)

A typical `stdout`: 

![Stage-16-stdout](https://user-images.githubusercontent.com/38893214/111944860-cda78480-8a95-11eb-808e-4843d7b16e66.png)


A typical `stderr`: 

![Uploading Stage-16-stderr.png…]()

**Comment by jtrenkle** [comment]
If it seems like it might be a matter of just being (very) time-consuming to compute these embeddings, are there any suggestions on configuration or conditioning of the Dataframe to take advantage of a large cluster with many cores?  BTW, are there any facilities for getting some intermediate informational output so we have a better intuition about where we are when running a multi-stage pipeline?

**Comment by maziyarpanahi** [comment]
Hi @jtrenkle 
First, I would like to thank you for such a complete issue. It will be an example for other issues to come for sure.

I can see this issue is a combination of Cluster tuning in Apache Spark (number of executors, number of cores, partitions, memory, etc.) and the fact that you are using a Transformer that requires accelerated hardware like GPU.

I have some recommendations from what I see and later on this week I will do the same over 120K dataset with ElmoEmbeddings and share my findings:

- I can see you already filter by character size (<128), so my advice will be more generic here. Removing SentenceDetector that splits documents into sentences is really helpful when dealing with Transformers such as ELMO or BERT. The sentences are shorter than a total document, you avoid hitting the max_sequence_length, and the shorter the input the faster the finish interfering
- I can see you have in total 4x16 cores. This means you have in total 64 cores, so the partition for your DataFrame should be in the best situation be set to 64. 
- Speaking of partitions, since ELMO is very computational the more cores mean more parallelism and faster computations
- I see lots of GC, I do suggest instead of 4 very massive workers to have maybe 10-20 smaller instances such as (8 cores with 16G memory) - 
- The Driver memory shouldn't be set in your Spark ENV, the Driver machine should be able to use all the memory assigned to it. Otherwise, the rest of that memory goes wasted as it won't be used for any execution.
- You are correct `spark = sparknlp.start()` is not needed in Databricks as the cluster comes with SparkSession already


The advice you can take it right away:
- The Spark NLP 3.0.0 is out. So please use `spark-nlp_2.12` on Databricks 7.3 or above (spark 3.0.x or spark 3.1.1) which has more optimizations
- Do use `sentence` as the input for `Tokenizer` and `ElmoEmbeddings` instead of DocumentNormalizer output
- Please try other Transformers such as `BertEmbeddings` which is already optimized in Spark NLP 3.0.0, the following is what I do in Databricks for distribution tests:

```scala
val embeddings = BertEmbeddings
    .pretrained("small_bert_L2_128")
    .setInputCols("sentence", "token")
    .setOutputCol("embeddings")
    .setBatchSize(8)
```

This is `BERT Tiny`, I run this over 120K documents from `News Category` datasets and it finishes/saves on DBFS in 30 seconds over the following cluster:

```
Driver
m4.2xlarge 32.0 GB Memory, 8 Cores, 1.5 DBU

10x Workers
m4.2xlarge 32.0 GB Memory, 8 Cores, 1.5 DBU
```

PS: I will try ElmoEmbeddings over 120K documents this week and share my findings with you

**Comment by jtrenkle** [comment]
Thanks for the great feedback.  I was actually only using ELMO as it was in the example, but the BERT tiny is more in my sweet spot.  I'll digest your advice and get back to you soon.  Thanks for the timely response!

**Comment by jtrenkle** [comment]
Also, thanks for mentioning that the Spark 3 variant was available.  I didn't see it when I was installing originally. It was quite a step back from my current environment to go back to DB 6.4.

**Comment by jtrenkle** [comment]
Got the new Spark 3 version working fresh from the oven.  Looks very nice so far

**Comment by jtrenkle** [comment]
Quick question on the prescribed way to get GloVe embedding: This is what I've seen in a couple places: 

```
    theXFormer = (WordEmbeddings.pretrained("glove_6B_300", "xx")
                  .setInputCols("sentence", "token")
                  .setOutputCol("embedding")
                 )
```

However when I put that in, I get this:

`AttributeError: type object 'WordEmbeddings' has no attribute 'pretrained'`

The code block: 

```
# Basic Spark NLP Pipeline
document_assembler = (DocumentAssembler()
                      .setInputCol("text")
                      .setOutputCol("document")
                     )
                      
cleanUpPatterns = ["[^\w\d\s]", "<[^>]*>", "\-\_"]  # ["a-zA-Z"]
removalPolicy = "pretty_all"
document_normalizer = (DocumentNormalizer()
                      .setInputCols("document")
                      .setOutputCol("normalizedDocument")
                      .setAction("clean")
                      .setPatterns(cleanUpPatterns)
                      .setPolicy(removalPolicy)
                      .setLowercase(True)
                      )

tokenizer = (Tokenizer()
             .setInputCols(["normalizedDocument"])
             .setOutputCol("token")
            )

theXFormer = (WordEmbeddings.pretrained("glove_6B_300", "xx")
              .setInputCols("token", "normalizedDocument")
              .setOutputCol("embedding")
             )

nlpPipeline = Pipeline(stages=[
                                document_assembler,
                                document_normalizer,
                                tokenizer,
                                theXFormer,
                              ])
```

Has the signature for GloVe changed in the latest version of `spark-nlp`?

**Comment by jtrenkle** [comment]
BTW, your advice for parameter tuning has panned out and I have been able to churn through some good-sized queries in a timely manner.  Still cleaning some things, but I am in a good spot now.  Although I _do_ have one more question WRT `DocumentNormalizer`

**Comment by maziyarpanahi** [comment]
Hi,

Actually, the correct way for pretrained WordEmbeddings is as follow:

```python
WordEmbeddingsModel.pretrained("glove_6B_300", "xx")
                  .setInputCols("sentence", "token")
                  .setOutputCol("embedding")
```
Unlike other embedding annotators, this one can actually read Word2Vec files, so WordEmbeddings is to read embeddings. And `WordEmbeddingsModel` is to use pretrained models.

**Comment by jtrenkle** [comment]
Thanks for the clarification.  Good news — I was able to run 16M sentences thru BERT in about 12 Minutes.  So, I am on my way to getting the collection I wanted to experiment with.  I'm going to try out Universal Sentence Embeddings, XLNet and I should be golden.  Thanks for the help and the great module!
