### ISSUE TITLE
NER label always 'O' with Pyspark 

### ISSUE THREAD

**Issue by admunnik** [JohnSnowLabs/spark-nlp#253]
When training a ner label via Pyspark, the results of the NER tags always is 'O'.
This issue happens when following the provided example notebooks for NER tagging. One can simply reproduce this by following the example on Github: 
https://github.com/JohnSnowLabs/spark-nlp/blob/1.6.0/python/example/crf-ner/ner.ipynb

It seems to work fine when using the pretrained() POS and NER in a pipeline, but using a NerCrfApproach() in a pipeline results in 'O'.

**Comment by saifjsl** [comment]
The issue happened also in Scala. It is related to a bug introduced in 1.6.0 with newly trained models, having bad accuracy due changes in DocumentAssembler that caused breaking of CONLL format.

https://github.com/JohnSnowLabs/spark-nlp/pull/252

**Comment by saifjsl** [comment]
Fixed for CRF in 1.6.1. Will be fixed for DL in 1.6.2
