### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.spark.ml.util.MLWritable.$init$(Lorg/apache/spark/ml/util/MLWritable;)

### ISSUE THREAD

**Issue by arcpool** [JohnSnowLabs/spark-nlp#2593]
## Description
As I was loading my fine-tuned model in google collab(25GB RAM), it is outputting an error as mentioned in the title.

## Expected Behavior

Ideally, as it was working before, it should load the model within seconds and not give any error.
## Current Behavior

**It is giving the following error:**
"NER_BERTModel" is the name of my saved model.
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-7-d0f22f950cec> in <module>()
----> 1 loaded_ner_model = NerDLModel.load("/content/NER_BERTModel")    .setInputCols(["sentence", "token", "bert"])   .setOutputCol("ner")
      2 

8 frames
/usr/local/lib/python3.7/dist-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling None.com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel.
: java.lang.NoSuchMethodError: org.apache.spark.ml.util.MLWritable.$init$(Lorg/apache/spark/ml/util/MLWritable;)V
	at com.johnsnowlabs.nlp.AnnotatorModel.<init>(AnnotatorModel.scala:15)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel.<init>(NerDLModel.scala:24)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)`

## Steps to Reproduce

1. Trained the model before
2. Saved it to local system
3. Tried loading it to google collab
4. Error occured

## Context

I have loaded the model before and it was working perfectly fine. 
Since today morning, I am getting this error. Kindly request you to help. 

## Your Environment

* Spark NLP version `3.0.0`:
* Apache NLP version `2.4.4`:
* Java version `1.8.0_282`:
* Operating System and version: macOS High Sierra | 10.13.6
![58850235-cee3-4fe0-a8de-ffc641e477ca](https://user-images.githubusercontent.com/65263304/112468535-638d2900-8d8e-11eb-8765-3220078c27d4.jpg)

**Comment by maziyarpanahi** [comment]
Hi,
The issue is this:

Spark NLP version 3.0.0:
Apache NLP version 2.4.4:

You forgot to share how you install Spark NLP and PySpark and how you start SparkSession, but the error represents version mismatch:

https://github.com/JohnSnowLabs/spark-nlp/discussions/2562

**Comment by maziyarpanahi** [comment]
PS: forgot to also mention we have Colab instructions with a demo notebook:

- https://github.com/JohnSnowLabs/spark-nlp#google-colab-notebook
- https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/quick_start_google_colab.ipynb

**Comment by mwunderlich** [comment]
I ran into the same issue with SparkNLP 2.7.5 and PySpark 2.4.4. I was able to resolve it by downgrading my Conda environment from Python 3.9 to Python 3.7.11 and also making sure that my IDE (IntelliJ) was using the correct python interpreter. 

Here is a good overview about which versions of SparkNLP are compatible with which PySpark version 
https://pypi.org/project/spark-nlp/#pipconda
