### ISSUE TITLE
Example Colab Notebook Throws Error (Detect Emotions in Tweets)

### ISSUE THREAD

**Issue by nico3865** [JohnSnowLabs/spark-nlp#2597]
## Description

I'm running the example colab notebook for "Detect Emotions in Tweets"
https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/streamlit_notebooks/SENTIMENT_EN_EMOTION.ipynb

At the code cell under section 5 "Define Spark NLP pipeline", it's throwing this error: 

`---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-3-bd7bcdb22dff> in <module>()
----> 1 spark = sparknlp.start()

7 frames
/usr/local/lib/python3.7/dist-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
	at scala.xml.Null$.<init>(Null.scala:23)
	at scala.xml.Null$.<clinit>(Null.scala)
	at org.apache.spark.ui.jobs.AllJobsPage.<init>(AllJobsPage.scala:43)
	at org.apache.spark.ui.jobs.JobsTab.<init>(JobsTab.scala:47)
	at org.apache.spark.ui.SparkUI.initialize(SparkUI.scala:61)
	at org.apache.spark.ui.SparkUI.<init>(SparkUI.scala:80)
	at org.apache.spark.ui.SparkUI$.create(SparkUI.scala:178)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:444)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)`

## Expected Behavior

It should run the demo normally, i.e. predict emotions in the sentences in that notebook (?)!!!

## Current Behavior

It throws an error, described above (I pasted the whole error). 

## Possible Solution

Is it because of the new version 3.0.0?
I have no idea though. 

## Steps to Reproduce

1. go to --> https://demo.johnsnowlabs.com/public/SENTIMENT_EN_EMOTION/
2. click the "open in colab" link
3. run all cells in the Colab notebook
4. observe the error I pasted above

## Context

Running the demo colab for detecting emotions in Tweets. 

## Your Environment

The versions are fully defined in that example colab notebook.
FYI they are (from the first cell):

!apt-get update -qq
!apt-get install -y openjdk-8-jdk-headless -qq > /dev/null
!java -version
!pip install --ignore-installed -q pyspark==2.4.4
!pip install --ignore-installed spark-nlp

**Comment by maziyarpanahi** [comment]
Hi @diatrambitas 

This streamlit app is pointing to a Colab that installs pyspark==2.4.4 but spark-nlp has no version so it installs the latest which is 3.0.0.

All the Notebooks should be either spark-nlp==2.7.5 to work as before or pyspark=3.1.1 to work with spark-nlp=3.0.0 (I suggest the 3.1.1)

**Comment by nico3865** [comment]
Ok. I tried spark-nlp==2.7.5, but Colab doesn't seem to let me install it, and installs spark-nlp==3.0.0 instead.




Code in first cell:

!apt-get update -qq
!apt-get install -y openjdk-8-jdk-headless -qq > /dev/null
!java -version
!pip install --ignore-installed -q pyspark==2.4.4
!pip install --ignore-installed spark-nlp==2.7.5




Output from first cell:

openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
Collecting spark-nlp==2.7.5
  Using cached https://files.pythonhosted.org/packages/1b/d9/44fd438e15fa9a02c0e3b3ca9eaffc509fc626592f7a03ce05d8f156d448/spark_nlp-2.7.5-py2.py3-none-any.whl
Installing collected packages: spark-nlp
Successfully installed spark-nlp-3.0.0
WARNING: The following packages were previously imported in this runtime:
  [com,sparknlp]
You must restart the runtime in order to use newly installed versions.



After I restart the runtime, it still throws errors ... I can't get it to install spark-nlp==2.7.5

**Comment by nico3865** [comment]
Then I tried spark-nlp==3.0.0 with pyspark==3.1.1, and that throws a new error:

Code in first cell:

!apt-get update -qq
!apt-get install -y openjdk-8-jdk-headless -qq > /dev/null
!java -version
!pip install --ignore-installed -q pyspark==3.1.1
!pip install --ignore-installed spark-nlp==3.0.0



... Which runs fine, but then the second cell throws an error:


ImportError                               Traceback (most recent call last)
<ipython-input-5-fe3d854fcf5c> in <module>()
      5 os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]
      6 import json
----> 7 from pyspark.ml import Pipeline
      8 from pyspark.sql import SparkSession
      9 import pyspark.sql.functions as F

3 frames
/usr/local/lib/python3.7/dist-packages/pyspark/resource/requests.py in <module>()
     16 #
     17 
---> 18 from pyspark.util import _parse_memory
     19 
     20 

ImportError: cannot import name '_parse_memory' from 'pyspark.util' (/usr/local/lib/python3.7/dist-packages/pyspark/util.py)


NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by maziyarpanahi** [comment]
Please do a factory reset to remove any leftover dependencies installed previously (a simple reset won’t remove those), and just follow this new instruction:

https://github.com/JohnSnowLabs/spark-nlp#google-colab-notebook

**Comment by HashamUlHaq** [comment]
Hi, @nico3865  and @maziyarpanahi this issue has been fixed. All the notebooks have been updated. @nico3865 please report if you encounter any other issue.
