### ISSUE TITLE
Feature request: Annotation-flattening transformer

### ISSUE THREAD

**Issue by arnold-jr** [JohnSnowLabs/spark-nlp#267]
Use case: I want to feed tokenized (cleaned) words (`Array[String]`) into a SparkML pipeline.

Problem: `Tokenizer` yields `Array[Annotation]` which needs to be mapped. To use further in a Spark ML pipeline requires a `Transformer`.

Proposed solution: A standard `AnnotationFlattener` transformer to do this. I implemented one myself, with the pertinent bit being
```scala
  override def transform(dataset: Dataset[_]): DataFrame = {

    val metadataBuilder: MetadataBuilder = new MetadataBuilder()
    metadataBuilder.putString("annotatorType", annotatorType)

    dataset.withColumn(
      getOutputCol,
      Annotation.flattenArray(col(getInputCol)).as(getOutputCol, metadataBuilder.build)
    )
  }
```

Thanks!

**Comment by saifjsl** [comment]
Hi @arnold-jr thanks for the idea. Indeed sometimes someone might want to feed into tokenized content.

Our DocumentAssembler is capable of reading Array[String] columns although it's output is going to be of type DOCUMENT and not token.
