### ISSUE TITLE
Can not download fat jar for version 1.6.3

### ISSUE THREAD

**Issue by daniel-cortez-stevenson** [JohnSnowLabs/spark-nlp#274]
## Description
Hey y'all, thanks for the great package! Just getting started working with it but it's exactly what I need. My issue is that the fat jar for version 1.6.3 is not downloading.

## Expected Behavior
The download for the fat jar should commence when clicking the 'here' button within https://nlp.johnsnowlabs.com/quickstart.html (section: Pre-Compiled Spark-NLP for download)

## Current Behavior
When I try to download the fat jar for version 1.6.3 from https://nlp.johnsnowlabs.com/quickstart.html (section: Pre-Compiled Spark-NLP for download), I am directed to this url: https://s3.amazonaws.com/auxdata.johnsnowlabs.com/spark-nlp-assembly-1.6.3.jar, which returned an "Access Denied" page:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>7940056C90531BFA</RequestId>
<HostId>quKdFmT/K1l8C6F2fLyqSPbYnHseaVt/0S8fdGFhypdRMFPhfaC5kChKK8xdI2ygPb+/M4CZbuk=</HostId>
</Error>
```
If I change the url to: https://s3.amazonaws.com/auxdata.johnsnowlabs.com/spark-nlp-assembly-1.6.2.jar, the download commences just fine.

I have tried with Firefox and Google Chrome.

## Possible Solution
Issue with AWS S3 permissions perhaps?

## Steps to Reproduce
1. click on this link https://s3.amazonaws.com/auxdata.johnsnowlabs.com/spark-nlp-assembly-1.6.3.jar

## Context
It would be great to used the fat jar to run spark-nlp locally.

## Your Environment

* Version used: N/A
* Browser Name and version: 
Mozilla 62.0 (64-bit) 
Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): 
Desktop MacOS
* Link to your project: N/A

**Comment by saifjsl** [comment]
Thank you @daniel-cortez-stevenson 

I am now uploading the jars, should be available in the next few minutes from this comment

**Comment by daniel-cortez-stevenson** [comment]
Great, thanks @saifjsl
