### ISSUE TITLE
libtensorflow_framework.so not found

### ISSUE THREAD

**Issue by peili-uzh** [JohnSnowLabs/spark-nlp#2752]
## Description
When using NerDLApproach to train a Ner model, Tensoflow fails to load library from sparknlp_contrib_spar 

## Current Behavior
`An exception or error caused a run to abort: libtensorflow_framework.so: cannot open shared object file: No such file or directory 
java.lang.UnsatisfiedLinkError: libtensorflow_framework.so: cannot open shared object file: No such file or directory
	at org.tensorflow.TensorFlow.loadLibrary(TensorFlow.java:47)
	at com.johnsnowlabs.nlp.annotators.ner.dl.LoadsContrib$.loadContribToTensorflow(LoadsContrib.scala:68)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLApproach.beforeTraining(NerDLApproach.scala:104)
	at com.johnsnowlabs.nlp.AnnotatorApproach.fit(AnnotatorApproach.scala:44)`

It points to TensorFlow.loadLibrary(fp1), and the file fp1 indeed exists in path: /tmp/spark-89f66167-45a0-413f-929b-5333a301db1e/userFiles-4ccf632e-c865-4d26-93a9-72346b266ad9/sparknlp_contrib_spar

## Steps to Reproduce

`val input = CoNLL(conllLabelIndex = 1).readDataset(spark = sqlContext.sparkSession,
      path="$path/ner_train.txt")
    val document = new DocumentAssembler().setInputCol("text").setOutputCol("document")
    val sentence = new SentenceDetector().setInputCols(Array("document")).setOutputCol("sentence")
    val token = new Tokenizer().setInputCols(Array("sentence")).setOutputCol("token")
    val bert = BertEmbeddings.pretrained("bert_base_cased", "en")
      .setInputCols(Array("sentence", "token"))
      .setOutputCol("bert")

    val nerTagger = new NerDLApproach()
      .setInputCols(Array("sentence", "token", "bert"))
      .setLabelColumn("label")
      .setOutputCol("ner")

    val pipeline = new Pipeline().setStages(Array(
      document, sentence, token, bert
    ))

    val trainData = pipeline.fit(input).transform(input)
    nerTagger.fit(trainData)`

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.0.0
* Apache NLP version `spark.version`: 3.0.1
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version: Ubuntu 20.04.1
* Link to your project (if any):

**Comment by peili-uzh** [comment]
run `ldd <fp1>` leads to:
`linux-vdso.so.1 (0x00007fff1d7a4000)
libtensorflow_framework.so => not found
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff85d710000)
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff85d52f000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff85d514000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff85d320000)
/lib64/ld-linux-x86-64.so.2 (0x00007ff85d8c3000)`

**Comment by maziyarpanahi** [comment]
- please complete the template by adding java version and how you installed/and using spark-nlp
- Please share your full code
- Also this part doesn’t make any sense:

This version doesn’t exist:
Spark NLP version sparknlp.version(): 2.2.2.4

If you are using spark 3.x you have to use spark-nlp 3.0.0 as well
Apache NLP version spark.version: 3.0.1

**Comment by peili-uzh** [comment]
@maziyarpanahi  thanks a lot for the feedback. The problem is indeed caused by old spark-nlp version (2.2.2). It works now when upgrading to 3.0.0:

**Comment by maziyarpanahi** [comment]
I am glad it worked out, please open a new issue if you face any other problem(s).
