### ISSUE TITLE
NerConverter - add confidence score for entities

### ISSUE THREAD

**Issue by dkincaid** [JohnSnowLabs/spark-nlp#2753]
In the column that results from running the NerConverter annotator against the output of an NER model it would be very useful to have the confidence score for the entity in the metadata. Would it be possible to add this? For multi-token entities something like the average confidence score could be used.

**Comment by C-K-Loan** [comment]
This feature is part of the Spark NLP Healthcare library and available via the NerConverterInternal.
It gets you one confidence score for every extracted entity as described by you.

Maybe it can become an open-source feature

**Comment by dkincaid** [comment]
Sorry. Where is the right place to suggest new features for the Healthcare library?

**Comment by maziyarpanahi** [comment]
Hi @dkincaid
That does exist in another annotator in a licensed product, but I think we can bring it to open-source as well.

PS: For anything related to licensed products you can either contact JSL directly or use the slack channel for healthcare. (Those are pretty direct access to the right people)

**Comment by dkincaid** [comment]
Thanks. We have the licensed products, so we can use that one. Seems like a nice feature to add to the open source though too.

**Comment by dkincaid** [comment]
Thanks. I just tried out the licensed version of the annotator and it looks like it's doing exactly what I am asking for here. We'll use that one and you can decide if you want to bring that feature to the open source version.

**Comment by maziyarpanahi** [comment]
I will do and thanks for the feature request @dkincaid
