### ISSUE TITLE
UniversalSentenceEncoder works in Python but not Scala

### ISSUE THREAD

**Issue by katelynrwalker** [JohnSnowLabs/spark-nlp#2773]
## Description and Steps to Reproduce
The documentation for the UniversalSentenceEncoder in Scala shows the following example:

```
val use = new UniversalSentenceEncoder()
        .setInputCols("document")
        .setOutputCol("use_embeddings")
        .setLazyAnnotator(false)
```

Running this code as part of a pipeline results in error when I attempt to use the resulting dataframe:
```
SparkException: Failed to execute user defined function(HasSimpleAnnotate$$Lambda$5207/711150161: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>)
Caused by: NoSuchElementException: None.get
```

I also tried the following (to match both the Python syntax and the syntax for all other Scala embedding annotators), but got "error: type pretrained is not a member of object com.johnsnowlabs.nlp.annotator.UniversalSentenceEncoder"
```
val use = new UniversalSentenceEncoder.pretrained()
        .setInputCols("document")
        .setOutputCol("use_embeddings")
        .setLazyAnnotator(false)
```

## Expected Behavior
In Python, I can run the equivalent pipeline with no errors.
```
use = UniversalSentenceEncoder.pretrained() \
        .setInputCols("document") \
        .setOutputCol("use_embeddings") \
        .setLazyAnnotator(False)
```

## Steps to Reproduce
Full Pipeline:
```
val docAssembler = new DocumentAssembler()
  .setInputCol("citClean")
  .setOutputCol("sentence")
  .setCleanupMode("shrink_full")

val sentEncoder = new UniversalSentenceEncoder()
  .setInputCols("sentence")
  .setOutputCol("embeddings")
  .setLazyAnnotator(false)

val Pipe = new Pipeline().setStages(Array(docAssembler, sentEncoder))
val pipeFit = Pipe.fit(Seq.empty[String].toDF("citClean"))
val useDF = pipeFit.transform(trainDF)
```

## Your Environment

* Spark NLP version `3.0.0 and 3.0.1`:
* Databricks runtime 7.5ML
* Setup and installation (Pypi, Conda, Maven, etc.): PyPI and Maven

**Comment by C-K-Loan** [comment]
Hi @katelynrwalker,
on scala side , to call the `.pretraiend()` method you may not use the `new` keyword. It refers to a method of a fresh object, whereas `UniversalSentenceEncoder.pretrained()` is a singelton 

This is an example of how you would do it in scala
```
val use = UniversalSentenceEncoder.pretrained()
        .setInputCols("document")
        .setOutputCol("use_embeddings")
        .setLazyAnnotator(false)

val docAssembler = new DocumentAssembler()
  .setInputCol("name")
  .setOutputCol("document")
  .setCleanupMode("shrink_full")


val Pipe = new Pipeline().setStages(Array(docAssembler, use))
val pipeFit = Pipe.fit(df)
pipeFit.transform(df).show()
```

**Comment by maziyarpanahi** [comment]
Hi @katelynrwalker 
You got that from our documentation which was wrong and I fixed it. As @C-K-Loan mentioned, even though `UniversalSentenceEncoder` is a Class, but it only has `pretrained` models so no need for the `New`:

```scala
val use = UniversalSentenceEncoder.pretrained()
        .setInputCols("document")
        .setOutputCol("use_embeddings")
```
I have fixed the docs: https://nlp.johnsnowlabs.com/docs/en/annotators#universalsentenceencoder
