### ISSUE TITLE
Unable to save pipeline containing DrugNormalizer

### ISSUE THREAD

**Issue by kgoz12** [JohnSnowLabs/spark-nlp#2781]
## Description
A pipeline containing DrugNormalizer() cannot be saved. 

## Expected Behavior
Should be able to save pipeline.

## Current Behavior
The following error is thrown: "Output directory file:/content/drive/MyDrive/brand_new_models/stages/1_DrugNormalizer_2ea3f4efa8bb/fields/patterns already exists". This can be reproduced using the R sparknlp package, when trying to save the model to a local directory.

## Steps to Reproduce
Example here: https://github.com/kgoz12/JSL/blob/master/Error_saving_pipeline_containing_drug_normalizer.ipynb

## Your Environment
Google colab...
* Spark NLP version `sparknlp.version()`: 3.0.1
* Apache NLP version `spark.version`: 3.1.1
* Java version `java -version`: 1.8.0_282
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any): https://github.com/kgoz12/JSL/blob/master/Error_saving_pipeline_containing_drug_normalizer.ipynb

**Comment by maziyarpanahi** [comment]
Hi,
Unfortunately, we cannot help licensed products as we have no access to reproduce. You can either ask via email or on Slack in #healthcare channel.
However, this error:

```
Py4JJavaError: An error occurred while calling o789.save.
: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory file:/content/drive/MyDrive/brand_new_models/stages/1_DrugNormalizer_2ea3f4efa8bb/fields/patterns already exists
	at org.apache.hadoop.mapred.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:131)
	
```
Simply is saying you already have it so it is not going to save it again. If you want you can add .mode(“overwrite”) or manually remove the existing path.
