### ISSUE TITLE
Misleading Compatibility/Version field in "Detect Assertion Status for Radiology" model page

### ISSUE THREAD

**Issue by ken-mckesson** [JohnSnowLabs/spark-nlp#2782]
**Link to doc page in question (if any):**

https://nlp.johnsnowlabs.com/2021/03/18/assertion_dl_radiology_en.html

**Name of the Spark NLP feature whose docs need improvement:**

Compatibility field says "Spark NLP 2.7.4+", but actually this model is not available in the free / open source edition.

**What you think the docs should say:**

Compatibility field should say "Spark NLP for Healthcare x.x.x".

It currently just says Spark NLP, so when I was searching for "Assertion" models I mistakenly thought this was available in the open source edition.

This confusion could also be resolved by displaying the "License" field on the search results page.

**Comment by maziyarpanahi** [comment]
@HashamUlHaq do you mind fixing this model card? The rest of them are fine, but this one has a wrong edition even though it is still saying licensed.

**Comment by HashamUlHaq** [comment]
@maziyarpanahi ok, sure!
