### ISSUE TITLE
Creating custom annotators

### ISSUE THREAD

**Issue by bairathirahul** [JohnSnowLabs/spark-nlp#281]
Dear Team,

Is there any guide to develop custom transformers or annotators with the spark-nlp framework? I know we can use the Finisher and then use our Spark ML transformers. But it would be easier to develop something complying to this framework, so that we can plug our functions in between the pipeline.

**Comment by saifjsl** [comment]
hi! I believe we have an outdated documentation here:
https://nlp.johnsnowlabs.com/contribute.html
which might give you a few ideas. also, there is a recent commit with a silly-simple annotator here:
https://github.com/JohnSnowLabs/spark-nlp/blob/9a8319a2bd6ac395eb62cf157660f5f2e414d333/src/main/scala/com/johnsnowlabs/nlp/Chunk2Doc.scala

Feel free to join slack or propose some new documentation

**Comment by bairathirahul** [comment]
Thanks a lot. I will look into these.
