### ISSUE TITLE
how to load PretrainedPipeline from disq

### ISSUE THREAD

**Issue by elkhadirzyad** [JohnSnowLabs/spark-nlp#2875]
hello,

In first time, when i load a PretrainedPipeline i use the instruction

`new PretrainedPipeline("explain_document_md", "fr")`

It takes a while to load.

In the second time, i used the same instruction and it takes also a while.

Is there a way to save the PretrainedPipeline in disq and load it from the disq ? thank you

**Comment by maziyarpanahi** [comment]
The instructions for using Spark NLP in offline mode for Pipelines and Models are here: https://github.com/JohnSnowLabs/spark-nlp#offline

That's being said, the time it takes to load the second time is the time it takes to load a model or a pipeline. Spark NLP never downloads a pipeline or a model more than once whether in the same session or even after you close your application and run it again.
