### ISSUE TITLE
SparkNLP 3.0.3 DocumentAssembler doesnt work with pyspark 2.4.4

### ISSUE THREAD

**Issue by drbonis** [JohnSnowLabs/spark-nlp#2908]
## Description

I have tried this code with sparknlp 3.0.3 and pyspark 2.4.4 getting an error that doesnt appear when using pyspark 3.0.1

import sparknlp
from sparknlp.annotator import *
from sparknlp.base import *

spark = sparknlp.start()

doc_ass = DocumentAssembler()\
    .setInputCol("text") \
    .setOutputCol("document")

## Expected Behavior

Get a doc_ass instance of DocumentAssembler.

## Current Behavior

---------------------------------------------------------------------------

Py4JJavaError                             Traceback (most recent call last)

<ipython-input-4-7800a5f372de> in <module>
----> 1 doc_ass = DocumentAssembler()\
      2     .setInputCol("text") \
      3     .setOutputCol("document")
      4 

~/pyenvs/sparknlp303spark24/lib/python3.6/site-packages/pyspark/__init__.py in wrapper(self, *args, **kwargs)
    108             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    109         self._input_kwargs = kwargs
--> 110         return func(self, **kwargs)
    111     return wrapper
    112 

~/pyenvs/sparknlp303spark24/lib/python3.6/site-packages/sparknlp/base.py in __init__(self)
    161     @keyword_only
    162     def __init__(self):
--> 163         super(DocumentAssembler, self).__init__(classname="com.johnsnowlabs.nlp.DocumentAssembler")
    164         self._setDefault(outputCol="document", cleanupMode='disabled')
    165 

~/pyenvs/sparknlp303spark24/lib/python3.6/site-packages/pyspark/__init__.py in wrapper(self, *args, **kwargs)
    108             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    109         self._input_kwargs = kwargs
--> 110         return func(self, **kwargs)
    111     return wrapper
    112 

~/pyenvs/sparknlp303spark24/lib/python3.6/site-packages/sparknlp/internal.py in __init__(self, classname)
     85         self.setParams(**kwargs)
     86         self.__class__._java_class_name = classname
---> 87         self._java_obj = self._new_java_obj(classname, self.uid)
     88 
     89 

~/pyenvs/sparknlp303spark24/lib/python3.6/site-packages/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

~/pyenvs/sparknlp303spark24/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1523         answer = self._gateway_client.send_command(command)
   1524         return_value = get_return_value(
-> 1525             answer, self._gateway_client, None, self._fqn)
   1526 
   1527         for temp_arg in temp_args:

~/pyenvs/sparknlp303spark24/lib/python3.6/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

~/pyenvs/sparknlp303spark24/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling None.com.johnsnowlabs.nlp.DocumentAssembler.
: java.lang.NoSuchMethodError: org.apache.spark.ml.util.MLWritable.$init$(Lorg/apache/spark/ml/util/MLWritable;)V
	at com.johnsnowlabs.nlp.DocumentAssembler.<init>(DocumentAssembler.scala:13)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

## Steps to Reproduce

1.
2.
3.
4.

## Context

Use SparkNLP 3.0.3 with pyspark 2.4.4

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.0.3
* Apache NLP version `spark.version`:
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version: Ubuntu trusty
* Link to your project (if any):

**Comment by wolliq** [comment]
Hi @drbonis ,

I reproduced the error you described using the following configuration:

- pyspark 2.4.4
- spark-nlp 3.0.3

This happens because Spark 2.4.x binaries are compiled using Scala 2.11.x.

If we downgrade pyspark 2.4.2, the only binary distribution compiled in Scala 2.12.x the error disappears.

Could you please retest downgrading PySpark 2.4.2 ?

Thank you

**Comment by maziyarpanahi** [comment]
I didn't see the pyspark 2.4.x and spark-nlp 3.x. 
In this case, this line must be changed:

spark = sparknlp.start()

To

spark = sparknlp.start(spark24=True)

Because the spark-nlp 3.x comes by default for pyspark 3.x, for pyspark 2.4.x must have that param.

@wolliq so the error is related to incompatible pyspark/spark-nlp, there is no model and this is a transformer so we don't see the usual errors in this situation?

**Comment by maziyarpanahi** [comment]
Ok I was wrong,

java.lang.NoSuchMethodError: org.apache.spark.ml.util.MLWritable.$init$(Lorg/apache/spark/ml/util/MLWritable;)V

This means exactly what I said. You need that param in the sparknlp.start(spark24=True) and pyspark 2.4.4 should be fine. 

https://github.com/JohnSnowLabs/spark-nlp/discussions/2562
