### ISSUE TITLE
Specify application.conf location using Pyspark in S3 Cluster with no Hadoop configuration

### ISSUE THREAD

**Issue by katalinwesthoff** [JohnSnowLabs/spark-nlp#2909]
## Description
I am using Pyspark and want to define the tmp storage location to be in S3. 

## Expected Behavior
According to the README I should to the following:

```
import com.johnsnowlabs.util.ConfigLoader
ConfigLoader.setConfigPath("/somewhere/to/put/application.conf")
```
and add the desired path to the storage location. 

## Current Behavior
I cannot import com.johnsnowlabs.util.ConfigLoader. It tells me

```
An error was encountered:
No module named 'com'
```

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.0.3
* Apache NLP version `spark.version`: 2.4.3
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.): downloaded package (spark-nlp/python/sparknlp/) from git and installed manually (installation on AWS Glue dev endpoint)
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
That is not how you override `application.conf` file, you don't have access to ConfigLoader, it's a private and internal class.

Here is an example that you can adapt to your situation whether you are local or in a cluster:


```
spark-submit --files "$LOCAL_PATH/application.conf --conf spark.driver.extraJavaOptions="-Dconfig.file=file:application.conf" --conf spark.executor.extraJavaOptions="-Dconfig.file=file:application.conf" 
```

```

**Comment by maziyarpanahi** [comment]
Doesn't matter where you are, however you are using the Spark, you need a SparkSession. Those confs need to be set when you are creating a SparkSession. Whether manually like:

```python
spark = SparkSession.builder \
    .appName("Spark NLP")\
    .master("local[4]")\
    .config("spark.driver.memory","16G")\
    .config("spark.driver.maxResultSize", "0") \    
    .config("spark.kryoserializer.buffer.max", "2000M")\
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.12:3.0.3")\
    .getOrCreate()
```

Or via command line while using pyspark or spark-submit, or in Zeppelin interpreter, etc. You need to know how you should set Spark conf for SparkSession in your environment which in your case is `AWS Glue`. Looking through the docs for Glue you should be able to see where and how you can set Spark conf. (application.conf needs to be accessible via the cluster, so it should be on a distributed file system)

**Comment by katalinwesthoff** [comment]
Yes, I know where to do this in AWS Glue - but the questions is how can I "tell" sparknlp to use this new defined application.conf, or check which path its currently using?

**Comment by maziyarpanahi** [comment]
Your new `application.conf` will override the default one via:

```
--files "$LOCAL_PATH/application.conf --conf spark.driver.extraJavaOptions="-Dconfig.file=file:application.conf" --conf spark.executor.extraJavaOptions="-Dconfig.file=file:application.conf" 
```

Please try it.
