### ISSUE TITLE
Issues of integration with Zeppelin on local environment

### ISSUE THREAD

**Issue by lisaslyis** [JohnSnowLabs/spark-nlp#293]
The library is not usable in local Zeppelin 0.8.0 + Spark 2.3.1 environment when the instruction is followed.
Some of the issues might need to be fixed on Zeppelin side.

## Description
1. Spark-nlp python API has issues when the maven artifact is configured in Zeppelin web interface
    1. commons-codec 1.3 seems to have a version conflict issue in Zeppelin pyspark interpreter
![image](https://user-images.githubusercontent.com/7444407/47472338-12de1280-d85a-11e8-98a8-7cef805c5166.png)
    2. The pythonpath needs to be added explicitly for python wrappers (In addition to the real python wrapper files)

2. SPARK_SUBMIT_OPTIONS doesn't seem to work with spark-nlp artifact when it was set in zeppelin-env.sh
    1. Zeppelin 0.8.0 seems to have an issue with SPARK_SUBMIT_OPTIONS dependencies regarding ivy server/cache when it's run as yarn-client with other default settings. It looks like Zeppelin client has its own way of runtime library resolution.
![image](https://user-images.githubusercontent.com/7444407/47472314-fb068e80-d859-11e8-82cc-96a4dab9aae4.png)

## Reproducing steps
1.
    1. Configure `com.johnsnowlabs.nlp:spark-nlp_2.11:1.7.2` in Zeppelin spark interpreter setting on web UI
    2. Download python wrapper files and configure spark's pythonpath to refer to them
    3. Run python spark-nlp API on Zeppelin
2.
    1. put `export SPARK_SUBMIT_OPTIONS="--packages JohnSnowLabs:spark-nlp:1.7.2` in zeppelin-env.sh 
    2. Run scala spark-nlp API on Zeppelin

## Temporary workaround
1. Download and pass a fat-jar file directly as a dependency and configure pythonpath for it
2. Download a jar from remote repo (spark-repo: jar, maven-repo: jar <+ python wrapper from the other place>) using Zeppelin or Spark configuration and set pythonpath for it.

## Your Environment
* Spark-nlp 1.7.2
* Zeppelin 0.8.0
* Spark 2.3.1
* Yarn-client mode on local cluster

**Comment by saifjsl** [comment]
Thanks, we should review the current installation instructions and see what's going on. A user on Slack reported the same issue with the apache.commons.codec path.

**Comment by lisaslyis** [comment]
The dependency is as follows
 aws-java-sdk 1.7 -> commons-codec 1.3

I guess using a different version of aws-java-sdk or enforcing commons-codec >=1.4 in build-process can be a solution if it doesn't create any compatibility issue.

**Comment by saifjsl** [comment]
Yes I am investigating this. I could reproduce the issue. So far the only thing I learned is that SPARK_SUBMIT_OPTIONS is not reliable in anyway anymore. If I could suggest a package for zeppelin that upgrades commons-codec that should be enough for now, but still testing.

**Comment by saifjsl** [comment]
https://github.com/JohnSnowLabs/spark-nlp/pull/296

**Comment by maziyarpanahi** [comment]
I’m closing this as the latest releases after2.x are compatible with latest Apache Spark and latest Apache Zeppelin 0.8.2.
