### ISSUE TITLE
How  to use spark-nlp 3.1.0 with scala?

### ISSUE THREAD

**Issue by mengban** [JohnSnowLabs/spark-nlp#2971]
when I install the library dependencies  in build.sbt with 
`libraryDependencies += "com.johnsnowlabs.nlp" %% "spark-nlp" %"3.1.0"`
error happened.
I found the latest version spark-nlp was 3.0.3 in https://mvnrepository.com/artifact/com.johnsnowlabs.nlp/spark-nlp
SO How  can I  use spark-nlp 3.1.0  with scala?

**Comment by maziyarpanahi** [comment]
Hi,

That version hasn't been released yet: https://github.com/JohnSnowLabs/spark-nlp/pull/2907

All the available releases are in the release notes: https://github.com/JohnSnowLabs/spark-nlp/releases

**Comment by mengban** [comment]
> Hi,
> 
> That version hasn't been released yet: #2907
> 
> All the available releases are in the release notes: https://github.com/JohnSnowLabs/spark-nlp/releases
Thanks for your reply.
However, I found there are lots of pre-trained models with spark-nlp 3.1.0  have been released in
https://nlp.johnsnowlabs.com/models.

**Comment by mengban** [comment]
> Hi,
> 
> That version hasn't been released yet: #2907
> 
> All the available releases are in the release notes: https://github.com/JohnSnowLabs/spark-nlp/releases

Thanks for your reply.
However, I found there are lots of pre-trained models with spark-nlp 3.1.0 have been released in
https://nlp.johnsnowlabs.com/models.
Is there any plan for the release of the version 3.1.0?
