### ISSUE TITLE
Loading NER Model on Windows fails with RocksDBException

### ISSUE THREAD

**Issue by EnricoMi** [JohnSnowLabs/spark-nlp#298]
Loading a pre-trained Crf or DL NER Model on Windows fails with an `org.rocksdb.RocksDBException: Snappy not supported or corrupted Snappy compressed block contents`.

## Description
When loading a pre-trained Crf (ner_fast_en_1.7.0_2_1539896043754) or DL (ner_precise_en_1.7.0_2_1539623388047) NER model on Windows, I get this exception:
```
Caused by: org.rocksdb.RocksDBException: Snappy not supported or corrupted Snappy compressed block contents
at org.rocksdb.RocksDB.get(Native Method)
at org.rocksdb.RocksDB.get(RocksDB.java:788)
at com.johnsnowlabs.nlp.embeddings.WordEmbeddingsRetriever.result$lzycompute$1(WordEmbeddingsRetriever.scala:21)
...
```

## Expected Behavior
The models should load without an exception.

## Current Behavior
An exception is thrown.

## Possible Solution
The model might be written to disk with Linux and this is not binary compatible to Windows.

## Steps to Reproduce
```
import spark.implicits._

import com.johnsnowlabs.nlp.annotator.{NerCrfModel, NerDLModel, SentenceDetector}
import org.apache.spark.ml.{Pipeline, PipelineModel}

val data = Seq("Here is some text.").toDF("text")

val basicPipeline = PipelineModel.read.load("/home/user/cache_pretrained/pipeline_basic_en_1.6.1_2_1533856444797")
val sentence = new SentenceDetector().setOutputCol("sentence")
val ner = NerCrfModel.read.load("/home/user/cache_pretrained/ner_fast_en_1.7.0_2_1539896043754")
//val ner = NerDLModel.read.load("/home/user/cache_pretrained/ner_precise_en_1.7.0_2_1539623388047")
val pipeline = new Pipeline().setStages(Array(basicPipeline, sentence, ner))
pipeline.fit(Seq.empty[String].toDF("text")).transform(data).show(false)
```

## Context
I simply want to load any pre-trained NER model on Windows and use it for NER tagging.

## Your Environment
* Spark: 2.3.0
* Spark-NLP: 1.7.2
* NER Model: Crf (ner_fast_en_1.7.0_2_1539896043754) or DL (ner_precise_en_1.7.0_2_1539623388047)
* OS: Windows 10

**Comment by EnricoMi** [comment]
The very same Spark code on Windows is able to write parquet files with Snappy compression, so some Snappy implementation seems to be available.

However, providing models trained on Windows would be an easy fix to this.

**Comment by amandeep1991** [comment]
Is it fixed, can I download models trained on windows now? If yes, please share some references for the same.

**Comment by maziyarpanahi** [comment]
Yes, this happens automatically in latest versions (2.0.9). But in case for offline downloading:
https://nlp.johnsnowlabs.com/docs/en/models

The ones with _contrib are for unix-based OS only.
