### ISSUE TITLE
Using a NER model throws NoSuchElementException / SparkException

### ISSUE THREAD

**Issue by EnricoMi** [JohnSnowLabs/spark-nlp#299]
Using a pre-trained Crf or DL NER Model with a DataFrame having multiple partitions fails with a `NoSuchElementException` and `SparkException: Failed to get broadcast_6_piece0 of broadcast_6`.

## Description
When tagging a DataFrame using a pre-trained Crf (ner_fast_en_1.7.0_2_1539896043754) or DL (ner_precise_en_1.7.0_2_1539623388047) NER model in cluster mode, I get this exception:
```
java.util.NoSuchElementException: 60
...
Caused By: `org.apache.spark.SparkException: Failed to get broadcast_6_piece0 of broadcast_6
...
```
This works perfectly fine in local mode or in cluster mode with a DataFrame having a single partition.

## Expected Behavior
The DataFrame should be tagged without an exception.

## Current Behavior
An exception is thrown.

## Steps to Reproduce
```
import spark.implicits._

import com.johnsnowlabs.nlp.annotator.{NerCrfModel, NerDLModel, SentenceDetector}
import org.apache.spark.ml.{Pipeline, PipelineModel}

val data = Seq("Here is some text.").toDF("text")

val basicPipeline = PipelineModel.read.load("/home/user/cache_pretrained/pipeline_basic_en_1.6.1_2_1533856444797")
val sentence = new SentenceDetector().setOutputCol("sentence")
val ner = NerCrfModel.read.load("/home/user/cache_pretrained/ner_fast_en_1.7.0_2_1539896043754")
//val ner = NerDLModel.read.load("/home/user/cache_pretrained/ner_precise_en_1.7.0_2_1539623388047")
val pipeline = new Pipeline().setStages(Array(basicPipeline, sentence, ner))
pipeline.fit(Seq.empty[String].toDF("text")).transform(data).show(false)  // this works just fine, even in cluster mode
pipeline.fit(Seq.empty[String].toDF("text")).transform(data.repartition(100)).show(false)  // this fails in cluster mode
```

## Context
I simply want to use any pre-trained NER model for NER tagging.

## Your Environment
* Spark: 2.3.0
* Spark-NLP: 1.7.2
* NER Model: Crf (ner_fast_en_1.7.0_2_1539896043754) or DL (ner_precise_en_1.7.0_2_1539623388047)

**Comment by saifjsl** [comment]
Thank you, I am investigating the issue. Sounds to be introduced in 1.7.x.

**Comment by saifjsl** [comment]
https://github.com/JohnSnowLabs/spark-nlp/pull/303

**Comment by EnricoMi** [comment]
I can confirm that this is fixed for me. Great work, thanks!
