### ISSUE TITLE
Pregenerated downloadable models

### ISSUE THREAD

**Issue by saifjsl** [JohnSnowLabs/spark-nlp#30]
We want to make possible to the user to download pretrained annotators and even entire pipelines, to be ready to process text without a training stage.

**Comment by Bhuvanamitra** [comment]
This is highly required as training the model is time taking and should be avoided as much as possible. I tested NER with PERSON Dataset of my own, which contains 6.4Lakh names and it takes close to 30 seconds to produce result. This can be reduced if pretrained models are present.

**Comment by aleksei-ai** [comment]
Implemented it: https://github.com/JohnSnowLabs/spark-nlp/pull/104
Will be released in 1.5
