### ISSUE TITLE
Implement Java API

### ISSUE THREAD

**Issue by saifjsl** [JohnSnowLabs/spark-nlp#31]
We want to extend Spark NLP support in Java Spark

**Comment by Mahesha999** [comment]
What is status of this? Is Spark NLP fully compatible with Java. There are some Java specific classes available in spark core api such as JavaRDD, JavaSparkContext. So I feel its not 100% compatible. If it is not, has anyone tried using this in Java with some work around?

**Comment by saifjsl** [comment]
Hi, I've seen many people using Spark-NLP on Java. Scala interoperability should work by default with Java Spark. Closing this until further feedback.

**Comment by maziyarpanahi** [comment]
The examples for Java: https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/java/annotation
