### ISSUE TITLE
SPARK_HOME Issue + DeIdentification Fix + Normalizer Improvement

### ISSUE THREAD

**Issue by danilojsl** [JohnSnowLabs/spark-nlp#310]
1. There is an issue whit pip installation when SPARK_HOME variable is setup.
2. There is a fix required in DeIdentification unit tests.
3. There is a pending improvement in Normalizer.

## Description

Installation of spark-nklp with Python package is working in all environments, but when SPARK_HOME is setup, it does not find _sparknlp.jar_

## Expected Behavior

1. When using spark-nlp under pyhton, it should locate _sparknlp.jar_ automatically.
2. Unit tests should not use pretrained models.
3. Normalizer should work as always after the improvement.

## Current Behavior

When SPARK_HOME is setup, spark-nlp is not able to find _sparknlp.jar_, thus a python user requires to set spark session manually.

## Steps to Reproduce

1. Set SPARK_HOME
2. Install spark-nlp through python package (pip)
3. In a python terminal write:
 `from sparknlp.base import *`
`spark_nlp_session = SparkNLP().spark_session`
4. spark-nlp cannot find the jar

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by maziyarpanahi** [comment]
Is this issue resolved? @danilojsl
