### ISSUE TITLE
Data format of setExternalDataset() in NerCrfApproach() 

### ISSUE THREAD

**Issue by lidan1014** [JohnSnowLabs/spark-nlp#317]
Other than CoNLL 2003 IOB based dataset format, does setExternalDataset() support other data format input? If yes, could you provide an example? 

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by saifjsl** [comment]
Hi, aside from CoNLL format (The labels do not have to be IOB, that is completely up to the user) we allow training from the dataset passed to `fit()`.

The parameter `labelCol` should be defined and exist in the provided dataframe.

And this column should be of type Array[Annotation] although this is not yet very well documented. If you can go through a little bit on the code, you'll see that an Annotation is a case class
`Annotation(annotatorType: String, begin: Int, end: Int, result: String, metadata: Map[String, String])`
Into which result must match the label each Annotation refers to, and each of them is a token that matches also the tokens in the Part of Speech columns.

It's a little bit tricky for now.

**Comment by lidan1014** [comment]
Hi Saif,

Thanks for your reply. Could you please add me to slack? I am still having
some difficulties.

Thanks,
Dan

**Comment by sparkuser3** [comment]
Hi Team,

I am new to Spark NLP. Could you please explain in detail with an example as to how we can use training dataset other than conll2003 format. Conll2003 format is cumbersome if we want to use for a domain specific  nlp entity recognition . For example I want to extract entities like account number , phone number , address street , zipcode etc . I have a training data in name,entitytype(label) . But dont know how to use it . This becomes cumbersome when we want to convert it to conll2003 format . Please advise
