### ISSUE TITLE
How can i remove HTML tags from text 

### ISSUE THREAD

**Issue by dharaghodasara** [JohnSnowLabs/spark-nlp#326]
As part of text cleaning/normalization process, i want to remove HTMl tags from text. 
## Description

I am using NLTK library. To remove HTML tags , i am using BeautifulSoup library's HTML parser. 
But now we are moving to Spark for large scale text processing.  

I checked documentation but didn't find any way to remove HTML tags. Can  you help me that?

**Comment by maziyarpanahi** [comment]
I think you should take a look at `Normalizer`. It has `setPatterns` option which allows you to define some regex strings. It will replace them with space.
Or you can use the same regex which removes HTML tags from the text in a simple UDF that can be applied on your DataFrame before it goes to Spark NLP pipeline.
