### ISSUE TITLE
How to get OCR works with Databricks notebook?

### ISSUE THREAD

**Issue by KayShenClarivate** [JohnSnowLabs/spark-nlp#330]
So I am trying to follow this notebook and get it to work on a databricks notebook: https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/ocr-spell/OcrSpellChecking.ipynb ; However, after installing all the packages, I still get stuck by the time I get to

```
{ // for displaying
val regions = data.select("region").collect().map(_.get(0))
regions.foreach{chunk =>
    println("---------------")
    println(chunk)}
}
```

Error message is:

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 4 times, most recent failure: Lost task 0.3 in stage 3.0 (TID 51, 10.195.249.145, executor 4): java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.tess4j.TessAPI
```

Anyone knows why? Much appreciated!

**Comment by saifjsl** [comment]
Hi, welcome.

For help it is better if you join Slack so people can help you. You are probably installing Tesseract incorrectly.

Please close as this is not a specific issue with the library
