### ISSUE TITLE
Verify all embeddings pathing is correct when redefining local dirs

### ISSUE THREAD

**Issue by saifjsl** [JohnSnowLabs/spark-nlp#337]
## Description

setting configurations like `--conf "spark.local.dir=/home/saif/tmp/"` makes embeddings not work (embeddingsRef not found) properly in local environments. Internal config readings should be synchronized.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by maziyarpanahi** [comment]
@saifjsl This has been resolved, right?
