### ISSUE TITLE
SparkR Support

### ISSUE THREAD

**Issue by saif-ellafi** [JohnSnowLabs/spark-nlp#34]
Implement SparkR support for NLP annotators library.

**Comment by yiruol** [comment]
Which version will contain this feature?

**Comment by yiruol** [comment]
Which version will contain this feature? @aleksei-ai

**Comment by randomgambit** [comment]
Also interested in that. What about Sparklyr? https://github.com/rstudio/sparklyr

**Comment by kevinykuo** [comment]
@randomgambit sparklyr support will be coming later this year, tracking at https://github.com/rstudio/sparklyr/issues/1286

**Comment by maziyarpanahi** [comment]
There is amazing support for Spark NLP on R, so I am closing this feature request in favour of: https://github.com/r-spark/sparknlp 🚀
