### ISSUE TITLE
Spark-NLP Annotators Incompatible with Custom Transformers

### ISSUE THREAD

**Issue by johnmccain** [JohnSnowLabs/spark-nlp#340]
## Description
Using a custom Spark transformer before a Spark-NLP annotator causes an exception.  This holds true when the custom transformer does nothing.

**[Notebook with steps to replicate](https://gist.github.com/johnmccain/2a572be76a0ef3dce69416b2516614f7)**

Exception can be seen in cell 16.  A similar exception occurs when the custom transformer is placed before the Normalizer, so this isn't specific to the NorvigSweetingApproach.  Moving the custom transformer to after Spark-NLP Annotators (between NorvigSweetingApproach and Finisher in my example) works just fine.

The implementation for the custom transformer is in cell 9.

In cell 12, you can see that partial pipelines (leading up to the NorvigSweetingApproach stage) produce identical output with or without the custom transformer stage.  The `token` column which the NorvigSweetingApproach operates on is unchanged by the custom transformer.

The exception originates from [com.johnsnowlabs.nlp.AnnotatorModel.scala:52](https://github.com/JohnSnowLabs/spark-nlp/blob/1.6.3/src/main/scala/com/johnsnowlabs/nlp/AnnotatorModel.scala#L52) when the input fails the validate method in [com.johnsnowlabs.nlp.HasInputAnnotationCols:24](https://github.com/JohnSnowLabs/spark-nlp/blob/1.6.3/src/main/scala/com/johnsnowlabs/nlp/HasInputAnnotationCols.scala#L25).

What confuses me is why a pipeline stage that has no apparent effect can cause the pipeline to break.

Thanks in advance for any help!

## Exception Message:

```

'requirement failed: Wrong or missing inputCols annotators in SPELL_43ee494b563b. Received inputCols: token. Make sure such columns have following annotator types: token'
Traceback (most recent call last):
  File "/data11/hadoop/yarn/local/usercache/jmccain/appcache/application_1542049750721_0372/container_e29_1542049750721_0372_01_000001/pyspark.zip/pyspark/ml/base.py", line 173, in transform
    return self._transform(dataset)
  File "/data11/hadoop/yarn/local/usercache/jmccain/appcache/application_1542049750721_0372/container_e29_1542049750721_0372_01_000001/pyspark.zip/pyspark/ml/pipeline.py", line 262, in _transform
    dataset = t.transform(dataset)
  File "/data11/hadoop/yarn/local/usercache/jmccain/appcache/application_1542049750721_0372/container_e29_1542049750721_0372_01_000001/pyspark.zip/pyspark/ml/base.py", line 173, in transform
    return self._transform(dataset)
  File "/data11/hadoop/yarn/local/usercache/jmccain/appcache/application_1542049750721_0372/container_e29_1542049750721_0372_01_000001/pyspark.zip/pyspark/ml/wrapper.py", line 305, in _transform
    return DataFrame(self._java_obj.transform(dataset._jdf), dataset.sql_ctx)
  File "/data11/hadoop/yarn/local/usercache/jmccain/appcache/application_1542049750721_0372/container_e29_1542049750721_0372_01_000001/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 1160, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/data11/hadoop/yarn/local/usercache/jmccain/appcache/application_1542049750721_0372/container_e29_1542049750721_0372_01_000001/pyspark.zip/pyspark/sql/utils.py", line 79, in deco
    raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.IllegalArgumentException: 'requirement failed: Wrong or missing inputCols annotators in SPELL_43ee494b563b. Received inputCols: token. Make sure such columns have following annotator types: token'
```

## Your Environment

* Spark-NLP version: 1.6.3
* Spark version: 2.3.0

**Comment by maziyarpanahi** [comment]
Hi @johnmccain,

I took a look at your code. There seem to be one too many columns named `token`. Can you please rename the columns to unique name such as `token` for Tokenizer, `normal` for Normalizer, `custom` for custome_transformer and see if the error still the same? Also, a `printSchema` in each stage would be good to make sure the schema of all columns is the same.

Sorry, I am not a Python developer so I don't have the right environment set up to do it myself.

Many thanks :)

**Comment by pedrochavessd** [comment]
Hello @johnmccain any success with this? @maziyarpanahi has there been any development towards supporting custom transformers?

**Comment by maziyarpanahi** [comment]
Actually, we have many users who developed a custom Transformer in Spark ML in both Scala and PySpark (so it's possible and not a blocker). The trick is to make sure you respect the Annotation.type with all its metadata. (I think we have had similar questions on Slack if you have a question there are people who can look at your code and help you to achieve this.)

Let me close this and you can continue on Slack (#sparknlp or #development channels), something like this questions: https://spark-nlp.slack.com/archives/CA118BWRM/p1623938358133600
