### ISSUE TITLE
SymmetricDeleteApproach.setCorpus Has Different Behavior In Python vs. Scala

### ISSUE THREAD

**Issue by johnmccain** [JohnSnowLabs/spark-nlp#345]
## Description
The [documentation for the SymmetricDeleteApproach.setCorpus](https://nlp.johnsnowlabs.com/components.html#SymmChecker) method suggests that it can be called with a single String argument.  This is true in Python, but not in Scala.

## Expected Behavior

```
# Python
spell_checker = SymmetricDeleteApproach() \
  .setInputCols(["token"]) \
  .setOutputCol("spell") \
  .setCorpus("./sherlockholmes.txt")
```

should be equivalent to:

```
// Scala
val spellChecker = new SymmetricDeleteApproach()
  .setInputCols(Array("normalized"))
  .setOutputCol("spell")
  .setCorpus("./sherlockholmes.txt")
```

## Current Behavior

The Python version works, while

```
// Scala
val spellChecker = new SymmetricDeleteApproach()
  .setInputCols(Array("normalized"))
  .setOutputCol("spell")
  .setCorpus("./sherlockholmes.txt")
```

fails with the message:

```
<console>:89: error: type mismatch;
 found   : String
 required: com.johnsnowlabs.nlp.util.io.ExternalResource
           .setCorpus(spellingCorpusPath))
```

Passing in a tokenPattern as well works just fine.

```
// Scala
val spellChecker = new SymmetricDeleteApproach()
  .setInputCols(Array("normalized"))
  .setOutputCol("spell")
  .setCorpus("./sherlockholmes.txt", "\\S+")
```

## Possible Solution
There is no default value for tokenPattern in the Scala implementation of SymmetricDeleteApproach

**[SymmetricDeleteApproach.scala](https://github.com/JohnSnowLabs/spark-nlp/blob/master/src/main/scala/com/johnsnowlabs/nlp/annotators/spell/symmetric/SymmetricDeleteApproach.scala#L37)**
```
// Scala
  def setCorpus(path: String,
                tokenPattern: String,
                readAs: ReadAs.Format = ReadAs.LINE_BY_LINE,
                options: Map[String, String] = Map("format" -> "text")): this.type =
    set(corpus, ExternalResource(path, readAs, options ++ Map("tokenPattern" -> tokenPattern)))
```

while there is a default value for tokenPattern in the Python implementation:

**[annotator.py](https://github.com/JohnSnowLabs/spark-nlp/blob/master/python/sparknlp/annotator.py#L796)**
```
# Python
    def setCorpus(self, path, token_pattern="\S+", read_as=ReadAs.LINE_BY_LINE, options={"format": "text"}):
        opts = options.copy()
        if "tokenPattern" not in opts:
            opts["tokenPattern"] = token_pattern
        return self._set(corpus=ExternalResource(path, read_as, opts))
```

It looks like there should be a default value for tokenPattern in the Scala implementation.

## Steps to Reproduce
Import the SymmetricDeleteApproach and try to initialize how the documentation suggests.

[Gist](https://gist.github.com/johnmccain/e01d2e86ae629371daad40d1a29f068d)

## Your Environment

* Version used: Tested in 1.6.3, though current source code on Github indicates this issue exists in the current version of Spark-NLP

**Comment by johnmccain** [comment]
This also appears to affect NorvigSweetingApproach.

**Comment by danilojsl** [comment]
Thanks for reporting it, I created a [PR](https://github.com/JohnSnowLabs/spark-nlp/pull/349) that solves the issue.
