### ISSUE TITLE
application resource missing while running spark submit

### ISSUE THREAD

**Issue by ukamath** [JohnSnowLabs/spark-nlp#35]
1. Latest spark-nlp downloaded
2. Run using Spark 2.2
spark-submit --jars /Users/john/spark-nlp/spark-nlp-snapshot.jar 
Exception in thread "main" java.lang.IllegalArgumentException: Missing application resource.
	at org.apache.spark.launcher.CommandBuilderUtils.checkArgument(CommandBuilderUtils.java:241)

**Comment by showy** [comment]
Hi @ukamath . The spark-submit command actually expects a jar file as a the last argument which holds the compiled code. eg. `spark-submit --jars spark-nlp.jar --class Main app.jar`.

If you want to have the repl environment, you could use spark-shell.

I'm closing this issue as is not specific to the library.
