### ISSUE TITLE
DeepSentenceDetector.read() is missing

### ISSUE THREAD

**Issue by Tshimanga** [JohnSnowLabs/spark-nlp#358]
The DeepSentenceDetector class introduced in @danilojsl 's PR #342 is missing an implementation of `ParamsAndFeaturesReadable[DeepSentenceDetector]` as per @saifjsl .

As such, one can train and persist DL NER Sentence Splitting models/pipelines but cannot then re-load them.

**Comment by danilojsl** [comment]
I created a [PR](https://github.com/JohnSnowLabs/spark-nlp/pull/361) that solves this issue
