### ISSUE TITLE
Implement Coreference Resolution

### ISSUE THREAD

**Issue by ukamath** [JohnSnowLabs/spark-nlp#36]
Adding support in the pipeline for Coreference resolution will be really beneficial
https://nlp.stanford.edu/projects/coref.shtml

**Comment by showy** [comment]
@ukamath Thanks for the recommendation man, we'll definitely add to the task list. Also you are welcome to contribute to library in any way you can. Let us know if you are interested on taking on the task. We'll happy to assist you.

**Comment by ukamath** [comment]
Thanks. I can implement the base components and strategies around Neural, Statistical, etc. and provide an implementation for some and have others plug-in the implementations.

**Comment by gregar** [comment]
Would this include NE Disambiguation as a more general case?

**Comment by ddell003** [comment]
Has conference resolution been implemented for Spark-Nlp?

**Comment by danilojsl** [comment]
Hi @ddell003 I'm nos sure if we have that feature. @maziyarpanahi or @fernandrez do we have this feature on spark-nlp or spark-nlp internal?

**Comment by maziyarpanahi** [comment]
We do not have this feature but it is on the roadmap
