### ISSUE TITLE
Cache embeddings locally to avoid re download

### ISSUE THREAD

**Issue by rohit-nlp** [JohnSnowLabs/spark-nlp#364]
## Description

Currently, the embeddings helper downloads the embeddings everytime it is loaded. This cause a lot of delay as the embeddings file is quite huge in size. Like the pretrained model the embeddings should also be cached locally so that it is not downloaded every time.

**Comment by maziyarpanahi** [comment]
This issue has been resolved.

Thanks @rohit-nlp
