### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by albertoandreottiATgmail** [JohnSnowLabs/spark-nlp#367]
'setIncludeKeys' still mentioned in documentation for Finisher.
![image](https://user-images.githubusercontent.com/4570303/52318011-407e4000-29a1-11e9-9ba2-86a6b5119882.png)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by saifjsl** [comment]
Fixed

90473453d373182919ed717d8502fc7b9169fc20
