### ISSUE TITLE
Research a MOCKing library for making easier unit testing annotations

### ISSUE THREAD

**Issue by saif-ellafi** [JohnSnowLabs/spark-nlp#408]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Tshimanga** [comment]
There seems to be a parallel Scala project for Mockito https://github.com/mockito/mockito-scala

How does that look for your desiderata?
