### ISSUE TITLE
Error occurs when using TrainValidationSplit() on a Spark ML pipeline that includes Spark NLP annotators. 

### ISSUE THREAD

**Issue by C-Youssef** [JohnSnowLabs/spark-nlp#4322]
## Description
When including Spark NLP components in a ML pipline, using TrainValidationSplit() to fine-tune the hyperparameters of the ML model fails.  

I created a Google Colab Notebook to easily reproduce the issue using a basic example:

https://colab.research.google.com/drive/1LwpMhgG59kwV6J3BMr35qJxX8TD5-RsW?usp=sharing

## Stacktrace

Py4JJavaError: An error occurred while calling o3009.evaluate.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 78.0 failed 1 times, most recent failure: Lost task 1.0 in stage 78.0 (TID 145, 8bd90f541597, executor driver): org.apache.spark.SparkException: Failed to execute user defined function(HasSimpleAnnotate$$Lambda$2271/675664388: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>>>)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
...
...
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: feature rules is not set
	at com.johnsnowlabs.nlp.serialization.Feature.$anonfun$getOrDefault$1(Feature.scala:81)
	at scala.Option.getOrElse(Option.scala:189)
	at com.johnsnowlabs.nlp.serialization.Feature.getOrDefault(Feature.scala:81)
...
...
## Possible Solution

Since this is similar to the open issue 1158 that affects Crossvalidator, I am splitting the NLP and ML components into two different pipelines, as suggested by Maziyar. This is working fine for my purpose. However, there are cases when using a single pipeline is useful, such as when there is a need to fine-tune the hyperparameters of both the Spark NLP and Spark ML components. 

## Your Environment
openjdk version "1.8.0_292"
Spark NLP version 3.0.3
Apache Spark version: 3.0.2

**Comment by maziyarpanahi** [comment]
Sorry I was about to update that issue but forgot.
None of the Spark NLP annotators actually compatible with CV in Spark ML. The way they use thread/parallelism is just not compatible with TensorFlow session in Spark NLP.
We debugged it but them realized it's a lot of work so for the moment is not a priority to fix anything that doesn't work. (We might have to create our own CV/paramGrid at the end)

**Comment by kaismh** [comment]
@maziyarpanahi is spark nlp CV on the roadmap or any workarounds to use Spark ML CV
