### ISSUE TITLE
Pretrained SentimentDetector broken in 2.0.3

### ISSUE THREAD

**Issue by CyborgDroid** [JohnSnowLabs/spark-nlp#517]
The sentiment detector is not able to use the pretrained models.

```
sentiment = SentimentDetector.pretrained("sentiment_vivekn", "en")\
          .setInputCols(["lemma", "document"]) \
          .setOutputCol("sentiment")
```
Error:
```
AttributeError: type object 'SentimentDetector' has no attribute 'pretrained'
```

And if I try this I get a different error suggesting this method exists but the model does not:

```
sentiment = ViveknSentimentModel.pretrained("sentiment_vivekn", "en")\
          .setInputCols(["lemma", "document"]) \
          .setOutputCol("sentiment")
```
Error:
```
IllegalArgumentException: 'requirement failed: 
Was not found appropriate resource to download for request: 
ResourceRequest(sentiment_vivekn,Some(en),public/models,2.0.3,2.4.0) with downloader: 
com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader@5333d106'
```

running spark-nlp 2.0.3 on Azure Databricks

**Comment by CyborgDroid** [comment]
Same issue in 2.0.4

**Comment by saifjsl** [comment]
Thank you, will take a look

**Comment by saifjsl** [comment]
There was a bug in the remote model repository metadata, this should be fixed now. Please confirm.

By the way, we don't have a pretrained model for `SentimentDetector`, only for `ViveknSentimentModel`.

**Comment by CyborgDroid** [comment]
Thank you, this works now:

```
sentiment = ViveknSentimentModel.pretrained('sentiment_vivekn', "en")\
          .setInputCols(["lemma", "document"]) \
          .setOutputCol("sentiment")
```

The results are not very good but that is a different problem:

```"Outstanding service and professionalism shown by all staff"```  ---> negative
```"Good overall performance"``` ---> negative

I also found an example for a pretrained sentiment pipeline that is not in the documentation. I would add it and submit a PR but I don't know the model's download link:

https://github.com/JohnSnowLabs/spark-nlp/blob/master/docs/en/models.md#english-pipelines

add:
```
analyze_sentiment_ml
```
Example is here:
https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/annotation/english/dictionary-sentiment/sentiment_rb.ipynb

**Comment by saifjsl** [comment]
Thanks. Yes, this is probably an IMDB dummy model, may not be a good one. Will ask the team to review the accuracy.

You are right, many pipelines are missing from the list. Probably @maziyarpanahi can help with their appropriate links.

**Comment by CyborgDroid** [comment]
Thank you, this works now:

```
sentiment = ViveknSentimentModel.pretrained('sentiment_vivekn', "en")\
          .setInputCols(["lemma", "document"]) \
          .setOutputCol("sentiment")
```

The results are not very good but that is a different problem:

```"Good overall performance"``` ---> negative

I also found an example for a pretrained sentiment pipeline that is not in the documentation. I would add it and submit a PR but I don't know the model's download link:

https://github.com/JohnSnowLabs/spark-nlp/blob/master/docs/en/models.md#english-pipelines

add:
```
analyze_sentiment_ml
```
Example is here:
https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/annotation/english/dictionary-sentiment/sentiment_rb.ipynb

**Comment by maziyarpanahi** [comment]
Thanks for confirming it.
