### ISSUE TITLE
Lemmatizer should use POS and token to generate Lemma, have a default dictionary, and allow addition + overriding

### ISSUE THREAD

**Issue by sujitpal** [JohnSnowLabs/spark-nlp#52]
## Description

This is an enhancement request the Lemmatizer.

## Expected Behavior

1. The current lemmatizer appears to be dictionary based, and the caller needs to supply a mapping of word to lemma. From other dictionary based lemmatizers I have seen, the key is usually (token, pos). This is because certain words need to be lemmatized differently based on what POS it is - for example, stranger as NOUN is lemmatized to stranger, but stranger as ADJ is lemmatized to strange. The Transformer API allows this, I see others support setInputCols(Array[String]) signature, ie, setInputCols(Array("token", "pos")) instead of setInputCols(Array("token")) as it is currently. Only thing to be careful of is that the pos tag style output by the POSTagger must match the style in the Lemma dictionary key.

2. The implementation does not provide a lemma dictionary and requires the caller to supply one. There are good open source lemma dictionaries available thanks to the [FreeLing project](https://github.com/TALP-UPC/FreeLing) for various languages (look under data/{lang}/dictionary/entries), which could be leveraged and provided as part of the spark-nlp download (at least for language=en) so there would be a sensible default for most people. This would make it easier for people to start working with lemmatizers in spark-nlp.

3. Lemmatizer dictionaries are usually incomplete, so an addLemmaDict() call could be provided that allows user-supplied mappings to be added to the dictionary. The setLemmaDict() could still be used to override the default if needed.

## Possible Solution

I haven't provided a solution, since I figure that this is a fairly easy fix for people familiar with the codebase, but if you would prefer a pull request, please let me know and I can work on it.

## Your Environment

* Version used: spark-nlp-2.11-1.2.3

**Comment by showy** [comment]
@sujitpal Thanks for the observations. Effectively the lemma should make use of the POS tag. We'll be looking towards supporting these changes.

**Comment by maziyarpanahi** [comment]
To contribute to this discussion, I use CoNLL-U from Universal Dependencies to train POS tagger models. If you look at the format most of the languages/datasets come with Lemma included. Just one example of how to unify the training for Lemma which needs POS and they all come from the same `test`, `dev`, `train` datasets.

http://universaldependencies.org/format.html

**Comment by ArnaudFnr** [comment]
Hi, do you any update on this issue please ?
Thank you in advance.

**Comment by maziyarpanahi** [comment]
It’s not really an issue more of an enhancement or a feature request. 

In case of POS, I don’t think we will be implementing this feature for a while.
We also support 4 languages now and all of them come with pre-trained lemmatizer models so you don’t need to deal with any dictionaries.

**Comment by ArnaudFnr** [comment]
Ok thanks for your answer, I will use the pretrained model.
Nice work by the way :slightly_smiling_face:
