### ISSUE TITLE
Scala code on Python code tabs on Project's website.

### ISSUE THREAD

**Issue by clayms** [JohnSnowLabs/spark-nlp#53]
Much of the "Python" code on the components.html page is a strange mixture of Scala and Python code.

**Comment by saifjsl** [comment]
Hey @clayms can you help pinpoint one example of a strange mixture? thank you!

**Comment by clayms** [comment]
Hi @saifjsl   on the (http://nlp.johnsnowlabs.com/components.html)[components] site the following pyspark annotators still has the `val` and `new` scala code there: 

stemmer: Looks like you just fixed it :-)

SentenceDetector, POSTagger, and Finisher still need fixing.  I think that is about it.

**Comment by saifjsl** [comment]
Very much appreciated @clayms. Feel free to let us know of any other misleading information.
