### ISSUE TITLE
spark-nlp (2.0.8) 

### ISSUE THREAD

**Issue by nehadave78** [JohnSnowLabs/spark-nlp#538]
@maziyarpanahi  @saifjsl 
**getting following error : Trying PertainedPipeline with scala:**
scala> val pipeline = PretrainedPipeline("pos_anc", language="en")
java.lang.NoClassDefFoundError: Could not initialize class com.johnsnowlabs.nlp.pretrained.ResourceDownloader$
  at com.johnsnowlabs.nlp.pretrained.PretrainedPipeline$.apply$default$3(PretrainedPipeline.scala:10)
  ... 51 elided

**Comment by maziyarpanahi** [comment]
Hi @nehadave78 

It's not `language` but `lang` to be unified with Python APIs as well. Also, for `en` you can just not mention `lang` all together since the default is `en`.

```scala
val pipeline = PretrainedPipeline("pos_anc", lang="en")
```
