### ISSUE TITLE
bert_multi_cased metadata broken

### ISSUE THREAD

**Issue by CyborgDroid** [JohnSnowLabs/spark-nlp#540]
```python
word_embeddings = BertEmbeddings.pretrained('bert_multi_cased', 'en')\
    .setInputCols(["document"])\
    .setOutputCol('bert')
```
Error:
```
IllegalArgumentException: 'requirement failed: 
Was not found appropriate resource to download for request: 
ResourceRequest(bert_multi_cased,Some(en),public/models,2.0.5,2.4.0) with downloader: 
com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader@1002942d'
```

**Comment by maziyarpanahi** [comment]
HI @CyborgDroid,
This is my bad, I was going to add a Multi-language section in our model as the `bert_multi_cased` and even GloVe embeddings are not really `English`.

If you look at the link of each model you can see the right language inside its name:
https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/models/bert_multi_cased_xx_2.0.3_2.4_1557923470812.zip

The right language is: 
```python 
word_embeddings = BertEmbeddings.pretrained('bert_multi_cased', 'xx')\
    .setInputCols(["document"])\
    .setOutputCol('bert')
```

I have fixed the doc as well:
https://nlp.johnsnowlabs.com/docs/en/models#multi-language

**Comment by CyborgDroid** [comment]
Thank you Maziyar, so multi refers to language (multi lingual), and it is also case-sensitive? In other words right now we have a case-insensitive english-only model (bert_uncased) and a case sensitive multi-lingual model (bert_multi_cased)?

**Comment by CyborgDroid** [comment]
Thank you. @maziyarpanahi !
