### ISSUE TITLE
Pretrained match_pattern and match_datetime not described in the docs

### ISSUE THREAD

**Issue by alinapetukhova** [JohnSnowLabs/spark-nlp#556]
## Description

Pretrained models `match_pattern`, `match_datetime` and `ContextSpellCheckerModel()` presented in the spark-nlp-workshop, but not described in the spark-nlp docs

[https://nlp.johnsnowlabs.com/docs/en/pipelines](url)

`/annotation/english/match-datetime-pipeline/Pretrained-MatchDateTime-Pipeline.ipynb`
`/annotation/english/match-pattern-pipeline/Pretrained-MatchPattern-Pipeline.ipynb`
`/annotation/english/spellchecking/ContextSpellChecking.ipynb`

## Your Environment

* Spark-NLP version: 2.0.4
* Apache Spark version: 2.4.0
* Operating System and version: Ubuntu 18.04 and Docker
* Deployment (Docker, Jupyter, Scala, pip, conda, etc.): Docker + Jupyter

**Comment by maziyarpanahi** [comment]
Hi @alinapetukhova,

Thanks for reminding me that hose pipelines are missing from the docs. I will add them and the rest of the pipelines.

We are also adding a feature where users can print the name of existing pipelines/models names, language, and versions right from their code.

**Comment by maziyarpanahi** [comment]
It's been updated. https://nlp.johnsnowlabs.com/docs/en/pipelines
