### ISSUE TITLE
Documentation for WordSegmenter is missing from the documentation web page

### ISSUE THREAD

**Issue by dkincaid** [JohnSnowLabs/spark-nlp#5674]
https://nlp.johnsnowlabs.com/docs/en/annotators

The WordSegmenter annotator is listed in the table, but there is no documentation for it.

**Comment by maziyarpanahi** [comment]
Thanks @dkincaid for reporting this. We are updating both Scaladoc and docs on the Website with end-to-end examples and will add the missing items.

Hi @hatrungduc 
I know you are in the middle of updating Scaladoc and then the `annotators` page. Just in case, in summary, the followings are missing:
- RegexTokenizer
- WordSegmenter
- DistilBertEmbeddings
- RoBertaEmbeddings
- XlmRoBertaEmbeddings

I think adding these with your complete examples would make the docs much more useful 😊  - many thanks

**Comment by C-K-Loan** [comment]
Hi @hatrungduc 
I would like to extend @maziyarpanahi list,  listed, the `T5` model is not documented on the annotator page yet as well.

Thanks

**Comment by hatrungduc** [comment]
Thanks a lot @dkincaid, @maziyarpanahi, @C-K-Loan for the useful information. I'm on it 💪
