### ISSUE TITLE
DateMatcher() : Date Identification Issues 

### ISSUE THREAD

**Issue by Rachana-Baldania** [JohnSnowLabs/spark-nlp#569]
Hello,

I am using Johnsnowlabs Spark NLP for implementing question answering system and we are unable to detect dates correctly while using datematcher() function:

Two consecutive date formats in one string then cannot detect two dates
For example, "who sold the most beer in 1/02/2014 and 1/05/2016"
Johnsnowlabs NLP DateMatcher: [2014/01/02]

Getting a wrong result when I am trying to extract data
For example, "sold the most cake during April 2015 5:30 a.m"
Johnsnowlabs NLP DateMatcher: [2015/04/05]

I want to identify dates only not amount
For example, "items which have above 23372.8 $ sales value"
Johnsnowlabs NLP DateMatcher: [2017/12/08]

When date and value are in one string should be identified date and value separately and correctly
For example, "I need to know how many sales of less than 8,000 were made in March of 2015"
Johnsnowlabs NLP DateMatcher: [2015/03/08]

So, Can you please enhance/solve these bugs of DateMatcher() as soon as possible? please share your suggestions.

Thank you.
 @Rachana-Baldania

**Comment by Rachana-Baldania** [comment]
Hello,

I am using Johnsnowlabs Spark NLP for implementing question answering system and we are unable to detect dates correctly while using datematcher() function:

Two consecutive date formats in one string then cannot detect two dates
For example, "who sold the most beer in 1/02/2014 and 1/05/2016"
Johnsnowlabs NLP DateMatcher: [2014/01/02]

Getting a wrong result when i am trying to extract date
For example, "sold the most cake during April 2015 5:30 a.m"
Johnsnowlabs NLP DateMatcher: [2015/04/05]

I want to identify dates only not amount
For example, "items which have above 23372.8 $ sales value"
Johnsnowlabs NLP DateMatcher: [2017/12/08]

When date and value are in one string should be identified date and value separately and correctly
For example, "I need to know how many sales of less than 8,000 were made in March of 2015"
Johnsnowlabs NLP DateMatcher: [2015/03/08]

So, Can you please enhance/solve these bugs of DateMatcher() as soon as possible? please share your suggestions.

Thank you.

**Comment by maziyarpanahi** [comment]
I see two issues:
1. Only the first matched date is being extracted
2. Values are ignored or mistaken as dates

Am I right? By the way, how do you extract the values like `8,000`? I don't think DateMather is the annotator for that. Maybe RegexTokenizer?

**Comment by Rachana-Baldania** [comment]
Yes both two points are correct.

DateMatcher not showing POS for numbers for ex. , any date or value. So
some times 8,000 value is ignored by Datematcher or sometimes its merged
with date output for ex. what are the sales which is greater than 8000 in
march,15.

I dont know there is problem with regex or annotator but i think values
should be treated differently from date.

Thank you.

*Regards,*
*Rachana Baldania.*

**Comment by maziyarpanahi** [comment]
There is a new annotator called `MultiDateMatcher` that allows the extraction of multiple dates in a document and sentence. The behavior is the same as `DateMatcher` so it can be replaced easily with `MultiDateMatcher` in the pipeline.
