### ISSUE TITLE
Running the example hangs on "Download done! Loading the resource."

### ISSUE THREAD

**Issue by foopub** [JohnSnowLabs/spark-nlp#5699]
## Description

Following the instructions almost verbatim, with the only exception being that numpy doesn't get pulled as a dependency (why doesn't it?), so I have to `pip install numpy` before launching python console. Everything else is copy/pasted as is. Pipeline doesn't load, yet no errors are thrown either.

## Expected Behavior

Pipeline loads.

## Current Behavior

```
>>> pipeline = PretrainedPipeline('explain_document_dl', lang='en')
explain_document_dl download started this may take some time.
Approx size to download 169.3 MB
[ | ]explain_document_dl download started this may take some time.
Approximate size to download 169.3 MB
Download done! Loading the resource.
[ / ]
```
Stuck like this for 30+ minutes.

I tried setting log level to DEBUG, but there's simply too much output for me to make out what the problem might be. I don't know how to log to a file, but if you let me know, I can try that and upload it.

## Steps to Reproduce

```
$ conda create -n sparknlp python=3.7 -y
$ conda activate sparknlp
$ pip install spark-nlp==3.1.0 pyspark==3.1.1
$ pip install numpy 
$ python

from sparknlp.base import *
from sparknlp.annotator import *
from sparknlp.pretrained import PretrainedPipeline
import sparknlp
spark = sparknlp.start()
pipeline = PretrainedPipeline('explain_document_dl', lang='en')
```

## Your Environment

* Spark NLP version `sparknlp.version()`:
 '3.1.0'
* Apache NLP version `spark.version`:
'3.1.1'
* Java version `java -version`:
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b02)
OpenJDK 64-Bit Server VM (build 25.272-b02, mixed mode)
* Setup and installation (Pypi, Conda, Maven, etc.):
conda --version
conda 4.10.1
pip --version
pip 21.1.2
* Operating System and version:
Void Linux 5.12.10_1 x86_64 glibc, up to date
* Link to your project (if any):
n/a

**Comment by maziyarpanahi** [comment]
Hi,

The `numpy` is a dependency required by pyspark, not spark-nlp. Sometimes `pyspark` doesn't install it or check that it exists so you can report that to Apache Spark directly. 

Models should be downloaded pretty quickly considering they are hosted on S3. So anything above a few minutes means there is a problem. 

- I can think of a very slow Internet connection
- Slow connection to S3
- You can download the [models/pipelines](https://nlp.johnsnowlabs.com/models) directly and [load them](https://github.com/JohnSnowLabs/spark-nlp#offline)
- I would check inside `~/cache_pretrained` that is where it downloads it, extracts it and tries to load it from.
- You can check and see if there is any leftovers, corrupted files,
- You can check that directory permission/space left / etc.
