### ISSUE TITLE
Unable to download pretrained models of dependency parser

### ISSUE THREAD

**Issue by tushartilwankar** [JohnSnowLabs/spark-nlp#573]
Getting an access denied error while downloading DependencyParser and TypedDependencyParser pretrained models.

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>xxx</RequestId>
<HostId>
xxx
</HostId>
</Error>`

**Comment by tushartilwankar** [comment]
Is anyone else facing this issue?

**Comment by maziyarpanahi** [comment]
Are you using `pretrained()` function or manually downloading it from our models documentation?

**Comment by tushartilwankar** [comment]
I am downloading models from documentation.

**Comment by maziyarpanahi** [comment]
I have just updated the documentation with correct URLs. I have tested them and they will be available in few minutes after GitHub pages finish compiling.
