### ISSUE TITLE
Basque lemmatizer gives empty string as result

### ISSUE THREAD

**Issue by aitorme** [JohnSnowLabs/spark-nlp#5733]
I am trying to run the lemmatizer for Basque following the steps on the Basque lemmatizer site you have and I get an empty output when parsing a single word or a sentence. These are the steps I am running:

```import pyspark
import sys

from pyspark.sql import SparkSession
from pyspark.ml import PipelineModel

import sparknlp
from sparknlp.annotator import *
from sparknlp.common import *
from sparknlp.base import *
from sparknlp.pretrained import ResourceDownloader

spark = sparknlp.start()

lemmatizer = LemmatizerModel.pretrained("lemma","eu").setInputCols(["token"]).setOutputCol("lemma")

nlp_pipeline = Pipeline(stages=[lemmatizer])
light_pipeline = LightPipeline(nlp_pipeline.fit(spark.createDataFrame([['']]).toDF("text")))
results = light_pipeline.fullAnnotate("etxeko")
results
[{'lemma': []}]

```

* Spark NLP version 3.1.1
* Apache NLP version 3.1.1
I'm running this on a jupyter notebook inside a container from the following Docker image:
https://hub.docker.com/r/jupyter/pyspark-notebook

**Comment by maziyarpanahi** [comment]
Hi,

I don't see the rest of the stages required for that annotator in your pipeline. As you can see, the inputCols for Lemmatizer is `token`, so you need a Tokenizer, then before that, you need either DocumentAssembler and/or SentenceDetector if you want sentence detection.

In the model's card to not make the page long, we just put `...` before the Lemmatizer. But there are codes behind and you can see them in `Open in Colab` (please have a look): https://nlp.johnsnowlabs.com/2020/07/29/lemma_eu.html


Example: 

```python
from pyspark.ml import Pipeline, PipelineModel

import sparknlp
from sparknlp.annotator import *
from sparknlp.base import *

spark = sparknlp.start()

document_assembler = DocumentAssembler() \
    .setInputCol("text")

sentence_detector = SentenceDetector() \
    .setInputCols(["document"]) \
    .setOutputCol("sentence")

tokenizer = Tokenizer() \
    .setInputCols(["sentence"]) \
    .setOutputCol("token")

lemmatizer = LemmatizerModel.pretrained("lemma","eu").setInputCols(["token"]).setOutputCol("lemma")

nlp_pipeline = Pipeline(stages=[document_assembler, sentence_detector, tokenizer, lemmatizer])
light_pipeline = LightPipeline(nlp_pipeline.fit(spark.createDataFrame([['']]).toDF("text")))
results = light_pipeline.fullAnnotate("etxeko")
results

# [{'document': [Annotation(document, 0, 5, etxeko, {})], 'sentence': [Annotation(document, 0, 5, etxeko, {'sentence': '0'})], 'token': [Annotation(token, 0, 5, etxeko, {'sentence': '0'})], 'lemma': [Annotation(token, 0, 5, etxe, {'sentence': '0'})]}]


results = light_pipeline.annotate("etxeko")
results

# {'document': ['etxeko'], 'sentence': ['etxeko'], 'token': ['etxeko'], 'lemma': ['etxe']}
```

I am not familiar with `Basque` language but apparently, the lemmatized of `etxeko` is `etxe` in our model

**Comment by aitorme** [comment]
@maziyarpanahi thank you for the quick reply. With your full code it works, but some highly common Basque words are not tokenized at all, e.g.
```
[{'document': [Annotation(document, 0, 39, batzutan otsoa eta usoa katuarekin daude, {})],
  'sentence': [Annotation(document, 0, 39, batzutan otsoa eta usoa katuarekin daude, {'sentence': '0'})],
  'token': [Annotation(token, 0, 7, batzutan, {'sentence': '0'}),
   Annotation(token, 9, 13, otsoa, {'sentence': '0'}),
   Annotation(token, 15, 17, eta, {'sentence': '0'}),
   Annotation(token, 19, 22, usoa, {'sentence': '0'}),
   Annotation(token, 24, 33, katuarekin, {'sentence': '0'}),
   Annotation(token, 35, 39, daude, {'sentence': '0'})],
  'lemma': [Annotation(token, 0, 7, batzuk, {'sentence': '0'}),
   Annotation(token, 9, 13, otsoa, {'sentence': '0'}),
   Annotation(token, 15, 17, eta, {'sentence': '0'}),
   Annotation(token, 19, 22, usoa, {'sentence': '0'}),
   Annotation(token, 24, 33, katuarekin, {'sentence': '0'}),
   Annotation(token, 35, 39, egon, {'sentence': '0'})]}]
```
here the words wolf, dove and cat are not tokenized at all, since they should be `otso`, `uso` and `katu`. Is there a way to see how the tokenizer is implemented? What rules does it follow?

**Comment by maziyarpanahi** [comment]
You are welcome. The documentation for the Tokenizer:

- https://nlp.johnsnowlabs.com/docs/en/annotators#tokenizer
- APIs: https://nlp.johnsnowlabs.com/api/com/johnsnowlabs/nlp/annotators/Tokenizer
- Source code: https://github.com/JohnSnowLabs/spark-nlp/blob/master/src/main/scala/com/johnsnowlabs/nlp/annotators/Tokenizer.scala

You can also use RegexTokenizer with simple regex rule(s) to tune your tokenization

**Comment by aitorme** [comment]
thank you, I'm also having a look at the lemmatizer docs. is everything implemented in Scala though? How does your lemmatizer learn the rules for more agglutinative languages?
