### ISSUE TITLE
Issues loading NorvigSweetingModel pretrained model since 3.1.1

### ISSUE THREAD

**Issue by DevinTDHa** [JohnSnowLabs/spark-nlp#5738]
## Description

The parameter `wordCount` can not be loaded from the pretrained model since commit 7457c0b307aaa2932dbb4f1b4ca537feb2357a22. Checking out commits prior to that one is fine.

Training a new instance of the model with `NorvigSweetingApproach` works fine.

`"explain_document_dl"` pretrained Pipeline is also affected, since it contains the pretrained `NorvigSweetingModel`

### Example Pipe

<details>
  <summary>Click to expand</summary>

```scala
    import com.johnsnowlabs.nlp.annotators.Tokenizer
    import com.johnsnowlabs.nlp.annotators.spell.norvig.NorvigSweetingModel
    import com.johnsnowlabs.nlp.base.DocumentAssembler
    import org.apache.spark.ml.Pipeline
    import spark.implicits._

    println(spark.version)
    val documentAssembler = new DocumentAssembler()
      .setInputCol("text")
      .setOutputCol("document")

    val tokenizer = new Tokenizer()
      .setInputCols("document")
      .setOutputCol("token")

    val spellChecker: NorvigSweetingModel = NorvigSweetingModel.pretrained()
      .setInputCols("token")
      .setOutputCol("spell")

    val pipeline = new Pipeline().setStages(Array(
      documentAssembler,
      tokenizer,
      spellChecker
    ))

    val data = Seq("spmetimes i wrrite wordz erong.").toDF("text")
    val result = pipeline.fit(data).transform(data)
    result.select("spell.result").show(false)
```

</details>

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.1.1
* Apache NLP version `spark.version`: 3.0.2
* Java version `java -version`: 1.8
* Setup and installation (Pypi, Conda, Maven, etc.): Maven

**Comment by maziyarpanahi** [comment]
Hi @diatrambitas 
Could you please assign a member to train a new `NorvigSweetingApproach` and after redoing the `explain_document_dl` pipeline?

**Comment by maziyarpanahi** [comment]
@DevinTDHa Do we know what caused this in that specific commit which resulted in this error? (is it the same on Spark 2.3, 2.4, 3.0.x, and 3.1.x or it only happens on some of them)

**Comment by DevinTDHa** [comment]
Hi @maziyarpanahi,

I tried to look into it but 'm not entirely sure what caused it. But in that commit the version of the whole package is changed from `3.1.0` to `3.1.1`.

**Comment by maziyarpanahi** [comment]
@DevinTDHa Interesting, it would be great if you can check to see with spark-nlp-spark24==3.1.1 and pyspark==2.7.4 the issue still there. Want to be sure it's about us and not pyspark version.
Many thanks.

**Comment by DevinTDHa** [comment]
@maziyarpanahi From the versions I tested (`2.4.7`, `3.0.2`, `3.1.2`) none of them seem to be working, when running locally.

**Comment by drbonis** [comment]
I have checked the following code with:

pyspark==2.4.0
sparknlp==3.1.1

And apparently it works:

```
from sparknlp.pretrained import PretrainedPipeline
import sparknlp
from sparknlp.annotator import *

sparknlp.start(spark24=True)
pipeline = PretrainedPipeline('explain_document_dl', lang = 'en')
pipeline.annotate("Helo I am very happy!")
norvig = NorvigSweetingModel.pretrained()
```

==========

I have also tried with:

pyspark==3.0.1
sparknlp==3.1.1

And it also works:

```
from sparknlp.pretrained import PretrainedPipeline
import sparknlp
from sparknlp.annotator import *

sparknlp.start(spark24=False)
pipeline = PretrainedPipeline('explain_document_dl', lang = 'en')
pipeline.annotate("Helo I am very happy!")
norvig = NorvigSweetingModel.pretrained()
```

**Comment by DevinTDHa** [comment]
This is getting quite confusing, running it on Databricks with coordinates `com.johnsnowlabs.nlp:spark-nlp_2.12:3.1.1` results in an error, `com.johnsnowlabs.nlp:spark-nlp_2.12:3.1.0` is fine
