### ISSUE TITLE
Python and Scala Interface discrepancies

### ISSUE THREAD

**Issue by DevinTDHa** [JohnSnowLabs/spark-nlp#5760]
## Description

There are some APIs that are not identical between the Python and the Scala version. This could cause some confusion:

| Annotator                       | Python                          | Scala                    | Note                                            |
| ------------------------------- | ------------------------------- | ------------------------ | ----------------------------------------------- |
| **BigTextMatcher**              | `setStorageRef` / `setEntities` | `setStoragePath`         | using `setStorageRef` in scala changes behavior |
| **ContextSpellCheckerApproach** | `setLanguageModelClasses`       | `setLMClasses`           | Similarly with `ContextSpellCheckerModel`       |
|                                 | `setWordMaxDistance`            | `setWordMaxDist`         |                                                 |
|                                 | `setInitialBatchSize`           | `setBatchSize`           |                                                 |
|                                 | `setInitialRate`                | `setInitialLearningRate` |                                                 |
|                                 | `setFinalRate`                  | `setFinalLearningRate`   |                                                 |
|                                 | `setCompoundCount`              | `setBlackListMinFreq`    |                                                 |
|                                 | `setClassCount`                 | `setClassThreshold`      |                                                 |
|                                 | `setWeightedDistPath`           | `setWeights`             |                                                 |
| **PerceptronApproach**          | `setPosCol`                     | `setPosColumn`           |                                                 |
|                                 | `setIterations`                 | `setNIterations`         |                                                 |
| **RegexMatcher**                | `setExternalRules`              | `setRules`               |                                                 |
| **ViveknSentimentApproach**     | `setPruneCorpus`                | `setCorpusPrune`         |                                                 |
| **WordSegmenterApproach**       | `setPosCol`                     | `setPosColumn`           |                                                 |
|                                 | `setIterations`                 | `setNIterations`         |                                                 |

**Comment by maziyarpanahi** [comment]
Hi @DevinTDHa 

- `BigTextMatcher` in both Scala and Python is extended via `HasStorage` which also has `HasStorageRef`. These two provide `setStorageRef` and `setStoragePath` in both Scala and Python - Let's create a specific issue for this and how the behavior changes from Scala to Python for more investigation
- `setEntities ` is for `TextMatcher` not `BigTextMatcher` - it seems it's the same in both Scala and Python
- ContextSpellCheckerApproach, yes, the variables are the same in both but the setters and getters are different! I'll match the Scala with Python
- `WordSegmenterApproach`, `setPosCol` is for both Scala and Python. However, `setNIterations` is being synced for both Python and Scala
- `ViveknSentimentApproach` now has `setPruneCorpus` synced between both Scala and Python
- 'RegexMatcher' now has `setExternalRules` in both Scala and Python
- `PerceptronApproach` now has `setPosColumn` in both Scala and Python
- `ContextSpellCheckerApproach` has synced parameters between Python and Scala
