### ISSUE TITLE
Cannot find Bert Model for Local usage in Closed Environment

### ISSUE THREAD

**Issue by Dirkster99** [JohnSnowLabs/spark-nlp#5776]
## Description

I am trying to find the blow Bert model for local usage replacing the statement below (which can be used in CoLab) to use the same model in a closed air tight environment:

```py
bert_annotator = BertEmbeddings.pretrained('small_bert_L2_128', 'en') \
 .setInputCols(["sentence",'token'])\
 .setOutputCol("bert")\
.setBatchSize(8)
```

I've tried to find the model in the model hub [with this query](https://nlp.johnsnowlabs.com/models?q=small_bert_L2_128&task=Embeddings),. So, I downloaded [this model](https://nlp.johnsnowlabs.com/2020/08/25/sent_small_bert_L2_128.html) (which is displayed twice in the previous search results page?) only to receive the below exception with the below code replacement:

```py
bert_annotator = BertEmbeddings.load('./sent_small_bert_L2_128_en') \
 .setInputCols(["sentence",'token'])\
 .setOutputCol("bert")\
.setBatchSize(8)
```

**EXCEPTION: com.johnsnowlabs.nlp.embeddings.BertSentenceEmbeddings cannot be cast to com.johnsnowlabs.nlp.embeddings.BertEmbeddings**

## Expected Behavior

I should find the model in the models hub page when I enter the name of the model as stated in the `pretrained` method [eg `BertEmbeddings.pretrained(...)`]. So entering the string `small_bert_L2_128` in the search box of the models hub page should bring up the models card.

## Current Behavior

The correct model card cannot be found in the model hub search page. Therefore, the model cannot be used in an air tight environment.

## Possible Solution

1) It would be great if models (when they are being downloaded in an open environment like CoLab) via `pretrained(....)` method could output/display a download link to manually download the exact copy of what was being used in the open environment.

2) The functionality of the Search Page in the models hub should be reviewed as it seems to display many duplicate result entries (in the above example I received 2 result entries to the exact same model). And it should be possible to enter the name from the `pretrained()` method to find the actual model for manual download.

## Steps to Reproduce

1. Enter the above code samples as given

## Context

This bug blocks me from using Spark NLP in my companies air tight environment.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.x
* Apache NLP version `spark.version`: 3.x
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.): Pypi
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,

There are two annotators which is one doe word embeddings and it’s called BertEmbeddings and the other one is for sentence embeddings which is called BertSentenceEmbeddings.

You downloaded the sentence embeddings and trying to load it in the word embeddings (it’s in the error). You can check the examples in each model’s card for the correct usage/annotator if you are not sure from the title.

**Comment by Dirkster99** [comment]
So when I search for (BertEmbeddings)[https://nlp.johnsnowlabs.com/models?q=BertEmbeddings&task=Embeddings] I get a list of 9 models with completely different names:

1) Recognize Entities OntoNotes - BERT Medium (Base, Large, Medium, Mini, Small, Tiny)
2) Recognize Entities OntoNotes - ELECTRA (Base, Large, Small)

I take that I have to use one of the models in the first entry to replace a Bert model, correct?

I came on to this through [this notebook](https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/blogposts/3.NER_with_BERT.ipynb) which does not state the correct name in *cell 8* - it only talks about *Bert* models. It would be really useful if there was a deterministic way to find a model in the hub that was downloaded automatically. So, you are saying I can always search for the Class name, correct?If thats the case, why is that not stated in the notebook?
