### ISSUE TITLE
using setRequiredAnnotatorTypes() with many of the annotators throws error.

### ISSUE THREAD

**Issue by clayms** [JohnSnowLabs/spark-nlp#58]
Many of the annotators in annotator.py list `requiredAnnotatorTypes()` as a parameter when using either `<annotatorName>().explainParams()`, or `dir(<annotatorName>)`.

However, when using `<annotatorName>().setRequiredAnnotatorTypes` on most of these annotators, the following error is thrown.

```
Py4JJavaError: An error occurred while calling o830.getParam.
: java.util.NoSuchElementException: Param requiredAnnotatorTypes does not exist.
```

The only place where the `requiredAnnotatorTypes` parameter is shown is in the `class AnnotatorProperties` of annotator.py starting on line 29.

**Comment by aleksei-ai** [comment]
@clayms  What annotator you use?
I tried with different annotators and it works for me:
print(PerceptronApproach().explainParams())
print(EntityExtractor().explainParams())
print(ViveknSentimentApproach().explainParams())
print(NorvigSweetingApproach().explainParams())
print(NerCrfApproach().explainParams())

**Comment by clayms** [comment]
Hi @aleksei-ai I have tried it with RegexTokenizer, Normalizer, Stemmer, Lemmatizer, RegexMatcher, EntityExtractor, DateMatcher, SentenceDetectorModel, PerceptronApproach, SentimentDetectorModel, NERRegexApproach, and NorvigSweetingApproach.

the .explainParams() method works on all of them, but when I try and use the .setRequiredAnnotatorTypes when building the annotator to use in a pipeline, that is when the error I referenced above is thrown.

Thanks,

**Comment by saifjsl** [comment]
Hi, setRequiredAnnotatorTypes() is a deprecated method and should not be used. This function in python code is just a mistake of a lingering code. Shall be deleted. Thank you @clayms

**Comment by saifjsl** [comment]
Merged Fix
