### ISSUE TITLE
Request : Add customizable Relation Extraction annotator

### ISSUE THREAD

**Issue by 222579630** [JohnSnowLabs/spark-nlp#5810]
Can you please add a feature to train Relation Extraction models similar to the feature in SparkNLP for Healthcare?

**Comment by maziyarpanahi** [comment]
Hi,

We cannot add licensed features to the public library.

**Comment by maziyarpanahi** [comment]
Hi @xegulon 
Yes! This is an open-source library and we welcome any contribution! 😊

**Comment by xegulon** [comment]
When I master it, I'd like to implement LUKE, but this won't come before long I fear. What's the purpose of the GraphExtraction annotator?
Thanks @maziyarpanahi
