### ISSUE TITLE
DateNormalizer annotator getAnchorDateMonth returns incorrect value after setting the parameter

### ISSUE THREAD

**Issue by dkincaid** [JohnSnowLabs/spark-nlp#5814]
The DateNormalizer annotator is displaying the same behavior described in issue #5673. The `getAnchorDateMonth` method is returning a value one less than what was set in the object.

After creating a DateNormalizer annotator and using setAnchorDateMonth() to set the parameter, a call to getAnchorDateMonth() returns a different value than was set. It appears to return one less than whatever integer was set.

```java
DateNormalizer myMatcher = new DateNormalizer();
myMatcher.setAnchorDateMonth(5);
int wrongMonth = myMatcher.getAnchorDateMonth();
// wrongMonth will be 4 instead of 5
```

* Spark NLP version sparknlp.version(): 3.1.2
* Apache NLP version spark.version: 3.1.1
* Java version java -version: OpenJDK 1.8.0_292
* Operating System and version: Linux Pop_OS 21.04
* Link to your project (if any): https://github.com/r-spark/sparknlp

**Comment by maziyarpanahi** [comment]
Hi @dkincaid 
Thanks for reporting this, but this feature is licensed not public. I would recommend reaching out to the team on the Slack #healthcare channel or via email.

**Comment by xusliebana** [comment]
I copied to Spark-nlp-internal
