### ISSUE TITLE
Could not initialize class com.johnsnowlabs.util.ConfigHelper$

### ISSUE THREAD

**Issue by beginneruser2021** [JohnSnowLabs/spark-nlp#5817]
Receiving an error when trying to load pretrained model from hdfs.
## Description

In HDFS, loaded offline pre trained model file(s). Apply or use it in code e.g. bert = BertEmbeddings.load(<path>) throws an error "Could not initialize class com.JohnSnowLabs.util. ConfigHelper"
## Expected Behavior

It should load pre trained model from the uncompressed file in HDFS.
## Current Behavior

Receiving an error message: 
Py4JJavaError: An error occurred while calling None.com.johnsnowlabs.nlp.embeddings.BertEmbeddings.
: java.lang.NoClassDefFoundError: Could not initialize class com.johnsnowlabs.util.ConfigHelper$
## Possible Solution

Reference to the offline model might be wrong OR something needs to be updated in Config.
## Steps to Reproduce

1. Import all spark NLP libs
from sparknlp.base import *
from sparknlp.annotator import *  
from sparknlp.common import *
import sparknlp
2.  Sparknlp.start()
spark = sparknlp.start()
3. document_assembler = DocumentAssembler()\
                        .setInputCol("text")\
                        .setOutputCol("document")
4. Load the pretrained model from hdfs path.
bert = BertEmbeddings.load("/user/xxx/bert_base_cased_en_2.4.0_2.4_1580579557778") \
    .setInputCols(["document"]) \
    .setOutputCol("bert") \
    .setCaseSensitive(False)\
    .setPoolingLayer(0)
 
## Context

Trying to apply ClassifierDL - word embedding and sentence Embeddings (USE). classiferDL is new for me, fixing this issue will enable it's use for many different applications.
## Your Environment

* Spark NLP version `sparknlp.version()`: 2.4.5
* Apache NLP version `spark.version`: 2.3.2.3.1.0.0-78
* Java version `java -version`: openjdk version "1.8.0_282", OpenJDK Runtime Environment (build 1.8.0_282-b08), OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
* Setup and installation (Pypi, Conda, Maven, etc.): Pyspark
* Operating System and version: Hadoop Cluster
* Link to your project (if any):

Thank you for the help.

**Comment by maziyarpanahi** [comment]
Hi,

Since you are in a cluster, could you please describe the following:
- Which Hadoop cluster is this? 
- Where is your PySpark? (jupyter, pyspark shell, etc.)
- How are you starting your SparkSession? (spark = sparknlp.start() is for local use only, inside the cluster it means nothing really)
- Please explain how you installed Spark NLP in your cluster? (do you have `spark-nlp` PyPI package installed on all the machines? Is it the Maven or the JAR being included in the SparkSession?
- Is there a specific reason you are on SPark NLP 2.4.5 and not 3.1.x? given the fact Spark, NLP 3.1.x also supports Apache Spark 2.3.x with lots of bug fixes and new features. 

We need detailed answers to each of these questions to understand the issue.

**Comment by beginneruser2021** [comment]
Thank you for your assistance.

Let me get back to you soon with answers.

**Comment by albertoandreottiATgmail** [comment]
Hi, 

I'm experiencing the same issue on EMR while passing the spark-nlp jar as a maven coordinate.

**Comment by beginneruser2021** [comment]
@maziyarpanahi Sorry for the delay. Thank you again for your help.
Here are the answers:
•	Which Hadoop cluster is this? Hortonworks Data Platform (HDP) 3.1.0
•	Where is your PySpark? (jupyter, pyspark shell, etc.) Jupyter
•	How are you starting your SparkSession? (spark = sparknlp.start() is for local use only, inside the cluster it means nothing really)
   conf = SparkConf()
    conf.setAppName(user_app_name) 
     conf.setMaster("yarn") 
    conf.set('spark.executor.memory', '32g')
    conf.set('spark.driver.memory', '32g')
    conf.set('spark.executor.instances','4')
    conf.set('spark.executor.cores',4)
    conf.set('spark.rpc.message.maxSize','1024')
    #conf.set("spark.driver.memory","16G") 
    conf.set("spark.driver.maxResultSize","0") 
    conf.set("spark.kryoserializer.buffer.max","2000M") 
    conf.set("spark.jars","/xxx/jars/spark-nlp-assembly-2.4.5.jar") 
    conf.set("spark.driver.extraClassPath","/xxx/jars/com.johnsnowlabs.nlp_spark-nlp_2.11-2.4.5.jar") 

•	Please explain how you installed Spark NLP in your cluster? (do you have spark-nlp PyPI package installed on all the machines? Is it the Maven or the JAR being included in the SparkSession? Pip install of PyPI package, and it is installed on all the nodes in the cluster.
•	Is there a specific reason you are on SPark NLP 2.4.5 and not 3.1.x? given the fact Spark, NLP 3.1.x also supports Apache Spark 2.3.x with lots of bug fixes and new features. Spark NLP 2.4.5 version requested by users.

Please let me know if I can provide any additional details that'll be helpful to fix this issue. Thank you.

**Comment by maziyarpanahi** [comment]
Thanks @beginneruser2021 

Could you please let me know where did you get this jar `spark-nlp-assembly-2.4.5.jar`?

**Comment by beginneruser2021** [comment]
Thank you very much, @maziyarpanahi 
Getting the answers....in few minutes.

**Comment by beginneruser2021** [comment]
•where did you get this jar spark-nlp-assembly-2.4.5.jar?
compiled FAT Jar file provided in Johnsnowlabs MAVEN repository
• what is the size of this jar? 208MB
• does this /xxx/jars/ mean hdfs:///xxx/jars/?
          It's a local reference.
•	also, why do you set this config? I don't believe we ever mention this anywhere and the jar seems to be a light jar from Maven conf.set("spark.driver.extraClassPath","/xxx/jars/com.johnsnowlabs.nlp_spark-nlp_2.11-2.4.5.jar") “spark.driver.extraClassPath” is used to reference additional jar files

Thank you.

**Comment by maziyarpanahi** [comment]
The jar(s) on the MAVEN repository is meant to be used as a coordinate, not as an assembly JAR. You need a FAT jat. That is why in each release we list the actual FAT JARs under the release notes. Please follow these steps:

- Download this Fat JAR which is complete with all the required dependencies: https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/jars/spark-nlp-assembly-2.4.5.jar
- Make sure you put this fat JAR on HDFS, since you are in the cluster it's best to have that JAR on HDFS and not locally. 
- I highly advise you to remove the current jar(s) so you don't make a mistake in the naming since they both have the same name. But the real FAT JAR is much bigger in size
- Please also remove the .conf that is for `extraClassPath` entirely and rely on the `spark.jars` pointing to a real FAT JAR on your HDFS. We never mentioned this and it was never tested especially in the cluster.

**Comment by beginneruser2021** [comment]
@maziyarpanahi , truly appreciate your help with this. Thank you again.
I will follow the steps you mentioned and will get back to you soon. Thank you.

**Comment by beginneruser2021** [comment]
@maziyarpanahi 

As you suggested, I followed the steps:
(1) and (2) - verified FAT Jar and dependencies (I can't directly do and done by separate team) - It was actually downloaded from the location you mentioned above.
I copied to HDFS and updated config as
conf.set("spark.jars","hdfs://user/jars/spark-nlp-assembly-2.4.5.jar") 

Receiving an error while trying to use DocumentAssembler:
**Code:**
document_assembler = DocumentAssembler()\
                        .setInputCol("text")\
                        .setOutputCol("document")
**Error**
TypeErrorTraceback (most recent call last)
<ipython-input-22-ec1d86c1e82b> in <module>()
----> 1 document_assembler = DocumentAssembler()                        .setInputCol("text")                        .setOutputCol("document")

/usr/hdp/3.1.0.0-78/spark2/python/lib/pyspark.zip/pyspark/__init__.py in wrapper(self, *args, **kwargs)
    103             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    104         self._input_kwargs = kwargs
--> 105         return func(self, **kwargs)
    106     return wrapper
    107 

/usr/lib/python2.7/site-packages/sparknlp/base.py in __init__(self)
    146     @keyword_only
    147     def __init__(self):
--> 148         super(DocumentAssembler, self).__init__(classname="com.johnsnowlabs.nlp.DocumentAssembler")
    149         self._setDefault(outputCol="document", cleanupMode='disabled')
    150 

/usr/hdp/3.1.0.0-78/spark2/python/lib/pyspark.zip/pyspark/__init__.py in wrapper(self, *args, **kwargs)
    103             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    104         self._input_kwargs = kwargs
--> 105         return func(self, **kwargs)
    106     return wrapper
    107 

/usr/lib/python2.7/site-packages/sparknlp/internal.py in __init__(self, classname)
     70         self.setParams(**kwargs)
     71         self.__class__._java_class_name = classname
---> 72         self._java_obj = self._new_java_obj(classname, self.uid)
     73 
     74 

/usr/hdp/3.1.0.0-78/spark2/python/lib/pyspark.zip/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     61             java_obj = getattr(java_obj, name)
     62         java_args = [_py2java(sc, arg) for arg in args]
---> 63         return java_obj(*java_args)
     64 
     65     @staticmethod

TypeError: 'JavaPackage' object is not callable

Please advise further. Thank you.

**Comment by maziyarpanahi** [comment]
OK this means the JAR is not part of the SparkSession:

```
TypeError: 'JavaPackage' object is not callable
```

The problem is that Jupyter masks most of the important errors during the SparkSession creation. Do you have access to a machine that can run `pyspark --master yarn --mode client --jars hdfs:///user/jars/spark-nlp-assembly-2.4.5.jar`?

**Comment by beginneruser2021** [comment]
Thank you @maziyarpanahi 
Let me update you soon.

**Comment by beginneruser2021** [comment]
@maziyarpanahi 
I can access to a machine and ran pyspark --master yarn --mode client --jars hdfs:///user/jars/spark-nlp-assembly-2.4.5.jar with a small update as pyspark --master yarn --deploy-mode client --jars hdfs:///user/jars/spark-nlp-assembly-2.4.5.jar

Welcome to
    Spark         
SparkSession available as 'spark'.
>>>

**Comment by maziyarpanahi** [comment]
That's great, now we can see the errors more clearly. Let's run this command (closely watch the logs at the beginning and anything about `spark-nlp-assembly`):
```sh
pyspark --master yarn \
--deploy-mode client \
--driver-memory 16g \
--executor-memory 16g \
--driver-cores 8 \
--executor-cores 8 \
--jars hdfs:///user/jars/spark-nlp-assembly-2.4.5.jar
```

Once you are in the pyspark shell, could you please run the following and see what's the error:

```python
from sparknlp.base import *
from sparknlp.annotator import *
import sparknlp

print("Spark NLP version: ", sparknlp.version())
print("Apache Spark version: ", spark.version)

document = DocumentAssembler()\
    .setInputCol("text")\
    .setOutputCol("document")

sentence = SentenceDetector()\
    .setInputCols(['document'])\
    .setOutputCol('sentence')

token = Tokenizer()\
    .setInputCols(['sentence'])\
    .setOutputCol('token')

prediction_pipeline = Pipeline(
    stages = [
        document,
        sentence,
        token
    ]
)

prediction_data = spark.createDataFrame([["Maria is a nice place."]]).toDF("text")

result = prediction_pipeline.fit(prediction_data).transform(prediction_data)
result.select("token.result").show(1, False)

```

Let's see how this goes, if you still see `TypeError: 'JavaPackage' object is not callable` it means the Fat JAR didn't load correctly. (you can also have the Fat JAR locally in this scenario just to be sure the path is accessible and try again just for the sake of testing)

**Comment by beginneruser2021** [comment]
That's awesome....Thank you @maziyarpanahi 
Will get back in few minutes.

**Comment by beginneruser2021** [comment]
@maziyarpanahi , As you said, I ran the code above and receiving different error message.
>>> from sparknlp.base import * 
>>> from sparknlp.annotator import * 
>>> import sparknlp 
>>> 
>>> print("Spark NLP version: ", sparknlp.version()) 
('Spark NLP version: ', '2.4.5')
>>> print("Apache Spark version: ", spark.version) 
('Apache Spark version: ', u'2.3.2.3.1.0.0-78')
>>> 
>>> document = DocumentAssembler()\
...     .setInputCol("text")\
...     .setOutputCol("document")
>>> 
>>> sentence = SentenceDetector()\
...     .setInputCols(['document'])\
...     .setOutputCol('sentence')
>>> 
>>> token = Tokenizer()\
...     .setInputCols(['sentence'])\
...     .setOutputCol('token')
>>> 
>>> prediction_pipeline = Pipeline(
...     stages = [
...         document,
...         sentence,
...         token
...     ]
... ) 
>>> 
>>> prediction_data = spark.createDataFrame([["Maria is a nice place."]]).toDF("text") 
>>> 
>>> result = prediction_pipeline.fit(prediction_data).transform(prediction_data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/hdp/current/spark2-client/python/pyspark/ml/base.py", line 132, in fit
    return self._fit(dataset)
  File "/usr/hdp/current/spark2-client/python/pyspark/ml/pipeline.py", line 95, in _fit
    if not (isinstance(stage, Estimator) or isinstance(stage, Transformer)):
  File "/usr/lib64/python2.7/abc.py", line 144, in __instancecheck__
    return cls.__subclasscheck__(subtype)
  File "/usr/lib64/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/usr/lib64/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/usr/lib64/python2.7/abc.py", line 179, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
>>> result.select("token.result").show(1, False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'result' is not defined
>>> 


Please advise further. Thank you for your help. I am going to keep Fat JAR locally and see.

**Comment by maziyarpanahi** [comment]
Please copy the entire error, it does not seem to be related to the Spark NLP or the JAR.

```
NameError: name 'result' is not defined
```

**Comment by beginneruser2021** [comment]
That is the entire error message....result is with fit and transform...

>>> result = prediction_pipeline.fit(prediction_data).transform(prediction_data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/hdp/current/spark2-client/python/pyspark/ml/base.py", line 132, in fit
    return self._fit(dataset)
  File "/usr/hdp/current/spark2-client/python/pyspark/ml/pipeline.py", line 95, in _fit
    if not (isinstance(stage, Estimator) or isinstance(stage, Transformer)):
  File "/usr/lib64/python2.7/abc.py", line 144, in __instancecheck__
    return cls.__subclasscheck__(subtype)
  File "/usr/lib64/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/usr/lib64/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/usr/lib64/python2.7/abc.py", line 179, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
>>> result.select("token.result").show(1, False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'result' is not defined
>>> 

Anything I need to update in the code to see? Please advise.

**Comment by maziyarpanahi** [comment]
I am sorry I am not inside the console, it is a simple Python error saying the variable doesn't exist. Please try to find the issue and see if you are seeing the initial errors mentioned in this issue. 

If the initial error is resolved we can close this issue.

**Comment by beginneruser2021** [comment]
Thank you @maziyarpanahi 
I don't see the error I was receiving "could not initialize class com.johnsnowlabs.util.confighelper". As you said, it's just a variable 'result'.

**Comment by beginneruser2021** [comment]
@maziyarpanahi 

I copied the JAR file locally and updated my config:
conf.set("spark.jars","spark-nlp-assembly-2.4.5.jar") 
conf.set("spark.jars.packages","/user/jars/com.johnsnowlabs.nlp_spark-nlp_2.11-2.4.5.jar") 

And ran the same code above. I am receiving an error message which is "java package object is not callable".
Full error message:
TypeErrorTraceback (most recent call last)
<ipython-input-44-dcb0f88e68eb> in <module>()
----> 1 document = DocumentAssembler()    .setInputCol("text")    .setOutputCol("document")
      2 
      3 sentence = SentenceDetector()    .setInputCols(['document'])    .setOutputCol('sentence')
      4 
      5 token = Tokenizer()    .setInputCols(['sentence'])    .setOutputCol('token')

/usr/hdp/3.1.0.0-78/spark2/python/lib/pyspark.zip/pyspark/__init__.py in wrapper(self, *args, **kwargs)
    103             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    104         self._input_kwargs = kwargs
--> 105         return func(self, **kwargs)
    106     return wrapper
    107 

/usr/lib/python2.7/site-packages/sparknlp/base.py in __init__(self)
    146     @keyword_only
    147     def __init__(self):
--> 148         super(DocumentAssembler, self).__init__(classname="com.johnsnowlabs.nlp.DocumentAssembler")
    149         self._setDefault(outputCol="document", cleanupMode='disabled')
    150 

/usr/hdp/3.1.0.0-78/spark2/python/lib/pyspark.zip/pyspark/__init__.py in wrapper(self, *args, **kwargs)
    103             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    104         self._input_kwargs = kwargs
--> 105         return func(self, **kwargs)
    106     return wrapper
    107 

/usr/lib/python2.7/site-packages/sparknlp/internal.py in __init__(self, classname)
     70         self.setParams(**kwargs)
     71         self.__class__._java_class_name = classname
---> 72         self._java_obj = self._new_java_obj(classname, self.uid)
     73 
     74 

/usr/hdp/3.1.0.0-78/spark2/python/lib/pyspark.zip/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     61             java_obj = getattr(java_obj, name)
     62         java_args = [_py2java(sc, arg) for arg in args]
---> 63         return java_obj(*java_args)
     64 
     65     @staticmethod

TypeError: 'JavaPackage' object is not callable


Please advise further. Thank you again for your continued assistance.
