### ISSUE TITLE
Missing/None predictions while using Bert Embeddings in Ner Models

### ISSUE THREAD

**Issue by HashamUlHaq** [JohnSnowLabs/spark-nlp#5831]
## Description

Sometimes we get None/Missing results for tokens while using Bert Word embeddings (biobert_pubmed_base_cased) in Ner model. **This does not happen with WordEmbeddings; only with BertEmbeddings**

## Expected Behavior

We should get output tag per token, but that is not the case as explained in the example below - A document containing 272 tokens gets only 79 predictions. 

## Current Behavior

A lot of tokens get None in the result. When used in lightpipeline, they are discarded altogether.. 

## Steps to Reproduce
Here is the code:

`
text = """Form XX ) Mattis Dementia Rating Scale , 2nd Edition ( DRS-2 ) Neuropsychological Assessment Battery ( NAB ) Wechsler Adult Intelligence Scale , Third Edition ( WAIS-III ) Wechsler Adult Intelligence Scale , Fourth Edition ( WAIS-IV ) Wechsler Abbreviated Scale of Intelligence ( WASI ) Test of Variables of Attention ( TOVA ) Auditory Consonant Trigrams ( ACT ) Paced Auditory Serial Addition Test ( PASAT ) Ruff 2 & 7 Selective Attention Test Symbol Digit Modalities Test ( SDMT ) Multilingual Aphasia Examination , Second Edition ( MAE-II ) Token Test Sentence Repetition Visual Naming Controlled Oral Word Association Spelling Test Aural Comprehension Reading Comprehension Boston Naming Test , Second Edition ( BNT-2 ) Animal Naming Test Controlled Oral Word Association Test ( COWAT : F-A-S ) The Beery-Buktenica Developmental Test of Visual-Motor Integration ( VMI ) The Beery-Buktenica Developmental Test of Motor Coordination The Beery-Buktenica Developmental Test of Visual Perception Hooper Visual Organization Test ( VOT ) Judgment of Line Orientation ( JOLO ) Rey Complex Figure Test ( RCFT ) Wechsler Memory Scale , Third Edition ( WMS-III ) Wechsler Memory Scale , Fourth Edition ( WMS-IV ) California Verbal Learning Test , Second Edition ( CVLT-II ) Rey Auditory-Verbal Learning Test ( RAVLT ) Delis-Kaplan Executive Function System ( D-KEFS ) Trail Making Test Verbal Fluency ( Letter & Category ) Design Fluency Color-Word Interference Test Tower Wisconsin Card Sorting Test ( WCST ) Stroop Color-Word Test Color Trails Trail Making Test A & B Wide Range Achievement Test , Fourth Edition ( WRAT-IV ) Woodcock Johnson Tests of Achievement , Third Edition ( WJ-III )"""

documentAssembler = (
DocumentAssembler()
.setInputCol("text")
.setOutputCol("document")
)

tokenizer = Tokenizer().setInputCols(["document"]).setOutputCol("token")

word_embeddings = (
BertEmbeddings.pretrained("biobert_pubmed_base_cased")
.setInputCols(["document", "token"])
.setOutputCol("embeddings")
)

ner = (
MedicalNerModel.pretrained("ner_dl_bert_base_cased")
.setInputCols(["document", "token", "embeddings"])
.setOutputCol("ner_tags")
)
ner_converter = (
NerConverterInternal()
.setInputCols(["document", "token", "ner_tags"])
.setOutputCol("ner_chunks")
)
pipeline = Pipeline(
stages=[
documentAssembler,
tokenizer,
word_embeddings,
ner, ner_converter,
]
)

data_ner = spark.createDataFrame([["text"]]).toDF("text")
p_model = pipeline.fit(data_ner)
l_model = LightPipeline(p_model)

res = l_model.fullAnnotate([text])[0]
print (len(res['token']))
print (len(res['ner_tags']))
`

## Context

Trying to train and test a model using Bert embeddings.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.1.2
* Apache NLP version `spark.version`: 3.0.2
* Java version `java -version`: 8
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version: ubuntu
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
BERT and other encoders have max sequence length. If the document is larger than that it will truncate/trim it so there will be nothing to predict. I suggest setting the macSentenceLength param wisely and also break the documents to sentences instead of directly going from DocumentAssembler to Tokenizer:

```
.setInputCols(["document", "token"]) # this should come from SentenceDetector to break the longer documents to shorter sentences to have less truncated inputs
```
