### ISSUE TITLE
py4j.security.Py4JSecurityException: Constructor public com.johnsnowlabs.nlp.DocumentAssembler(java.lang.String) is not whitelisted.

### ISSUE THREAD

**Issue by ShubhamPal7** [JohnSnowLabs/spark-nlp#5850]
I am trying to run spark nlp's document assembler on Databricks HC cluster but I am getting this error.

An error occurred while calling None.com.johnsnowlabs.nlp.DocumentAssembler. Trace:
py4j.security.Py4JSecurityException: Constructor public com.johnsnowlabs.nlp.DocumentAssembler(java.lang.String) is not whitelisted.
	at py4j.security.WhitelistingPy4JSecurityManager.checkConstructor(WhitelistingPy4JSecurityManager.java:451)
	at py4j.Gateway.invoke(Gateway.java:249)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)

Thanks in advance.
This place has been super helpful to me.

**Comment by maziyarpanahi** [comment]
Hi,

Could you please complete the issue template with all the information, steps, code, etc.? It's hard to diagnose from this.

Also, please make sure you follow this instruction step by step: https://github.com/JohnSnowLabs/spark-nlp#databricks-cluster

**Comment by ShubhamPal7** [comment]
Sure,

df_t = df_final
def preprocess(column):
 
  
  document_assembler = DocumentAssembler() \
    .setInputCol(column) \
    .setOutputCol("document")# convert document to array of tokens
  
  tokenizer = Tokenizer() \
  .setInputCols(["document"]) \
  .setOutputCol("token")

  normalizer = Normalizer() \
    .setInputCols(["token"]) \
    .setOutputCol("normalized")
  stopwords_cleaner = StopWordsCleaner()\
      .setInputCols("normalized")\
      .setOutputCol("cleanTokens")\
      .setCaseSensitive(False)# stems tokens to bring it to root form
  stemmer = Stemmer() \
    .setInputCols(["cleanTokens"]) \
    .setOutputCol("stem")# Convert custom document structure to array of tokens.
  
  finisher = Finisher() \
    .setInputCols(["stem"]) \
    .setOutputCols(["{}_token_features".format(column)]) \
    .setOutputAsArray(True) \
    .setCleanAnnotations(False)# To generate Term Frequency

  hashingTF = HashingTF(inputCol="{}_token_features".format(column), outputCol="rawFeatures", numFeatures=1000)# To generate Inverse Document Frequency
  idf = IDF(inputCol="rawFeatures", outputCol="{}_features".format(column), minDocFreq=5)# convert labels (string) to integers. Easy to process compared to string

  nlp_pipeline = Pipeline(
     stages=[document_assembler, 
            tokenizer,
            normalizer,
            stopwords_cleaner, 
            stemmer, 
            finisher,
            hashingTF,
            idf])
  model = nlp_pipeline.fit(df_t)
  df = model.transform(df_t)
  df = df.drop('document','token','normalized','cleanTokens','stem','rawFeatures',column)
  
  return df
  
I am getting this error when trying to run this function, i.e
df_t = preprocess('description')


This code works perfect when I run this on my personal cluster in Databricks but when I run this in High Concurrency shared cluster, I get this error. There is nothing mentioned in that blog regarding HC cluster in Databricks.

**Comment by ShubhamPal7** [comment]
My spark config is:

spark.driver.extraJavaOptions -Djava.net.useSystemProxies=true -Djava.security.properties=
javax.jdo.option.ConnectionPassword {{secrets/kv-cerebro-prod-scope/cerebro-eastus2-prd-cerebromsbase-sqldb-pwd-scope}}
spark.databricks.delta.preview.enabled true
spark.databricks.passthrough.enabled true
javax.jdo.option.ConnectionURL jdbc:sqlserver://cerebro-eastus2-prd-cerebromsbase-sqldb.database.windows.net:1433;database=cerebromsbase;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
spark.hadoop.foundry.trustStorePath /usr/lib/jvm/zulu8-ca-amd64/jre/lib/security/cacerts
spark.databricks.pyspark.trustedFilesystems com.databricks.s3a.S3AFileSystem,shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.SecureAzureBlobFileSystem,shaded.databricks.v20180920_b33d810.org.apache.hadoop.fs.azurebfs.SecureAzureBlobFileSystem,com.databricks.adl.AdlFileSystem,shaded.databricks.V2_1_4.com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem,shaded.databricks.org.apache.hadoop.fs.azure.NativeAzureFileSystem,shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem,com.palantir.foundry.fs.FoundryFileSystem
spark.databricks.pyspark.iptable.outbound.whitelisted.ports 3128
spark.hadoop.fs.foundry.impl com.palantir.foundry.fs.FoundryFileSystem
spark.databricks.repl.allowedLanguages python,sql,scala,r
spark.databricks.cluster.profile serverless
spark.executor.extraJavaOptions -Djava.net.useSystemProxies=true -Djava.security.properties= -Doracle.jdbc.javaNetNio=false -DsocksProxyHost=10.241.0.61 -DsocksProxyPort=8128 -DsocksNonProxyHosts="*.windows.net\|*.azuredatabricks.net\|localhost" -Dhttp.nonProxyHosts="*.windows.net\|*.azuredatabricks.net\|localhost"
spark.sql.hive.metastore.jars /dbfs/metastore/*
javax.jdo.option.ConnectionDriverName com.microsoft.sqlserver.jdbc.SQLServerDriver
spark.sql.hive.metastore.version 3.1.0
javax.jdo.option.ConnectionUserName metastoredbadmin@cerebro-eastus2-prd-cerebromsbase-sqldb
spark.databricks.pyspark.enableProcessIsolation true

**Comment by maziyarpanahi** [comment]
We never tested HC cluster on Databricks. If you are interested in our members to test it we would still need a clean filled template with all the info, steps, screenshots from the Libraries, Cluster configs, etc. With the current information, I am afraid we can spend time debugging something in the dark.

**Comment by ShubhamPal7** [comment]
Thanks for your response.

What would be the ideal Databricks personal / regular cluster configuration you would suggest when we are trying to process 10 million data. like spark,gpu wise ?

**Comment by maziyarpanahi** [comment]
- For the steps to setup Spark NLP for Databricks: https://github.com/JohnSnowLabs/spark-nlp#databricks-cluster
- If you uncheck the HC feature since we never tested it, as you mentioned everything will be fine.

That's being said, lots of parameters are involved in deciding your cluster setup and tuning it. The tasks (DL, rule-based, etc.), the number of rows maybe is 10 million but how many sentences or how long each sentence, etc. In reality, nobody knows better than you who has both hardware and real-life use cases to experiment with.

I recommend watching this Webinar which is also using Databricks regarding scaling, CPU vs. GPU, and how some tasks will be cheaper and faster on GPU clusters compare to CPU clusters: https://events.johnsnowlabs.com/webinar-speed-optimization-benchmarks-in-spark-nlp-3-making-the-most-of-modern-hardware?hsCtaTracking=a9bb6358-92bd-4cf3-b97c-e76cb1dfb6ef%7C4edba435-1adb-49fc-83fd-891a7506a417

**Comment by cjohnson57** [comment]
I'm getting this error as well in Databricks. No idea about the cluster configuration as I'm not allowed to access or change that. Anyone have any idea what to do about it? If we just need to upgrade the pyspark version maybe I could pass that on to the people who can do it. Or maybe I just need to actually request permission to be able to update the spark config?

**Comment by maziyarpanahi** [comment]
> I'm getting this error as well in Databricks. No idea about the cluster configuration as I'm not allowed to access or change that. Anyone have any idea what to do about it? If we just need to upgrade the pyspark version maybe I could pass that on to the people who can do it. Or maybe I just need to actually request permission to be able to update the spark config?

This is a very old issue, all the versions and dependencies have changed and the solution may not be the same. Could you please create a new issue and fill in the template? We will try to reproduce this and provide a better solution to match the new runtimes. Following this instruction, all runtime (except 13) are compatible: https://github.com/JohnSnowLabs/spark-nlp#databricks-cluster
