### ISSUE TITLE
Different  Performance between 2.7.5 and 3.1.1 when we use have a bertEmbeddings column and when we apply some transformations in other column

### ISSUE THREAD

**Issue by xusliebana** [JohnSnowLabs/spark-nlp#5874]
## Description

There are a issue perfomance when we make some transformations in one column and there are a BetEmbeddings column present in the dataset for the 2.7.5 and 3.1.1. If we remove the bertEmbeddings column in the dataset then the query plan is the same and the Performance is the same.
This is the code that I'm executing:
[SparkExplain3.zip](https://github.com/JohnSnowLabs/spark-nlp/files/6877509/SparkExplain3.zip)

And those are the query plans for the version.
[query_plan_3.1.1spark3.x.txt](https://github.com/JohnSnowLabs/spark-nlp/files/6877317/query_plan_3.1.1spark3.x.txt)
[query_plan_2.7.5.txt](https://github.com/JohnSnowLabs/spark-nlp/files/6877318/query_plan_2.7.5.txt)
[query_plan_3.1.1spark2.4.txt](https://github.com/JohnSnowLabs/spark-nlp/files/6877319/query_plan_3.1.1spark2.4.txt)

## Expected Behavior
Have the same physical plan for version 2.7.5 and 3.1.1 when existing a BertEMbeddings column.

## Current Behavior
The phisical plan is different for version 3.1.1 and 2.7.5 when we run the code. And the performance is bad for version 3.1.1 when we had the BertEmbeddings column in the dataset.

The time to execute:

| Version      | Time (s) | BertEmbeddings|
| ----------- | ----------- |------- |
| 2.7.5      | 34       | No
| 3.1.1   | 127        | No
| 2.7.5      | 37       | Yes
| 3.1.1   | 40        | Yes

## Possible Solution
The problem basically when exists a BertEmbedding column then spark adds the following attributes for the physical plan:

```
  +- MapPartitions com.johnsnowlabs.nlp.AnnotatorModel$$Lambda$2593/1599166845@188e2633, obj#1286: org.apache.spark.sql.Row
  +- DeserializeToObject createexternalrow(value#0.toString, staticinvoke(class scala.collection.mutable.WrappedArray$, variable(MapObject, .....
  +- *(1) Project [value#0, UDF(value#0) AS document#1261, UDF(array(UDF(value#0))) AS sentence#1269, UDF(array(UDF(array(UDF(value#0))))) AS token#1275]
  +- FileScan text [value#0] Batched: false, DataFilters: [], Format: Text, Location: InMemoryFileIndex[file:/home/jsl/IdeaProjects/SparkExplain3/src/main/resources/inputFile.txt], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<value:string>
```
I think that mapParttions is making the query slower and should not be there.

## Steps to Reproduce

1.Run the for the differents versions and check the performance
2 Check the physical plan for the following code 
```
  resultDatasetWrite.select("config_1").explain(true)
```
3. You will see different query plans and differents performance

Alternative
1 Run the code for version 3.1.1 and comment the line when I add the bertEMbeddings column in the NlpPipeline object

```scala
  def getPipeline(): Pipeline = {
    val pipelineStagesList = new util.LinkedList[PipelineStage]
    pipelineStagesList.add(getDocumentAssembler)
    pipelineStagesList.add(getSentenceDetector)
    pipelineStagesList.add(getTokenizer)
    //pipelineStagesList.add(getBertEmbeddings)
    for (i <- 1 to 40) {
      pipelineStagesList.add(getContextualTextMatcher("config_" + i, "config.json"))
    }
    new Pipeline().setStages(pipelineStagesList.toArray(new Array[PipelineStage](0)))
  }

```
2 Check the physical plan for the following code 
3 You will see different query plans and differents performance

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.1.1
* Apache NLP version `spark.version`: 3.0.2 and 2.4.4
* Java version `java -version`: 1.8
* Setup and installation (Pypi, Conda, Maven, etc.): 
* Operating System and version: Ubuntu 20.04
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Could you please have the full code that we can run to reproduce this? (The majority of the code and data is missing, I am mot even sure what this piece of code is supposed to do)
