### ISSUE TITLE
Not all models can be downloaded for usage in airtight environment

### ISSUE THREAD

**Issue by Dirkster99** [JohnSnowLabs/spark-nlp#5896]
Attempt to download a model from [this URL](https://nlp.johnsnowlabs.com/2020/09/06/w2v_cc_300d_de.html) by clicking the download button:
![Unbenannt](https://user-images.githubusercontent.com/2129700/127969822-160f5151-deb7-4af8-a533-227f78d53886.png)

## Expected Behavior

The download of the model starts as it does for other models...

## Current Behavior

The system shows an error message:
**This XML file does not appear to have any style information associated with it. The document tree is shown below.**

```XML
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>8J203C0DCDP93XKQ</RequestId>
<HostId>Iz6qSlZMA50YfAvBRa1YyGAIlfPMbp3jJ1AnJi4mggUbHHWiUtvFKPuJ6zaad/hXa0LA0j+SyNc=</HostId>
</Error>
```

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version `sparknlp.version()`:
* Apache NLP version `spark.version`:
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Thanks @Dirkster99 

I think when they were uploading it they must have chosen a licensed model by mistake and it went to a private bucket. We'll fix it.

@Digaari Could you please take care of this model card? (I will update the metadata and move the actual model to the public and fix the URL, but I need you to just fix the metadata, code, removing anything that says healthcare and licensed.)
