### ISSUE TITLE
Problem with Spark NLP, This error occurs while loading a pretrained Deep learning model

### ISSUE THREAD

**Issue by shubbham37** [JohnSnowLabs/spark-nlp#5918]
## Description

The Fatal Error occurs while loading the pre-trained model. Spark Session gets started and model gets downloaded successfully but while loading the pre-trained model fatal error occurs.

My code:

def start(secret):
    builder = SparkSession.builder \
        .appName("Spark NLP Licensed") \
        .master("local[*]") \
        .config("spark.driver.memory", "16G") \
        .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer") \
        .config("spark.kryoserializer.buffer.max", "2000M") \
        .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.12:"+version) \
        .config("spark.jars", "https://pypi.johnsnowlabs.com/"+secret+"/spark-nlp-jsl-"+jsl_version+".jar")
    return builder.getOrCreate()

import json
import os
from pyspark.ml import Pipeline,PipelineModel
from pyspark.sql import SparkSession
from sparknlp.annotator import *
import sparknlp_jsl
import sparknlp
params = {"spark.driver.memory":"16G",
"spark.kryoserializer.buffer.max":"2000M",
"spark.driver.maxResultSize":"2000M"}
spark = sparknlp_jsl.start(license_keys['SECRET'],params=params)
print ("Spark NLP Version :", sparknlp.version())
print ("Spark NLP_JSL Version :", sparknlp_jsl.version())

documentAssembler = DocumentAssembler()\
        .setInputCol("text")\
        .setOutputCol("document")

sentenceDetector = SentenceDetectorDLModel.pretrained("sentence_detector_dl_healthcare","en","clinical/models")\
        .setInputCols(["document"])\
        .setOutputCol("sentence")

## Expected Behavior

The model Should have loaded without any fatal error

## Current Behavior

Error on terminal:

 A fatal error has been detected by the Java Runtime Environment:

  SIGILL (0x4) at pc=0x00007f36f5b636d0, pid=5883, tid=0x00007f38ae938700

 JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-b10)
 Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libtensorflow_framework.so.2+0x160d6d0]  nsync::nsync_mu_init(nsync::nsync_mu_s_*)+0x0

Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /datadrive/Shubham-user-space/hs_err_pid5883.log

 If you would like to submit a bug report, please visit:
   https://github.com/AdoptOpenJDK/openjdk-support/issues
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

#Error: in Jupyter notebook:

sentence_detector_dl_healthcare download started this may take some time.
Approximate size to download 363.9 KB
[ — ]
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/datadrive/Shubham-user-space/apps/spark-3.0.3-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1207, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datadrive/Shubham-user-space/apps/spark-3.0.3-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1033, in send_command
    response = connection.send_command(command)
  File "/datadrive/Shubham-user-space/apps/spark-3.0.3-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1212, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
[OK!]
---------------------------------------------------------------------------
Py4JError                                 Traceback (most recent call last)
<ipython-input-6-649f3d3b78c8> in <module>
      9         #.setInputCols(["document"])\
     10         #.setOutputCol("sentence")
---> 11 sentenceDetector = SentenceDetectorDLModel.pretrained("sentence_detector_dl_healthcare","en","clinical/models")\
     12         .setInputCols(["document"])\
     13         .setOutputCol("sentence")

/datadrive/Shubham-user-space/sparknlpapi/lib/python3.6/site-packages/sparknlp/annotator.py in pretrained(name, lang, remote_loc)
   8524     def pretrained(name="sentence_detector_dl", lang="en", remote_loc=None):
   8525         from sparknlp.pretrained import ResourceDownloader
-> 8526         return ResourceDownloader.downloadModel(SentenceDetectorDLModel, name, lang, remote_loc)
   8527 
   8528 

/datadrive/Shubham-user-space/sparknlpapi/lib/python3.6/site-packages/sparknlp/pretrained.py in downloadModel(reader, name, language, remote_loc, j_dwn)
     58             t1.start()
     59             try:
---> 60                 j_obj = _internal._DownloadModel(reader.name, name, language, remote_loc, j_dwn).apply()
     61             except Py4JJavaError as e:
     62                 sys.stdout.write("\n" + str(e))

/datadrive/Shubham-user-space/sparknlpapi/lib/python3.6/site-packages/sparknlp/internal.py in __init__(self, reader, name, language, remote_loc, validator)
    192 class _DownloadModel(ExtendedJavaWrapper):
    193     def __init__(self, reader, name, language, remote_loc, validator):
--> 194         super(_DownloadModel, self).__init__("com.johnsnowlabs.nlp.pretrained."+validator+".downloadModel", reader, name, language, remote_loc)
    195 
    196 

/datadrive/Shubham-user-space/sparknlpapi/lib/python3.6/site-packages/sparknlp/internal.py in __init__(self, java_obj, *args)
    145         super(ExtendedJavaWrapper, self).__init__(java_obj)
    146         self.sc = SparkContext._active_spark_context
--> 147         self._java_obj = self.new_java_obj(java_obj, *args)
    148         self.java_obj = self._java_obj
    149 

/datadrive/Shubham-user-space/sparknlpapi/lib/python3.6/site-packages/sparknlp/internal.py in new_java_obj(self, java_class, *args)
    155 
    156     def new_java_obj(self, java_class, *args):
--> 157         return self._new_java_obj(java_class, *args)
    158 
    159     def new_java_array(self, pylist, java_class):

/datadrive/Shubham-user-space/apps/spark-3.0.3-bin-hadoop2.7/python/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     67             java_obj = getattr(java_obj, name)
     68         java_args = [_py2java(sc, arg) for arg in args]
---> 69         return java_obj(*java_args)
     70 
     71     @staticmethod

/datadrive/Shubham-user-space/apps/spark-3.0.3-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1303         answer = self.gateway_client.send_command(command)
   1304         return_value = get_return_value(
-> 1305             answer, self.gateway_client, self.target_id, self.name)
   1306 
   1307         for temp_arg in temp_args:

/datadrive/Shubham-user-space/apps/spark-3.0.3-bin-hadoop2.7/python/pyspark/sql/utils.py in deco(*a, **kw)
    126     def deco(*a, **kw):
    127         try:
--> 128             return f(*a, **kw)
    129         except py4j.protocol.Py4JJavaError as e:
    130             converted = convert_exception(e.java_exception)

/datadrive/Shubham-user-space/apps/spark-3.0.3-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    334             raise Py4JError(
    335                 "An error occurred while calling {0}{1}{2}".
--> 336                 format(target_id, ".", name))
    337     else:
    338         type = answer[1]

Py4JError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel

## Steps to Reproduce

1.
2.
3.
4.

## Context

I am trying to use Spark NLP API for my research in NER

## Your Environment

* Spark NLP version `sparknlp.version()`:3.1.1
* Apache NLP version `spark.version`:3.0.3
* Java version `java -version`:1.8.0_292
* Setup and installation (Pypi, Conda, Maven, etc.):Pypi
* Operating System and version:Ubuntu 18.04.5 LTS
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi @shubbham37 

This is an open-source library, we don't have any knowledge of licensed products/models. You can either:

- contact the person who gave you the license key via email 
- or ask the question on Slack under #healthcare channel

A team of engineers will immediately start helping you :)

**Comment by shubbham37** [comment]
Can you please take a look at the error ... Its not about the downloading the licenced model its about the error in loading it. I am getting the same error while load ling a public model.

Thank you

**Comment by maziyarpanahi** [comment]
I understand, it has definitely something with your `gcc` version that is not compatible with TensorFlow models. However, since you have a licensed library involved, we cannot set up an environment exactly like yours (we just don't have that library). 

The team behind the licensed products is very active and competent. I am sure if you just post this on the Slack #healthcare channel or send an email they will resolve this for you quickly. (they've seen errors like this way more than us in the open-source)
