### ISSUE TITLE
Constructor com.johnsnowlabs.nlp.training.CoNLL() does not exist

### ISSUE THREAD

**Issue by VRCMF** [JohnSnowLabs/spark-nlp#5948]
I encounter a problem that I could not read the txt file into CoNLL().
These codes worked few days ago and they does not work now. I check the file_loc and it does exist. 
`from sparknlp.training import CoNLL`
`file_loc = '..../train_text.txt'`
`train = CoNLL().readDataset(spark, file_loc)`

The error shows that:
`py4j.Py4JException: Constructor com.johnsnowlabs.nlp.training.CoNLL([class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.Integer, class java.lang.Integer, class java.lang.String, class java.lang.String, class java.lang.Boolean, class java.lang.String]) does not exist`

The environment is listed as following:
- Databrick 8.0 ML 
- Apache Spark 3.1.1
- Scala 2.12
- com.johnsnowlabs.nlp:spark-nlp_2.12:3.1.2 (Maven)

**Comment by VRCMF** [comment]
The problem is the version of  the spark-nlp.

**Comment by RajarshiBhadra** [comment]
I see this is closed. What was the correct version used?

**Comment by maziyarpanahi** [comment]
```python
! pip install -q pyspark==3.1.2 spark-nlp

import sparknlp

spark = sparknlp.start() # for GPU training >> sparknlp.start(gpu = True) # for Spark 2.3 =>> sparknlp.start(spark23 = True)

from sparknlp.base import *
from sparknlp.annotator import *

print("Spark NLP version", sparknlp.version())

print("Apache Spark version:", spark.version)

from sparknlp.training import CoNLL

training_data = CoNLL().readDataset(spark, './eng.train')

training_data.show(3)
```

If you have the correct pyspark/spark-nlp installed and correctly started the Spark NLP (SparkSession) the code should work. (please look at any logs/errors that indicates your SparkSession might have failed which without that you cannot access CoNLL)

https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/4.NERDL_Training.ipynb
