### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/spark/ml/util/MLWritable$class error on GCP Dataproc Cluster

### ISSUE THREAD

**Issue by iamvarol** [JohnSnowLabs/spark-nlp#5966]
java.lang.NoClassDefFoundError: org/apache/spark/ml/util/MLWritable$class error has been observed when I tried to run 
documentAssembler = DocumentAssembler()\
    .setInputCol("text")\
    .setOutputCol("document")

## Description

java.lang.NoClassDefFoundError: org/apache/spark/ml/util/MLWritable$class error has been observed when I tried to run 
documentAssembler = DocumentAssembler()\
    .setInputCol("text")\
    .setOutputCol("document")

Py4JJavaError: An error occurred while calling None.com.johnsnowlabs.nlp.DocumentAssembler.
: java.lang.NoClassDefFoundError: org/apache/spark/ml/util/MLWritable$class

*Even if you change the model, it repeats.*

## Expected Behavior

It should download the DocumentAssembler Model and load it.

## Current Behavior

Give an error

## Steps to Reproduce

1. I can provide the jupyter notebook if it is needed.
2.
3.
4.

## Context

Can not create and run any pipeline.

## Your Environment

* Spark NLP version `sparknlp.version()`:  3.2.1
* Apache NLP version `spark.version`:  3.1.2
* Java version `java -version`: OpenJDK 64-Bit Server VM, 1.8.0_292
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:  2.0.17-debian10
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
https://github.com/JohnSnowLabs/spark-nlp/discussions/2562
