### ISSUE TITLE
java.lang.IllegalArgumentException: Wrong FS: s3://, expected: file:///

### ISSUE THREAD

**Issue by surendra-lalwani-rft** [JohnSnowLabs/spark-nlp#5969]
## Description
This happens when trying to load a saved model from S3.

java.lang.IllegalArgumentException: Wrong FS: s3://<<>>/artifacts/static/model/nerDLModel_3.2.1/stages/2_WORD_EMBEDDINGS_MODEL_48cffc8b9a76/storage/EMBEDDINGS_glove_100d, expected: file:///
In sparknlp version 2.5.4 and spark version 2.4 this works fine with python 3.6
 Where it doesn't work
sparknlp version 3.2.1, spark version 3.1.1 and python version 3.7 (AWS Glue version 3.0)

**Comment by maziyarpanahi** [comment]
Hi,
In Spark NLP 2.5.x we didn't have `storage` as it was implemented in 2.6.x or 2.7.x. The `storage` which extracts indexes for the RocksDB database only supports local stage, HDFS, and DBFS. The S3 is not supported for `WordEmbeddings` annotator which is one of the stages in your pipeline. 

ref: https://github.com/JohnSnowLabs/spark-nlp#spark-nlp-configuration (`cluster_tmp_dir`) - you have to have DBFS or HDFS in your cluster or use other annotators for word embeddings that don't require RocksDB inside `cluster_tmp_dir`.
