### ISSUE TITLE
create graph for tensorflow only works with numpy==1.19

### ISSUE THREAD

**Issue by drbonis** [JohnSnowLabs/spark-nlp#5975]
https://github.com/JohnSnowLabs/spark-nlp/blob/6a9c96ff3121b10e4f4593cb1ef438290ac3a31d/python/tensorflow/ner/create_models.py#L1

When running the script to create new graphs for TF 1.15 if you have a version of numpy over 1.19 it will fails.

To solve the issue you need to force numpy to 1.19: 

`pip install numpy==1.19`

**Comment by maziyarpanahi** [comment]
Closing in reference to a discussion: https://github.com/JohnSnowLabs/spark-nlp/discussions/5977

Thanks @drbonis for the guide 👍🏼
