### ISSUE TITLE
SpaCy's `EntityRuler`-like functionality in Spark NLP

### ISSUE THREAD

**Issue by xegulon** [JohnSnowLabs/spark-nlp#5989]
**Is your feature request related to a problem? Please describe.**
I would like to annotate documents against a Knowledge Base, like spaCy's EntityRuler does.

cf https://spacy.io/api/entityruler

**Describe the solution you'd like**
This would be an annotator called `EntityRuler`, that would be instantiated by loading a local ontology in, let's say, JSON or CSV format.

**Describe alternatives you've considered**
Using spaCy for that, but on Big Data I fear it won't scale.

**Additional context**
No additional context.

**Comment by xegulon** [comment]
You mean, if I have an ontology with 10K classes, I'd need 10K `.txt` files and 10K columns in my output Spark DataFrame?

**Comment by maziyarpanahi** [comment]
I think TextMatcher was designed for the other way around, dozens of categories but each contains thousands of possibilities.

I just noticed that the licensed product might have a similar feature: https://nlp.johnsnowlabs.com/docs/en/licensed_annotators#contextualparser

**Comment by xegulon** [comment]
It seems the contextual parser is a model that takes into account the context of the sentence, statistical properties, etc. 

I am looking for something way simpler that only fetches strict matches (with no context).

**Comment by maziyarpanahi** [comment]
Great, so this can be a new feature that we don't have anywhere. I'll add a member who is good in this rule-based features to see what comes out of this :)

**Comment by xegulon** [comment]
Great, as mentioned in the title of the issue, SpaCy's Entity-Ruler can be a good starting point I think:

https://github.com/explosion/spaCy/blob/master/spacy/pipeline/entityruler.py

**Comment by danilojsl** [comment]
Hi @xegulon, I'm working on `EntityRuler` annotator and I have an alpha version of it. If you want to check this out, please see [this Colab notebook ](https://colab.research.google.com/drive/1xMb7W0WSkt-omJg8NK4zUu-ZESpzPXW6?usp=sharing). We will truly appreciate any feedback on this new feature.

**Comment by xegulon** [comment]
Hi @danilojsl, much thanks for the speed, the nice work and the notebook! 

I've been through the notebook, and something I think could be enhanced is the schema of your JSON/CSV. In addition to `label` and `pattern` keys, it would be great to have an `ID` key (that would reference the entity uniquely), and the ability to have any other key/metadata related to the entity.

Moreover, I think taking into account JSONL format in addition to pure JSON could be interesting for speed (SpaCy people recommend that).

An error I had in the notebook:

![image](https://user-images.githubusercontent.com/74178038/135419501-13082d1c-ace5-4bc8-a9af-314b21de9e0d.png)

Thanks again!

**Comment by maziyarpanahi** [comment]
Thanks @xegulon  for the feedback. I think the `ID` and supporting JSONL format are interesting. 

PS: for the error, he is using a custom-made JAR which you don't have, that is why you get the `JavaPackage` error. I think once it's finalized we can put a custom JAR on public S3 to make the notebook executable for you for the last test before releasing it.
