### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable 

### ISSUE THREAD

**Issue by MaggieX** [JohnSnowLabs/spark-nlp#5991]
Get "TypeError: 'JavaPackage' object is not callable " error whenever trying to call annotators.
Siimlar to issue [#232](https://github.com/JohnSnowLabs/spark-nlp/issues/232)

## Description

```
  document_assembler = DocumentAssembler().setInputCol(input_col).setOutputCol("sentence")
  File "/mnt/a-spark/app/apache-spark/python/lib/pyspark.zip/pyspark/__init__.py", line 110, in wrapper
  File "/usr/local/lib/python3.6/site-packages/sparknlp/base.py", line 388, in __init__
    super(DocumentAssembler, self).__init__(classname="com.johnsnowlabs.nlp.DocumentAssembler")
  File "/mnt/a-spark/app/apache-spark/python/lib/pyspark.zip/pyspark/__init__.py", line 110, in wrapper
  File "/usr/local/lib/python3.6/site-packages/sparknlp/internal.py", line 106, in __init__
    self._java_obj = self._new_java_obj(classname, self.uid)
  File "/mnt/a-spark/app/apache-spark/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 69, in _new_java_obj
 TypeError: 'JavaPackage' object is not callable
```

## Environment

* Spark NLP version `sparknlp.version()`:
* Apache NLP version `spark.version`:
* Java version `java -version`: 11
* Setup and installation (Pypi, Conda, Maven, etc.): Poetry/Pypi
* Running Spark in a Kubernetes container. 

spark-nlp = "3.2.1"

```
spark_session = (
        SparkSession.builder
        .appName(JOB_NAME)
        .master("local[4]")
        .config("spark.driver.memory", "16G")
        .config("spark.driver.maxResultSize", "0") \
        .config("spark.kryoserializer.buffer.max", "2000M")\
        .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.12:3.2.1") \
        .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
        .config("spark.sql.execution.arrow.enabled", "true")
        .enableHiveSupport()
        .getOrCreate())
```
Could you please help? I am stuck on this. It worked well when I run on mac but won't work when running it in the spark in a container. Is there any setup I am missing?

**Comment by maziyarpanahi** [comment]
Hi @MaggieX 

I know you have fixed the Java 8 which should be confirmed by `java -version` in the same terminal you are using Spark NLP. 

9 out of 10 times the `TypeError: 'JavaPackage' object is not callable` error is when the Maven or JAR for Spark NLP is not included in SparkSession. Most of the time users think they are creating a SparkSession, but it's `.getOrCreate`. It means if there is already a SparkSession active it will reuse that and all the new configs including the JAR or the Maven coordinates will be ignored.

I suspect something similar is happening. Could you please explain your setup, where you are, and how you are using PySpark/Spark NLP? (is this Jupyter notebook? Have you tried to use a different environment in your setup for testing? Have you tried the exact same process locally? any more information as to how to reproduce this step by step would be very useful)

**Comment by knjpollard** [comment]
Team, 

There is definitely something not intuitive with your stuff. I may be doing something wrong. Its really nuanced if I am. 

Here's my experience: 
1.  Works on Colab fine, I run a ton of it there. 
2. I also got it working perfectly fine in Databricks ML 8.4. 

**BUT**......it does not wqwork when
1. Installed on my Win10 Laptop
2. Or my Unbuntu Linux Desktop

- I have 3.1.1 and 3.1.2 verifiably running and I used conda for Win10 and pip instructions for Linux. 
- In both cases, I even get the output saying the version of Spark 3.1.1 and SparkNLP version 3.2.2 which are loaded into the notebook sessions. 
- In both cases, it breaks right when you call the pipeline cell. "TypeError: 'JavaPackage' object is not callable." 

What is it that i am doing wrong locally that Colab and Databricks are automagically doing right?

**Comment by knjpollard** [comment]
> Team,
> 
> There is definitely something not intuitive with your stuff. I may be doing something wrong. Its really nuanced if I am.
> 
> Here's my experience:
> 
> 1. Works on Colab fine, I run a ton of it there.
> 2. I also got it working perfectly fine in Databricks ML 8.4.
> 
> **BUT** it does not work when....
> 
> 1. Installed on my Win10 Laptop
> 2. Or my Unbuntu Linux Desktop
> 
> * I have 3.1.1 and 3.1.2 verifiably running and I used conda for Win10 and pip instructions for Linux.
> * In both cases, I even get the output saying the version of Spark 3.1.1 and SparkNLP version 3.2.2 which are loaded into the notebook sessions.
> * In both cases, it breaks right when you call the pipeline cell. "TypeError: 'JavaPackage' object is not callable."
> 
> What is it that i am doing wrong locally that Colab and Databricks are automagically doing right?



UPDATE:

Mystery Solved, and upon reading closer this note states the issue. 

Here's the trick DO NOT under any circumstances set sc or spark prior to this code below. If there is a spark context or session started already or if you set it in a different way than shown you get the "TypeError: 'JavaPackage' object is not callable."

===================Notebook Cell Below=========================
import sparknlp
from pyspark.sql import SparkSession
from sparknlp.pretrained import PretrainedPipeline


#create or get Spark Session
# change this **.master("spark://pi4b5:7077")\** to this **.master("local[*]")\** if your spark is local on a laptop

spark = SparkSession.builder \
    .appName("ner")\
    **.master("spark://pi4b5:7077")\**
    .config("spark.driver.memory","2G")\
    .config("spark.driver.maxResultSize", "1G") \
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.12:3.2.1")\
    .config("spark.kryoserializer.buffer.max", "500m")\
    .getOrCreate()

#spark = sparknlp.start()  # this is just a more simple option than above when parameters are not needed
print("sparknlp version", sparknlp.version(), "sparkversion", spark.version)
======================End Cell Code===================================

**Comment by maziyarpanahi** [comment]
Thanks @knjpollard for updating your issue.

The `TypeError: 'JavaPackage' object is not callable` error is always regarding the actual Spark NLP core (Maven or JAR via `spark.jars.packages` or `spark.jars`) missing in the current SparkSession. By missing, it doesn't mean the user hasn't used it via a custom SparkSession.builder or `sparknlp.start()` function, it's always about SparkSession already exists and what the user has used was ignored due to `.getOrCreate`. (it will reuse the existing SparkSession so it will ignore all the new confs)

Thanks again for looking into this and updating this issue.
