### ISSUE TITLE
Velocity of this project

### ISSUE THREAD

**Issue by javadba** [JohnSnowLabs/spark-nlp#60]
This project was featured as a blog on DataBricks site on October 19. Since then the project was pushed to github and 24 issues logged. Of these *five* have been closed as of December 13: and those were only between October 21 and Nov 5.  So there has been visible activity for about two weeks out of the project's 8 weeks of visible lifetime.   

What is the story about project maintenance and improvement here - including the long list of "want to haves" on the README?  Most OSS projects die rather quickly due to neglect: what evidence can we have this will not be one of those?

**Comment by saifjsl** [comment]
Thank you @javadba for the honest feedback. It is true we've been lagging behind but it is also because we are catching up and synchronizing priorities. We are actively working on this project and shall see further activity towards the beginning of the new year for sure.

**Comment by javadba** [comment]
Thanks - it would be great to have better nlp related algos in spark.
