### ISSUE TITLE
Broken `DistilBertForTokenClassification` and `LongFormer` models

### ISSUE THREAD

**Issue by C-K-Loan** [JohnSnowLabs/spark-nlp#6046]
## Description

I found multiple broken models from the Spark NLP 3.2.0 release which fall in 3 categories.
I checked all other models from 3.2.0, they are fine if there are not mentioned here.

## Bug 1 

According to the Release Notes, Modelhub page and Modelname  `distilbert_base_token_classifier_conll03`  should be a Distilbert model.
But Loading it via Distilbert annotator class throws
```
: java.lang.ClassCastException: com.johnsnowlabs.nlp.annotators.classifier.dl.BertForTokenClassification cannot be cast to com.johnsnowlabs.nlp.annotators.classifier.dl.DistilBertForTokenClassification
```

When loading via `BertForTokenClassification` there is no exception thrown.
It looks like there is a `BertForTokenClassification` stored in the S3 bucket for `distilbert_base_token_classifier_conll03`.

### Other Models in S3 with the same error
The same error mentioned above seems to apply to multiple distilbert models.
TokenBert models are stored, but it should be distilbert for the following :

- `distilbert_base_token_classifier_ontonotes`
  -`distilbert_token_classifier_persian_ner`
- `distilbert_base_token_classifier_conll03`

### Reproduce the Error

This should work but throws above mentioned exception
```python
from sparknlp.annotator import *
b = DistilBertForTokenClassification.pretrained('distilbert_base_token_classifier_conll03') \
    .setInputCols("sentence", "token") \
    .setOutputCol("tokendistilbert")

```

this should not work but it does
```python
from sparknlp.annotator import BertForTokenClassification
b = BertForTokenClassification.pretrained('distilbert_base_token_classifier_conll03') \
    .setInputCols("sentence", "token") \
    .setOutputCol("tokendistilbert")
```

## Bug2

```python
b = DistilBertForTokenClassification.pretrained('distilbert_base_token_classifier_few_nerd') \
    .setInputCols("sentence", "token") \
    .setOutputCol("tokendistilbert")
```
throws
```
: java.io.FileNotFoundException: File file:/root/cache_pretrained/distilbert_base_token_classifier_few_nerd_en_3.2.0_2.4_1628435975886/distilbert_classification_tensorflow does not exist
```

## Bug3
```python
b = LongformerEmbeddings.pretrained('ner_conll_longformer_base_4096')
```
throws
```
Caused by: org.apache.hadoop.fs.ChecksumException: Checksum error: file:/root/cache_pretrained/ner_conll_longformer_base_4096_en_3.2.0_2.4_1628081396660/metadata/part-00000 at 0 exp: -1986108792 got: 1077450543
```

## Notebook to reproduce error
https://colab.research.google.com/drive/16pYE-SxRqLNjDSIAXp7q-TvYCa7VWwPh?usp=sharing

**Comment by maziyarpanahi** [comment]
Hi @C-K-Loan 

Yes, I am aware of these modes being saved with the wrong class. I will fix them. Thanks for listing them here 👍🏼

**Comment by maziyarpanahi** [comment]
@C-K-Loan 

I have fixed and re-uploaded these models:

* distilbert_base_token_classifier_ontonotes model
* distilbert_base_token_classifier_conll03 model
* distilbert_base_token_classifier_few_nerd model
* distilbert_token_classifier_persian_ner model
* ner_conll_longformer_base_4096 model

A quick note, `ner_conll_longformer_base_4096` is for `NerDLModel` and not `Longformer`. But it required to be fixed.
