### ISSUE TITLE
explain_document_dl fails with sparknlp 3.0.3

### ISSUE THREAD

**Issue by drbonis** [JohnSnowLabs/spark-nlp#6052]
When downloading the explain_document_dl pretrained model from sparknlp 3.0.3 it doesnt work.

## Description

I am using sparknlp 3.0.3 (installed from pypi. When trying to use the pretrained model explain_document_dl I am getting some errors probably related with that pretrained model being trained with a new version of PretrainedPipeline().

In particular the version in cache_pretrained is explain_document_dl_en_3.0.0_3.0_1626763223904 

## Current Behavior
It is giving errors like:

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline. : java.util.NoSuchElementException: Param includeAllConfidenceScores does not exist.

Py4JJavaError: An error occurred while calling o499.annotateJava.
: java.lang.Exception: feature Number of words in the dictionary is not set (this happens when trying from sparknlp version 3.1.2)

## Steps to Reproduce

1.
2.
3.
4.

## Context
Use that pretrained model.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.0.3
* Apache NLP version `spark.version`: 3.0.2
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.): Pypi
* Operating System and version: Ubuntu 18.04
* Link to your project (if any):

**Comment by danilojsl** [comment]
Hi @drbonis, thanks for reporting it. Could you please retry it with both versions and let us know if it is working now.
