### ISSUE TITLE
PerceptronModel freezes in some very specific cases.

### ISSUE THREAD

**Issue by drbonis** [JohnSnowLabs/spark-nlp#6061]
## Description

When defining this pipeline:

    docass = DocumentAssembler()\
        .setInputCol("text")\
        .setOutputCol("document")

    sentdl = SentenceDetectorDLModel\
        .pretrained("sentence_detector_dl", "en") \
        .setInputCols(["document"]) \
        .setOutputCol("sentence")

    tokenizer = Tokenizer() \
        .setInputCols(["sentence"]) \
        .setOutputCol("token") \
        .setSplitChars(['-']) \
        .setContextChars(['(', ')', '?', '!']) \
        .setExceptions([]) \
        .setSplitPattern("'") \
        .setMaxLength(99999) \
        .setCaseSensitiveExceptions(False)

    pos = PerceptronModel.pretrained("pos_anc", 'en')\
            .setInputCols("sentence", "token")\
            .setOutputCol("pos")

    pipeline2 = Pipeline(stages=[
        docass,
        sentdl,
        tokenizer,
        pos
    ])
    model2 = pipeline2.fit(spark.createDataFrame([[""]]).toDF("text"))
    lp2 = LightPipeline(model2)

It works well but when trying to annotate this sentence it freezes:

lp2.fullAnnotate("Exercise induced PH was related to higher levels of creatinine ( p<0.05), increased left atrial volume ( p<0.05 ) and right ventricular diastolic area ( p<0.05), larger E/Em waves ratio derived from spectral and tissue Doppler ( p<0.05), and higher TRV at rest ( p<0.005).")

## Expected Behavior
To return POS tag of the sentence.

## Current Behavior
It freezes (not for other sentences).

## Context
To get the pos tags.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.1.0
* Apache NLP version `spark.version`: 3.0.1
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.): pypi
* Operating System and version: Ubuntu 18.04
* Link to your project (if any):

**Comment by danilojsl** [comment]
Hi @drbonis. I tried to reproduce this error on [this](https://colab.research.google.com/drive/1xMb7W0WSkt-omJg8NK4zUu-ZESpzPXW6?usp=sharing) Google Colab notebook, but it is working. 
I'm using the same spark and sparknlp version of your environment. Could you please take a look and see if you can make it fail so I can debug it.

**Comment by drbonis** [comment]
Hi, I also tried to reproduce, now looks like is working. I think we can close it now.
