### ISSUE TITLE
Pretrained tokenizer model not available to download

### ISSUE THREAD

**Issue by ArnaudFnr** [JohnSnowLabs/spark-nlp#608]
I would like to use the Tokenizer pretrained model as I did with other transformers. However, I can't neither download it from the code nor find it on the public web page. I think it should be present because the method `pretrained()` is defined with default values.

## Description
I can't find the Tokenizer model online, in particular on this web page : https://nlp.johnsnowlabs.com/docs/en/models. However, it is not present in the list. 

I also tried without success to download the model from the code using `pretrained()` method. I have the following error : 
`java.lang.IllegalArgumentException: requirement failed: Was not found appropriate resource to download for request: ResourceRequest(token_rules,Some(en),public/models,2.1.0,2.0.2) with downloader: com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader@2bfb583b
`

I think the model should be present because in the [online documentation](https://nlp.johnsnowlabs.com/docs/en/annotators#how-to-read-this-section) it says that pretrained models can be loaded for annotators, including Tokenizer.

## Possible Solution
The model might have not been uploaded on the S3 server, or the default values are incorrect for this model.

## Context
I'm trying to use some of the Pipeline transformers of SparkNLP inside a built-in Pipeline, in Java.

## Your Environment
SDK : Java 8
Project version : com.johnsnowlabs.nlp:spark-nlp_2.11:2.1.0

Thanks in advance.
Arnaud

**Comment by maziyarpanahi** [comment]
Thanks for reporting this. I don’t think we have released any pre-trained models for Tokenizer. I will look and release some for our languages, however, you would still not be able to download them. Our models/pipelines are for Apache Spark 2.4.x so you need to update your Apache Spark to 2.4.3 :)

**Comment by maziyarpanahi** [comment]
I just checked we do have it for English so the issue for you is not having Apache Spark 2.4.x and it won’t be able to find any of our models/pipelines.
