### ISSUE TITLE
Regex in Normalizer is not working for Pyspark

### ISSUE THREAD

**Issue by alinapetukhova** [JohnSnowLabs/spark-nlp#611]
Regex in Normalizer is not working for Pyspark

## Description
Specifying custom normalization cleanup pattern is not working in Normalizer.

## Expected Behavior
Ability to set up custom regex pattern for Normalizer

## Current Behavior
`normalizer = Normalizer().setInputCols(["token"]).setOutputCol("normalized")
.setCleanupPatterns("[^A-Za-z]")`

giving an error **Invalid param value given for param cleanupPatterns. Could not convert [^A-Za-z] to list of strings**

## Context
Need to clean short words (less, then 3 symbols)

## Your Environment

* Python with pyspark
* Version used: Spark-nlp 2.1.0
* Operating System and version (desktop or mobile): Ubuntu 18.04

**Comment by maziyarpanahi** [comment]
Hi @alinapetukhova 

As it states in the error, the type in Scala is `Array[String]` and `toListString`.

Here is the example that works without any issue:

```scala
val normalizer = new Normalizer()
      .setInputCols("token")
      .setOutputCol("normalized")
      .setCleanupPatterns(Array("[^A-Za-z]"))
```
