### ISSUE TITLE
NerConverter crops first 2 chars of labels when used with DistilBertForTokenClassification

### ISSUE THREAD

**Issue by drbonis** [JohnSnowLabs/spark-nlp#6141]
NerConverter crops first 2 chars of labels when used with DistilBertForTokenClassification

## Description

This happends when using 'distilbert_base_token_classifier_few_nerd' followed by NerConverter.

tokenClassifier = DistilBertForTokenClassification \
      .pretrained('distilbert_base_token_classifier_few_nerd', 'en') \
      .setInputCols(['token', 'document']) \
      .setOutputCol('ner') \
      .setCaseSensitive(True) \
      .setMaxSentenceLength(512)

ner_converter = NerConverter().setInputCols(["document","token","ner"]).setOutputCol("ner_chunk")

## Expected Behavior

NerConverter should create the labels like: product-software, person-other, etc.

## Current Behavior

Instead the NerConverter is missing the first 2 chars of the label: oduct-software, rson-other, etc.

+---------------------------------------------------------------------+--------------+
|chunk                                                                |label         |
+---------------------------------------------------------------------+--------------+
|Tara Sweitzer                                                        |oduct-software|
|EOL                                                                  |oduct-software|
|Phillip Allen                                                        |rson-other    |
|Mary                                                                 |rson-other    |
+---------------------------------------------------------------------+--------------+

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.2.2
* Apache NLP version `spark.version`: 3.0.2
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.): pip
* Operating System and version: Ubuntu
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Thanks @drbonis 

You shouldn't use `NerConverter` for all the NER models. Only the ones that are IOB and IOB2 (B- or I-). As you can see this model doesn't have that and NerConverter cannot be used here. (it only supports IOB/IOB2 format)

In examples, we didn't use NerConverter: https://nlp.johnsnowlabs.com/2021/08/08/distilbert_base_token_classifier_few_nerd_en.html
