### ISSUE TITLE
Py4JJavaError  - When using MedicalNerModel and SentenceEntityResolverModel

### ISSUE THREAD

**Issue by sarathsurpur** [JohnSnowLabs/spark-nlp#6173]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version `sparknlp.version()`:
* Apache NLP version `spark.version`:
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
@sarathsurpur This repo only supports public and open-source features. What you are using is licensed (we have no info), please either contact them directly via email or on Slack you can ask them inside the `#healthcare` channel.
