### ISSUE TITLE
Cosine Similarity

### ISSUE THREAD

**Issue by MathieuLAllier** [JohnSnowLabs/spark-nlp#621]
## Description

It says on this page https://databricks.com/blog/2017/10/19/introducing-natural-language-processing-library-apache-spark.html

That spark-nlp comes with a distributed cosine similarity function out-of-the-box. I have been trying to find it in the repo but couldn't. 

Is this a mistake ? how would you suggest to apply cosine similarity with spark-nlp embeddings ?

Thanks

**Comment by maziyarpanahi** [comment]
I think they meany Word Embeddings (GloVe, FastText, and Word2Vec) and recently BertEmbeddings. I don’t believe there is a straightforward annotator that just gives you cosine similarity. We use word embeddings n training and prediction of NER.
You may want to extract the embeddings and apply any Spark ML or third-party algorithm you want to get cosine similarities.

**Comment by MathieuLAllier** [comment]
I see, thanks for the quick answer !
