### ISSUE TITLE
ner_log file generation issue on Databricks

### ISSUE THREAD

**Issue by muhammetsnts** [JohnSnowLabs/spark-nlp#6213]
## Description

When we trained a NER model by using `NerDLApproach()`, ner_log file wasn't generated, but we could get metrics from the trained model.

![image](https://user-images.githubusercontent.com/76607915/135728597-9a4eb5ef-1254-4ed6-afbf-262b04a56ccc.png)
![image](https://user-images.githubusercontent.com/76607915/135728623-60c2d031-e185-47da-b2c3-20fc0f7378d9.png)
![image](https://user-images.githubusercontent.com/76607915/135728630-45e167ec-3790-4342-b6c3-11a8a9a77579.png)
![image](https://user-images.githubusercontent.com/76607915/135728639-7c5ed4af-ee85-4741-82f6-2e89be9b702d.png)
![image](https://user-images.githubusercontent.com/76607915/135728777-ccce2e53-2c4d-4fb3-96f2-ef5591576beb.png)

## Expected Behavior

generation of ner_log file
## Current Behavior

not able to generate ner_log file
## Steps to Reproduce

1. You can use this notebook for reproducing the issue : [Training and Reusing Named Entity Recognition Models.ipynb](https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/databricks_notebooks/3.%20Training%20and%20Reusing%20Named%20Entity%20Recognition%20Models.ipynb)

## Context

Trying to train NER model.
## Your Environment

* Spark NLP version `sparknlp.version()`: 3.2.3
* Apache NLP version `spark.version`: 3.1.0
* Java version `java -version`: 
* Setup and installation (Pypi, Conda, Maven, etc.): com.johnsnowlabs.nlp:spark-nlp_2.12:3.2.3
* Operating System and version: AWS Databricks
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
We are now supporting writing logs on DBFS fileSystem, you need to:
- always use a full path, never assume your `ner_logs` go where you think it goes
- since you are in a cluster environment, the correct path the file is saved is `dbfs:/databricks/driver/ner_logs` not `file:/`
