### ISSUE TITLE
Error while using Tokenizer in Jupyter with Scala

### ISSUE THREAD

**Issue by nishant-ai** [JohnSnowLabs/spark-nlp#630]
I am using using Spark-NLP 2.2.1 with Spark 2.4.0 and Scala 2.11.12.
I am trying to transform the Document column generated by DocumentAssembler into the Token format by using Tokenizer.
`val tokenizer = new Tokenizer().setInputCols(Array("annotated-text")).setOutputCol("words")
tokenizer.fit(annotatedData).transform(annotatedData).show`
But I'm getting this error : 

> 2019-09-10 20:04:05 ERROR Executor:91 - Exception in task 0.0 in stage 28.0 (TID 41)
> org.apache.spark.SparkException: Failed to execute user defined function($anonfun$dfAnnotate$1: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>,sentence_embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>,sentence_embeddings:array<float>>>)
> 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
> 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
> 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$11$$anon$1.hasNext(WholeStageCodegenExec.scala:619)
> 	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
> 	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:121)
> 	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.ClassCastException: com.johnsnowlabs.nlp.util.regex.RuleFactory cannot be cast to com.johnsnowlabs.nlp.util.regex.RuleFactory
> 	at com.johnsnowlabs.nlp.annotators.TokenizerModel$$anonfun$tag$1$$anonfun$3.apply(TokenizerModel.scala:89)
> 	at com.johnsnowlabs.nlp.annotators.TokenizerModel$$anonfun$tag$1$$anonfun$3.apply(TokenizerModel.scala:75)
> 	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
> 	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
> 	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
> 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
> 	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
> 	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
> 	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
> 	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
> 	at scala.collection.AbstractIterator.to(Iterator.scala:1334)
> 	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
> 	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1334)
> 	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
> 	at scala.collection.AbstractIterator.toArray(Iterator.scala:1334)
> 	at com.johnsnowlabs.nlp.annotators.TokenizerModel$$anonfun$tag$1.apply(TokenizerModel.scala:108)
> 	at com.johnsnowlabs.nlp.annotators.TokenizerModel$$anonfun$tag$1.apply(TokenizerModel.scala:66)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
> 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
> 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
> 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
> 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
> 	at com.johnsnowlabs.nlp.annotators.TokenizerModel.tag(TokenizerModel.scala:66)
> 	at com.johnsnowlabs.nlp.annotators.TokenizerModel.annotate(TokenizerModel.scala:116)
> 	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:35)
> 	at com.johnsnowlabs.nlp.AnnotatorModel$$anonfun$dfAnnotate$1.apply(AnnotatorModel.scala:34)
> 	... 21 more

I have no clue why this is happening, please help me with the same. 
Thanks

**Comment by nishant-ai** [comment]
I just used the DocumentAssembler on a String type column before using the Tokenizer.
It's like this : 

```
val documentAssembler = new DocumentAssembler().setInputCol("text").setOutputCol("annotated-text")
var annotatedData = documentAssembler.transform(data).select("productid","text","annotated-text")
val tokenizer = new Tokenizer().setInputCols(Array("annotated-text")).setOutputCol("words")
tokenizer.fit(annotatedData).transform(annotatedData).show
```
I guess there is some issue with the Tokenizer.

**Comment by maziyarpanahi** [comment]
Your code is very fine. Let’s talk about your Apache Spark setup, where it is, how do you start it, is it YARN, client or cluster mode, etc? And is it possible to test this with Apache Spark 2.4.3 version?

**Comment by nishant-ai** [comment]
I am running it on a S3 single client mode. And i've tested it on both 2.4.0 and 2.4.3 versions of Apache Spark. I'm getting the same error with both.

**Comment by maziyarpanahi** [comment]
Is there any chance you can share few sentences of your text? Likeat least one document so I can reproduce this. Many thanks.

**Comment by nishant-ai** [comment]
The first two rows of my Dataframe before using the DocumentAssembler are : 

```
+--------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|productid           |text                                                                                                                                                                                                                                                                                  |
+--------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|440827719_black     |printed shirt dress stylised stylised three-quarters leafprint Falling to a flattering mini length, this shirt dress featuring an all-over print and a shift silhouette uses the formula of glamour to illuminate the space with grace and style single-button cuffs mini collar rayon|
|460040075_offwhite  |highlow shift dress shift metallic zip with button closure shift sleeveless solid Featuring side slits, a high-neck, and cutout at the back, this chic dress redefines classic style designed and made in london attheknee high insert pocket polyester                               |
```
Really sorry for the late response.

**Comment by maziyarpanahi** [comment]
I'll do some tests even though everything looks fine to me. The last thing is to see if you can reproduce the error locally, or try using Apache Spark `2.4.3`.

**Comment by maziyarpanahi** [comment]
Can you produce the error locally? I want to exclude the S3 environment being an issue here.

**Comment by nishant-ai** [comment]
Yeah i can produce the error locally. And one question, in the tokenizer, what's the TargetPattern pattern set to by default ? 
When i don't set it and use the default one, i get the error as mentioned above and when i explicitly set it as "[\\s]+"  , I don't get the error but the column returned by the tokenizer is simply [], like null.
How can this be explained ?

**Comment by maziyarpanahi** [comment]
How do you run it locally? Is it in spark-shell or Zeppelin?

**Comment by maziyarpanahi** [comment]
The reason I am asking is that I’ve seen this error when Scala is used in Jupyter, it has some bad encoding for Scala. Could you please test it in spark-shell if you haven’t already?

**Comment by nishant-ai** [comment]
Yeah I am running it in Jupyter only by using the spylon-kernel. 
Alright, I will test it in the spark-shell and let you know.

**Comment by nishant-ai** [comment]
It actually does work fine in the spark-shell. Thank you !
Do you have any idea if this issue exists just with the spylon-kernel or with Apache Toree as well ?

**Comment by maziyarpanahi** [comment]
Not sure, but I remember the person changed to Zeppelin to work with Scala as Jupyter had many issues with Scala.

I’m glad the issue has been resolved.

**Comment by nishant-ai** [comment]
Okay, thanks again !
