### ISSUE TITLE
Spark v3.2.0 compatibility issue

### ISSUE THREAD

**Issue by muhammetsnts** [JohnSnowLabs/spark-nlp#6327]
## Description

When we want to use `sparknlp` with `spark` v3.2.0, it gives error. Everything is fine with `spark ` v3.1.2.

## Expected Behavior

To be able to run spark-nlp components.
## Current Behavior

Gives error.
![Screenshot_1](https://user-images.githubusercontent.com/76607915/137996667-54297307-34d6-4696-8976-7912389eb7cf.png)
 
![Screenshot_2](https://user-images.githubusercontent.com/76607915/137996675-63e1e206-1a28-432d-ac44-5590577d6367.png)

## Steps to Reproduce

! pip install pyspark spark-nlp

## Context

Not able to run spark-nlp components.
## Your Environment

* Spark NLP version `sparknlp.version()`: v3.3.1, 3.3.0, 3.2.3
* Apache NLP version `spark.version`: v3.2.0
* Java version `java -version`: 
* Setup and installation (Pypi, Conda, Maven, etc.): pip install pyspark spark-nlp
* Operating System and version: Google Colab 
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,

Spark NLP is not yet compatible with Apache Spark 3.2.0 nor Scala 2.13:

- https://github.com/JohnSnowLabs/spark-nlp#apache-spark-support
- https://github.com/JohnSnowLabs/spark-nlp#scala-and-python-support
