### ISSUE TITLE
Improve CoNLL reader to read large datasets

### ISSUE THREAD

**Issue by ethnhll** [JohnSnowLabs/spark-nlp#6331]
**Is your feature request related to a problem? Please describe.**
_We are attempting to load a directory of CoNLL files totalling 9000+ files and 400+MB using `CoNLL().readDataset(spark, dataset)`, however this fails with OOM exceptions even on a driver with 24GB of RAM available. The proposed workaround to be able to load this dataset all at once for training is the following:_

> [R]ead the files one by one, and then write as parquet, and then read [all] at once

**Describe the solution you'd like**
_I would like to be able to avoid reading in individual files into a dataframe, writing the dataframes to parquet, then re-reading those files back into a dataframe. This approach feels more like a workaround against the spirit of what the CoNLL reader should be able to do. It would be wonderful for the reader to have some extra params, or methods on the `CoNLL` class that allow for efficiently loading larger CoNLL training sets._

**Comment by ethnhll** [comment]
Is there any path forward for reading in lots of CoNLL text files and converting to parquet, quickly while a change to the CoNLL reader is made?

**Comment by maziyarpanahi** [comment]
Hi @ethnhll 

At the moment this is the only way to have multiple conll files inside CoNLL() class, but we are working on optimizing that class as much as possible to be faster with less memory consumption for larger files, and also see if we can add an ability to read multiple files from a directory instead of 1 at a time.

**Comment by albertoandreottiATgmail** [comment]
@ethnhll , @maziyarpanahi  we have a candidate implementation in healthcare library, will share with Ethan soon.

**Comment by amir1m** [comment]
@albertoandreottiATgmail 
> @ethnhll , @maziyarpanahi we have a candidate implementation in healthcare library, will share with Ethan soon.

Could you please share the implementation build/version details on how we can use it?

**Comment by maziyarpanahi** [comment]
@amir1m it's been already released: https://github.com/JohnSnowLabs/spark-nlp/releases/tag/3.3.3

PR with an example: https://github.com/JohnSnowLabs/spark-nlp/pull/6482
