### ISSUE TITLE
Predicting efficently with MultiClassifierDLModel()

### ISSUE THREAD

**Issue by Dirkster99** [JohnSnowLabs/spark-nlp#6364]
**Link to doc page in question (if any):**
[Docu Page for MultiClassifierDLModel](https://nlp.johnsnowlabs.com/api/python/reference/autosummary/sparknlp.annotator.MultiClassifierDLModel.html)

**Name of the Spark NLP feature whose docs need improvement:**
- MultiClassifierDLModel

**What you think the docs should say:**
I am trying to make multilabel classification predictions using the pipeline shown in the [Docu Page for the MultiClassifierDLModel](https://nlp.johnsnowlabs.com/api/python/reference/autosummary/sparknlp.annotator.MultiClassifierDLModel.html) using the this [UniversalSentence Encoder](https://nlp.johnsnowlabs.com/2021/05/06/tfhub_use_multi_lg_xx.html).

As a side note I have trained and saved a model using this pipeline:
```py
import sparknlp
from sparknlp.base import *
from sparknlp.annotator import *
from pyspark.ml import Pipeline

documentAssembler = DocumentAssembler() \
    .setInputCol("text") \
    .setOutputCol("document") \
    .setCleanupMode("shrink")

# Download Source: https://nlp.johnsnowlabs.com/2021/05/06/tfhub_use_multi_lg_xx.html
remoteUnsentEncModelPath = 'gs://lab-dev/notebooks/jupyter/SparkNLP/SentenceEmbedding/tfhub_use_multi_lg_xx_3.0.0_3.0_1620294638956/'

embeddings = UniversalSentenceEncoder.load(remoteUnsentEncModelPath) \
    .setInputCols("document") \
    .setOutputCol("embeddings")

docClassifier = MultiClassifierDLApproach() \
    .setInputCols("embeddings") \
    .setOutputCol("category") \
    .setLabelColumn("labels") \
    .setBatchSize(128) \
    .setMaxEpochs(10) \
    .setLr(1e-3) \
    .setThreshold(0.5) \
    .setValidationSplit(0.1) \
    .setEnableOutputLogs(True)

pipeline = Pipeline().setStages([
    documentAssembler,
    embeddings,
    docClassifier
])
```

Now when I try to make predictions with this pipeline:
```py
import sparknlp
from sparknlp.base import *
from sparknlp.annotator import *
from pyspark.ml import Pipeline

documentAssembler = DocumentAssembler() \
    .setInputCol("text") \
    .setOutputCol("document") \
    .setCleanupMode("shrink")

# Download Source: https://nlp.johnsnowlabs.com/2021/05/06/tfhub_use_multi_lg_xx.html
remoteUnsentEncModelPath = 'gs://lab-dev/notebooks/jupyter/SparkNLP/SentenceEmbedding/tfhub_use_multi_lg_xx_3.0.0_3.0_1620294638956/'
embeddings = UniversalSentenceEncoder.load(remoteUnsentEncModelPath) \
    .setInputCols("document") \
    .setOutputCol("embeddings")

remoteClassifierModelPath = 'gs://lab-dev/notebooks/jupyter/data/model/V1/'
docClassifier = MultiClassifierDLModel.load(remoteClassifierModelPath) \
    .setInputCols("embeddings") \
    .setOutputCol("category")

pipeline = Pipeline().setStages([
    documentAssembler,
    embeddings,
    docClassifier
])
```
I am facing a performance issue I cannot seem to get around using more worker nodes. What I am traing to accomplish is to make predictions on about 953K rows of text with  an average length of 6 words. I am using the following code for the prediction:

```py
resultDF = pipeline.fit(testDF).transform(testDF)
resultDF.select('RowId','DocId','SentId', 'category', 'text').explain()
```
**Outputs:**
```
== Physical Plan ==
*(1) Project [RowId#11L, DocId#10, SentId#12L, UDF(array(UDF(array(UDF(sentence#14))))) AS category#92, sentence#14 AS text#20]
+- FileScan json [DocId#10,RowId#11L,SentId#12L,sentence#14] Batched: false, DataFilters: [], Format: JSON, Location: InMemoryFileIndex[gs://lab-dev/notebooks/jupyter/KOMMENTAR_..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<DocId:string,RowId:bigint,SentId:bigint,sentence:string>

```

```py
%%time

resultDF.select('RowId','DocId','SentId', 'category', 'text').orderBy('RowId') \
       .coalesce(1).write.format('json').save(baseDataPath + 'V1_Sentences_RowId_TopicsMatrix_prediction.json')
```

I have 23 categories and the **anonymized** dataframe output for 1 row looks like this:
`|I am having an unresolved Spark NLP problem |[{category, 0, 46, Class20, {Class1 -> 1.2523003E-6, Class2 -> 3.654007E-7, Class3 -> 1.2571637E-9, Class4 -> 1.2918437E-5, Class5 -> 2.3385151E-7, Class6 -> 1.6361493E-8, Class7 -> 1.2714304E-8, Class8 -> 2.9660441E-5, Class9 -> 1.6520813E-6, Class10 -> 5.1388514E-7, Class11 -> 0.99992454, Class12 -> 6.938853E-6, Class13 -> 5.5197853E-7, Class14 -> 9.956975E-7, Class15 -> 1.5563526E-5, Class16 -> 1.1050588E-9, Class17 -> 3.4834682E-10, Class18 -> 5.1273254E-8, Class19 -> 2.540965E-7, Class20 -> 0.8740393, Class21 -> 1.6739254E-5, Class22 -> 4.621199E-7, Class23 -> 9.403253E-7, sentence -> 0}, []}, {category, 0, 46, Class11, {Class1 -> 1.2523003E-6, Class2 -> 3.654007E-7, Class3 -> 1.2571637E-9, Class4 -> 1.2918437E-5, Class5 -> 2.3385151E-7, Class6 -> 1.6361493E-8, Class7 -> 1.2714304E-8, Class8 -> 2.9660441E-5, Class9 -> 1.6520813E-6, Class10 -> 5.1388514E-7, Class11 -> 0.99992454, Class12 -> 6.938853E-6, Class13 -> 5.5197853E-7, Class14 -> 9.956975E-7, Class15 -> 1.5563526E-5, Class16 -> 1.1050588E-9, Class17 -> 3.4834682E-10, Class18 -> 5.1273254E-8, Class19 -> 2.540965E-7, Class20 -> 0.8740393, Class21 -> 1.6739254E-5, Class22 -> 4.621199E-7, Class23 -> 9.403253E-7, sentence -> 0}, []}]             |`

Now my issue is that I want to classify about **953K rows of text** with a similar content as the above example and I found through experiments with a limited number of rows that it will take me about 8 hours to perform this with 1 Master Node and GPU support. I have experimented with other cluster sizes (eg. 2 workers + GPU or 4 worker + GPU) and the processing time remained about the same no matter how big or small I've setup the DataProc cluster.

- time for saving 1000 rows is about 33.4 seconds (0,55 min)
- time for saving 10000 rows is about 306 seconds (5 min  sec) 

So, I am wondering if there is something silly I am doing wrong here and whether there is a simple way (using a Finisher?) to get the result saved/post-processed in a more efficient way?

**Comment by maziyarpanahi** [comment]
Hi,

When you do `.coalesce(1)` you practically bringing all the data from executors into the Driver. If you don't see OOM (which is totally possible) you see performance of having only 1 machine. 

Please use the following:

```
resultDF.select('RowId','DocId','SentId', 'category', 'text').orderBy('RowId') \
       .write.format('parquet').save(baseDataPath + 'V1_Sentences_RowId_TopicsMatrix_prediction.json')
```
- This way it will save the data in a distributed way (you can keep adding more executors and this will adjust automatically)
- If you must have it in JSON or CSV, you can read back the saved data (computed in parallel/distributed way) via spark.read.parquet(PATH), and then you can use `.coalesce(1)` with format of CSV or JSON. (this way still brings the data into the Driver memory, but at least there is no computations involved, just moving data and writing it into the disk)
- I would also test CPU only to have more cores = more parallel tasks. Both `MultiClassifierDLModel` and `UniversalSentenceEncoder` are not part of bathAnnotate which use the batchSize and feed more data into the GPU. So you may see a better performance on CPU. (we will adapt these two annotators with batchAnnotate soon to have higher throughput on GPU)

**Comment by Dirkster99** [comment]
Hi, thanks for the tips - I'll try using a parquet file as intermediate step and see if this improves things with multiple workers.

I only opted to save as JSON because the above array would not be savable as CSV. In the end, I'd like to save the result with the input columns (RowId, Text) and the predicted columns (Class1, Class2, ..., Class23) where Class_n contains the prediction value between 0 and 1. So, one row of the resulting dataframe would look like this:

```
RowId|Text                    |Class1 | Class2 | ..., |Class23
------+-----------------------+-------+--------+ ...  +-------
1     | I like Spark NLP      |  0.67 |  0.99  | ...  | 0.75
```

Is there a standard way to unpack the above array of class dictionary entries into rows (eg using a `Finisher`) or should I rather try to find a solution with `F.explode()` and `F.arrays_zip()`, etc...?

**Comment by maziyarpanahi** [comment]
You are welcome. You can use `Finisher()` that can convert the `.result` into array of results. https://nlp.johnsnowlabs.com/docs/en/annotators#finisher

For that custom DataFrame with each class as a column, the probabilities can be extracted from the `.metadata` but the rest should be done with a combination of UDF/explode+arrays_zip in PySpark itself.

**Comment by Dirkster99** [comment]
I found a solution to unpack the category array in the way I was looking for and it appears to be very fast even when using only 2 worker nodes :-) I post it below in case someone comes across the thread and is also wondering how the output of the `MultiClassifierDLModel()` could be post-processed.

I have only one more question on this subject. Is there any way to scale the training phase of the `MultiClassifierDLModel()`
out to more than 1 worker nodes or is this currently limited to one node only (just asking because I am not sure and my last training on about 250K text elements fed in from a CSV file took about 8 hours with GPU support and training data size is still increasing).

# Workflow to Unpack Category Array into Seperate Columns
```py
df.select('Id', F.explode(F.arrays_zip("category.result", "category.metadata")).alias("entities")).printSchema()
```

**Output**:
```
root
 |-- Id: string (nullable = true)
 |-- entities: struct (nullable = false)
 |    |-- 0: string (nullable = true)
 |    |-- 1: struct (nullable = true)
 |    |    |-- Class1: string (nullable = true)
 |    |    |-- Class2: string (nullable = true)
 |    |    |-- Class3: string (nullable = true)
 |    |    |-- Class4: string (nullable = true)
 |    |    |-- Class5: string (nullable = true)
 |    |    |-- Class6: string (nullable = true)
 |    |    |-- Class7: string (nullable = true)
 |    |    |-- Class8: string (nullable = true)
 |    |    |-- Class9: string (nullable = true)
 |    |    |-- Class10: string (nullable = true)
 |    |    |-- Class11: string (nullable = true)
 |    |    |-- Class12: string (nullable = true)
 |    |    |-- Class13: string (nullable = true)
 |    |    |-- Class14: string (nullable = true)
 |    |    |-- Class15: string (nullable = true)
 |    |    |-- Class16: string (nullable = true)
 |    |    |-- Class17: string (nullable = true)
 ...

 |    |    |-- Class21: string (nullable = true)
 |    |    |-- Class22: string (nullable = true)
 |    |    |-- Class23: string (nullable = true)
 |    |    |-- sentence: string (nullable = true)
```

```py
result = df.select('Id', F.explode(F.arrays_zip("category.result", "category.metadata")).alias("entities")) \
           .select('Id', F.expr("entities['0']").alias("class") \
                 , F.expr("entities['1']['Class1']").alias("Class1") \
                 , F.expr("entities['1']['Class2']").alias("Class2")
                 , F.expr("entities['1']['Class3']").alias("Class3")
                 , F.expr("entities['1']['Class4']").alias("Class4")
                 , F.expr("entities['1']['Class5']").alias("Class5")
                 , F.expr("entities['1']['Class6']").alias("Class6")
                 , F.expr("entities['1']['Class7']").alias("Class7")
                 , F.expr("entities['1']['Class8']").alias("Class8")
                 , F.expr("entities['1']['Class9']").alias("Class9")
                 , F.expr("entities['1']['Class10']").alias("Class10")
                 , F.expr("entities['1']['Class11']").alias("Class11")
                 , F.expr("entities['1']['Class12']").alias("Class12")
                 , F.expr("entities['1']['Class13']").alias("Class13")
                 , F.expr("entities['1']['Class14']").alias("Class14")
                 , F.expr("entities['1']['Class15']").alias("Class15")
                 , F.expr("entities['1']['Class16']").alias("Class16")
                 , F.expr("entities['1']['Class17']").alias("Class17")
                 , F.expr("entities['1']['Class18']").alias("Class18")
                 , F.expr("entities['1']['Class19']").alias("Class19")
                 , F.expr("entities['1']['Class20']").alias("Class20")
                 , F.expr("entities['1']['Class21']").alias("Class21")
                 , F.expr("entities['1']['Class22']").alias("Class22")
                 , F.expr("entities['1']['Class23']").alias("Class23")
         )

result.show()
```

**Output**:
```
Id   |class  |Class1 | Class2 | ..., |Class23
------+-------+-------+--------+ ...  +-------
1     | Class1 |  0.99  | ...  | 0.75
```

**Comment by maziyarpanahi** [comment]
Hi @Dirkster99 

Thank you very much for sharing this here, I'll share this on the Slack channel and with others when they need something similar. 

Unfortunately, at the moment the trainable annotators can only use Driver and cannot scale (CPU or GPU). We are waiting for TensorFlow on Java to catch up with TF distribution so we can scale on multiple GPUs on multiple executors.
