### ISSUE TITLE
bert_wiki_books model download takes too long

### ISSUE THREAD

**Issue by periperi24** [JohnSnowLabs/spark-nlp#6407]
**Is your feature request related to a problem? Please describe.**
I am building document parser with a Spark NLP NER pipeline. I use BertEmbeddings and a custom trained NerDLApproach in my pipeline. When I upload a document for parsing I want the output to be displayed in a few seconds(4-5 seconds). The time taken for BertEmbeddings - bert_wiki_books model to get downloaded every time is way too long - 30 seconds or more.

**Describe the solution you'd like**
Is it possible to save and load a lightpipeline version of my NER pipeline? I am guessing it would be faster.

**Describe alternatives you've considered**
I've tried saving the entire Spark NLP pipeline in another script and then loading it in my main script. This takes way too long - a few minutes sometimes.

**Comment by maziyarpanahi** [comment]
Hi,

I am not sure I understand the issue. To simplify:

- "bert_wiki_books model to get downloaded every time is way too long - 30 seconds or more." - we never download the same model nor the pipeline more than once. If it's downloaded, it will be reused in the next new session. So what do you mean by every time? Is this "every time" on a clean machine that doesn't keep the downloaded model?
- "I've tried saving the entire Spark NLP pipeline in another script and then loading it in my main script. This takes way too long" - It may take time to load a saved PipelineModel, but once it's loaded then there shouldn't be an issue. Are you keep starting Spark NLP (SparkSession) and doing a prediction and then killing it? And do this every time for each document? Apache Spark `SparkSession` (Spark NLP session) is not meant to be used this way, you have to start and load everything and then you can keep them alive for an unlimited number of predictions.

**Comment by periperi24** [comment]
Hi,
Thanks for the reply. This is my first Spark project.
Yes you have got it right. I have been starting a spark session, building the pipeline and killing the spark session for each document.

**Comment by maziyarpanahi** [comment]
You are welcome. No worries, in all Apache Spark applications you may have different ways of using your session:

- keeping the SparkSession alive while everything is loaded is the key if the application is being used as an interactive app. (REST API, backend to a UI, etc.)
- Batch processing or offline processing, then the whole app starts, downloads/loads everything, computes, saves the results, and then ends the session by submitting jobs via the `spark-submit`.
- An interactive Data Science notebook, the SparkSession is loaded in the background like Jupyter, Zeppelin, or Databricks, you execute each block of code interactively while waiting for the results.


Almost in all the use cases you would never start and kill the application unless it's a batch processing / offline processing where the jobs are scheduled (like once every night).

**Comment by periperi24** [comment]
Thanks for the detailed explanation. I am using Spark NLP with PySpark and my case is the one where the application uses an interactive app.

**Comment by maziyarpanahi** [comment]
That's great. In that case please start your application, and once everything is loaded keep it alive for all future uses. (think of it as keeping a Web server up and running all the time and not just when there is request coming to it via DNS)

**Comment by periperi24** [comment]
I have a follow-up question on this. I have now started the spark session on a server and  I have also created the pipeline.
When I post single requests to it, I am able to get a response. However when I try multiple requests at the same time it fails.
**Is this set up scalable to multiple users at all?** Can I set this up on a public website for multiple users to use? Or does Spark session started this way process only one request at a time?

My code flow is this way-
Setting Spark pipeline on the server -
spark = sparknlp.start() 
*Load NER model*
*Build pipeline*

Steps once I get request from user -
*Get document from user*
*Read text from document to RDD*
result = prediction_model.transform(my_data)

Will it help if I create a light pipeline and use it to parse the incoming documents instead of using the RDD?

Any guidance would be very helpful. Thanks!

**Comment by maziyarpanahi** [comment]
I think it's the architecture of your own application. You have to design your middle-ware in a way to not be sequential which depends on your framework. (if you use Streamlit for instance, you can have thousands of people sending requests to the same live session you have created at the same time because they do separate each request/thread/etc.)

It's up to what you are using to do this isolation for you:

> In other words, a single SparkContext instance can be used by multiple threads that give the ability to submit multiple Spark jobs that may or may not be running in parallel.

I can suggest also looking into [Livy](https://github.com/apache/incubator-livy) or any other framework that allows this isolation for you. In any case, this is outside of the Spark NLP topic and I suggest looking at other places, it has been done before and it's not Spark NLP, it's Apache Spark.
