### ISSUE TITLE
MultiClassifierModel to return predicted labels ordered by highest to lowest probabilities

### ISSUE THREAD

**Issue by drbonis** [JohnSnowLabs/spark-nlp#6466]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A new parameter added to the Approach and Model like "setSortedByProb(true)" in case you 
want the model to return the labels ordered by descending predicted probability.

**Additional context**
Could help in use cases where multiclass is desired but applying a "top n" approach instead of an arbitrary threshold.

**Comment by maziyarpanahi** [comment]
THanks @drbonis 

I think sort by score and topN would be nice features
