### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by xXSnehalXx** [JohnSnowLabs/spark-nlp#6472]
Spark NLP version:  3.3.2
Apache Spark version:  3.2.0
Java version :11.0.13
using a MacBook laptop 
Installed Apache spark using command  `brew install apache-spark` 

Installed Spark NLP using command `pip install spark-nlp==3.3.2`

-----------------------------------------------------------------------
### Code : 

```
import sparknlp

spark = sparknlp.start()

print("Spark NLP version: ", sparknlp.version())
print("Apache Spark version: ", spark.version)

from sparknlp.pretrained import PretrainedPipeline

pipeline = PretrainedPipeline('recognize_entities_dl', 'en')

result = pipeline.annotate('President Biden represented Delaware for 36 years in the U.S. Senate before becoming the 47th Vice President of the United States.')

print(result['ner'])
print(result['entities'])


```
-----------------------------------------------------------------------

For all my spark work Ive been using the `spark-submit [filepath]` command on the terminal

Below is the output after using the command 

`spark-submit /Users/snehalmachan/InternshipDEEP/SparkCourse/sparkNLP/test.py`

### Output:
-----------------------------------------------------------------------

Spark NLP version:  3.3.2
Apache Spark version:  3.2.0
recognize_entities_dl download started this may take some time.
Traceback (most recent call last):
  File "/Users/snehalmachan/InternshipDEEP/SparkCourse/sparkNLP/test.py", line 13, in <module>
    pipeline = PretrainedPipeline('recognize_entities_dl', 'en')
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/pretrained.py", line 141, in __init__
    self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/pretrained.py", line 72, in downloadPipeline
    file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/internal.py", line 231, in __init__
    super(_GetResourceSize, self).__init__(
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/internal.py", line 165, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/internal.py", line 175, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "/usr/local/Cellar/apache-spark/3.2.0/libexec/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 66, in _new_java_obj
TypeError: 'JavaPackage' object is not callable

-----------------------------------------------------------------------

### Please assist

**Comment by maziyarpanahi** [comment]
Hi,

This error indicates the JAR or Maven package required for Spark NLP in SparkSession is not available. In your case, the reason is `Apache Spark version: 3.2.0` which is not supported at moment: https://github.com/JohnSnowLabs/spark-nlp#apache-spark-support

**Comment by xXSnehalXx** [comment]
Hey ,

**Comment by xXSnehalXx** [comment]
Hey , 

I have now installed Apache spark 3.1.2 , you can view the same below

```
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.1.2
      /_/

Using Python version 3.8.5 (default, Sep  4 2020 02:22:02)
Spark context Web UI available at http://192.168.1.5:4045
Spark context available as 'sc' (master = local[*], app id = local-1637060265386).
SparkSession available as 'spark'.
>>> 

```


I ran the program , but unfortunately still getting the error 

```
Spark NLP version:  3.3.2
Apache Spark version:  3.1.2
recognize_entities_dl download started this may take some time.
Traceback (most recent call last):
  File "/Users/snehalmachan/InternshipDEEP/SparkCourse/sparkNLP/test.py", line 35, in <module>
    pipeline = PretrainedPipeline('recognize_entities_dl', 'en')
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/pretrained.py", line 141, in __init__
    self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/pretrained.py", line 72, in downloadPipeline
    file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/internal.py", line 231, in __init__
    super(_GetResourceSize, self).__init__(
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/internal.py", line 165, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/internal.py", line 175, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "/usr/local/Cellar/apache-spark/3.1.2/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 66, in _new_java_obj
TypeError: 'JavaPackage' object is not callable

```

I notice that the sparknlp.start() successfully returns a sparksesison object , im guessing sparknlp successfully loaded its configuration in the SparkSession object  , but the error is thrown after the next lines of code was executed

as a workaround is there a way to manually include the SparkNLP JAR into the object

**Comment by maziyarpanahi** [comment]
Thank you, the SparkSession successfully started and has Spark NLP inside if you went this far. So now we are going to look at some compatibility that is related to the system itself.

`using a MacBook laptop`, could you please tell me the following:

- exact version of macOS
- the hardware in that laptop (Intel, M1, etc.)
- Do you have Xcode command line tools installed

**Comment by xXSnehalXx** [comment]
Yes sure

MacOS Version = 11.6

Processor = 2.7 GHz Dual-Core Intel Core i5

Yes the cli tools are installed

```
(base) snehalmachan@smbp ~ % gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
(base) snehalmachan@smbp ~ % xcode-select -v
xcode-select version 2384.
```

**Comment by maziyarpanahi** [comment]
Great, thank you.

Could you please try the following:

```sh
spark-submit --packages com.johnsnowlabs.nlp:spark-nlp_2.12:3.3.2 /Users/snehalmachan/InternshipDEEP/SparkCourse/sparkNLP/test.py
```

**Comment by xXSnehalXx** [comment]
Yes sure , I had actually tried this but kept getting few errors , so I was stuck onto using spark-submit as it is , let me show you

I tried the below mentioned , but getting the same with or without `spark = sparknlp.start()` 

`spark-submit --packages com.johnsnowlabs.nlp:spark-nlp_2.12:3.3.2 /Users/snehalmachan/InternshipDEEP/SparkCourse/sparkNLP/test.py`

Output

```
(base) snehalmachan@smbp ~ % spark-submit --packages com.johnsnowlabs.nlp:spark-nlp_2.12:3.3.2 /Users/snehalmachan/InternshipDEEP/SparkCourse/sparkNLP/test.py

Ivy Default Cache set to: /Users/snehalmachan/.ivy2/cache
The jars for the packages stored in: /Users/snehalmachan/.ivy2/jars
:: loading settings :: url = jar:file:/usr/local/Cellar/apache-spark/spark-3.0.3/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.johnsnowlabs.nlp#spark-nlp_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-4763177f-988d-4f94-89ba-7e9a2de98a3c;1.0
	confs: [default]
	found com.johnsnowlabs.nlp#spark-nlp_2.12;3.3.2 in central
	found com.typesafe#config;1.4.1 in central
	found org.rocksdb#rocksdbjni;6.5.3 in central
	found com.amazonaws#aws-java-sdk-bundle;1.11.603 in central
	found com.github.universal-automata#liblevenshtein;3.0.0 in central
	found com.google.code.findbugs#annotations;3.0.1 in central
	found net.jcip#jcip-annotations;1.0 in local-m2-cache
	found com.google.code.findbugs#jsr305;3.0.1 in central
	found com.google.protobuf#protobuf-java-util;3.0.0-beta-3 in central
	found com.google.protobuf#protobuf-java;3.0.0-beta-3 in central
	found com.google.code.gson#gson;2.3 in central
	found it.unimi.dsi#fastutil;7.0.12 in central
	found org.projectlombok#lombok;1.16.8 in central
	found org.slf4j#slf4j-api;1.7.21 in local-m2-cache
	found com.navigamez#greex;1.0 in central
	found dk.brics.automaton#automaton;1.11-8 in central
	found org.json4s#json4s-ext_2.12;3.5.3 in central
	found joda-time#joda-time;2.9.5 in central
	found org.joda#joda-convert;1.8.1 in central
	found com.johnsnowlabs.nlp#tensorflow-cpu_2.12;0.3.3 in central
	found net.sf.trove4j#trove4j;3.0.3 in central
:: resolution report :: resolve 551ms :: artifacts dl 27ms
	:: modules in use:
	com.amazonaws#aws-java-sdk-bundle;1.11.603 from central in [default]
	com.github.universal-automata#liblevenshtein;3.0.0 from central in [default]
	com.google.code.findbugs#annotations;3.0.1 from central in [default]
	com.google.code.findbugs#jsr305;3.0.1 from central in [default]
	com.google.code.gson#gson;2.3 from central in [default]
	com.google.protobuf#protobuf-java;3.0.0-beta-3 from central in [default]
	com.google.protobuf#protobuf-java-util;3.0.0-beta-3 from central in [default]
	com.johnsnowlabs.nlp#spark-nlp_2.12;3.3.2 from central in [default]
	com.johnsnowlabs.nlp#tensorflow-cpu_2.12;0.3.3 from central in [default]
	com.navigamez#greex;1.0 from central in [default]
	com.typesafe#config;1.4.1 from central in [default]
	dk.brics.automaton#automaton;1.11-8 from central in [default]
	it.unimi.dsi#fastutil;7.0.12 from central in [default]
	joda-time#joda-time;2.9.5 from central in [default]
	net.jcip#jcip-annotations;1.0 from local-m2-cache in [default]
	net.sf.trove4j#trove4j;3.0.3 from central in [default]
	org.joda#joda-convert;1.8.1 from central in [default]
	org.json4s#json4s-ext_2.12;3.5.3 from central in [default]
	org.projectlombok#lombok;1.16.8 from central in [default]
	org.rocksdb#rocksdbjni;6.5.3 from central in [default]
	org.slf4j#slf4j-api;1.7.21 from local-m2-cache in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   21  |   0   |   0   |   0   ||   21  |   0   |
	---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
		[NOT FOUND  ] org.slf4j#slf4j-api;1.7.21!slf4j-api.jar (2ms)

	==== local-m2-cache: tried

	  file:/Users/snehalmachan/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::              FAILED DOWNLOADS            ::

		:: ^ see resolution messages for details  ^ ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.slf4j#slf4j-api;1.7.21!slf4j-api.jar

		::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [download failed: org.slf4j#slf4j-api;1.7.21!slf4j-api.jar]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1389)
	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:871)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
(base) snehalmachan@smbp ~ % 

```

**Comment by maziyarpanahi** [comment]
OK this is actually a good error. You should remove this `spark = sparknlp.start()`, it's just no point and it won't start anything if you are using `spark-submit`

What happens here is, it first downloads the spark-nlp dependency from the Maven, and then starts downloading other dependencies from other places. For some reason (Internet, proxy, firewall, etc.) it cannot download/find this: `slf4j-api-1.7.21.jar`

Could you try the Fat JAR (totally offline option - it has everything inside)?


```sh
spark-submit --jars https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/jars/spark-nlp-assembly-3.3.2.jar /Users/snehalmachan/InternshipDEEP/SparkCourse/sparkNLP/test.py
```

You can find Fat JARs in release notes if you are using a different version or if you wish to download them somewhere else: https://github.com/JohnSnowLabs/spark-nlp/releases

**Comment by xXSnehalXx** [comment]
Hey , in short `spark-submit` with `--packages` option worked!!

The following are what I did

I cleaned the `.m2`  in `/Users/snehalmachan/.m2/*` , yet it wouldn't work , adding to your idea , I additionally cleaned the Ivy default cache at `/Users/snehalmachan/.ivy2/*`

Next , 

As suggested I removed the `spark = sparknlp.start()` and then ran `spark-submit` with `--packages`

After all the successfull  sparknlp package downloads (earlier this didn't happen saying `slf4j` couldn't be downloaded  ) 

 it threw the following error 

```
Traceback (most recent call last):
  File "/Users/snehalmachan/InternshipDEEP/SparkCourse/sparkNLP/test.py", line 28, in <module>
    pipeline = PretrainedPipeline('recognize_entities_dl', 'en')
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/pretrained.py", line 141, in __init__
    self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/pretrained.py", line 72, in downloadPipeline
    file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/internal.py", line 231, in __init__
    super(_GetResourceSize, self).__init__(
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/internal.py", line 165, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "/Users/snehalmachan/anaconda3/lib/python3.8/site-packages/sparknlp/internal.py", line 175, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "/usr/local/Cellar/apache-spark/spark-3.0.3/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 65, in _new_java_obj
  File "/usr/local/Cellar/apache-spark/spark-3.0.3/python/lib/pyspark.zip/pyspark/ml/util.py", line 45, in _jvm
AttributeError: Cannot load _jvm from SparkContext. Is SparkContext initialized?

```

So I re-included the `spark = sparknlp.start()` and it actually worked! the pipeline got downloaded and it executed all further lines of code

THANKS A LOT , thank you sir for guiding me with every minute detail.

Not related to this issue , But I want to know where do these pipelines/models get downloaded in my machine? , do they get deleted after being used in the code? considering each download being 150+ MB 😅😅

**Comment by maziyarpanahi** [comment]
Fantastic! Many thanks for sharing this, sometimes I forgot how to use spark-submit correctly with Python script. (in Scala I just package everything together)

So both sparknlp.start() inside the code and `--packages` or `--jars` are needed.

PS: The downloaded models/pipelines go to `~/cache_pretrained` directory, but you can configure that via SparkSession: https://github.com/JohnSnowLabs/spark-nlp#spark-nlp-configuration - you can also use `ResourceDownloader` to clean the whole thing programmatically if you really don't need them (it's faster to load them instead of re-downloading them).
