### ISSUE TITLE
Missing link for lemma_antbnc in model hub

### ISSUE THREAD

**Issue by pratik027** [JohnSnowLabs/spark-nlp#6486]
lemma_antbnc is default model for LemmatizerModel. However It is missing from [model hub](https://nlp.johnsnowlabs.com/models?task=Lemmatization&language=en ). Could you add it in hub?
I found link for lemma_antbnc  https://nlp.johnsnowlabs.com/docs/en/models. Is it updated & good to be used with sparknlp 3.3.2?

**Comment by maziyarpanahi** [comment]
Thanks for reporting this, we will add it to the Models Hub. (the link you found is an old version of Models Hub, even though `lemma_antbnc` is still the same model we will add it to the official [Models Hub](https://nlp.johnsnowlabs.com/models))

**Comment by maziyarpanahi** [comment]
Has been added to Models Hub
