### ISSUE TITLE
Wrong Language for XLM_ROBERTQA

### ISSUE THREAD

**Issue by ahmedlone127** [JohnSnowLabs/spark-nlp#6488]
**Link to doc page in question (if any):**
https://nlp.johnsnowlabs.com/2021/09/01/sent_xlm_roberta_base_xx.html
**Name of the Spark NLP feature whose docs need improvement:**
![image](https://user-images.githubusercontent.com/66001253/142726087-941126e0-29d9-4110-9a59-f22149886349.png)

**What you think the docs should say:**
The language said 'en' which resulted in a model not found error whereas using 'xx' made it work

**Comment by maziyarpanahi** [comment]
Thanks for reporting this, it should be fixed now: https://nlp.johnsnowlabs.com/2021/09/01/sent_xlm_roberta_base_xx.html
