### ISSUE TITLE
'JavaPackage' object is not callable when 'PretrainedPipeline('explain_document_ml', 'en')'

### ISSUE THREAD

**Issue by vasudhajain0** [JohnSnowLabs/spark-nlp#649]
TypeError                                 Traceback (most recent call last)
<ipython-input-19-a7109be74d27> in <module>()
----> 1 pipline = PretrainedPipeline('explain_document_ml', 'en')

/home/bioxcel/anaconda3/lib/python3.7/site-packages/sparknlp/pretrained.py in __init__(self, name, lang, remote_loc)
     89 
     90     def __init__(self, name, lang='en', remote_loc=None):
---> 91         self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
     92         self.light_model = LightPipeline(self.model)
     93 

/home/bioxcel/anaconda3/lib/python3.7/site-packages/sparknlp/pretrained.py in downloadPipeline(name, language, remote_loc)
     50     def downloadPipeline(name, language, remote_loc=None):
     51         print(name + " download started this may take some time.")
---> 52         file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
     53         if file_size == "-1":
     54             print("Can not find the model to download please check the name!")

/home/bioxcel/anaconda3/lib/python3.7/site-packages/sparknlp/internal.py in __init__(self, name, language, remote_loc)
     68         super(_ClearCache, self).__init__("com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.clearCache", name, language, remote_loc)
     69 
---> 70 
     71 class _GetResourceSize(ExtendedJavaWrapper):
     72     def __init__(self, name, language, remote_loc):

/home/bioxcel/anaconda3/lib/python3.7/site-packages/sparknlp/internal.py in __init__(self, java_obj, *args)
      9         super(ExtendedJavaWrapper, self).__init__(java_obj)
     10         self.sc = SparkContext._active_spark_context
---> 11         self._java_obj = self.new_java_obj(java_obj, *args)
     12         self.java_obj = self._java_obj
     13 

/home/bioxcel/anaconda3/lib/python3.7/site-packages/sparknlp/internal.py in new_java_obj(self, java_class, *args)
     19 
     20     def new_java_obj(self, java_class, *args):
---> 21         return self._new_java_obj(java_class, *args)
     22 
     23     def new_java_array(self, pylist, java_class):

/opt/spark-2.4.3-bin-hadoop2.7/python/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

TypeError: 'JavaPackage' object is not callable

**Comment by maziyarpanahi** [comment]
Please fill the template completely, we need all the information to reproduce this error or help you. Right now, I don't see anything useful here. Indicate the versions, your setup, how you installed, how you are creating the Spark Session or any code that can help.

**Comment by vasudhajain0** [comment]
spark.version
2.4.3

sparknlp.version()
2.2.1

I am using centos 7 machine.

-----------------------------------------------------------------------------
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

import sparknlp
from sparknlp.pretrained import PretrainedPipeline
spark= sparknlp.start()
pipeline = PretrainedPipeline('recognize_entities_dl', 'en')

**Comment by vasudhajain0** [comment]
> Please fill the template completely, we need all the information to reproduce this error or help you. Right now, I don't see anything useful here. Indicate the versions, your setup, how you installed, how you are creating the Spark Session or any code that can help.

I have updated information, please check.

**Comment by vasudhajain0** [comment]
> ng is you start the session without any package (spark-nlp) and then run spark= sparknlp.start() which is too late. Remove the first and use spark= sparknlp.start() please.

I still get the same error.

**Comment by maziyarpanahi** [comment]
The error indicates you don’t have spark-nlp in your SparkSession. Where do you run the code? Is it python console, pyspark-shell, etc?

**Comment by vasudhajain0** [comment]
> The error indicates you don’t have spark-nlp in your SparkSession. Where do you run the code? Is it python console, pyspark-shell, etc?

i am running the code in jupyter notebook.

**Comment by maziyarpanahi** [comment]
So in your environment you did “pip install pyspark spark-nlp”?

**Comment by maziyarpanahi** [comment]
Could you please follow this notebook and tell me what you see for the versions?
https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/quick_start.ipynb

**Comment by vasudhajain0** [comment]
> So in your environment you did “pip install pyspark spark-nlp”?

yes I did that. 
But I think it is a spark error,
because if I run spark = SparkSession.builder.getOrCreate()

I get the error, This SparkContext may be an existing one.


sparknlp.version()
2.2.2
spark.version
name 'spark' is not defined

**Comment by vasudhajain0** [comment]
> Could you please follow this notebook and tell me what you see for the versions?
> https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/quick_start.ipynb



import findspark
findspark.init('/opt/spark-2.4.3-bin-hadoop2.7')

import pyspark
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

Error:

Exception                                 Traceback (most recent call last)
<ipython-input-17-fd60f140e9ec> in <module>()
      5 from pyspark.sql import SparkSession
      6 
----> 7 spark = SparkSession.builder.getOrCreate()

/opt/spark-2.4.3-bin-hadoop2.7/python/pyspark/sql/session.py in getOrCreate(self)
    171                     for key, value in self._options.items():
    172                         sparkConf.set(key, value)
--> 173                     sc = SparkContext.getOrCreate(sparkConf)
    174                     # This SparkContext may be an existing one.
    175                     for key, value in self._options.items():

/opt/spark-2.4.3-bin-hadoop2.7/python/pyspark/context.py in getOrCreate(cls, conf)
    365         with SparkContext._lock:
    366             if SparkContext._active_spark_context is None:
--> 367                 SparkContext(conf=conf or SparkConf())
    368             return SparkContext._active_spark_context
    369 

/opt/spark-2.4.3-bin-hadoop2.7/python/pyspark/context.py in __init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls)
    131                     " note this option will be removed in Spark 3.0")
    132 
--> 133         SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
    134         try:
    135             self._do_init(master, appName, sparkHome, pyFiles, environment, batchSize, serializer,

/opt/spark-2.4.3-bin-hadoop2.7/python/pyspark/context.py in _ensure_initialized(cls, instance, gateway, conf)
    314         with SparkContext._lock:
    315             if not SparkContext._gateway:
--> 316                 SparkContext._gateway = gateway or launch_gateway(conf)
    317                 SparkContext._jvm = SparkContext._gateway.jvm
    318 

/opt/spark-2.4.3-bin-hadoop2.7/python/pyspark/java_gateway.py in launch_gateway(conf)
     44     :return: a JVM gateway
     45     """
---> 46     return _launch_gateway(conf)
     47 
     48 

/opt/spark-2.4.3-bin-hadoop2.7/python/pyspark/java_gateway.py in _launch_gateway(conf, insecure)
    106 
    107             if not os.path.isfile(conn_info_file):
--> 108                 raise Exception("Java gateway process exited before sending its port number")
    109 
    110             with open(conn_info_file, "rb") as info:

Exception: Java gateway process exited before sending its port number

**Comment by maziyarpanahi** [comment]
That’s for Google Colab only. You either don’t have Apache Spark (pyspark) installed correctly or don’t have spark-nlp package. As you mentioned, you don’t have Apache Spark installed. You need to install PySpark whether via pip or conda.
I suggest using the Docker Image we have in that repo that comes with lots of examples. Or use google colab notebooks which you need to login with your google account. At the end, if you want to have it locally, you need to have Apache Spark setup:
https://medium.com/spark-nlp/introduction-to-spark-nlp-installation-and-getting-started-part-ii-d009f7a177f3

**Comment by vasudhajain0** [comment]
> That’s for Google Colab only. You either don’t have Apache Spark (pyspark) installed correctly or don’t have spark-nlp package. As you mentioned, you don’t have Apache Spark installed. You need to install PySpark whether via pip or conda.
> I suggest using the Docker Image we have in that repo that comes with lots of examples. Or use google colab notebooks which you need to login with your google account. At the end, if you want to have it locally, you need to have Apache Spark setup:
> https://medium.com/spark-nlp/introduction-to-spark-nlp-installation-and-getting-started-part-ii-d009f7a177f3

I did installed pyspark again, now I again get the first error while using pretrained pipeline.

**Comment by maziyarpanahi** [comment]
I gave you a link to a notebook, please run that Notebook not any other code and paste the results from the version block.

**Comment by vasudhajain0** [comment]
Output-



recognize_entities_dl download started this may take some time.
Approx size to download 157.9 MB
[OK!]

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
/opt/spark-2.4.3-bin-hadoop2.7/python/pyspark/sql/utils.py in deco(*a, **kw)
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:

/home/bioxcel/anaconda3/lib/python3.7/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline.
: java.lang.IllegalArgumentException: requirement failed: Was not found appropriate resource to download for request: ResourceRequest(recognize_entities_dl,Some(en),public/models,2.2.1,2.4.3) with downloader: com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader@15b2cdd8
	at scala.Predef$.require(Predef.scala:224)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadResource(ResourceDownloader.scala:328)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:359)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:354)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadPipeline(ResourceDownloader.scala:446)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)


During handling of the above exception, another exception occurred:

IllegalArgumentException                  Traceback (most recent call last)
<ipython-input-3-d759b18b57fc> in <module>()
----> 1 pipeline = PretrainedPipeline('recognize_entities_dl', 'en')

/home/bioxcel/anaconda3/lib/python3.7/site-packages/sparknlp/pretrained.py in __init__(self, name, lang, remote_loc)
     89 
     90     def __init__(self, name, lang='en', remote_loc=None):
---> 91         self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
     92         self.light_model = LightPipeline(self.model)
     93 

/home/bioxcel/anaconda3/lib/python3.7/site-packages/sparknlp/pretrained.py in downloadPipeline(name, language, remote_loc)
     59             t1.start()
     60             try:
---> 61                 j_obj = _internal._DownloadPipeline(name, language, remote_loc).apply()
     62                 jmodel = JavaModel(j_obj)
     63             finally:

/home/bioxcel/anaconda3/lib/python3.7/site-packages/sparknlp/internal.py in __init__(self, name, language, remote_loc)
     57 class _DownloadPipeline(ExtendedJavaWrapper):
     58     def __init__(self, name, language, remote_loc):
---> 59         super(_DownloadPipeline, self).__init__("com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline", name, language, remote_loc)
     60 
     61 

/home/bioxcel/anaconda3/lib/python3.7/site-packages/sparknlp/internal.py in __init__(self, java_obj, *args)
      9         super(ExtendedJavaWrapper, self).__init__(java_obj)
     10         self.sc = SparkContext._active_spark_context
---> 11         self._java_obj = self.new_java_obj(java_obj, *args)
     12         self.java_obj = self._java_obj
     13 

/home/bioxcel/anaconda3/lib/python3.7/site-packages/sparknlp/internal.py in new_java_obj(self, java_class, *args)
     19 
     20     def new_java_obj(self, java_class, *args):
---> 21         return self._new_java_obj(java_class, *args)
     22 
     23     def new_java_array(self, pylist, java_class):

/opt/spark-2.4.3-bin-hadoop2.7/python/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

/home/bioxcel/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/opt/spark-2.4.3-bin-hadoop2.7/python/pyspark/sql/utils.py in deco(*a, **kw)
     77                 raise QueryExecutionException(s.split(': ', 1)[1], stackTrace)
     78             if s.startswith('java.lang.IllegalArgumentException: '):
---> 79                 raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
     80             raise
     81     return deco

IllegalArgumentException: 'requirement failed: Was not found appropriate resource to download for request: ResourceRequest(recognize_entities_dl,Some(en),public/models,2.2.1,2.4.3) with downloader: com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader@15b2cdd8'

**Comment by vasudhajain0** [comment]
> Ok now the error is different. Good news is that you have Spark and Spark NLP. For some reason it cannot download recognize_entities_dl pipeline. Are you behind a proxy? You can also download the pipelines and use them offline:
> https://nlp.johnsnowlabs.com/docs/en/pipelines

------------------------------

I was able to download the pipeline few minutes back, but now again I face a different error--

Py4JJavaError                             Traceback (most recent call last)
<ipython-input-3-d759b18b57fc> in <module>()
----> 1 pipeline = PretrainedPipeline('recognize_entities_dl', 'en')

/tmp/spark-18f91723-694f-48b8-bd6d-7527223fe583/userFiles-e1c7e1c1-9059-4265-9f03-b9d71f905169/JohnSnowLabs_spark-nlp-2.2.1.jar/sparknlp/pretrained.py in __init__(self, name, lang, remote_loc)
     89 
     90     def __init__(self, name, lang='en', remote_loc=None):
---> 91         self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
     92         self.light_model = LightPipeline(self.model)
     93 

/tmp/spark-18f91723-694f-48b8-bd6d-7527223fe583/userFiles-e1c7e1c1-9059-4265-9f03-b9d71f905169/JohnSnowLabs_spark-nlp-2.2.1.jar/sparknlp/pretrained.py in downloadPipeline(name, language, remote_loc)
     59             t1.start()
     60             try:
---> 61                 j_obj = _internal._DownloadPipeline(name, language, remote_loc).apply()
     62                 jmodel = JavaModel(j_obj)
     63             finally:

/tmp/spark-18f91723-694f-48b8-bd6d-7527223fe583/userFiles-e1c7e1c1-9059-4265-9f03-b9d71f905169/JohnSnowLabs_spark-nlp-2.2.1.jar/sparknlp/internal.py in __init__(self, name, language, remote_loc)
     57 class _DownloadPipeline(ExtendedJavaWrapper):
     58     def __init__(self, name, language, remote_loc):
---> 59         super(_DownloadPipeline, self).__init__("com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline", name, language, remote_loc)
     60 
     61 

/tmp/spark-18f91723-694f-48b8-bd6d-7527223fe583/userFiles-e1c7e1c1-9059-4265-9f03-b9d71f905169/JohnSnowLabs_spark-nlp-2.2.1.jar/sparknlp/internal.py in __init__(self, java_obj, *args)
      9         super(ExtendedJavaWrapper, self).__init__(java_obj)
     10         self.sc = SparkContext._active_spark_context
---> 11         self._java_obj = self.new_java_obj(java_obj, *args)
     12         self.java_obj = self._java_obj
     13 

/tmp/spark-18f91723-694f-48b8-bd6d-7527223fe583/userFiles-e1c7e1c1-9059-4265-9f03-b9d71f905169/JohnSnowLabs_spark-nlp-2.2.1.jar/sparknlp/internal.py in new_java_obj(self, java_class, *args)
     19 
     20     def new_java_obj(self, java_class, *args):
---> 21         return self._new_java_obj(java_class, *args)
     22 
     23     def new_java_array(self, pylist, java_class):

/opt/spark-2.4.3-bin-hadoop2.7/python/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

/opt/spark-2.4.3-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/opt/spark-2.4.3-bin-hadoop2.7/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/opt/spark-2.4.3-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline.
: java.io.FileNotFoundException: /tmp/sparknlp_contrib_spar (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.johnsnowlabs.nlp.annotators.ner.dl.LoadsContrib$.copyResourceToTmp(LoadsContrib.scala:39)
	at com.johnsnowlabs.nlp.annotators.ner.dl.LoadsContrib$.loadContribToCluster(LoadsContrib.scala:57)
	at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel$class.readTensorflowModel(TensorflowSerializeModel.scala:60)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel$.readTensorflowModel(NerDLModel.scala:139)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$class.readNerGraph(NerDLModel.scala:117)
	at com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel$.readNerGraph(NerDLModel.scala:139)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$$anonfun$2.apply(NerDLModel.scala:121)
	at com.johnsnowlabs.nlp.annotators.ner.dl.ReadsNERGraph$$anonfun$2.apply(NerDLModel.scala:121)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:31)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:30)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$class.com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead(ParamsAndFeaturesReadable.scala:30)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:19)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at org.apache.spark.ml.util.DefaultParamsReader$.loadParamsInstance(ReadWrite.scala:652)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:274)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:272)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:272)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:348)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:342)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:360)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.downloadPipeline(ResourceDownloader.scala:354)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.downloadPipeline(ResourceDownloader.scala:446)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vasudhajain0** [comment]
> Ok now the error is different. Good news is that you have Spark and Spark NLP. For some reason it cannot download recognize_entities_dl pipeline. Are you behind a proxy? You can also download the pipelines and use them offline:
> https://nlp.johnsnowlabs.com/docs/en/pipelines

and will we have to download the pipeline everytime we want to use it?
If not, then how should I call it?

**Comment by maziyarpanahi** [comment]
No need to download it every time. Just download it, unzip (extract), and keep it somewhere you have access from Apache Spark and load it. There is an instruction here:
https://nlp.johnsnowlabs.com/docs/en/pipelines#offline

```scala
val advancedPipeline = PipelineModel.load("/tmp/recognize_entities_dl_en_2.1.0_2.4_1562946909722/")
// To use the loaded Pipeline for prediction
advancedPipeline.transform(YOUR_DATAFRAME)
```

**Comment by vasudhajain0** [comment]
> access from Apache Spark and load it. There is an instruction h

okay.
but can you help me the above error?
what is it about?

**Comment by vasudhajain0** [comment]
> No need to download it every time. Just download it, unzip (extract), and keep it somewhere you have access from Apache Spark and load it. There is an instruction here:
> https://nlp.johnsnowlabs.com/docs/en/pipelines#offline
> 
> ```scala
> val advancedPipeline = PipelineModel.load("/tmp/recognize_entities_dl_en_2.1.0_2.4_1562946909722/")
> // To use the loaded Pipeline for prediction
> advancedPipeline.transform(YOUR_DATAFRAME)
> ```

also tell me how do I call it in python. The example provid4ed is for scala and I am using python.

**Comment by vasudhajain0** [comment]
> No need to download it every time. Just download it, unzip (extract), and keep it somewhere you have access from Apache Spark and load it. There is an instruction here:
> https://nlp.johnsnowlabs.com/docs/en/pipelines#offline
> 
> ```scala
> val advancedPipeline = PipelineModel.load("/tmp/recognize_entities_dl_en_2.1.0_2.4_1562946909722/")
> // To use the loaded Pipeline for prediction
> advancedPipeline.transform(YOUR_DATAFRAME)
> ```
please reply!

**Comment by maziyarpanahi** [comment]
It’s the same!

advancedPipeline = PipelineModel.load("/tmp/recognize_entities_dl_en_2.1.0_2.4_1562946909722/")
// To use the loaded Pipeline for prediction
advancedPipeline.transform(YOUR_DATAFRAME)


I suggest using our Docker image that comes with all the examples and everything installed already:
https://github.com/JohnSnowLabs/spark-nlp-workshop

**Comment by vasudhajain0** [comment]
I haven't used docker images before and hence it will be a bit difficult for me to use it.

Also, using
 advancedPipeline = PipelineModel.load("/tmp/recognize_entities_dl_en_2.1.0_2.4_1562946909722/")

gives an error of   name 'PipelineModel' is not defined.

**Comment by maziyarpanahi** [comment]
I suggest using the Docker image. Your errors are kept changing and that shows you have issues with the basics from Spark installation to using Spark. A simple search will get you to this:
```python
from pyspark.ml import PipelineModel, Pipeline
```
Please read the documentation, look at our examples, and do some searching. Since your initial error has been resolved, I consider this issue as being resolved.

Best of luck.
