### ISSUE TITLE
BertEmbeddings model unzipped lacks necessary structure for loading

### ISSUE THREAD

**Issue by marilenaoita** [JohnSnowLabs/spark-nlp#650]
I download the BertEmbeddings (large_uncased) | bert_large_uncased model from 
https://nlp.johnsnowlabs.com/docs/en/models ; 
but when unzipping, unlike other models, I get another folder structure which lacks the required "metadata" folder so that the model can load properly. 

bert_base_uncased = (BertEmbeddings) BertEmbeddings.load(unzipped_path)

Thank you for your help, Marilena 
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by maziyarpanahi** [comment]
Could you please show me what is in the extracted folder and what is the exact error you are receiving. Also, it is very necessary to fill in the Environment section as we need to know which Apache Spark version, Spark NLP version, which language, and anything else about your environment to be bale to reproduce the error.
