### ISSUE TITLE
AttributeError: module 'sparknlp' has no attribute 'version'

### ISSUE THREAD

**Issue by grajee-everest** [JohnSnowLabs/spark-nlp#6506]
Unable to run  **sparknlp.start()**

## Description
We have a [SQLServer BDC](https://docs.microsoft.com/en-us/sql/big-data-cluster/release-notes-cumulative-update-13?view=sql-server-ver15) cluster with Apache Spark v3.12 and we would like to use sparknlp with pyspark. The cluster has locally attached HDFS file system to which we download and copy the libraries since the cluster does not have outbound internet access.

I use the tool Azure Data Studio to connect to the cluster and use jupyter notebooks. I copied the files to hdfs as below (v3.3.2) and I add them to the notebook. I ran the below code but I'm getting an error:

```
sc.addFile('hdfs:///modules/python/sparknlp/',True)
import sparknlp 
sparknlp.start()
```
Looks like something is not right with the way the library has been deployed into HDFS.  The version details are at the link - https://docs.microsoft.com/en-us/sql/big-data-cluster/release-notes-cumulative-update-13?view=sql-server-ver15

![image](https://user-images.githubusercontent.com/66425640/143088506-a18d7c2e-5305-4af4-88de-d1d1b82d5a36.png)

## Expected Behavior
Have never seen what would happen if sparknlp.start() runs successfully.

## Current Behavior

> An error was encountered:
> module 'sparknlp' has no attribute 'start'
> Traceback (most recent call last):
> AttributeError: module 'sparknlp' has no attribute 'start'

## Steps to Reproduce

1.
2.
3.
4.

## Context
Not able to proceed any further

All the environment details are here :

**Microsoft Spark Runtime 2021.1
Spark: 3.1.2
Delta Lake: 1.0.0
Java: Azul Zulu JRE 1.8.0_275
Scala: 2.12
Python: 3.8 (miniforge 4.9)
R: Microsoft R 3.5.2
Spark SQL Connector: 1.2.0**

## Your Environment
* Setup and installation (Pypi, Conda, Maven, etc.):
**I download the library using "pip install -t  spark-nlp" and copied the folder to the HDFS location**

**Comment by maziyarpanahi** [comment]
Hi,

The way to use Spark NLP in a cluster especially a PySpark cluster is as follow:

- You need to have PyPI package of Spark NLP
- You must have Maven package / of Fat JAR of Spark NLP in SparkSession

A few notes:

- You must install `spark-nlp` PyPI package on **all the executors**. (in the same Python Env that your cluster is set up for Apache Spark) - I've never tried `sc.addFile` as an alternative so I'll trust you know better here, but it must be installed on all machines and in the same Python Env not just your machine/Driver
- Since this is a cluster `spark = sparknlp.start()` no longer has any value. It is meant for local environments with `local[*]` as master. 
- I can see you have a YARN cluster, this means once you are in that notebook, you already have a SparkSession and there is no way to include the Maven package for Spark NLP - SparkSession is getOrCreate() so it will just reuse the current session. (the fact that you have `sc.addFile` means you already have SparkSession up and running without Spark NLP Maven/JAR)

All you need to do is before starting SparSession (I am not sure how you start it, does it start with each notebook like Zeppelin, or is it started before the notebook like Databricks) having Spark NLP Maven package inside:

Your issue:
- There is no PyPI package for `spark-nlp` or it's not available on all the machines. Or else `sparknlp` had a `.start()` function. (even those this is not the way to start, so the better way to test is `sparknlp.version()`)

- once you do have PyPI of `spark-nlp` available on all the machines, you will need Spark NLP Maven package in your SparkSession: `--packages com.johnsnowlabs.nlp:spark-nlp_2.12:3.3.3` which can come in different forms depending on how your SarkSession for YARN is being created for your notebooks.

We have installation instructions and if you check for those that are in a cluster (like Databricks, EMR, etc.) the setup is to have PyPI on all the machines and Maven included in the SparkSession from the beginning: https://github.com/JohnSnowLabs/spark-nlp#usage

**Comment by grajee-everest** [comment]
The tool that we use is Azure Data Studio and it gives you an interface to code in SparkR/Scala/Pyspark
![image](https://user-images.githubusercontent.com/66425640/143050597-9a6cd6c5-2d1f-47c8-829f-bb16e63702db.png)

When I open a new notebook, choose Pyspark as kernel and select the cluster in "Attach to" a session is automatically created when I execute the code in the first cell. A session named Spark is first created and then the code in the cell is executed.

The addfile is able to distribute the nlp library on all the nodes otherwise "import sparknlp" would have errored out. 

I need to find out how to include the JAR file in the session.
<<You must have Maven package / of Fat JAR of Spark NLP in SparkSession>>
![image](https://user-images.githubusercontent.com/66425640/143088173-0aa2f818-74b0-47f3-a73b-4b4f131dbc16.png)


Thanks,
grajee

**Comment by maziyarpanahi** [comment]
Thanks for the information, it's pretty similar to Databricks where you create the cluster beforehand and then attach different notebooks to that cluster. It must have a place where you can add Maven coordinates which will include those third-party packages inside SparkSession when the cluster starts. (all the managed clusters like Databricks, EMR, Cloudera, etc. have this feature for external/third-party Maven/PyPI packages)

**Comment by grajee-everest** [comment]
Could you be referring to what is in this link?

**https://docs.microsoft.com/en-us/sql/big-data-cluster/spark-install-packages?view=sql-server-ver15**

Since the jar file, **_hdfs://modules/jar/spark-nlp/spark-nlp-assembly-3.3.3.jar_**,  is local in my case, what would it be?

![image](https://user-images.githubusercontent.com/66425640/143092859-b737d00a-2758-47fe-a434-17a46f719a0a.png)

**Comment by maziyarpanahi** [comment]
Yes, it's like Apache Zeppelin:

```
%%configure -f \
{"conf": {"spark.jars.packages": "com.johnsnowlabs.nlp:spark-nlp_2.12:3.3.3"}}
```

But please beware of this part exactly like Apache Zeppelin:

>Maven packages can be installed onto your Spark cluster using notebook cell configuration at the start of your spark session. **Before starting a spark session** in Azure Data Studio, run the following code: 

Even though you attached the cluster, before you run any block this must be at the very beginning and be executed as the very first thing in that notebook

**Comment by grajee-everest** [comment]
When I set the **CONFIG** setting in the first cell and run the **addFile line - sc.addFile('hdfs:///modules/python/sparknlp/',True)** in the second cell I get the below error . 

How would the system know the jar file that I uploaded in the green rectangle? The sparknlp libraries are in the red rectangle. Note that the system **does not have** outbound **internet** access and it seems to be looking for other jar files. Whatever files are needed I need to download and save them on the hdfs drive

The [offline instruction](https://github.com/JohnSnowLabs/spark-nlp#offline) mentioned that I download the FAT Jar file which is what I uploaded (green rectangle)

![image](https://user-images.githubusercontent.com/66425640/143134858-d40f876e-47bd-4f89-80cc-dbedcb935d96.png)


> Starting Spark application
> The code failed because of a fatal error:
> 	Session 344 unexpectedly reached final status 'dead'. See logs:
> stdout: 
> :: loading settings :: url = jar:file:/opt/mls/python/pkgs/pyspark-3.1.2-pyh6c4a22f_0/site-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
> 
> stderr: 
> Ivy Default Cache set to: /home/livy/.ivy2/cache
> The jars for the packages stored in: /home/livy/.ivy2/jars
> com.johnsnowlabs.nlp#spark-nlp_2.12 added as a dependency
> :: resolving dependencies :: org.apache.spark#spark-submit-parent-d7402c04-e2fb-4789-92fe-d3b7b12d045f;1.0
> 	confs: [default]
> :: resolution report :: resolve 448ms :: artifacts dl 0ms
> 	:: modules in use:
> 	---------------------------------------------------------------------
> 	|                  |            modules            ||   artifacts   |
> 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
> 	---------------------------------------------------------------------
> 	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
> 	---------------------------------------------------------------------
> 
> :: problems summary ::
> :::: WARNINGS
> 		module not found: com.johnsnowlabs.nlp#spark-nlp_2.12;3.3.3
> 
> 	==== local-m2-cache: tried
> 
> 	  file:/home/livy/.m2/repository/com/johnsnowlabs/nlp/spark-nlp_2.12/3.3.3/spark-nlp_2.12-3.3.3.pom
> 
> 	  -- artifact com.johnsnowlabs.nlp#spark-nlp_2.12;3.3.3!spark-nlp_2.12.jar:
> 
> 	  file:/home/livy/.m2/repository/com/johnsnowlabs/nlp/spark-nlp_2.12/3.3.3/spark-nlp_2.12-3.3.3.jar
> 
> 	==== local-ivy-cache: tried
> 
> 	  /home/livy/.ivy2/local/com.johnsnowlabs.nlp/spark-nlp_2.12/3.3.3/ivys/ivy.xml
> 
> 	  -- artifact com.johnsnowlabs.nlp#spark-nlp_2.12;3.3.3!spark-nlp_2.12.jar:
> 
> 	  /home/livy/.ivy2/local/com.johnsnowlabs.nlp/spark-nlp_2.12/3.3.3/jars/spark-nlp_2.12.jar
> 
> 	==== central: tried
> 
> 	  https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.12/3.3.3/spark-nlp_2.12-3.3.3.pom
> 
> 	  -- artifact com.johnsnowlabs.nlp#spark-nlp_2.12;3.3.3!spark-nlp_2.12.jar:
> 
> 	  https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.12/3.3.3/spark-nlp_2.12-3.3.3.jar
> 
> 	==== spark-packages: tried
> 
> 	  https://repos.spark-packages.org/com/johnsnowlabs/nlp/spark-nlp_2.12/3.3.3/spark-nlp_2.12-3.3.3.pom
> 
> 	  -- artifact com.johnsnowlabs.nlp#spark-nlp_2.12;3.3.3!spark-nlp_2.12.jar:
> 
> 	  https://repos.spark-packages.org/com/johnsnowlabs/nlp/spark-nlp_2.12/3.3.3/spark-nlp_2.12-3.3.3.jar
> 
> 		::::::::::::::::::::::::::::::::::::::::::::::
> 
> 		::          UNRESOLVED DEPENDENCIES         ::
> 
> 		::::::::::::::::::::::::::::::::::::::::::::::
> 
> 		:: com.johnsnowlabs.nlp#spark-nlp_2.12;3.3.3: not found
> 
> 		::::::::::::::::::::::::::::::::::::::::::::::
> 
> 
> :::: ERRORS
> 	Server access error at url https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.12/3.3.3/spark-nlp_2.12-3.3.3.pom (javax.net.ssl.SSLException: Connection reset)
> 
> 	Server access error at url https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.12/3.3.3/spark-nlp_2.12-3.3.3.jar (javax.net.ssl.SSLException: Connection reset)
> 
> 	Server access error at url https://repos.spark-packages.org/com/johnsnowlabs/nlp/spark-nlp_2.12/3.3.3/spark-nlp_2.12-3.3.3.pom (javax.net.ssl.SSLException: Connection reset)
> 
> 	Server access error at url https://repos.spark-packages.org/com/johnsnowlabs/nlp/spark-nlp_2.12/3.3.3/spark-nlp_2.12-3.3.3.jar (javax.net.ssl.SSLException: Connection reset)
> 
> 
> :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
> Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: com.johnsnowlabs.nlp#spark-nlp_2.12;3.3.3: not found]
> 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1445)
> 	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
> 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
> 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:910)
> 	at org.apache.spark.deploy.SparkSubmit$$anon$1.run(SparkSubmit.scala:165)
> 	at org.apache.spark.deploy.SparkSubmit$$anon$1.run(SparkSubmit.scala:163)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at javax.security.auth.Subject.doAs(Subject.java:422)
> 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1761)
> 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:163)
> 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
> 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
> 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1055)
> 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1064)
> 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> 
> YARN Diagnostics: 
> spark-submit start failed.
> 
> Some things to try:
> a) Make sure Spark has enough available resources for Jupyter to create a Spark context.
> b) Contact your Jupyter administrator to make sure the Spark magics library is configured correctly.
> c) Restart the kernel.

How would it know the location of the jar file that is in the red rectangle in the HDFS folder?

Without the CONFIG line the addFile in the second cell goes thru.

**Comment by grajee-everest** [comment]
I reviewed the documentation for offline and I got it right with %%CONFIG
`%%configure -f \
{"conf": {"spark.jars": "hdfs:///modules/jar/spark-nlp/spark-nlp-assembly-3.3.3.jar"}}`

**but I'm still seeing the error when I run** 
`print("Spark NLP version: ", sparknlp.version())`

> An error was encountered:
> module 'sparknlp' has no attribute 'version'
> Traceback (most recent call last):
> AttributeError: module 'sparknlp' has no attribute 'version'

**Is addFile the right way to bring in the library:**
`sc.addFile('hdfs:///modules/python/sparknlp/',True)`

![image](https://user-images.githubusercontent.com/66425640/143260623-6f0c71ee-a7b2-478b-9693-4f54b754ef41.png)

**Comment by grajee-everest** [comment]
Is there a different way to download files for offline use? Here is a screenshot of how I'm doing it. Once downloaded, I merely copy the **sparknlp folder** it to the HDFS location - **hdfs://modules/python/sparknlp/** and eventually use **sc.addFile** in the code

![image](https://user-images.githubusercontent.com/66425640/143267743-e7a7f84a-edc5-4651-8725-5f31b6a34b5e.png)

**Comment by maziyarpanahi** [comment]
I am sorry I’ve never used add file to install a PyPI package on a cluster. Please have a look there must be a simple way like you did with packages or jars at the beginning to install the Python package on all the machines.

At this point I guess there is a standard way which we recommend and almost all the environments support and there must be other ways which can be specific to the environment or a preference to a user which we cannot garantie nor help.
