### ISSUE TITLE
identify intent model classifierdl_use_snips fails with 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by programmeddeath1** [JohnSnowLabs/spark-nlp#6539]
## Description

The live demo for intent classification (https://demo.johnsnowlabs.com/public/NER_CLS_SNIPS/) shows that classifier model 
classifierdl_use_snips used for classification of intent. But when I add the model to the NER colab on running 
```
classifier = ClassifierDLModel('classifierdl_use_snips').setInputCols(['sentence_embeddings']).setOutputCol('class')
```
as shown in the how to use sample code, it fails with 
```
'JavaPackage' object is not callable
```
## Expected Behavior
It should load the model and process the text for classification.

## Current Behavior
It is not able to load the model because of some incompatibility error.
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-8292bb9972c0> in <module>
     16     .setOutputCol("sentence_embeddings")
     17 
---> 18 classifier = ClassifierDLModel('classifierdl_use_snips').setInputCols(['sentence_embeddings']).setOutputCol('class')
     19 
     20 classnlp_pipeline = Pipeline(stages=[document_assembler, classembeddings, classifier])

3 frames
/usr/local/lib/python3.7/dist-packages/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     64             java_obj = getattr(java_obj, name)
     65         java_args = [_py2java(sc, arg) for arg in args]
---> 66         return java_obj(*java_args)
     67 
     68     @staticmethod

TypeError: 'JavaPackage' object is not callable
```

## Possible Solution
There might be a specific combination of pyspark and nlp-spark version which runs this code based on which the demo is running, this was an error with earler models in spark-nlp which was due to version incompatibilty, But I have tried all possible combinations of 
spark-nlp and pyspark even older compatible versions but I get the same error.

## Steps to Reproduce
You can check the code im running on the colab below. the classifier is run after the NER step, even on running the classifier first it does not work.
https://colab.research.google.com/drive/1DoW-CzkLERl3IrZJQoTz_eR4dbc_oygD?usp=sharing
1. Setup nlp-spark through the colab.sh script
2. Start spark-nlp session
3. Run the classifier code for classifierdl_use_snips

## Context
I am trying to replicate the demo for Understand intent and actions in general commands, its colab contains only NER recognition code, so I am adding the classifier used in the demo based on (https://nlp.johnsnowlabs.com/2021/02/15/classifierdl_use_snips_en.html).

## Your Environment
* Spark NLP version `sparknlp.version()`: 3.3.4
* Apache NLP version `spark.version`:3.0.3
* Java version `java -version`: 11
* Setup and installation (Pypi, Conda, Maven, etc.): pip
* Operating System and version: google colab
* Link to your project (if any): https://colab.research.google.com/drive/1DoW-CzkLERl3IrZJQoTz_eR4dbc_oygD?usp=sharing

**Comment by maziyarpanahi** [comment]
Hi @programmeddeath1 

- In your Google Colab and the Model's card for `classifierdl_use_snips` is being used wrongly (hence your error). It must be used as `ClassifierDLModel.pretrained('classifierdl_use_snips')`. It is missing a `.pretrained(NAME, LANG)`

@josejuanmartinez Could you please assign a member to 
- fix the missing `.pretrained()` in both Python and Scala on the Model's card (https://nlp.johnsnowlabs.com/2021/02/15/classifierdl_use_snips_en.html)

**Comment by josejuanmartinez** [comment]
@maziyarpanahi  on it!

**Comment by murat-gunay** [comment]
@maziyarpanahi @josejuanmartinez 
I fixed this issue by [this PR](https://github.com/JohnSnowLabs/spark-nlp/pull/6542).
