### ISSUE TITLE
Java IO exception while saving a pipeline to S3 location

### ISSUE THREAD

**Issue by dkincaid** [JohnSnowLabs/spark-nlp#654]
## Description
When trying to save a fitted pipeline I get an exception stating `java.io.Exception: Can't make directory for path 's3://<bucketname>/path/to/save/location since it is a file.` I'll include the full stack trace as an attachment to the issue.

[exception.txt](https://github.com/JohnSnowLabs/spark-nlp/files/3686328/exception.txt)

The pipeline I am trying to save includes a DocumentAssembler, SentenceDetector, Tokenizer, PerceptronModel, WordEmbeddingsModel and NerCRfModel. In the location on S3 that I am saving to I can see directories for the DocumentAssember, SentenceDetector, REGEX_TOKENIZER, POS and WORD_EMBEDDINGS_MODEL. The first 4 include both a `fields` and `metadata` directories. However, the word embeddings directory only has a `metadata` directory (no `fields` directory).

So, this fact along with the mention of WordEmbeddingsModel in the exception stack trace seems to point at a problem in that object.

## Expected Behavior
The pipeline should be saved to the S3 location specified without error.

## Steps to Reproduce
I will attach a Jupyter notebook that demonstrates the error.

[IDEXX John Snow General Pipeline - demo.zip](https://github.com/JohnSnowLabs/spark-nlp/files/3686326/IDEXX.John.Snow.General.Pipeline.-.demo.zip)

## Context
We are evaluating the library for our own use. I was testing the ability to save a fitted pipeline (one that may have some custom trained models) to S3 for use later.

## Your Environment
* Version used: 2.2.2
* This was run in a Jupyter notebook running on AWS EMR cluster

**Comment by maziyarpanahi** [comment]
Since we changed a lot in WordEmbeddings in our latest release, is it possible to test the new 2.4.0 release? You can use pretrained for all the models, they are all updated.
