### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by ghnp5** [JohnSnowLabs/spark-nlp#6563]
Hi,

I'm trying to test this project, for language detection, but I'm stuck with an error.
I'm following some tutorials, and also looked at the Issues that other people reported for the same error, but I'm not understanding what I'm missing here.

I have this Dockerfile installing **Java 8, spark-nlp==3.3.4, pyspark==3.1.2**

```
#Download base image ubuntu 18.04
FROM ubuntu:18.04

ENV NB_USER yuefeng
ENV NB_UID 1000
ENV HOME /home/${NB_USER}

ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3

RUN apt-get update && apt-get install -y \
    tar \
    wget \
    bash \
    rsync \
    gcc \
    libfreetype6-dev \
    libhdf5-serial-dev \
    libpng-dev \
    libzmq3-dev \
    python3 \ 
    python3-dev \
    python3-pip \
    unzip \
    pkg-config \
    software-properties-common \
    graphviz

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    ${NB_USER}

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;
# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

RUN echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/" >> ~/.bashrc

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir notebook==5.* numpy spark-nlp==3.3.4 pyspark==3.1.2 pandas mlflow Keras scikit-spark scikit-learn scipy matplotlib pydot graphviz

USER root
RUN chown -R ${NB_UID} ${HOME}
USER ${NB_USER}

WORKDIR ${HOME}

# Specify the default command to run
CMD ["jupyter", "notebook", "--ip", "0.0.0.0"]
```

Then in the jupyter, I'm trying to run the following:

```python
import sparknlp
from sparknlp.pretrained import PretrainedPipeline

spark = sparknlp.start()

language_detector_pipeline = PretrainedPipeline('detect_language_21', lang='xx')
language_detector_pipeline.annotate("Harry Potter is a great movie")
```

But I get:

> detect_language_21 download started this may take some time.
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-12-fd65316f798f> in <module>
>       4 spark = sparknlp.start()
>       5 
> ----> 6 language_detector_pipeline = PretrainedPipeline('detect_language_21', lang='xx')
>       7 language_detector_pipeline.annotate("Harry Potter is a great movie")
> 
> /usr/local/lib/python3.6/dist-packages/sparknlp/pretrained.py in __init__(self, name, lang, remote_loc, parse_embeddings, disk_location)
>     139     def __init__(self, name, lang='en', remote_loc=None, parse_embeddings=False, disk_location=None):
>     140         if not disk_location:
> --> 141             self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
>     142         else:
>     143             self.model = PipelineModel.load(disk_location)
> 
> /usr/local/lib/python3.6/dist-packages/sparknlp/pretrained.py in downloadPipeline(name, language, remote_loc)
>      70     def downloadPipeline(name, language, remote_loc=None):
>      71         print(name + " download started this may take some time.")
> ---> 72         file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
>      73         if file_size == "-1":
>      74             print("Can not find the model to download please check the name!")
> 
> /usr/local/lib/python3.6/dist-packages/sparknlp/internal.py in __init__(self, name, language, remote_loc)
>     230     def __init__(self, name, language, remote_loc):
>     231         super(_GetResourceSize, self).__init__(
> --> 232             "com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize", name, language, remote_loc)
>     233 
>     234 
> 
> /usr/local/lib/python3.6/dist-packages/sparknlp/internal.py in __init__(self, java_obj, *args)
>     163         super(ExtendedJavaWrapper, self).__init__(java_obj)
>     164         self.sc = SparkContext._active_spark_context
> --> 165         self._java_obj = self.new_java_obj(java_obj, *args)
>     166         self.java_obj = self._java_obj
>     167 
> 
> /usr/local/lib/python3.6/dist-packages/sparknlp/internal.py in new_java_obj(self, java_class, *args)
>     173 
>     174     def new_java_obj(self, java_class, *args):
> --> 175         return self._new_java_obj(java_class, *args)
>     176 
>     177     def new_java_array(self, pylist, java_class):
> 
> /usr/local/lib/python3.6/dist-packages/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
>      64             java_obj = getattr(java_obj, name)
>      65         java_args = [_py2java(sc, arg) for arg in args]
> ---> 66         return java_obj(*java_args)
>      67 
>      68     @staticmethod
> 
> TypeError: 'JavaPackage' object is not callable

**Comment by maziyarpanahi** [comment]
`TypeError: 'JavaPackage' object is not callable` means the Maven or JAR of Spark NLP is not inside SparkSession. You are using `spark = sparknlp.start()` to start SparkSession which automatically will include this in the session. Two things can happen here to see this error:

- The SparkSession already exists. So `sparknlp.start()` won't do anything and therefore it won't have Spark NLP. Solution, making sure there is no SparkSession available before running that like. (how to test this, once you opened your jupyter with a new kernel, just see if `spark` variable exists. If there is no such variable then you don't have SparkSession and you can move to the second possibility)
- Your container doesn't have access to the internet or Maven repository. How to test this? If you have acess to the conosle logs of your Jupyter notebook inside that container you can monitor what happens when you run `sparknlp.start()` command. If you see FAILED then it couldn't dowload the require dependencies. I am not sure if it's the networking on your Docker or your machine (it's off topic to this repo), but we use this sample to create Spark NLP container without issue: https://github.com/JohnSnowLabs/spark-nlp/discussions/1714 - So I would look into proxy/firewall/networking etc.

**Comment by ghnp5** [comment]
Thank you.

If I remove `spark = sparknlp.start()`, I get:

> AttributeError: Cannot load _jvm from SparkContext. Is SparkContext initialized?

Which is what I was getting initially, and then I found I had to initialize a session.

Heh... apparently restarting the Docker container resolved this..

> detect_language_21 download started this may take some time.
> Approx size to download 7.7 MB
> [OK!]
> {'document': ['Harry Potter is a great movie'],
>  'sentence': ['Harry Potter is a great movie'],
>  'language': ['en']}

Running multiple times also seems to work fine (I was expecting it would fail, due to the session/spark variable already existing, based on your first point above).


What I'm seeing now is that sometimes it hangs, until I shutdown and try again.
Not sure what it's doing when it hangs. That's before it even says "detect_language_21 download started this may take some time.".

Thank you anyway! Really appreciate that.

**Comment by ghnp5** [comment]
It only hangs when it's not downloaded yet (or maybe when it initializes the session).

Wow - I'm trying multiple short sentences, and this is REALLY pretty accurate!

Well done!
Thank you very much for this!

**Comment by ghnp5** [comment]
The reason it hangs is apparently because when the session is initialized, there's always downloads being done:


> :: loading settings :: url = jar:file:/usr/local/lib/python3.8/dist-packages/pyspark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
> Ivy Default Cache set to: /home/spark/.ivy2/cache
> The jars for the packages stored in: /home/spark/.ivy2/jars
> com.johnsnowlabs.nlp#spark-nlp_2.12 added as a dependency
> :: resolving dependencies :: org.apache.spark#spark-submit-parent-b3777ab5-e6ba-4470-9d27-bc8f9574571d;1.0
>    confs: [default]
>    found com.johnsnowlabs.nlp#spark-nlp_2.12;3.3.4 in central
>    found com.typesafe#config;1.4.1 in central
>    found org.rocksdb#rocksdbjni;6.5.3 in central
>    found com.amazonaws#aws-java-sdk-bundle;1.11.603 in central
>    found com.github.universal-automata#liblevenshtein;3.0.0 in central
>    found com.google.code.findbugs#annotations;3.0.1 in central
>    found net.jcip#jcip-annotations;1.0 in central
>    found com.google.code.findbugs#jsr305;3.0.1 in central
>    found com.google.protobuf#protobuf-java-util;3.0.0-beta-3 in central
>    found com.google.protobuf#protobuf-java;3.0.0-beta-3 in central
>    found com.google.code.gson#gson;2.3 in central
>    found it.unimi.dsi#fastutil;7.0.12 in central
>    found org.projectlombok#lombok;1.16.8 in central
>    found org.slf4j#slf4j-api;1.7.21 in central
>    found com.navigamez#greex;1.0 in central
>    found dk.brics.automaton#automaton;1.11-8 in central
>    found org.json4s#json4s-ext_2.12;3.5.3 in central
>    found joda-time#joda-time;2.9.5 in central
>    found org.joda#joda-convert;1.8.1 in central
>    found com.johnsnowlabs.nlp#tensorflow-cpu_2.12;0.3.3 in central
>    found net.sf.trove4j#trove4j;3.0.3 in central
> downloading https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.12/3.3.4/spark-nlp_2.12-3.3.4.jar ...
>    [SUCCESSFUL ] com.johnsnowlabs.nlp#spark-nlp_2.12;3.3.4!spark-nlp_2.12.jar (971ms)
> downloading https://repo1.maven.org/maven2/com/typesafe/config/1.4.1/config-1.4.1.jar ...
>    [SUCCESSFUL ] com.typesafe#config;1.4.1!config.jar(bundle) (34ms)
> downloading https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/6.5.3/rocksdbjni-6.5.3.jar ...
>    [SUCCESSFUL ] org.rocksdb#rocksdbjni;6.5.3!rocksdbjni.jar (695ms)
> downloading https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.603/aws-java-sdk-bundle-1.11.603.jar ...
>    [SUCCESSFUL ] com.amazonaws#aws-java-sdk-bundle;1.11.603!aws-java-sdk-bundle.jar (3594ms)
> downloading https://repo1.maven.org/maven2/com/github/universal-automata/liblevenshtein/3.0.0/liblevenshtein-3.0.0.jar ...
>    [SUCCESSFUL ] com.github.universal-automata#liblevenshtein;3.0.0!liblevenshtein.jar (24ms)
> downloading https://repo1.maven.org/maven2/com/navigamez/greex/1.0/greex-1.0.jar ...
>    [SUCCESSFUL ] com.navigamez#greex;1.0!greex.jar (18ms)
> downloading https://repo1.maven.org/maven2/org/json4s/json4s-ext_2.12/3.5.3/json4s-ext_2.12-3.5.3.jar ...
>    [SUCCESSFUL ] org.json4s#json4s-ext_2.12;3.5.3!json4s-ext_2.12.jar (22ms)
> downloading https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/tensorflow-cpu_2.12/0.3.3/tensorflow-cpu_2.12-0.3.3.jar ...
>    [SUCCESSFUL ] com.johnsnowlabs.nlp#tensorflow-cpu_2.12;0.3.3!tensorflow-cpu_2.12.jar (4159ms)
> downloading https://repo1.maven.org/maven2/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar ...
>    [SUCCESSFUL ] net.sf.trove4j#trove4j;3.0.3!trove4j.jar (86ms)
> downloading https://repo1.maven.org/maven2/com/google/code/findbugs/annotations/3.0.1/annotations-3.0.1.jar ...
>    [SUCCESSFUL ] com.google.code.findbugs#annotations;3.0.1!annotations.jar (19ms)
> downloading https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java-util/3.0.0-beta-3/protobuf-java-util-3.0.0-beta-3.jar ...
>    [SUCCESSFUL ] com.google.protobuf#protobuf-java-util;3.0.0-beta-3!protobuf-java-util.jar(bundle) (19ms)
> downloading https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.0-beta-3/protobuf-java-3.0.0-beta-3.jar ...
>    [SUCCESSFUL ] com.google.protobuf#protobuf-java;3.0.0-beta-3!protobuf-java.jar(bundle) (58ms)
> downloading https://repo1.maven.org/maven2/it/unimi/dsi/fastutil/7.0.12/fastutil-7.0.12.jar ...
>    [SUCCESSFUL ] it.unimi.dsi#fastutil;7.0.12!fastutil.jar (506ms)
> downloading https://repo1.maven.org/maven2/org/projectlombok/lombok/1.16.8/lombok-1.16.8.jar ...
>    [SUCCESSFUL ] org.projectlombok#lombok;1.16.8!lombok.jar (60ms)
> downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar ...
>    [SUCCESSFUL ] org.slf4j#slf4j-api;1.7.21!slf4j-api.jar (20ms)
> downloading https://repo1.maven.org/maven2/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar ...
>    [SUCCESSFUL ] net.jcip#jcip-annotations;1.0!jcip-annotations.jar (17ms)
> downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar ...
>    [SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.1!jsr305.jar (18ms)
> downloading https://repo1.maven.org/maven2/com/google/code/gson/gson/2.3/gson-2.3.jar ...
>    [SUCCESSFUL ] com.google.code.gson#gson;2.3!gson.jar (26ms)
> downloading https://repo1.maven.org/maven2/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar ...
>    [SUCCESSFUL ] dk.brics.automaton#automaton;1.11-8!automaton.jar (25ms)
> downloading https://repo1.maven.org/maven2/joda-time/joda-time/2.9.5/joda-time-2.9.5.jar ...
>    [SUCCESSFUL ] joda-time#joda-time;2.9.5!joda-time.jar (39ms)
> downloading https://repo1.maven.org/maven2/org/joda/joda-convert/1.8.1/joda-convert-1.8.1.jar ...
>    [SUCCESSFUL ] org.joda#joda-convert;1.8.1!joda-convert.jar (26ms)
> :: resolution report :: resolve 12812ms :: artifacts dl 10443ms
>    :: modules in use:
>    com.amazonaws#aws-java-sdk-bundle;1.11.603 from central in [default]
>    com.github.universal-automata#liblevenshtein;3.0.0 from central in [default]
>    com.google.code.findbugs#annotations;3.0.1 from central in [default]
>    com.google.code.findbugs#jsr305;3.0.1 from central in [default]
>    com.google.code.gson#gson;2.3 from central in [default]
>    com.google.protobuf#protobuf-java;3.0.0-beta-3 from central in [default]
>    com.google.protobuf#protobuf-java-util;3.0.0-beta-3 from central in [default]
>    com.johnsnowlabs.nlp#spark-nlp_2.12;3.3.4 from central in [default]
>    com.johnsnowlabs.nlp#tensorflow-cpu_2.12;0.3.3 from central in [default]
>    com.navigamez#greex;1.0 from central in [default]
>    com.typesafe#config;1.4.1 from central in [default]
>    dk.brics.automaton#automaton;1.11-8 from central in [default]
>    it.unimi.dsi#fastutil;7.0.12 from central in [default]
>    joda-time#joda-time;2.9.5 from central in [default]
>    net.jcip#jcip-annotations;1.0 from central in [default]
>    net.sf.trove4j#trove4j;3.0.3 from central in [default]
>    org.joda#joda-convert;1.8.1 from central in [default]
>    org.json4s#json4s-ext_2.12;3.5.3 from central in [default]
>    org.projectlombok#lombok;1.16.8 from central in [default]
>    org.rocksdb#rocksdbjni;6.5.3 from central in [default]
>    org.slf4j#slf4j-api;1.7.21 from central in [default]
>    ---------------------------------------------------------------------
>    |                  |            modules            ||   artifacts   |
>    |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
>    ---------------------------------------------------------------------
>    |      default     |   21  |   21  |   21  |   0   ||   21  |   21  |
>    ---------------------------------------------------------------------
> :: retrieving :: org.apache.spark#spark-submit-parent-b3777ab5-e6ba-4470-9d27-bc8f9574571d
>    confs: [default]
>    21 artifacts copied, 0 already retrieved (399627kB/304ms)
> 21/12/04 19:21:17 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
> Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
> Setting default log level to "WARN".
> To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
> detect_language_21 download started this may take some time.
> Approx size to download 7.7 MB


(and the model seems to be always downloaded too, every time)

**Comment by maziyarpanahi** [comment]
- Glad your issue is resolved with the session. (it's usually a network issue in Docker when it cannot download dependencies during `sparknlp.start()`. 
- You will always see those messages regarding downloading dependencies or downloading models/pipelines. But they don't actually download anything if it already exists. For dependencies it will take them from ` /home/spark/.ivy2/cache` and for models/pipelines it will take them from `~/cache_pretrained`. Nothing will ever be downloaded twice, unless the Docker doesn't have enough resources so it appears to be slow when it actually loading them.
