### ISSUE TITLE
License already in use

### ISSUE THREAD

**Issue by karthikavarmar** [JohnSnowLabs/spark-nlp#6576]
When I re-ran a demo notebook or is trying to run another demo pipeline of spark Healthcare, it throws error as below :

An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.InternalsPythonResourceDownloader.downloadModel.
: com.johnsnowlabs.license.exceptions.JslInvalidLicenseException: Cannot check-in the license or license already in use.
 
![Screenshot (387)](https://user-images.githubusercontent.com/71928132/144901083-afb2768c-6925-46c6-9634-dc3353480279.png)

Please suggest a solution asap.

**Comment by maziyarpanahi** [comment]
Hi,

Unfortunately, we don't have any way to test anything that is licensed (even if it's related to open source). You can use direct email or Slack (#healthcare channel) for your questions regarding licensed products. (they are very quick and sort this out for you immediately via those channels)
