### ISSUE TITLE
Making RecursiveTokenizerModel ParamsAndFeaturesReadable

### ISSUE THREAD

**Issue by headlessButSmart** [JohnSnowLabs/spark-nlp#6679]
## Description

I believe RecursiveTokenizerModel is ParamsAndFeaturesWritable but not ParamsAndFeaturesReadable. When you save a pipeline with a RecursiveTokenizer, loading this pipeline using PipelineModel.load() fails.

## Expected Behavior

It should be possible to save & load a Pipeline with RecursiveTokenizer without workarounds.

## Current Behavior

PipelineModel.load() results in following Py4JJavaError:

java.lang.NoSuchMethodException: com.johnsnowlabs.nlp.annotators.RecursiveTokenizerModel.read()

## Possible Solution

Looks like some other Models apply following to enable read() calls, which might be applicable to RecursiveTokenizerModel:

object ChunkTokenizerModel extends ParamsAndFeaturesReadable[ChunkTokenizerModel]

## Steps to Reproduce

1. Create a RecursiveTokenizer()
2. Create a Pipeline() with stages including the tokenizer
3. Perform pipeline.save() to local path
4. Perform PipelineModel.load() from local path

## Context

We're trying to save and load a spell checker pipeline which has this tokenizer.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.3.4
* Apache NLP version `spark.version`: 3.2.0
* Java version `java -version`:  openjdk version "11.0.11" 2021-04-20
* Setup and installation (Pypi, Conda, Maven, etc.): Running on Google Colab, with pip install sparknlp & pyspark only
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RecursiveTokenizerModel](https://trello.com/c/LFFyrsz4/499-recursivetokenizermodel)
