### ISSUE TITLE
com.johnsnowlabs.nlp#spark-nlp-ocr_2.11;2.3.0: not found

### ISSUE THREAD

**Issue by mmarks13** [JohnSnowLabs/spark-nlp#668]
It appears that the most recent .jar (2.3.0) for the OCR module is not in any of the repositories. 

[mvnrepository](https://mvnrepository.com/artifact/com.johnsnowlabs.nlp/spark-nlp-ocr)
[repo.spring.io](http://repo.spring.io/plugins-release/com/johnsnowlabs/nlp/spark-nlp-ocr_2.11/)

Following the [OCR Module README](https://github.com/JohnSnowLabs/spark-nlp/blob/master/README.md#ocr-module) results in the following error:

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: com.johnsnowlabs.nlp#spark-nlp-ocr_2.11;2.3.0: not found

                ::::::::::::::::::::::::::::::::::::::::::::::

Thank you for your work on this wonderful package.

**Comment by maziyarpanahi** [comment]
I believe that module is no longer supported within the open source code: https://github.com/JohnSnowLabs/spark-nlp/releases/tag/2.3.0
