### ISSUE TITLE
NerCrfModel capitalization in the docs does not match the source file. 

### ISSUE THREAD

**Issue by marcinic** [JohnSnowLabs/spark-nlp#682]
https://nlp.johnsnowlabs.com/docs/en/models
The model is listed as NerCRFModel (NER with GloVe).

The source file is NerCrfModel
https://github.com/JohnSnowLabs/spark-nlp/blob/master/src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfModel.scala

Trying to import based on the documentation will give a not found error. A quick fix would be to to change the docs to match the source. Is NerCrfModel the capitalization convention we want or should I change the source to match NerDLModel?

**Comment by maziyarpanahi** [comment]
I close this issue as I approved the PR and it will be merged in the next release. 
Thanks for your contribution.
