### ISSUE TITLE
Getting an error when using Spark NLP with GPU support in CoLab

### ISSUE THREAD

**Issue by Dirkster99** [JohnSnowLabs/spark-nlp#6821]
I am trying to do a `MultiClassifierDLApproach` to train a Multi-Label Multi-Class model but it seems to always end in an error when I try to use the GPU in the public Google CoLab environment. I am using the following setting
![Untitled](https://user-images.githubusercontent.com/2129700/151079816-577c25a5-f6a1-44bb-b1d2-37fee8b055e6.png)

with the attached notebook:
[40_Training.zip](https://github.com/JohnSnowLabs/spark-nlp/files/7937978/40_Training.zip)

## Description

Here is a short version of the code used (please see attached notebook for full listing:
```py
# Install PySpark and Spark NLP
! pip install -q pyspark==3.1.2 spark-nlp==3.3.1

from pyspark.ml import PipelineModel
from sparknlp.annotator import *
from sparknlp.base import *
import sparknlp

spark = sparknlp.start(gpu=True)
spark

import sparknlp
from sparknlp.base import *
from sparknlp.annotator import *
from pyspark.ml import Pipeline


documentAssembler = DocumentAssembler() \
    .setInputCol("text") \
    .setOutputCol("document") \
    .setCleanupMode("shrink")

# Docs:
# https://nlp.johnsnowlabs.com/2021/07/20/sent_bert_use_cmlm_multi_base_xx.html
embeddings = BertSentenceEmbeddings.pretrained("sent_bert_use_cmlm_multi_base", "xx") \
    .setInputCols("document") \
    .setOutputCol("embeddings")

# Docs:
# https://nlp.johnsnowlabs.com/api/python/reference/autosummary/sparknlp.annotator.MultiClassifierDLApproach.html#sparknlp.annotator.MultiClassifierDLApproach
docClassifier = MultiClassifierDLApproach() \
    .setInputCols("embeddings") \
    .setOutputCol("category") \
    .setLabelColumn("labels") \
    .setBatchSize(128) \
    .setMaxEpochs(2) \
    .setShufflePerEpoch(True) \
    .setLr(1e-3) \
    .setThreshold(0.65) \
    .setValidationSplit(0.2) \
    .setVerbose(1)\
    .setEnableOutputLogs(True).setOutputLogsPath('/tmp/annotator_logs/')

pipeline = Pipeline().setStages([
    documentAssembler,
    embeddings,
    docClassifier
])

dataDF = spark.read.format("json").load(baseDataPath + 'raw_data/all_sentences_details_TopicsMatrix.json') \
         .withColumnRenamed('sentences', 'text') \
         .withColumnRenamed('TopicsArray', 'labels')

print (dataDF.count())
dataDF.printSchema()
dataDF.show(15)

dataDF = dataDF.where(isEmpty('labels') == False).select('labels','text').limit(1000)
dataDF.count()

%%time
pipelineModel = pipeline.fit(dataDF)

```

## Expected Behavior

This should train the model with the dataframes text and labels.

## Current Behavior

But I am always receiving the error below when I turn GPU support on while the notebook works fine (albeit slow) when I turn GPU support of and initialize the Spark session with `gpu=False`. This makes me think that I am doing something wrong when I try to use GPU support in the public CoLab environment(?).

Can you see what I am doing wrong or why I am receiving below error message?

I have tried this with current SparkNLP version 3.4 and earlier 3.3.1 but the error remains :-(

## Steps to Reproduce

See attached notebook for all details.

## Error Message

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55962)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/dist-packages/pyspark/accumulators.py", line 262, in handle
    poll(accum_updates)
  File "/usr/local/lib/python3.7/dist-packages/pyspark/accumulators.py", line 235, in poll
    if func():
  File "/usr/local/lib/python3.7/dist-packages/pyspark/accumulators.py", line 239, in accum_updates
    num_updates = read_int(self.rfile)
  File "/usr/local/lib/python3.7/dist-packages/pyspark/serializers.py", line 564, in read_int
    raise EOFError
EOFError
----------------------------------------
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/py4j/java_gateway.py", line 1207, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/py4j/java_gateway.py", line 1033, in send_command
    response = connection.send_command(command)
  File "/usr/local/lib/python3.7/dist-packages/py4j/java_gateway.py", line 1212, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving

---------------------------------------------------------------------------
Py4JError                                 Traceback (most recent call last)
<ipython-input-14-0a82ed432838> in <module>()
----> 1 get_ipython().run_cell_magic('time', '', 'pipelineModel = pipeline.fit(dataDF)')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2115             magic_arg_s = self.var_expand(line, stack_depth)
   2116             with self.builtin_trap:
-> 2117                 result = fn(magic_arg_s, cell)
   2118             return result
   2119 

<decorator-gen-53> in time(self, line, cell, local_ns)

/usr/local/lib/python3.7/dist-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/usr/local/lib/python3.7/dist-packages/IPython/core/magics/execution.py in time(self, line, cell, local_ns)
   1191         else:
   1192             st = clock2()
-> 1193             exec(code, glob, local_ns)
   1194             end = clock2()
   1195             out = None

<timed exec> in <module>()

/usr/local/lib/python3.7/dist-packages/pyspark/ml/base.py in fit(self, dataset, params)
    159                 return self.copy(params)._fit(dataset)
    160             else:
--> 161                 return self._fit(dataset)
    162         else:
    163             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/usr/local/lib/python3.7/dist-packages/pyspark/ml/pipeline.py in _fit(self, dataset)
    112                     dataset = stage.transform(dataset)
    113                 else:  # must be an Estimator
--> 114                     model = stage.fit(dataset)
    115                     transformers.append(model)
    116                     if i < indexOfLastEstimator:

/usr/local/lib/python3.7/dist-packages/pyspark/ml/base.py in fit(self, dataset, params)
    159                 return self.copy(params)._fit(dataset)
    160             else:
--> 161                 return self._fit(dataset)
    162         else:
    163             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/usr/local/lib/python3.7/dist-packages/pyspark/ml/wrapper.py in _fit(self, dataset)
    333 
    334     def _fit(self, dataset):
--> 335         java_model = self._fit_java(dataset)
    336         model = self._create_model(java_model)
    337         return self._copyValues(model)

/usr/local/lib/python3.7/dist-packages/pyspark/ml/wrapper.py in _fit_java(self, dataset)
    330         """
    331         self._transfer_params_to_java()
--> 332         return self._java_obj.fit(dataset._jdf)
    333 
    334     def _fit(self, dataset):

/usr/local/lib/python3.7/dist-packages/py4j/java_gateway.py in __call__(self, *args)
   1303         answer = self.gateway_client.send_command(command)
   1304         return_value = get_return_value(
-> 1305             answer, self.gateway_client, self.target_id, self.name)
   1306 
   1307         for temp_arg in temp_args:

/usr/local/lib/python3.7/dist-packages/pyspark/sql/utils.py in deco(*a, **kw)
    109     def deco(*a, **kw):
    110         try:
--> 111             return f(*a, **kw)
    112         except py4j.protocol.Py4JJavaError as e:
    113             converted = convert_exception(e.java_exception)

/usr/local/lib/python3.7/dist-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    334             raise Py4JError(
    335                 "An error occurred while calling {0}{1}{2}".
--> 336                 format(target_id, ".", name))
    337     else:
    338         type = answer[1]

Py4JError: An error occurred while calling o88.fit

```
## Your Environment

* Spark NLP version `sparknlp.version()`: 3.3.1
* Apache NLP version `spark.version`: 3.1.2
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,

I tried to make it as similar as possible with GPU on Colab and same parameters for training, it worked without any issue: https://colab.research.google.com/drive/1SdP2DgWC4TWOsRL9wne3vd8GUd3MDcno?usp=sharing

The error indicates the SparkSession was killed and normally it's due to either excessive memory use or something different. - Colab has more memory on CPU than GPU
- Every time you use `.limit` you have a different number of rows, I suggest using `.sample(0.1, seed=1234)` 
- Could be something bad in the input that causes this and randomly happens on any device

In terms of code, process, steps, etc. there is no difference between GPU and CPU usage in Spark NLP. If the GPU is available, compatible (cuda, cudnn), and Spark NLP is started with GPU, then everything is 100% the same. (if it runs on CPU, it must run on GPU and vice versa unless GPU runs out of the memory due to being always smaller than the whole system's memory compared to CPU or one of the points I mentioned could happen to give the feeling GPU is different)

**Comment by Dirkster99** [comment]
You seem to be right about the memory issue :-(

I found an alternative German specific model (https://nlp.johnsnowlabs.com/2021/09/15/sent_bert_base_cased_de.html) which I must have missed yesterday :-( anyways, since this is 300 Mb versus 1.7 Gb it runs through with a top limit file containing only the top 1000 entries. I'd like to do further tests but thats not an option right now since I cannot get an available GPU resource :-(

I think this issue can be closed but I have one question about pre-trained models. I would like to use CoLab to contribute pre-trained German models. Do you know whether thats possible resource vice, and if so, how would I proceed? If thats too much off topic can I open a seperate issue for it? Thanx Dirk

**Comment by Dirkster99** [comment]
OK, I got it finally to work for the complete dataset with the smaller German pre-trained model (after 1 trial that error'ed out after 2 hours and 1 trial that worked with 25 % of the total 225 K rows). But there seems to be an awful issue here, because I've seen this spike in memory usage which had appeared after the computation (about 4 hours) and probably during the saving of the models :-( Thats especially awful because it happens so late in the process :-(

Is it possible that the model saving could be responsible for the spike in memory usage? and if so could this be avoided?

![Untitled](https://user-images.githubusercontent.com/2129700/151609775-58821e46-326e-463c-b7bc-efec26715f4c.png)

Here's the code that I used to save the model:

```py
saveModelPath=drivePath +'models/V2/ClassifierDLModel/'
pipelineModel.stages[2].write().overwrite().save(saveModelPath)
```

```py
saveModelPath=drivePath +'models/V2/BertSentenceEmbeddings/'
pipelineModel.stages[1].write().overwrite().save(saveModelPath)
```

**Comment by maziyarpanahi** [comment]
Hi @Dirkster99 

The ClassifierDLModel is very small. I think it's 20MB raw and when it's compressed it's around 3-4MB. But the BERT is larger and depending on which model you are using this can be memory intensive when we ask for the actual weights. (but the good thing is you never need to save any of the Embeddings models, they are not trainable so they are exactly the same before or after any task being trained. Only the trained model which in this case is ClassifierDL model should be saved)
