### ISSUE TITLE
The output for token assembler cannot be used input to BertSentenceEmbeddings

### ISSUE THREAD

**Issue by akashindani** [JohnSnowLabs/spark-nlp#6827]
## Description

I am trying to use a sentence detector followed by a tokenizer and tokenNormalizer for removing some unwanted characters from sentences. After that, I am using tokenassembler to form back the sentences followed by BErtsentenceEmbedding to get the embeddings of those sentences. But the issue is here BErtsentenceEmbedding is not taking each sentence as input but creating embedding for the whole document.

## Expected Behavior

Sentence Embedding should be created for each sentence and not the whole document

## Current Behavior

Taking the whole document for the Sentence Embedding

## Possible Solution

Allow sentences tokenassembler as input to BErtsentenceEmbedding 

## Steps to Reproduce

documentAssembler = DocumentAssembler() \
    .setInputCol("FileText") \
    .setOutputCol("document")

sentence = SentenceDetectorDLModel\
  .pretrained("sentence_detector_dl","en") \
  .setInputCols(["document"]) \
  .setOutputCol("sentencesDL") \
  .setExplodeSentences(False)

tokenizer = Tokenizer() \
    .setInputCols(["sentencesDL"]) \
    .setOutputCol("token")

normalizer = Normalizer() \
    .setInputCols(["token"]) \
    .setOutputCol("normalized") \
    .setLowercase(False)\
    .setCleanupPatterns([ r'([\r\n]+|\r)', r'•'])

tokenAssembler = TokenAssembler() \
    .setInputCols(["sentencesDL", "normalized"]) \
    .setOutputCol("cleanText")

embeddings = BertSentenceEmbeddings.pretrained("sent_biobert_clinical_base_cased", "en") \
      .setInputCols("cleanText") \
      .setOutputCol("sentence_embeddings")

pipeline = Pipeline().setStages([
    documentAssembler,
    sentence,
    tokenizer,
    normalizer,
    tokenAssembler,
    embeddings])

data = spark.createDataFrame([[""]]).toDF("FileText")
fit_pipeline = pipeline.fit(data)

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.1.3
* Apache NLP version `spark.version`: 
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,

I know this issue but I forgot which version it was resolved. However, the latest 3.4.0 should work as is expected: 
demo https://colab.research.google.com/drive/1HSXPqksffuYjDrNzvta546EHME2xd-iE?usp=sharing
