### ISSUE TITLE
Saving the sparknlp models in Tensorflow or keras format

### ISSUE THREAD

**Issue by dsvrsecc** [JohnSnowLabs/spark-nlp#6831]
Is it possible to save the sparknlp models in Tensorflow or keras format so that they can be further pruned or qunatized for better performance

**Comment by maziyarpanahi** [comment]
Hi,
No, the saved models are Spark/Spark NLP format and the purpose of them is to be used in the same library and not to be universal. (not that we didn't want to, it is not possible with so many libraries staked together to do such a thing)

**Comment by dsvrsecc** [comment]
Thanks for the response.
In that case,is there any way to do quantization or pruning of developed spark NLP models

**Comment by maziyarpanahi** [comment]
Models that are imported via HuggingFace or TF Hub you can do that before and then reimport them: https://github.com/JohnSnowLabs/spark-nlp/discussions/5669

The rest we developed are no where near those giants language models to be worth quantizing. (But anything has to happen before and outside before being imported, pretrained models and existing saved modela in Spark NLP cannot be used in TenaorFlow.
