### ISSUE TITLE
Parameters that can be tuned for BertEmbeddings component

### ISSUE THREAD

**Issue by dsvrsecc** [JohnSnowLabs/spark-nlp#6832]
Hi,

In this blog 'https://towardsdatascience.com/named-entity-recognition-ner-with-bert-in-spark-nlp-874df20d1d77' ,there is a parameter 'setPoolingLayer' ,but in the latest version,I couldn't define this parameter as it is not available and I couldn't find about it in the documentation section as well. In this case,what is the default value of pooling layer of bert that is set.

**Comment by maziyarpanahi** [comment]
Hi,

none of those language models are trainable nor can be fine tuned just in case. There posts which are old so lots of things have changed or deprecated. We have a very complete documentation for everything that you can look to see how to use the new releases: https://nlp.johnsnowlabs.com/docs/en/quickstart

as it is mentioned in the docs (importing transformers, it is the last hidden layer)
