### ISSUE TITLE
How to load own models in spark nlp server

### ISSUE THREAD

**Issue by desis123** [JohnSnowLabs/spark-nlp#6866]
I am pretty new to ML and all this stuff. So it might sound dumb question. I have successfully installed the spark NLP server on my centos 8 OS.   Everything is working as expected. 

My question on sparknlp server how I can load my own model and use it through OPENAPI comes sparknlp server ?

**Comment by maziyarpanahi** [comment]
Hi @desis123 

It's actually a very good question. However, we are not that versed in other libraries using Spark NLP a dependency. The best place for this question can be on our Slack under `nlp-server` channel. (you can easily chat with the people who are developing it)

https://www.johnsnowlabs.com/slack-redirect/

**Comment by C-K-Loan** [comment]
Hi @desis123 
currently, there is no support yet for custom models for the NLP server, but it's on the roadmap and should be available in 1-2 releases, ~ 1 month
