### ISSUE TITLE
Spanish Lemmatizer

### ISSUE THREAD

**Issue by shulpeca** [JohnSnowLabs/spark-nlp#6877]
## Description

When I use Spanish lemmatizer, there are some nouns that don't erase the final 's' to convert to proper form. 
For example noun "envolvedoras" the lemma is "envolvedora" but the lemmatizer don't erase the last 's'. Otherwise, noun 'meses' is fine as the lemma is 'mes'.

## Expected Behavior

**Value** ----------- **Lemma** ----------- **Pos**
envolvedora -------- envolvedora --------- NOUN
envolvedoras ------- envolvedora --------- NOUN
bioestimulante ----- bioestimulante ------- NOUN
bioesitmulantes ---- bioestimulante ------- NOUN
meses --------------- mes ------------------- NOUN

## Current Behavior

**Value** ----------- **Lemma** ----------- **Pos**
envolvedora -------- envolvedora --------- NOUN
envolvedoras ------- envolvedoras -------- NOUN
bioestimulante ----- bioestimulante ------- NOUN
bioesitmulantes ---- bioestimulantes ------ NOUN
meses --------------- mes ------------------ NOUN

## Possible Solution

I don't know how can I fix this problem.

## Steps to Reproduce

```
text_df = spark.createDataFrame([["La envolvedora. Las envolvedoras. ¡Se fueron como un sueño los tres meses de vaciones!"]], "value"])

document_assembler = DocumentAssembler() \
    .setInputCol('value') \
    .setOutputCol('document')

tokenizer = Tokenizer() \
    .setSplitPattern("[\\p{L}\\w]+") \
    .setInputCols(['document']) \
    .setOutputCol('token')
    
posTagger = PerceptronModel.pretrained("pos_ud_gsd", "es") \
    .setInputCols(["document", "token"]) \
    .setOutputCol("pos")

lemmatizer = LemmatizerModel.pretrained("lemma", "es") \
    .setInputCols(['token', 'pos']) \
    .setOutputCol("lemmatized")

finish_pipeline = Pipeline(
    stages = [
        document_assembler,
        tokenizer,
        posTagger,
        lemmatizer
    ]
)

result = finish_pipeline.fit(text_df).transform(text_df)
```

## Context

After a lemmatizer process, I want to do a Tf-idf process, but the problem is that the words "envolvedoras" and "envolvedoras" is the same word, but when I apply lemmatizer the result is not the same words, so I can't do Tf-idf as the result is not accurate.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.4.0
* Apache NLP version `spark.version`:  3.1.2
* Java version `java -version`: 1.8.0_321
* Setup and installation (Pypi, Conda, Maven, etc.): Conda
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,

I'll see if we can find another dataset to train a Lemmatizer for the Spanish language that is more accurate, but I am afraid there is no Lemmatizer that is 100% accurate. In any case, if there are some known tokens that are not transforming to the correct lemma form, you can use Normalizer + SlangDict which takes all tokens like `bioestimulantes` and converts them to `bioestimulante` and so on.

I'll update here with a new model for Lemma in Spanish for you to test it.

**Comment by shulpeca** [comment]
Thank you for your fast answer.

I have been searching in your web, but I don't find the SlangDict that you mencioned before. Where can I found it?

Or if I have to create one for myself.

Thank you!

**Comment by shulpeca** [comment]
On the other hand, one of the best spanish lemmatizer has been trained with this dataset.

I don't know if it would be possible to train the lemmatizer with this dataset: https://github.com/UniversalDependencies/UD_Spanish-AnCora

Thank you!

**Comment by maziyarpanahi** [comment]
@shulpeca 
Yes, it's possible. I can ask someone to train a new Spanish Lemmatizer based on the lemma in that dataset. (most of our lemma comes from the UD dataset, but not the Spanish one so hopefully this helps)

**Comment by josejuanmartinez** [comment]
That model has been trained using specifically that UD_Spanish-AnCora dataset:

![image](https://user-images.githubusercontent.com/36634572/153230875-e16d1da7-bbd8-482c-b3cc-2f7fb01b5cba.png)

I have retrained it just in case but the results are the same. So I guess that the corpus does not have a very good coverage.

**Comment by josejuanmartinez** [comment]
![image](https://user-images.githubusercontent.com/36634572/153231252-79887124-7dbd-4bb5-898c-939c063a9da1.png)

**Comment by maziyarpanahi** [comment]
@josejuanmartinez @shulpeca 

The Lemmatizer annotator/model is entirely rule-based, meaning if there is no example for those words it will generate the same. In the [UD_Spanish-AnCora](https://github.com/UniversalDependencies/UD_Spanish-AnCora) there are no `bioestimulante(s)` or `envolvedora(s)` so it won't know what to do with them. 

Are these words domain specific? We can perhaps find other sources that cover the given domain if possible.

**Comment by shulpeca** [comment]
I thought that corpus would work well, as I use the ancora package from Stanza that is training with that corpus and I don't have this kind of problem with the words `bioestimulante(s)`.

**Comment by maziyarpanahi** [comment]
Unfortunately, unless there is an example that says `bioestimulantes` should be considered as `bioestimulante` in the training corpus the model won't know. 

However, you can improve this (resolve any issue) by custom rules as I mentioned before. We have an annotator called Normalizer that accepts dictionary and it transforms the tokens to another form, here is an example of how you can convert `bioestimulantes` to `bioestimulante` before going to Lemma:

https://colab.research.google.com/drive/14kv4eyuvEuyvcpnLKegLBSoKO-DxEy90?usp=sharing

**Comment by unoexperto** [comment]
Hi folks. I'm on version 4.5.1 and it doesn't seem to work for me. My code

```
    val props = StringUtils.argsToProperties("-props", "StanfordCoreNLP-spanish.properties")
    props.setProperty("annotators", "tokenize,pos,lemma");

    val pipeline = StanfordCoreNLP(props)
    val document = pipeline.processToCoreDocument("Prefieren simular que no sucedió.")
    for (tok in document.tokens()) {
        println(String.format("%s\t%s", tok.word(), tok.lemma()))
    }
```

What am I missing @maziyarpanahi @josejuanmartinez  ?
