### ISSUE TITLE
Resolve annotators and pipelines consuming lots of driver RAM

### ISSUE THREAD

**Issue by saifjsl** [JohnSnowLabs/spark-nlp#69]
## Description

Annotators, specifically the Vivekn Sentiment Analysis, is consuming lots of driver RAM due to standard scala collections containing model information. This becomes a storage both inside pipelines and when reading the models back. We need to let this information flow from disk instead

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by aleksei-ai** [comment]
@saifjsl Please try my fix with Kryo Serialization. Let me know is it works for you https://github.com/JohnSnowLabs/spark-nlp/tree/vivekn_sentiment_model_kryo_serialization

**Comment by saifjsl** [comment]
https://github.com/JohnSnowLabs/spark-nlp/pull/78
