### ISSUE TITLE
DeprecationWarning: invalid escape sequence

### ISSUE THREAD

**Issue by wboleksii** [JohnSnowLabs/spark-nlp#692]
I'm getting a bunch of warnings in the latest 2.3.3 version:

```
/sparknlp/annotator.py:50: DeprecationWarning: invalid escape sequence \S
/sparknlp/annotator.py:55: DeprecationWarning: invalid escape sequence \A
/sparknlp/annotator.py:60: DeprecationWarning: invalid escape sequence \z
```

I'm using Databricks (Spark 2.4.3, Scala 2.11)

**Comment by maziyarpanahi** [comment]
They are harmless warnings, we'll see if we can get rid of them but in any case, it won't affect the usage.
