### ISSUE TITLE
Multiple (different) pipelines causing sentence embeddings to embed whole document

### ISSUE THREAD

**Issue by amrothemich** [JohnSnowLabs/spark-nlp#6924]
## Description
When I create a pipeline (DocumentAssembler -> SentenceDetectorDLModel -> BertSentenceEmbeddings), the output is correct. When I create a second pipeline to process a different dataset with **no** sentence detector (DocumentAssembler -> BertSentenceEmbeddings), its output is correct. However, when I then access the first dataset again, BertSentenceEmbeddings uses the whole document (even though the SentenceDetectorDLModel is run and its output column is correct).

## Expected Behavior
The first dataset's sentence embeddings column should be the same before and after running the second pipeline on the second dataset. The sentence embeddings should be of the SentencesDL column, not the document column.

## Current Behavior
The sentence embeddings are run on the whole document column.

## Possible Solution
Not sure.

## Steps to Reproduce
1. Imports:
```
import sparknlp
from pyspark.ml import Pipeline
from sparknlp.annotator import *
from sparknlp.base import *
```

2. Run first pipeline
```
documentAssembler1 = DocumentAssembler() \
    .setInputCol("FileText") \
    .setOutputCol("document")

cleanUpPatterns = ["""[^\w\d\s]"""]

sentence = SentenceDetectorDLModel\
  .pretrained("sentence_detector_dl","en") \
  .setInputCols(["document"]) \
  .setOutputCol("sentencesDL") \
  .setExplodeSentences(True)

embeddings1 = BertSentenceEmbeddings.pretrained("sent_biobert_clinical_base_cased", "en") \
      .setInputCols("sentencesDL") \
      .setOutputCol("sentence_embeddings")

pipeline1 = Pipeline().setStages([
    documentAssembler1,
    sentence,
    embeddings1
    ])

empty1 = spark.createDataFrame([[""]]).toDF("FileText")
fit_pipeline1 = pipeline1.fit(empty1)

data1 = spark.createDataFrame([["this is the first sentence. this is the second. only one should appear in the sentence embeddings column."]]).toDF("FileText")

with_sentence_detector = fit_pipeline1.transform(data1)
display(with_sentence_detector)
```
3. Note that the sentence embeddings are on the sentences:

```
[{"annotatorType": "sentence_embeddings", "begin": 0, "end": 26, "result": "this is the first sentence.", "metadata": {"sentence": "0", "token": "this is the first sentence.", "pieceId": "-1", "isWordStart": "true"},
```
4. Run second pipeline:
```
documentAssembler2 = DocumentAssembler() \
    .setInputCol("requirement") \
    .setOutputCol("document")

embeddings2 = BertSentenceEmbeddings.pretrained("sent_biobert_clinical_base_cased", "en") \
      .setInputCols("document") \
      .setOutputCol("requirement_embeddings")

pipeline2 = Pipeline().setStages([
    documentAssembler2,
    embeddings2
])

empty2 = spark.createDataFrame([[""]]).toDF("requirement")
data2 = spark.createDataFrame([["only one sentence here"]]).toDF("requirement")

fit_pipeline2 = pipeline2.fit(empty2)

without_sentence_detector = fit_pipeline2.transform(data2)
display(without_sentence_detector)
``` 
5. Note that output is correct
6. Display first dataset again:
```
display(with_sentence_detector)
```
7. Note that although SentenceDetectorDL output column is present, sentence embeddings are now performed on entire document
```

[{"annotatorType": "sentence_embeddings", "begin": 0, "end": 104, "result": "this is the first sentence. this is the second. only one should appear in the sentence embeddings column.", "metadata": {"sentence": "0", "token": "this is the first sentence. this is the second. only one should appear in the sentence embeddings column.", "pieceId": "-1", "isWordStart": "true"}
```

## Context
We were embedding two datasets to compare their embeddings, one of which only had one sentence. We had to save the first dataset to disk in order to prevent this issue, which was time-consuming.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.4.1
* Apache NLP version `spark.version`: 3.0.1
* Java version `java -version`: 
```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (Zulu 8.52.0.23-CA-linux64) (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (Zulu 8.52.0.23-CA-linux64) (build 25.282-b08, mixed mode)
```

* Setup and installation (Pypi, Conda, Maven, etc.): Pypi
* Operating System and version: Databricks DBR 7.3 LTS
* Link to your project (if any): unavailable

**Comment by maziyarpanahi** [comment]
Hi,

This actually happens inside BertSentenceEmbeddings. In Spark NLP, you can have 1 AnnotatorModel that uses `.pretrained` in a live session. So your second BertSentenceEmbeddings.pretrained overrides your first one.

```python
embeddings1 = BertSentenceEmbeddings.pretrained("sent_biobert_clinical_base_cased", "en") \
      .setInputCols("sentencesDL") \
      .setOutputCol("sentence_embeddings")

embeddings2 = BertSentenceEmbeddings.pretrained("sent_biobert_clinical_base_cased", "en") \
      .setInputCols("document") \
      .setOutputCol("requirement_embeddings")

# they are both referring to the same AnnotatorModel 
# the variables are just references to the same object now
>>> embeddings1
BERT_SENTENCE_EMBEDDINGS_98ff48ba58c1
>>> embeddings2
BERT_SENTENCE_EMBEDDINGS_98ff48ba58c1
```

The only way to reuse the same AnnotatorModel (like BertSentenceEmbeddings) more than once is to save the results on disks (which you tried), but it's not a bug, this is how Spark NLP was designed when it comes to `.pretrained()`. (I am guessing the decision behind this was to reuse the same loaded model over and over, that's why you can run your pipeline 100x times and it will be the same models with no extra memory assigned)

**Comment by amrothemich** [comment]
okay, thanks for the prompt response! If you'll allow an outside opinion, I think it is typically the user's responsibility to recognize that creating a second instance will require twice the memory. The way it is implemented here, there's a silent "failure" that's very easy to miss, where as "out of memory" is easily recognized and addressed.

**Comment by dataanalyst4lyfe** [comment]
Question: Is this also true of non-pretrained models? i.e. if I used `BertSentenceEmbeddings.load(...)` multiple times, I would be referring to different instances of the AnnotatorModel, correct?

**Comment by maziyarpanahi** [comment]
Hi,

You can use the snippet code I provided to check the UIF of the instance. To my knowledge, loading the exact same model will be loaded once, same as the pretrained. (I will check this and update if it was not the case)
