### ISSUE TITLE
py4j error

### ISSUE THREAD

**Issue by paper-revise-crypt-12** [JohnSnowLabs/spark-nlp#695]
Hello,

I'm getting this error when running pipeline = PretrainedPipeline('explain_document_dl', lang='en')

"py4j.protocol.Py4JError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline"

This also happens when I call the Bert pretrained model:
word_embeddings = BertEmbeddings.pretrained('bert_uncased', 'en')\
    .setInputCols(["document"])\
    .setOutputCol('bert')

I'm using Spark NLP version 2.2.1 and Apache Spark version 2.4.3. 

Any help would be much appreciated. Thanks.

**Comment by maziyarpanahi** [comment]
Could you please fill the template completely, it is really important for us to know the rest of the information. 
PS: Please try to use the latest releases `2.3.3` and the right model's name (can be found here: https://nlp.johnsnowlabs.com/docs/en/models)
