### ISSUE TITLE
Not able to use ALAB

### ISSUE THREAD

**Issue by dsvrsecc** [JohnSnowLabs/spark-nlp#6953]
Hi,

I tried to update the ALAB version from 2.5.1 to 2.7.0 .After updation ,I am not able to find the previous created projects in 2.5.1 .So,then I degraded the version to 2.5.1 again,but I am not able to open ALAB.Can you please suggest on this

![image](https://user-images.githubusercontent.com/98377895/154805122-ad95cb61-49c2-42d6-b406-5f2b2ee954a6.png)

**Comment by maziyarpanahi** [comment]
Hi,

This is a repository for Spark NLP, we don’t have any knowledge for other product’s. 

For other libraries you can directly contact their team on Slack: https://www.johnsnowlabs.com/slack-redirect/ 
(It should be under annotation-lab channel)
