### ISSUE TITLE
Unable to load saved pipelinemodel if i used Stemmer in the pipeline

### ISSUE THREAD

**Issue by siddarthareddyt** [JohnSnowLabs/spark-nlp#71]
The error: **java.lang.NoSuchMethodException: com.johnsnowlabs.nlp.annotators.Stemmer.read()**
## Description

I have trained a classifier with following Annotators:
     documentAssembler,
      sentenceDetector,
      tokenizer,
      normalizer,
      spellChecker,
      stemmer,
      finisher,
      filterer.

The model is trained and saved successfully.
However, when I load the model to predict on new data, the load fails with the message:
java.lang.NoSuchMethodException: com.johnsnowlabs.nlp.annotators.Stemmer.read()

However, if I remove the Stemmer stage from the pipeline, it is loaded successfully.
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

I am using Spark 2.2.0, scala 2.11.12, spark-nlp 2.11-1.2.3
* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile): Mac OS
* Link to your project:

**Comment by aleksei-ai** [comment]
@siddarthareddyt  Thank you for the bug report.
I fixed it in master https://github.com/JohnSnowLabs/spark-nlp/commit/cb9aa4366f3e2c9863482df39e07b7bacff13049
Will be included into next release
