### ISSUE TITLE
Sentence detector error on documents containing single quotes, double quotes and $ symbol

### ISSUE THREAD

**Issue by dkincaid** [JohnSnowLabs/spark-nlp#713]
## Description
When using the SentenceDetector in a pipeline certain combinations of single quotes, double quotes and dollar signs cause an error. The stack trace is attached here: [exception-for-jsl.txt](https://github.com/JohnSnowLabs/spark-nlp/files/3942922/exception-for-jsl.txt)

## Steps to Reproduce
If you run the "bad" text below through a sentence detector you will get the error. The "good" text simply replaces the single quote before the dollar sign with a double quote and this processes with no error.

The "bad" text below that causes the error is a modified version of a real document in our database

## Code example
A Jupyter notebook that demonstrating the error is here:
[Example sentence detector error.zip](https://github.com/JohnSnowLabs/spark-nlp/files/3942926/Example.sentence.detector.error.zip)

```
# Bad
badtext = "The 'man' in the back said '$everyone attack\" and it turned into a ballroom blitz."

# Good
goodtext = "The 'man' in the back said \"$everyone attack\" and it turned into a ballroom blitz."
```
## Context
We are unable to process our documents because this error kills the Spark job

**Comment by saif-ellafi** [comment]
Fixed in https://github.com/JohnSnowLabs/spark-nlp/pull/718

Thank you for reporting this @dkincaid

**Comment by maziyarpanahi** [comment]
I'll close this issue as the fix was released in `2.3.5`. Please feel free to reopen it if the issue still exists.

**Comment by dkincaid** [comment]
Thanks for jumping on this one so fast. Had 2.3.5 been officially released now?

**Comment by maziyarpanahi** [comment]
Yes, it’s released every where. We are just waiting for Spark Packages to also push it through their cache or whatever it is they are slow but you can use the Maven coordinates instead for —packages
