### ISSUE TITLE
 Getting class is not whitelisted when I'm using on databricks

### ISSUE THREAD

**Issue by ravigurnatham** [JohnSnowLabs/spark-nlp#7149]
Hi, I have installed the spark-nlp on **databricks** cluster. i was able to import it but when i try to use it it is throwing the error  

```
from sparknlp.pretrained import PretrainedPipeline

explain_document_pipeline = PretrainedPipeline("explain_document_ml")
annotations = explain_document_pipeline.annotate("We are very happy about SparkNLP")
print(annotations)
```

**py4j.security.Py4JSecurityException: Method public static java.lang.String com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(java.lang.String,java.lang.String,java.lang.String) is not whitelisted on class class com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader** 

Any help is appreciated.

**Comment by maziyarpanahi** [comment]
Hi,

Could you please provide the following information:

## Your Environment

* Spark NLP version `sparknlp.version()`:
* Apache NLP version `spark.version`:
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):


* Databricks Runtime?
* Spark config tab inside Advanced options of the cluster
* Screenshot from `Libraries` tab inside Databricks Cluster to see what dependencies are being used

**Comment by ravigurnatham** [comment]
Spark NLP version :  3.4.2
Apache NLP version : 3.1.2
Java Version : 1.8.0_282 (Azul Systems, Inc.)
Setup and installation : followed instruction on installation guide for databricks
Databricks Runtime : 7.3 LTS ML

**Comment by maziyarpanahi** [comment]
You didn't share the screenshots I asked for, so I go with what I can say. This happens in Databricks under certain situations:

Problem:
- you have some configs (or those are automatically set by that runtime) that conflict with HC cluster mode

Solution:
- Either choose another Cluster mode. (not high concurrency)
- or follow this instruction given by Databricks (setting only one of them to true and the other one to false should fix the issue): https://kb.databricks.com/python/python-cmd-fail-high-con-cluster.html

**Comment by BartoszMaciejewski** [comment]
Exception is well-known and described in Azure documentation: https://docs.microsoft.com/en-gb/azure/databricks/security/credential-passthrough/adls-passthrough#py4jsecuritypy4jsecurityexception--is-not-whitelisted

Still, I don't know if class you're using can be somehow whitelisted (in cluster init scripts or somewhere else).

**Comment by maziyarpanahi** [comment]
> Is there any resolution here? I am on AWS and running into this same issue. Able to have success on a single user personal compute cluster but once I spin up a shared cluster I run into this sam error? No documentation on the AWS side.

This is totally out of our hands. In `shared cluster` mode the Databricks itself only allows certain classes from some sources for security. In fact, some of its own stuff and Apache Spark functions also don't work: https://kb.databricks.com/streaming/readstream-is-not-whitelisted

The only solutions here are:
- You should either use a different cluster mode: https://docs.databricks.com/clusters/configure.html#what-is-cluster-access-mode
- Or ask Databricks to whitelist these classes (we are not the customer, we just maintain this library so we cannot ask)

**Comment by zacayd** [comment]
@maziyarpanahi 
I have the same issue on Unity Catalog Cluster 
can I ask Databricks to whitelise these classes ?
I use maven classes
za.co.absa.spline.agent.spark:spark-3.3-spline-agent-bundle_2.12:2.0.0

py4j.security.Py4JSecurityException: Method public static org.apache.spark.sql.SparkSession za.co.absa.spline.harvester.SparkLineageInitializer.enableLineageTracking(org.apache.spark.sql.SparkSession) is not whitelisted on class class za.co.absa.spline.harvester.SparkLineageInitializer

**Comment by maziyarpanahi** [comment]
> @maziyarpanahi I have the same issue on Unity Catalog Cluster can I ask Databricks to whitelise these classes ? I use maven classes za.co.absa.spline.agent.spark:spark-3.3-spline-agent-bundle_2.12:2.0.0
> 
> py4j.security.Py4JSecurityException: Method public static org.apache.spark.sql.SparkSession za.co.absa.spline.harvester.SparkLineageInitializer.enableLineageTracking(org.apache.spark.sql.SparkSession) is not whitelisted on class class za.co.absa.spline.harvester.SparkLineageInitializer

Hi @zacayd 
I believe those who use spark-nlp in Databricks have asked and if I am not mistaken it should be whitelisted. (or Databricks offered them another solution for this, as far as I know we have users using unity catalog clusters.)

I need to ask to see what happened to them, but my guess is how much Databricks has trust in `za.co.absa.spline.agent.spark:spark-3.3-spline-agent-bundle_2.12` package.

**Comment by zacayd** [comment]
Thank @maziyarpanahi 
how can i know if they trust za.co.absa.spline.agent.spark:spark-3.3-spline-agent-bundle_2.12

**Comment by maziyarpanahi** [comment]
> Thank @maziyarpanahi how can i know if they trust za.co.absa.spline.agent.spark:spark-3.3-spline-agent-bundle_2.12

I am not sure if that's how they whitelist or whether they whitelist anything from third-party, but you need to get in contact with the support team in Databricks. They should be able to point you to the right people
