### ISSUE TITLE
Spark NLP getting BART models for Zero Shot Classifications

### ISSUE THREAD

**Issue by ericbugin** [JohnSnowLabs/spark-nlp#7162]
Hello, 
Was wondering if John Snow Labs had its eye on adding BART models from Huggingface for Zero Shot Classifications? 

Here a model example from Huggingface
https://huggingface.co/facebook/bart-large-mnli

Thanks

**Comment by maziyarpanahi** [comment]
I reopen this since it’s related to the discussion of how to import BART models.

**Comment by ericbugin** [comment]
You do not need to wait for SparkNLP to implement it, you can download the HF BART model and use the spark "broadcast" function to push it to all your nodes, this will allow inference on a spark dataframe. you'll have to make certain all of the necessary python libraries (i.e. transformers, pytorch) are installed on all of your nodes as well

**Comment by maziyarpanahi** [comment]
- I am re-opening this as we already released BartTransformer for summarization, translation, and text-generation. 
- We have also released BertForZeroShotClassification annotator
- I think the next best thing would be to also implement BartForZeroShotClassification as it seems to have more models out there

**Comment by khanhvy31** [comment]
@maziyarpanahi "I am re-opening this as we already released BartTransformer for summarization, translation, and text-generation." Hi, could you direct me to the notebook where you transfer Bart to spark nlp please?
