### ISSUE TITLE
Unable to load Bert embeddings due to tmp directory permission error

### ISSUE THREAD

**Issue by marcinic** [JohnSnowLabs/spark-nlp#723]
## Description

While some of the issue is specific to my environment, I think it could occur in multiple contexts where the user does not have write access for temporary directories. I am in an environment where I do not have write access to most folders and need to use sudo to accomplish most file-system tasks. My understanding is that spark nlp creates a temporary directory /tmp/sparknlp_contrib_spar for which in this case, it doesn't have permissions. 
## Expected Behavior

I should be able to load the embeddings and fit a model using them.
## Current Behavior

Py4JJavaError: An error occurred while calling o150.load.
: java.io.FileNotFoundException: /tmp/sparknlp_contrib_spar (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.johnsnowlabs.nlp.annotators.ner.dl.LoadsContrib$.copyResourceToTmp(LoadsContrib.scala:39)
	at com.johnsnowlabs.nlp.annotators.ner.dl.LoadsContrib$.loadContribToCluster(LoadsContrib.scala:57)
	at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel$class.readTensorflowModel(TensorflowSerializeModel.scala:60)
## Possible Solution

One possible solution would be to check if the directory is writable and if not allow the user to specify their own temporary directory.
## Steps to Reproduce

bert = BertEmbeddings.load(bert_path)\
    .setInputCols(["token","sentence"])\
    .setOutputCol("bert")

## Context

Use pretrained BertEmbeddings for classification and NER.
## Your Environment

* Version used: 2.3.4
* Operating System and version (desktop or mobile): CentOS 7.7.1908

**Comment by maziyarpanahi** [comment]
Hi,
We need a place to keep files and the /tmp is always accessible to all the users due to its nature and it's perfect to keep files that are not necessary to be present in the next reboot.

We might be able to let users set the tmp directory through application conf before they start the SparkSession. However, this takes some time and some changes in the strategies we have in keeping files so I will open a task for this and see if someone can take care of it for the next releases.

Thanks for asking for this feature and I'll keep you posted.

**Comment by marcinic** [comment]
Thanks @maziyarpanahi. There may be another work-around but if what I am saying makes sense I am happy to help figure out the best possible solution.

**Comment by maziyarpanahi** [comment]
Hi @marcinic 

I have found this in our `application.conf`

```
sparknlp {

  settings {

    overrideConfigPath = "./application.conf"
    annotatorSerializationFormat = "object"
    useBroadcastForFeatures = true

    embeddings {
      // Override with cluster location. Default is non set. Leads to fs.defaultFS scheme. e.g. hdfs:// in YARN.
      // and hadoop.tmp.dir. Highly dependant on defaultFS. Override in non hadoop, e.g. S3 storage based clusters.
      // cluster_tmp_dir = "s3://"
    }

    pretrained {
      s3_bucket = "auxdata.johnsnowlabs.com"
      s3_path = ""
      s3_socket_timeout = 3600000
      // Override as required. Defaults to home/cache_pretrained folder.
      // cache_folder = "/home/robert/models"
      credentials {}
    }

    annotator {
      // log_folder = "/home/robert/logs"
    }

  }
}
```
Does this help? You can override where to cache pretrained models/pipelines and also the `tmp` path.

**Comment by ajhepburn** [comment]
@maziyarpanahi 

I'm using Spark NLP on PySpark and I'm wanting to use some of the pretrained models. However, I'm running this on a Kubernetes cluster, where I don't have permissions to write to ~/cache_pretrained. I want to try overriding using application.conf but I was unsure as to where exactly I would put this config file and how I would map that to my master/workers. 

Do you have any advice as to how to effectively change the download folder via PySpark?

**Comment by maziyarpanahi** [comment]
@ajhepburn 

If you look into the `application.conf` you can override that via this path

```
sparknlp.settings.pretrained.cache_folder
```

You can set it as follow:

```
--files "$LOCAL_PATH/application.conf --conf spark.driver.extraJavaOptions="-Dconfig.file=file:application.conf" --conf spark.executor.extraJavaOptions="-Dconfig.file=file:application.conf" 
```

We need to update the docs for this, but we will rename them in the next release and update the docs with the new names. But for now, it can be set like that easily.

**Comment by kvanlieshout** [comment]
@ajhepburn apologies to jump into this issue ticket but did the changes that @maziyarpanahi recommend to your application.conf work? I am in a similar situation with needing to override this file in Kubernetes. Just wondering if your issue worked out. Thanks

**Comment by maziyarpanahi** [comment]
Maybe this helps for the future, how to change the `/tmp` default for Java in places where the security doesn't allow `/tmp` to be writable.
https://medium.com/spark-nlp/installing-spark-nlp-and-spark-ocr-in-air-gapped-networks-offline-mode-f42a1ee6b7a8
