### ISSUE TITLE
CoNLL produce bad sentences annotations

### ISSUE THREAD

**Issue by dukegris** [JohnSnowLabs/spark-nlp#728]
CoNLL produce bad sentences annotations

## Description

I train a NerDlApproach with CoNLL files, using the "sentences" column in the inputcols. After the fit, when i transform a test file in a pipeline with a NerConverter Anntoator, this one produces only results for the first sentence. Trying to evaluate with NerHelper.measureExact, the results are bad . If you make the same using the document column in NerDlApproach it works well. 

## Current Behavior

NER_SPAN (after finisher, extracting from metadata):
Any = WrappedArray([entity,MUT_DNA], [sentence,0], [chunk,0])
LABEL_SPAN (after finisher, extracting from metadata):
Any = WrappedArray([entity,MUT_DNA], [sentence,0], [chunk,0], [entity,MUT_PRO], [sentence,0], [chunk,1])

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version: 2.3.4
* Apache NLP version:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Hi,

To answer your first question about whether it should be DOCUMENT or SENTENCE:

> No, actually it is correct. The `annotatorType.DOCUMENT` is for both `document` (multiple sentences) and a `sentence` (sentence by sentence). You can look at our annotators when they have inputCol we use DOCUMENT which refers to both document column or sentence column and after that, we deal with them depending on whether it's a sentence by sentence or a batch of sentences together.

That's being said, we didn't observe any difference when we were training NerDLApproach by either using the `document` column (multiple sentences at the same time) or `sentence` (one sentence at a time). That is why by default `CoNLL()` class will explode all the sentences into one sentence per row for better optimizing memory during training without any difference in time and accuracy at the end. (our NER model cares about a sequence of characters in a token and tokens in a sentence, that is why one sentence or multiple sentences won't affect the results)

If you don't want sentence per row, you need to set `explodeSentences` to `false` so you get the result DataFrame in a normal way which has documented, and multiple sentences (if any, depending on your CoNLL file)

If this didn't work, please provide a CoNLL file in gist with few documents (each with multiple sentences) and your code and I can debug it for you.
