### ISSUE TITLE
Latest release (1.2.4) has not been yet published on Maven

### ISSUE THREAD

**Issue by maziyarpanahi** [JohnSnowLabs/spark-nlp#73]
## Description
Hello, the SBT can't find the latest release on Maven repository:
https://mvnrepository.com/artifact/com.johnsnowlabs.nlp/spark-nlp

Therefore, the SBT fails to download the new release on refresh. Also, the jar is pointed to 1.2.3 version from Maven on the Home Page:
http://nlp.johnsnowlabs.com/

Many thanks.

## Current Behavior
```
[warn] 	:: com.johnsnowlabs.nlp#spark-nlp_2.11;1.2.4: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.johnsnowlabs.nlp:spark-nlp_2.11:1.2.4 
[warn] 		  +- default:multivac-nlp_2.11:0.1
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.johnsnowlabs.nlp#spark-nlp_2.11;1.2.4: not found

```
## Steps to Reproduce

`  "com.johnsnowlabs.nlp" %% "spark-nlp" % "1.2.4"
`

**Comment by showy** [comment]
@maziyarpanahi Thanks for noticing. We have already published the artifacts to maven central and spark-packages.
