### ISSUE TITLE
Data format Nercrfapproach

### ISSUE THREAD

**Issue by sparkuser3** [JohnSnowLabs/spark-nlp#737]
Hi Team,

I am new to Spark NLP. Could you please explain in detail with an example as to how we can use training dataset other than conll2003 format. Conll2003 format is cumbersome if we want to use for a domain specific  nlp entity recognition . For example I want to extract entities like account number , phone number , address street , zipcode etc . I have a training data in name,entitytype(label) . But dont know how to use it . This becomes cumbersome when we want to convert it to conll2003 format . Please advise

_Originally posted by @sparkuser3 in https://github.com/JohnSnowLabs/spark-nlp/issues/317#issuecomment-571885699_

**Comment by maziyarpanahi** [comment]
There are examples of how to train NER in our repo: https://github.com/JohnSnowLabs/spark-nlp-workshop

Having CoNLL format is mandatory for training NER, you need to convert your training dataset into that format.

**Comment by sparkuser3** [comment]
Thanks for the quick reply , Do you know of any tool which can help me convert data to conll2003 format. Like I said if I have a huge data it becomes cumbersome to convert it to conll2003 format .

**Comment by maziyarpanahi** [comment]
Unfortunately, I've never used any tool to create CoNLL file. You should do a search and if there is nothing suitable you can write your own script to convert it into CoNLL format.
