### ISSUE TITLE
Show Example button missing for models in Annotator Page

### ISSUE THREAD

**Issue by DevinTDHa** [JohnSnowLabs/spark-nlp#7445]
## Description

Ever since the front-end refactor (I suspect commit 4f1330f6fa34c92bf4e66c42dbc0b4e6fe7af773), the examples for the models in the [main annotator page ](https://nlp.johnsnowlabs.com/docs/en/annotators) are not displayed correctly anymore. It seems that `/static/models.css` cannot be applied. 

Checking out the repo before tag 3.4.0 and running the docs, does not have that problem (`/static/models.css` is not queried)

## Expected Behavior

There should be a "Show Example" Button like for the Approach annotators

## Current Behavior

The "Show Example" buttons for the Model tab is missing.

## Steps to Reproduce

1. Go to the main Page and Scroll down to an annotator with an Approach and Model tab.
2. Button for example is missing.

**Comment by maziyarpanahi** [comment]
@DevinTDHa Does this correlate to a specific browser? I have them on Chrome:
![image](https://user-images.githubusercontent.com/5762953/160785168-47fb635d-6bb4-46f7-8e6e-788a826336ff.png)

**Comment by DevinTDHa** [comment]
Issue was on my side, multiple browsers on my machine still had old caches it seems. It's fine after reinstalling!
