### ISSUE TITLE
Pip uninstall can't purge the directory com/johnsnowlabs/nlp

### ISSUE THREAD

**Issue by wbo4958** [JohnSnowLabs/spark-nlp#7471]
## How to repro:
```
pip install sparknlp
pip uninstall sparknlp
```

and the directory installed by sparknlp is still in the site-packages,

`python3.8/site-packages/com/johnsnowlabs/nlp`

**Comment by maziyarpanahi** [comment]
You probably installed spark-nlp, I suggest uninstalling sparknlp and spark-nlp.
In any case, this is really between your system and pip, no Python package has any power when it cones to pip uninstall. (It’s not like we have a uninstaller l)
