### ISSUE TITLE
Japanese translator not translating all of the text. 

### ISSUE THREAD

**Issue by ericbugin** [JohnSnowLabs/spark-nlp#7678]
Env: com.johnsnowlabs.nlp:spark-nlp-spark24_2.11:3.4.0

Using this model to translate Japanese to English
https://nlp.johnsnowlabs.com/2021/06/04/translate_ja_en_xx.html

Here is a screenshot of how it is working in my notebook using Spark NLP.
It is only translating the 1st sentence into English
![Screen Shot 2022-04-05 at 2 58 40 PM](https://user-images.githubusercontent.com/70169379/161829651-286b1c28-f6d2-40cb-987e-54ce4fee8ac9.png)

Here is a screenshot of how it is working in my notebook using Huggingface's python library
![Screen Shot 2022-04-05 at 4 34 21 PM](https://user-images.githubusercontent.com/70169379/161844355-dc44aac5-abca-4729-903a-8eb897f7d989.png)

Here is it working properly in HF with the same sample text
https://huggingface.co/Helsinki-NLP/opus-mt-ja-en?text=%E3%81%95%E3%82%89%E3%81%AB%E3%80%81%E4%B8%BB%E8%A6%81%E3%81%AA%E4%BA%8B%E6%A5%AD%E9%83%A8%E9%96%80%E3%81%AB%E5%AF%BE%E3%81%99%E3%82%8BCOVID-19%E3%81%AE%E5%BD%B1%E9%9F%BF%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E6%9C%80%E6%96%B0%E3%81%AE%E6%9B%B4%E6%96%B0%E3%82%92%E3%81%99%E3%81%B9%E3%81%A6%E6%98%8E%E3%82%89%E3%81%8B%E3%81%AB%E3%81%97%E3%81%BE%E3%81%99%E3%80%82%E9%A1%A7%E5%AE%A2%E3%81%AE%E7%89%B9%E5%AE%9A%E3%81%AE%E8%A6%81%E6%9C%9B%E3%82%92%E6%8F%90%E4%BE%9B%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%81%AB%E3%82%88%E3%82%8A%E3%80%81%E3%81%A9%E3%81%AE%E7%A8%AE%E9%A1%9E%E3%81%AE%E8%A3%BD%E5%93%81%E3%82%92%E8%A3%BD%E9%80%A0%E3%80%81%E7%99%BA%E5%A3%B2%E3%80%81%E8%B2%A9%E5%A3%B2%E3%81%99%E3%82%8B%E3%81%8B%E3%82%92%E6%B1%BA%E5%AE%9A%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82+%E6%B3%8C%E5%B0%BF%E5%99%A8%E3%81%8C%E3%82%93%E6%B2%BB%E7%99%82%E8%96%AC%E3%81%AE%E4%B8%96%E7%95%8C%E5%B8%82%E5%A0%B4%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E4%B8%BB%E8%A6%81%E4%BC%81%E6%A5%AD%E3%81%AF%E6%AC%A1%E3%81%AE%E3%81%A8%E3%81%8A%E3%82%8A%E3%81%A7%E3%81%99%E3%80%82

**Comment by maziyarpanahi** [comment]
Hi @ericbugin 

You are using the pretrained pipeline, it has a pre-set input/output max length. (we had to save the pipeline with pre-defined parameters)

You can have your own pipeline and change those parameters (https://nlp.johnsnowlabs.com/2020/12/28/opus_mt_ja_en_xx.html):

```python
documentAssembler = DocumentAssembler()\ 
 .setInputCol("text")\ 
 .setOutputCol("document")

 sentencerDL = SentenceDetectorDLModel.pretrained("sentence_detector_dl", "xx")\ 
 .setInputCols(["document"])\ 
 .setOutputCol("sentences")

 marian = MarianTransformer.pretrained("opus_mt_ja_en", "xx")\ 
 .setInputCols(["sentence"])\ 
 .setOutputCol("translation")\
 .setMaxInputLength(200)\
 .setMaxOutputLength(200)

marian_pipeline = Pipeline(stages=[documentAssembler, sentencerDL, marian])
light_pipeline = LightPipeline(marian_pipeline.fit(spark.createDataFrame([[""]]).toDF("text")))
result = light_pipeline.fullAnnotate(data)
```
