### ISSUE TITLE
Result "entity" of NerConverter for Japanese is truncated

### ISSUE THREAD

**Issue by taka-yayoi** [JohnSnowLabs/spark-nlp#7688]
## Description
I tried NER on Japanese text, NER itself works fine but applying NerConverter to NER result returns truncated entity name.

## Expected Behavior

NerConverter returns correct entity name.

## Current Behavior

NerConverter returns (first 2 characters) truncated entity name.

![Screen Shot 2022-04-08 at 12 03 47](https://user-images.githubusercontent.com/74801096/162354838-03856ceb-afa5-48e1-be9b-23c1db3cb9c7.png)

## Steps to Reproduce

1. On Databricks, install pyspark==3.1.2, spark-nlp, spark-nlp-display
2. Import sparknlp library
3. Build NLP pipeline specifying pretrained model for Japanese and NerConverter
4. Input Japanese text into the pipeline
5. Display result using NerVisualizer

## Context

Cannot display correct named entity. I'd like to display named entities correctly using NerConverter and NerVisualizer.

## Your Environment

* Spark NLP version `sparknlp.version()`:3.4.2
* Apache NLP version `spark.version`:3.2.1
* Java version `java -version`:1.8.0_302
* Setup and installation (Pypi, Conda, Maven, etc.):Pypi
* Operating System and version: Ubuntu 20.04.4 LTS
* Link to your project (if any): https://sajpstorage.blob.core.windows.net/yayoi/NER%20for%20Japanese.html

**Comment by maziyarpanahi** [comment]
Hi @taka-yayoi 

The NerConverter is for NER models that were trained based on IOB/IOB2 style. It will take (token, I-PERSON) (token, B-PERSON) and return (token, PERSON) by removing I- and B-. (extracting entities)

However, the NER model you are using doesn't have IOB/IOB2 style. It is already an entity, so NerConverter won't work in terms of merging them. (that is why in the example there is no NerConverter as opposed to other NER models)

https://nlp.johnsnowlabs.com/2021/01/03/ner_ud_gsd_glove_840B_300d_ja.html

Solution: you shouldn't use NerConverter for this specific model and just get the results directly from NerDLModel. (you can have your own merge strategy)

**Comment by taka-yayoi** [comment]
Hi @maziyarpanahi 

Understood. Changing NER model worked! In the case where I have to use the NER model above, I will implement merge strategy. Thank you!

https://nlp.johnsnowlabs.com/2021/09/09/ner_ud_gsd_cc_300d_ja.html

![Screen Shot 2022-04-09 at 6 27 39](https://user-images.githubusercontent.com/74801096/162534675-f880fdd1-3ac8-4690-96f0-d0710c515182.png)
