### ISSUE TITLE
Typo in NerCrfApproach

### ISSUE THREAD

**Issue by Dabada** [JohnSnowLabs/spark-nlp#77]
https://github.com/JohnSnowLabs/spark-nlp/blob/fce84691a2d8943ee6db8b5c115c4144e5f5bc02/src/main/scala/com/johnsnowlabs/nlp/annotators/ner/crf/NerCrfApproach.scala#L61

The function setDatsetPath shoud be setDatasetPath

**Comment by maziyarpanahi** [comment]
I made a pull request, thanks

**Comment by saifjsl** [comment]
Thank you, merged
