### ISSUE TITLE
S3 Based cluster, no hadoop, python configuration

### ISSUE THREAD

**Issue by hjuhel-cdpq** [JohnSnowLabs/spark-nlp#781]
## Description
In https://github.com/JohnSnowLabs/spark-nlp#s3-cluster the instructions contains the ```ConfigLoader.setConfigPath("/somewhere/to/put/application.conf")``` . However, when using PySpark NLP 2.4 this class does not exposes the method in Python. What would be a way to set the config path in Python/Pyspark solution?

When using pretrained models (offline or online), the SparkNLP package raises an Error while trying to connect to HDFS. We have a Spark cluster without HDFS. We would like to use SparkNLP with S3 support. According to the documentation, this can be done by using the ```ConfigLoader.setConfigPath``` method. But this method is not available in the Python Package. The ```GetConfigPath.method``` is availble. Is it possible to set the config path from Python ? 

if so:

-  is the defaut path, ```.application.conf``` referring to a path inside the JAR ? Inside the Spark driver ? Or in the excutors file system.

- How one can specifies the AWS credentials for the ```s3``` path ? Is SparkNLP using environnement variables or does it need the ```.ssh``` file or ```aws cli``` to be set-up on each worker ?

Thanks a lot

## Expected Behavior

The ```setConfigPath``` method schould be working in Python / Pyspark

## Current Behavior

The config path can not be set up from PySpark

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version: 2.4
* Apache NLP version:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by alex2awesome** [comment]
are there any updates to this?

**Comment by maziyarpanahi** [comment]
The initial issue doesn’t have enough info in the template, could you please add some more info as where you are, how are you using S3, what is your setup, etc. The more info and steps the easier we can reproduce the environment.

Also, we don’t need those in python to pass application.conf, it can be in the class path when Spark being started. I will add some examples here today.

**Comment by alex2awesome** [comment]
ah ok thanks @maziyarpanahi. 

I look forward to seeing your examples. I am still getting used to my university's hardware setup, so I don't have precise answers for you about what my setup is. PySpark runs under the hood from jupyter notebooks on our cluster, and we (the users) don't have access to the HDFS or `spark-env.sh`; all our readable/writable drives (as users) are through S3, although I'm pretty sure PySpark is set up on HDFS.

This is doubtlessly not enough for you to understand my setup, as I don't fully understand it myself. 

This issue arose for me specifically when I was trying to get `WordEmbeddingModel` instantiated. Was trying to follow the instructions in the following issue, but could not:

https://github.com/JohnSnowLabs/spark-nlp/issues/937

Alex

**Comment by katalinwesthoff** [comment]
@maziyarpanahi  are there any updates on this? I am currently stucked with the same issue and would be very greateful to see this examples...

Kati

**Comment by katalinwesthoff** [comment]
@maziyarpanahi are there any updates on this? I am currently stucked with the same issue and would be very greateful to see this examples...

Kati

**Comment by maziyarpanahi** [comment]
Hi @katalinwesthoff 

It's been a long time and we've had many releases. I think the best way to start this and see where it goes is to create a new issue, complete the template with all the info and steps and requirements for us to reproduce the issue. This is something we have to do to guide any further and we really need all the info and steps to do so.
