### ISSUE TITLE
UniversalSentenceEncoder  low GPU utilization

### ISSUE THREAD

**Issue by BDomnenko** [JohnSnowLabs/spark-nlp#7928]
## The problem

I am running Spark NLP to produce **sentence embeddings**. I am using `UniversalSentenceEncoder`  and I see no performance increase over CPU, since GPU utilization never exceeds 10% (see the nvidia-smi logs attachments). I have looked into [Performance of BertEmbeddings issue](https://github.com/JohnSnowLabs/spark-nlp/issues/570) and overall - it seems to me that `UniversalSentenceEncoder` processes data either row by row or by a batch of rather small size. Is there an option to add `batchSize` parameter for `UniversalSentenceEncoder` or am I doing something wrong with vectorization and GPU?

### Model initialization

```
embedding_model = UniversalSentenceEncoder.pretrained("tfhub_use", "en") \
    .setInputCols("sentence") \
    .setOutputCol("vector") \

# Uncomment to use BERT
# embedding_model = BertSentenceEmbeddings.pretrained()\
#    .setInputCols("sentence")\
#    .setOutputCol("vector")\
#    .setCaseSensitive(False)\
#    .setDimension(768)\
#    .setStorageRef('sent_bert_base_cased') 

# embedding_model.setBatchSize(32)
```

### Pipeline and model

```
campaign_doc_assembler = DocumentAssembler() \
    .setInputCol("keywords") \
    .setOutputCol("sentence")

campaign_vectorization_pipeline = Pipeline(stages=[campaign_doc_assembler, embedding_model])
campaign_vectorization_model = campaign_vectorization_pipeline.fit(spark.createDataFrame([[""]]).toDF("keywords"))
```

### Data and schema
```
df = spark.read.format("bigquery")\
    .option("project", "MY_PROJECT")\
    .option("table", "MY_TABLE").load()

df_processed = df\
    .withColumn("hash", md5(col("keywords")))

df_processed.printSchema()
```
```
root
 |-- campaign_id: long (nullable = true)
 |-- keywords: string (nullable = false)
 |-- hash: string (nullable = false)
```
Keywords is a string of ~100 white space separated words, ~2500 rows in total

### Vectorization
```
vectorized_campaigns_spark_df = campaign_vectorization_model\
    .transform(df_processed)

vectorized_campaigns_spark_df = vectorized_campaigns_spark_df\
    .select(*["campaign_id", "hash", "vector"])

# For demo purposes
pandas_df = campaigns_spark_df.toPandas()
```

## The logs

- [spark_use_nvidia-smi_gpu_log.csv](https://github.com/JohnSnowLabs/spark-nlp/files/8480917/spark_use_gpu_log.csv)
- [spark_bert_nvidia-smi_gpu_log.csv](https://github.com/JohnSnowLabs/spark-nlp/files/8480916/spark_bert_gpu_log.csv)

## The setup

- Spark NLP GPU version: `3.4.2`
- Apache Spark version: `3.0.3`
- Scala version: `2.12.10`
- Java version: `11.0.14`
- Setup and installation: `Pypi + Pyspark`
- Operating System and version: `Debian GNU/Linux 10 (buster)`
- GPU
  - Hardware: `Tesla K80`
  - Driver version: `460.73.01`
  - CUDA version: `11.2`

**Comment by maziyarpanahi** [comment]
Hi @BDomnenko 

Thanks for reporting this, I think the UniversalSentenceEncoder is still on row by row transformation and does the batching within each row (by batching sentences to feed). I haven't moved it yet to batching by rows to improve GPU (needs testing to be sure it actually does improve)

One question that could help me, could you please test the following code:

```python

# Uncomment to use BERT
embedding_model = BertSentenceEmbeddings.pretrained("sent_bert_use_cmlm_en_base", "en") \
    .setInputCols("sentence")\
    .setOutputCol("vector")\
    .setBatchSize(8)
```

The new `CMLM` models are provided by the same team behind USE to replace English and multi-lingual models with more accuracy: https://nlp.johnsnowlabs.com/models?q=cmlm&task=Embeddings

You provided logs for BERT, but I am not sure if it's BertSentenceEmbeddings or BertEmbeddings. If you can run the code I provided, play around with the batchSize and have a look at the total amount of time it each time via the following would be great:

```python
vectorized_campaigns_spark_df = campaign_vectorization_model\
    .transform(df_processed)

vectorized_campaigns_spark_df.write.mode("overwrite").save("./bert_sent_test")
```

(saving as Parquet is very efficient and it also removes other none-spark layers like Pandas from the stack)

**Comment by maziyarpanahi** [comment]
Thanks, that's great. I'll start migrating `UniversalSentenceEncoder` to the new batching by rows to have equal improvements in speed while it's on GPU. (I'll update this issue once it's done)
