### ISSUE TITLE
if you use conda install, "import sparknlp" cant find the package

### ISSUE THREAD

**Issue by EdStone** [JohnSnowLabs/spark-nlp#799]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version:
* Apache NLP version:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Please fill the requested information and copy the error here with the way to reproduce it. We have no issue with that so you are missing a step.
