### ISSUE TITLE
Deploy spark-nlp 1.2.5 to maven-central

### ISSUE THREAD

**Issue by lambdaofgod** [JohnSnowLabs/spark-nlp#80]
## Description

Version 1.2.5 [is not uploaded to Maven Central](https://mvnrepository.com/artifact/com.johnsnowlabs.nlp/spark-nlp).

## Expected Behavior
It should be deployed since it says so in README ;)

**Comment by saifjsl** [comment]
thank you @lambdaofgod I'm working on it. It's been a struggling release :)

**Comment by saifjsl** [comment]
Published. It might take some time. It is already available if used as dependency

http://central.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.11/

**Comment by lambdaofgod** [comment]
It works! Thanks @saifjsl !
