### ISSUE TITLE
another error in your example

### ISSUE THREAD

**Issue by EdStone** [JohnSnowLabs/spark-nlp#800]
my SPARK_HOME points to Spark 2.4.1; see below.
but the attached sheet fails with error: "TypeError: 'JavaPackage' object is not callable"
Rename the attached sheet from Main.txt to Main.ipynb

Instead of wasting everyone's time, can you please provide a WORKING sample and installation instructions that ACTUALLY WORK

tx

[Main.txt](https://github.com/JohnSnowLabs/spark-nlp/files/4246258/Main.txt)

(nlp) C:\Users\aaa>spark-shell
20/02/24 13:49:02 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
20/02/24 13:49:08 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
Spark context Web UI available at http://VRD-21124-3.domain.voloridge.com:4041
Spark context available as 'sc' (master = local[*], app id = local-1582570148440).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.1
      /_/

Using Scala version 2.11.12 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_241)
Type in expressions to have them evaluated.
Type :help for more information.

**Comment by maziyarpanahi** [comment]
Your issues are related to Apache Spark installation especially in Jupyter. It has nothing to do with Spark NLP. Your issues are not following the template so we cannot help you, please follow the instructions, take a loom at the examples at workshop repo that comes with Docker image, keep in mind that many many users are using this library so if the first step is failing it’s probably your machine.

PS: Please keep your conversation civilized

**Comment by maziyarpanahi** [comment]
https://github.com/JohnSnowLabs/spark-nlp-workshop

**Comment by EdStone** [comment]
Sorry Maziyar, I'll try to be civil.
I work for a major hospital chain and we're examining the library.
After 3-4 days of pulling hair, still can't get it to work.
So, I've attached a step-by-step instruction that I followed; as I mentioned, still get error.
The commands (and resulting output) are in file "commands.txt" and an image of the error is in the attached file error.jpg.
Please let me know what we should be doing differently.Tx,E
    On Monday, February 24, 2020, 2:03:59 PM EST, Maziyar Panahi <notifications@github.com> wrote:  
 
 
https://github.com/JohnSnowLabs/spark-nlp-workshop

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
  

(base) C:\temp>conda create --name nlp python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\devel\conda\envs\nlp

  added / updated specs:
    - python=3.7


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/win-64::certifi-2019.11.28-py37_0
  openssl            pkgs/main/win-64::openssl-1.1.1d-he774522_4
  pip                pkgs/main/win-64::pip-20.0.2-py37_1
  python             pkgs/main/win-64::python-3.7.6-h60c2a47_2
  setuptools         pkgs/main/win-64::setuptools-45.2.0-py37_0
  sqlite             pkgs/main/win-64::sqlite-3.31.1-he774522_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
  wheel              pkgs/main/win-64::wheel-0.34.2-py37_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate nlp
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) C:\temp>conda activate nlp

(nlp) C:\temp>conda install -c johnsnowlabs spark-nlp==2.3.4 pyspark==2.4.4
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\devel\conda\envs\nlp

  added / updated specs:
    - pyspark==2.4.4
    - spark-nlp==2.3.4


The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl
  icc_rt             pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  intel-openmp       pkgs/main/win-64::intel-openmp-2020.0-166
  mkl                pkgs/main/win-64::mkl-2020.0-166
  mkl-service        pkgs/main/win-64::mkl-service-2.3.0-py37hb782905_0
  mkl_fft            pkgs/main/win-64::mkl_fft-1.0.15-py37h14836fe_0
  mkl_random         pkgs/main/win-64::mkl_random-1.1.0-py37h675688f_0
  numpy              pkgs/main/win-64::numpy-1.18.1-py37h93ca92e_0
  numpy-base         pkgs/main/win-64::numpy-base-1.18.1-py37hc3f5095_1
  pandas             pkgs/main/win-64::pandas-1.0.1-py37h47e9c7a_0
  py4j               pkgs/main/win-64::py4j-0.10.7-py37_0
  pyspark            pkgs/main/noarch::pyspark-2.4.4-py_0
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.1-py_0
  pytz               pkgs/main/noarch::pytz-2019.3-py_0
  six                pkgs/main/win-64::six-1.14.0-py37_0
  spark-nlp          johnsnowlabs/noarch::spark-nlp-2.3.4-py37_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(nlp) C:\temp>conda install jupyter
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\devel\conda\envs\nlp

  added / updated specs:
    - jupyter


The following NEW packages will be INSTALLED:

  attrs              pkgs/main/noarch::attrs-19.3.0-py_0
  backcall           pkgs/main/win-64::backcall-0.1.0-py37_0
  bleach             pkgs/main/win-64::bleach-3.1.0-py37_0
  colorama           pkgs/main/noarch::colorama-0.4.3-py_0
  decorator          pkgs/main/noarch::decorator-4.4.1-py_0
  defusedxml         pkgs/main/noarch::defusedxml-0.6.0-py_0
  entrypoints        pkgs/main/win-64::entrypoints-0.3-py37_0
  icu                pkgs/main/win-64::icu-58.2-ha66f8fd_1
  importlib_metadata pkgs/main/win-64::importlib_metadata-1.5.0-py37_0
  ipykernel          pkgs/main/win-64::ipykernel-5.1.4-py37h39e3cac_0
  ipython            pkgs/main/win-64::ipython-7.12.0-py37h5ca1d4c_0
  ipython_genutils   pkgs/main/win-64::ipython_genutils-0.2.0-py37_0
  ipywidgets         pkgs/main/noarch::ipywidgets-7.5.1-py_0
  jedi               pkgs/main/win-64::jedi-0.16.0-py37_0
  jinja2             pkgs/main/noarch::jinja2-2.11.1-py_0
  jpeg               pkgs/main/win-64::jpeg-9b-hb83a4c4_2
  jsonschema         pkgs/main/win-64::jsonschema-3.2.0-py37_0
  jupyter            pkgs/main/win-64::jupyter-1.0.0-py37_7
  jupyter_client     pkgs/main/win-64::jupyter_client-5.3.4-py37_0
  jupyter_console    pkgs/main/noarch::jupyter_console-6.1.0-py_0
  jupyter_core       pkgs/main/win-64::jupyter_core-4.6.1-py37_0
  libpng             pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
  libsodium          pkgs/main/win-64::libsodium-1.0.16-h9d3ae62_0
  m2w64-gcc-libgfor~ pkgs/msys2/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     pkgs/msys2/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ pkgs/msys2/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          pkgs/msys2/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ pkgs/msys2/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  markupsafe         pkgs/main/win-64::markupsafe-1.1.1-py37he774522_0
  mistune            pkgs/main/win-64::mistune-0.8.4-py37he774522_0
  msys2-conda-epoch  pkgs/msys2/win-64::msys2-conda-epoch-20160418-1
  nbconvert          pkgs/main/win-64::nbconvert-5.6.1-py37_0
  nbformat           pkgs/main/noarch::nbformat-5.0.4-py_0
  notebook           pkgs/main/win-64::notebook-6.0.3-py37_0
  pandoc             pkgs/main/win-64::pandoc-2.2.3.2-0
  pandocfilters      pkgs/main/win-64::pandocfilters-1.4.2-py37_1
  parso              pkgs/main/noarch::parso-0.6.1-py_0
  pickleshare        pkgs/main/win-64::pickleshare-0.7.5-py37_0
  prometheus_client  pkgs/main/noarch::prometheus_client-0.7.1-py_0
  prompt_toolkit     pkgs/main/noarch::prompt_toolkit-3.0.3-py_0
  pygments           pkgs/main/noarch::pygments-2.5.2-py_0
  pyqt               pkgs/main/win-64::pyqt-5.9.2-py37h6538335_2
  pyrsistent         pkgs/main/win-64::pyrsistent-0.15.7-py37he774522_0
  pywin32            pkgs/main/win-64::pywin32-227-py37he774522_1
  pywinpty           pkgs/main/win-64::pywinpty-0.5.7-py37_0
  pyzmq              pkgs/main/win-64::pyzmq-18.1.1-py37ha925a31_0
  qt                 pkgs/main/win-64::qt-5.9.7-vc14h73c81de_0
  qtconsole          pkgs/main/noarch::qtconsole-4.6.0-py_1
  send2trash         pkgs/main/win-64::send2trash-1.5.0-py37_0
  sip                pkgs/main/win-64::sip-4.19.8-py37h6538335_0
  terminado          pkgs/main/win-64::terminado-0.8.3-py37_0
  testpath           pkgs/main/noarch::testpath-0.4.4-py_0
  tornado            pkgs/main/win-64::tornado-6.0.3-py37he774522_3
  traitlets          pkgs/main/win-64::traitlets-4.3.3-py37_0
  wcwidth            pkgs/main/noarch::wcwidth-0.1.8-py_0
  webencodings       pkgs/main/win-64::webencodings-0.5.1-py37_1
  widgetsnbextension pkgs/main/win-64::widgetsnbextension-3.5.1-py37_0
  winpty             pkgs/main/win-64::winpty-0.4.3-4
  zeromq             pkgs/main/win-64::zeromq-4.3.1-h33f27b4_3
  zipp               pkgs/main/noarch::zipp-2.2.0-py_0
  zlib               pkgs/main/win-64::zlib-1.2.11-h62dcd97_3


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(nlp) C:\temp>jupyter notebook
[I 15:44:55.964 NotebookApp] Serving notebooks from local directory: C:\temp
[I 15:44:55.964 NotebookApp] The Jupyter Notebook is running at:
[I 15:44:55.970 NotebookApp] http://localhost:8888/?token=9b98991efb9b968aa06fb671adc18758dda01710f9d3673b
[I 15:44:55.973 NotebookApp]  or http://127.0.0.1:8888/?token=9b98991efb9b968aa06fb671adc18758dda01710f9d3673b
[I 15:44:55.973 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:44:56.039 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/erudshtein/AppData/Roaming/jupyter/runtime/nbserver-14856-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=9b98991efb9b968aa06fb671adc18758dda01710f9d3673b
     or http://127.0.0.1:8888/?token=9b98991efb9b968aa06fb671adc18758dda01710f9d3673b
[I 15:45:02.377 NotebookApp] Creating new notebook in
[I 15:45:03.492 NotebookApp] Kernel started: bf6d17f9-5e3c-4ab7-93a1-0a38b8ea1c07
