### ISSUE TITLE
Missing Lemmatizer and POS models in 3.4.3 release

### ISSUE THREAD

**Issue by maziyarpanahi** [JohnSnowLabs/spark-nlp#8119]
Some of the new models for Lemmatizer and POS that were released in 3.4.3 are missing the actual models.

**Comment by Pertona** [comment]
Hello, some of the lemmatizer models have "Access Denied" when trying to download the models. 
For example:
https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/models/lemma_lines_sv_3.4.3_3.0_1648738903498.zip
https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/models/lemma_bokmaal_no_3.4.3_3.0_1648738850520.zip
https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/models/lemma_kaist_ko_3.4.3_3.0_1648738885989.zip
https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/models/lemma_gsd_ko_3.4.3_3.0_1648738820489.zip
Help would be highly appreciated!
