### ISSUE TITLE
Spark-NLP fails to load TF related models/pipelines with newer stdlib

### ISSUE THREAD

**Issue by albertoandreottiATgmail** [JohnSnowLabs/spark-nlp#813]
## Description
Due to a problem with Tensorflow 1.15 and some incompatibilities with newer stdlib versions, loading a pipeline from disk fails in 2.4.1.
This is a TF problem, and I'm leaving this information here for reference, and to avoid future headaches of other users.
According to our testing, 
it works with libstdc++.so.6.0.25 and fails with libstdc++.so.6.0.28.
This is what the exception looks like at native level,
```
C  [libtensorflow_framework.so.1+0x10419e5]  tensorflow::random::New64()+0x95
C  [libtensorflow_framework.so.1+0xf6457d]  tensorflow::Device::BuildDeviceAttributes(std::string const&, tensorflow::DeviceType, tensorflow::gtl::IntType<tensorflow::Bytes_tag_, long long>, tensorflow::DeviceLocality const&, std::string const&)+0x5d
C  [libtensorflow_framework.so.1+0xfe2aa5]  tensorflow::NewSingleThreadedCpuDevice(tensorflow::Env*)+0xd5
C  [libtensorflow_framework.so.1+0xf94cd4]  tensorflow::GraphRunner::GraphRunner(tensorflow::Env*)+0x14
C  [libtensorflow_jni.so+0x6fc4af3]
C  [libtensorflow_jni.so+0xadef8d]
C  [libtensorflow_jni.so+0xadf0ae]
j  org.tensorflow.Graph.allocate()J+0
j  org.tensorflow.Graph.<init>()V+21
j  com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.readGraph(Ljava/lang/String;)Lorg/tensorflow/Graph;+16
j  com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.read(Ljava/lang/String;ZZ[Ljava/lang/String;Z)Lcom/johnsnowlabs/ml/tensorflow/TensorflowWrapper;+237
j  com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel$class.readTensorflowModel(Lcom/johnsnowlabs/ml/tensorflow/ReadTensorflowModel;Ljava/lang/String;Lorg/apache/spark/sql/SparkSession;Ljava/lang/String;ZZ[Ljava/lang/String;Z)Lcom/johnsnowlabs/ml/tensorflow/TensorflowWrapper;+189
j  com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel$.readTensorflowMode

```

## Expected Behavior
The pipeline should load without problems in any distro.

## Current Behavior
Due to some TF incompatibility it breaks with a segmentation fault.

## Possible Solution
+ Downgrade Spark-NLP TF version to 1.14 or 1.13 ??
+ Downgrade stdlib in your platform to libstdc++.so.6.0.25. Probably the easiest way to do this is to change to an older version of the OS.

## Steps to Reproduce

1. Check that your C++ library is the problematic version.
2. Try to load a pipelinne.
3. Tensorflow will break trying to create a session.
4. Not sure if it happens every time a session is created. Probably.

## Your Environment

* Spark NLP version:
* Apache NLP version:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version:
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Thanks Alberto, which operating system has this happened already? (Distro and its version)

**Comment by maziyarpanahi** [comment]
I close this issue as the pre-trained models/pipelines have been tested successfully in the following Ubuntu releases:

* Ubuntu 16.04
* Ubuntu 18.04
* Ubuntu 19.10

**Comment by bbodnar** [comment]
The error occurs also with Spark NLP 2.5.5 under Ubuntu 20.04. The default version of  libstdc++ of this OS is 6.0.28.

**Comment by albertoandreottiATgmail** [comment]
@bbodnar thanks for reporting, we have seen these kind of problems in the past related to stdlib, so probably your only option is to use an older Ubuntu, as we don't control all native dependencies and their versions.

**Comment by maziyarpanahi** [comment]
I re-opened this issue and pinned it for other users. But since TensorFlow only accepts up to libstdc++.so.6.0.25 we cannot do anything here. Rather an older OS or downgrade/link to libstdc++.so.6.0.25 would solve this issue.

**Comment by maziyarpanahi** [comment]
@albertoandreottiATgmail Can these be helpful in anyway?

- https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dynamic_or_shared.html#manual.intro.using.linkage.dynamic 

- libstdc++ FAQ at https://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.how_to_set_paths

**Comment by bbodnar** [comment]
Two libstdc++ versions differing only in the minor- or patch-version cannot coexist system-wide, because there is a symbolic link containing only the major version (eg. _libstdc++.so.6_ refers _libstdc++.so.6.0.28_). Applications (TensorFlow too) are mostly linked against such library-names containing only the major version. 
Ubuntu also does AFAIK not provide official packages for the same software differing only in the minor- or patch-version. From libstdc++ the version 5 is available, but that is too old for TensorFlow.

My workaround:
- create a directory "spark-nlp-lib"
- copy "_libstdc++.so.6.0.25_" from an Ubuntu 18.04 (same bitness) into this directory under the name _libstdc++.so.6_ (or create a symlink _libstdc++.so.6_ pointing to _libstdc++.so.6.0.25_)
- in the runtime-environment of Spark NLP set the environment-variable LD_LIBRARY_PATH to "spark-nlp-lib:$LD_LIBRARY_PATH" (use preferably an absolute path to "spark-nlp-lib")
