### ISSUE TITLE
Support Fasttext training?

### ISSUE THREAD

**Issue by bertomartin** [JohnSnowLabs/spark-nlp#814]
I'm new to spark-nlp. Is it possible to use spark-nlp to train fasttext based vectors? or would this have to first be implemented in spark.ml before I could use it as part of an annotator. Or would it be possible to use some other lib like Gensim for training, then hook it up as an annotator? Thanks in advance.

**Comment by maziyarpanahi** [comment]
Hi,
It is mot possible to train fastText in Apache Spark or Spark NLP. However, if you export the text file (token, vector) you can simply use WordEmbeddings() and load it there for distributed lookups same as GloVe or word2vec. (The process is as you describe, train it some where like Gensim, export in .bin / .txt format where each line is a token and a vector and load it in Spark NLP.

**Comment by bertomartin** [comment]
@maziyarpanahi Thank you! Makes sense
