### ISSUE TITLE
Wrong or missing inputCols annotators in TokenAssembler

### ISSUE THREAD

**Issue by sahilsingh1123** [JohnSnowLabs/spark-nlp#817]
## Your Environment

* Spark NLP version: 2.4.1
* Apache NLP version:
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version: linux
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Please provide your full code, we can't help you with one title :)

**Comment by sahilsingh1123** [comment]
I have shared the code in the steps to reproduce section

**Comment by sahilsingh1123** [comment]
from sparknlp.base import DocumentAssembler, TokenAssembler, Pipeline
documentAssembler = DocumentAssembler().setInputCol("Text").setOutputCol("dmx_docs")
tokenAssembler = TokenAssembler().setInputCols(["dmx_docs"]).setOutputCol("dmx_token")

pipeline = Pipeline().setStages([documentAssembler, tokenAssembler])
sentimentAnalysis = pipeline.fit(dataset)
datasetTest = sentimentAnalysis.transform(dataset)

**Comment by maziyarpanahi** [comment]
I don't understand the purpose of this pipeline but as the name suggests, TokenAssembler is to get tokens and assemble them together. You are missing Tokenizer(). 

https://nlp.johnsnowlabs.com/api/index#com.johnsnowlabs.nlp.TokenAssembler

**Comment by sahilsingh1123** [comment]
can you help to lemmatize the column which is basically the array of string, it tokenized it using the spark's own tokenizer.

Schema of my dataset...

root
 |-- Text: string (nullable = true)
 |-- Sentiment: string (nullable = true)
 |-- prediction_knime: string (nullable = true)
 |-- dmx_index: long (nullable = false)
 |-- dmx_tokenized: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- dmx_stopWords: array (nullable = true)
 |    |-- element: string (containsNull = true)

I want to pass the dmx_stopWords column to spark-nlp lemmatizer. and get the dataset with lemmatized column attached with it.

**Comment by maziyarpanahi** [comment]
We can't use Spark ML tokenizer or stop words remover. The annotation schema in Spark NLP is different. We have our own Tokenizer and StopWordsCleaner. 
What I suggest is to go from Spark NLP to Spark ML. Use Spark NLP pipeline for all the NLP even get the embeddings, then use Finisher and FinisherEmbeddings to get the array of results out, then go to Spark ML for classification etc.

Some examples: https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/tutorials/colab


PS: A dedicated ClassifierDL is coming for Text Classification: https://github.com/JohnSnowLabs/spark-nlp/pull/812

**Comment by sahilsingh1123** [comment]
this is what I was thinking too... that is why I started reading your documentation. how do I start, I want to use this on spark dataframe. there is no proper documentation for python

**Comment by maziyarpanahi** [comment]
I just gave you a repo full with Python examples which some of those actually integrate Spark NLP with Spark ML.

PS: Scala and Python APIs are the same in Apache Spark and Spark NLP.
