### ISSUE TITLE
Stem Annotator to work with splitChars

### ISSUE THREAD

**Issue by subhashiniy** [JohnSnowLabs/spark-nlp#818]
When Stemmer takes input from tokenizer; "many" and "applications" will be stemmed separately. Could it be done in a way that "mani_appli" is still with the glue character as is. 

## Description
If my input chunk to stem annotator is "many_applications" and the expected output is "mani_appl" then could you give me an idea of how to modify an existing annotator or if I should write a custom annotator.
Note: The current output is "many_appl". The current behaviour does not support splitting the input to stem at a symbol and putting it back together.

## Expected Behavior
"many_applications" to be stemmed by annotator to "mani_appl"
[all, leav_appl, will, be, proccessed., sinc, we, ar, current_process, mani_appl, there, will, be, delay.]

## Current Behavior
currently it stemmed to "many_appl"
[all, leave_appl, will, be, proccessed., sinc, we, ar, currently_process, many_appl, there, will, be, delay.]

## Steps to Reproduce

1. Please run the following piece of code as is: 
```
from sparknlp.annotator import *
import sparknlp
from sparknlp.annotator import *
from sparknlp.base import *
from pyspark.sql.types import StringType
spark = sparknlp.start()
data = ["All leave_applications will be proccessed. Since we are currently_processing many_applications there will be a delay."]

dfTest = spark.createDataFrame(data, StringType()).toDF("text")

document_assembler = DocumentAssembler()\
		.setInputCol("text")\
		.setOutputCol("document")

tokenizer = Tokenizer() \
		.setInputCols(["document"]) \
		.setOutputCol("token") \
		.setContextChars(['(', ')', '?', '!']) 

stop_words_cleaner = StopWordsCleaner() \
					.setInputCols(["token"]) \
					.setOutputCol("cleanTokens") \
					.setCaseSensitive(False) \
					.setStopWords(["this", "is", "and","i","a", "of","the", "has", "to", "do", "whom"])

stemmer = Stemmer() \
		.setInputCols(["cleanTokens"]) \
		.setOutputCol("stem") 

finisher = Finisher() \
			.setInputCols(["stem"]) \
			.setIncludeMetadata(True)

pipeline = Pipeline(stages=[ 
			document_assembler,
			tokenizer,
			stop_words_cleaner,
			stemmer,
			finisher])

model = pipeline.fit(dfTest)
prediction = model.transform(dfTest)
print (prediction.select("finished_stem").show(truncate=500))


```

## Context
Trying to stem chunks of data. For example after chunking was done and we would like to stem the words in the chunk individually for our use case. 

## Your Environment

* Spark NLP version: 2.4.2
* Apache NLP version: 2.4.4
* Setup and installation (Pypi, Conda, Maven, etc.): python, pip
* Operating System and version: Ubuntu 18.04.3 LTS  
* Link to your project (if any):

Thanks, any help is appreciated.

**Comment by maziyarpanahi** [comment]
Please complete the template so I know which version you are using?

Note: The input to Stemmer is Tokenizer, with a splitChars you should be able to break many_applications to many, applications which they can be separately stemmed. So you can play around with Tokenizer rules and params, but I don’t think it will keep the original form of mani_appli.
