### ISSUE TITLE
Don't have download link to pretrained 'ner_dl_bert' model

### ISSUE THREAD

**Issue by simon-oz** [JohnSnowLabs/spark-nlp#822]
#561  Description
From https://nlp.johnsnowlabs.com/docs/en/models,  it suggests that we can download the pre-trained models from https://github.com/JohnSnowLabs/spark-nlp-models.

I'd like to download 'ner_dl_bert' model, similar to the 'ner_dl' model, but couldn't find the the link to 'ner_dl_bert'  model anywhere

## Expected Behavior
Please provide the link to the 'ner_dl_bert'  for downloading ?

## Current Behavior
No link to the ner_dl_bert pre-trained model

## Context
I tested ner_dl model with GloVe, that works like a charm.
I also like to test ner_dl_bert with BertEmbeddings such as  bert_base_cased to evaluate which works better

## Environment
* Spark NLP version: 2.4.3
* Spark: 2.4.4
* Setup and installation (Pypi, Conda, Maven, etc.): Maven
* Operating System and version: Hadoop 2.7

**Comment by simon-oz** [comment]
@maziyarpanahi, thanks for labeling this.

But I am reporting an issue because I cannot find the download link for  ner_dl_bert would you provide the link to that model please ? From https://github.com/JohnSnowLabs/spark-nlp-models, there is no such model.

**Comment by maziyarpanahi** [comment]
I understood the issue. This is a very big library with lots of things to do, we assign the issue and get to them in the order :)

**Comment by simon-oz** [comment]
@maziyarpanahi Thanks for your kind reply, waiting for the updating :).

**Comment by maziyarpanahi** [comment]
It's been updated:
https://github.com/JohnSnowLabs/spark-nlp-models/blob/master/README.md#english---models

`NerDLModel.pretrained("ner_dl_bert")` also will download the latest version automatically.
