### ISSUE TITLE
Add test support for aarch64 

### ISSUE THREAD

**Issue by odidev** [JohnSnowLabs/spark-nlp#8275]
## Description
I tried testing **spark-nlp** package on **aarch64** architectures but it is generating errors for the` python3.7 -m run-tests` test command in Github Actions:
```
+ python3.7 -m run-tests
Traceback (most recent call last):
  File "/opt/_internal/cpython-3.7.13/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/_internal/cpython-3.7.13/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ws/python/run-tests.py", line 15, in <module>
    from test.annotators import *
  File "/ws/python/test/annotators.py", line 19, in <module>
    from sparknlp.annotator import *
  File "/ws/python/sparknlp/__init__.py", line 18, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
```
While on amd64, I am getting successful test result.

I found a link to [discussion](https://github.com/JohnSnowLabs/spark-nlp/discussions/2562) suggesting to change the versions of pyspark and set SPARK_HOME. When I tried this it didn't solve the issue and got the same above error.
Also macos-latest has been used for amd64, when I am using ubuntu-latest it does not work for both architectures.

When I tried locally for both architectures, similar to github actions it is not able to find pyspark.

## Expected Behavior
Successful test result for aarch64.

## Current Behavior
Gives error related to pyspark.

## Possible Solution
None

## Steps to Reproduce
None

## Context
Can not create and run.

## Your Environment
* Spark NLP version `sparknlp.version()`:  3.4.3
* Apache NLP version `spark.version`: 3.2.0
* Java version `java -version`: java-1.8.0
* Setup and installation (Pypi, Conda, Maven, etc.): 
* Operating System and version: LSB Version:core-4.1-aarch64:core-4.1-noarch, Distributor ID:	CentOS

**Comment by maziyarpanahi** [comment]
could you please fill the template when you are reporting an issue, that information is required in order to answer.

**Comment by odidev** [comment]
I have modified the issue according to the template, could you please share your feedback regarding this and suggest what can be done to test it over ARM64 server?

Thanks in advance.

**Comment by maziyarpanahi** [comment]
@odidev could you please add the snippet part, I need to see how you are starting your SparkSession. (the error indicates you use a Spark NLP that was compiled on one Apache Spark on a different Apache Spark, your code helps me to see that where you make this mistakes - then we can get to the part that whether or not aarch64 is supported)

**Comment by maziyarpanahi** [comment]
I just tested an EC2 instance with `aarch64` and TensorFlow for Java doesn't support that. (we are using tensorflow-java and it only supports `x86_64`. 

You can open a feature request here and see if they can provide support for `aarch64`: https://github.com/tensorflow/java
