### ISSUE TITLE
Introducing a new Multi-class Text Classification: ClassifierDL

### ISSUE THREAD

**Issue by maziyarpanahi** [JohnSnowLabs/spark-nlp#833]
We are very excited to release the very first multi-class text classifier in Spark NLP v2.4.4! We have built a generic ClassifierDL annotator that uses the state-of-the-art Universal Sentence Encoder as an input for text classifications. The ClassifierDL annotator uses a deep learning model (DNNs) we have built inside TensorFlow and supports up to 50 classes.

**NOTE**: ClassifierDL is an experimental feature in 2.4.4 before it becomes stable in 2.4.5 release. We have worked hard to aim for simplicity and we will add more examples by the upcoming days: 

Examples: [Python](https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/jupyter/training/english/classification) and [Scala](https://johnsnowlabs.github.io/spark-nlp-workshop/databricks/index.html#training/3-%20Train%20Multi-Class%20Text%20Classification%20on%20News%20Articles.html)

We are looking forward to your feedback as always.

**Known issues:**
* In Databricks, you need to add two spark configs if you are using UniversalSentenceEncoder. Full instructions: https://github.com/JohnSnowLabs/spark-nlp#databricks-cluster

* The ClassifierDLModel has an issue to be used immediately right after it's trained inside a closer. It needs to be saved and then be loaded back. https://github.com/JohnSnowLabs/spark-nlp/issues/857

**Comment by Aref-cs** [comment]
Hi, have you encountered such an error before while using USE and ClassifieDL for multilabel classification?
py4j.protocol.Py4JJavaError: An error occurred while calling o3063.fit.
: com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Unable to create serializer "com.esotericsoftware.kryo.serializers.FieldSerializer" for class: java.util.concurrent.locks.ReentrantLock

**Comment by maziyarpanahi** [comment]
Hi
I have not seen that error, but since you are using `USE` I would say it is important to have the following configs in the SparkSession:

- https://github.com/JohnSnowLabs/spark-nlp#databricks-cluster
- https://github.com/JohnSnowLabs/spark-nlp#python

```python
spark = SparkSession.builder
    .appName("Spark NLP")
    .master("local[*]")
    .config("spark.driver.memory", "16G")
    .config("spark.driver.maxResultSize", "0")
    .config("spark.kryoserializer.buffer.max", "2000M")
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.12:4.4.0")
    .getOrCreate()
```

The `buffer.max` seems to be an issue in some JVM environments, so setting it explicitly helps with models like USE.
