### ISSUE TITLE
Multi-language model glove_840B_300 not found

### ISSUE THREAD

**Issue by marcodeleonardis** [JohnSnowLabs/spark-nlp#841]
I have problems using the multi-language models Glove glove_840B_300 because I want use it for the italian language.
I' m trying to execute the following Pyspark lines code from Google Colab but I receive the following error. It iseems the model It's no longer available.

Could you check and help me?
![Outlook-qq2dnfsk](https://user-images.githubusercontent.com/10011012/77959061-4b4b1100-72d6-11ea-9b5a-138127c461fe.png)

Thank you!
Have a nice day!

## Context

Expermients
## Your Environment

* Spark NLP version: 2.4.4
* Apache NLP version: 2.4.4
* Java version (java -version): Java 8
* Setup and installation (Pypi, Conda, Maven, etc.): Pypi 
* Operating System and version: Google Colab
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Please update the template with the required information.

**Comment by marcodeleonardis** [comment]
Have you now all the informations required?

**Comment by maziyarpanahi** [comment]
Thanks, @marcodeleonardis  I also need the full code to reproduce this. One thing that is wrong is that you forgot to mention the `lang`. If you look at this repo, they all have the language as well:

https://github.com/JohnSnowLabs/spark-nlp-models

name=`glove_840B_300`, lang='xx'

But the error doesn't make sense, so could you please provide the steps to reproduce this error?

**Comment by maziyarpanahi** [comment]
Oh, I see now, the language is missing so it couldn't find it to download. Just add `lang=xx` after the name and it will be fine.

**Comment by marcodeleonardis** [comment]
I follow your suggestion but It still doesn't work as you can see:

![immagine](https://user-images.githubusercontent.com/10011012/77994330-15d01300-732a-11ea-8461-e4cd46af3f3c.png)

**Comment by maziyarpanahi** [comment]
There is no Italian language for that model. The language is in front of each model, which in this case is xx. That is glove with 840 billion tokens and all the languages. Please follow the table for each model/pipeline.

**Comment by marcodeleonardis** [comment]
Ok so. How can i download and use that model? My first code line was this but I eceveive error.
![immagine](https://user-images.githubusercontent.com/10011012/77996400-d4416700-732d-11ea-9fcc-040a578c37b5.png)

**Comment by maziyarpanahi** [comment]
I mentioned above! I left an example:
name=“glove_840B_300”, lang='xx'
 
Please read the docs and look st the examples, I mentioned all the necessary references.

**Comment by marcodeleonardis** [comment]
Ok. Now i understand e It's fine. Thanks for your support.

**Comment by maziyarpanahi** [comment]
You are welcome
