### ISSUE TITLE
Enabling scores for sentiments in the pretrained analyze_sentiment PipelineModel?

### ISSUE THREAD

**Issue by timrourke** [JohnSnowLabs/spark-nlp#843]
**Is your feature request related to a problem? Please describe.**
I am using spark-nlp v2.4.4 for sentiment detection, and am interested in using the `double`-based sentiment values instead of the simpler string values "positive" and "negative". I'm wondering if there is some way of enabling this behavior on a pre-trained model, specifically the `analyze_sentiment` model defined in [the spark-nlp-models](https://github.com/JohnSnowLabs/spark-nlp-models) repo.

**Describe the solution you'd like**
I'd like a way to work with the `Annotator` configuration on a pre-trained model containing [com.johnsnowlabs.nlp.annotators.sda.pragmatic.SentimentDetectorModel](https://github.com/JohnSnowLabs/spark-nlp/blob/2.4.4/src/main/scala/com/johnsnowlabs/nlp/annotators/sda/pragmatic/SentimentDetectorModel.scala) so that I can optionally enable scoring, as is possible by [setting this property to true](https://github.com/JohnSnowLabs/spark-nlp/blob/2.4.4/src/main/scala/com/johnsnowlabs/nlp/annotators/sda/pragmatic/SentimentDetectorModel.scala#L38).

**Describe alternatives you've considered**
I'm really not sure what the alternative approach would be, though one thing that comes to mind is to include the `double` value AND the `string` value for a given sentiment. Put another way, is there a good reason rendering a string representation for sentiment and rendering the double representation for the sentiment score are mutually exclusive? Why not include both values in the returned Annotator model?

**Additional context**
N/A

**Comment by maziyarpanahi** [comment]
Hi,

Thanks for the feature request. I think we forgot to re-train that model after we added that feature.

I will update you once it’s done.

**Comment by timrourke** [comment]
@maziyarpanahi Thanks! I really appreciate your hard work!

Do you have a feeling for how long it might take? No worries if it will be a while, I know you have a lot on your plate maintaining this!

Another question: I take it that it is not possible to configure settings on annotators at all for pre-trained models? Is that even viable?

**Comment by maziyarpanahi** [comment]
Hi @timrourke 
Sorry for the delay. So the answer is yes, you can access the parameters in the models inside a pipeline even if it's retained. You create a new model from that pipeline by using `asInstanceOf` and you can use .get to extract information or set new params and use it in another pipeline.

The issue with `analyze_sentiment` pipeline is that it's not using `SentimentDetectorModel` to enable the scores. It's using `ViveknSentimentModel` instead.

In the next versions, however, we are introducing a new annotator called `SentimentDL` which will be much easier to use, flexible, and way more accurate than these two. Plus, it will have the confidence scores for all the classes in the metadata by default.

I'll keep you posted here once it's out.

**Comment by timrourke** [comment]
Thanks @maziyarpanahi for the tips and the excellent work!!!
