### ISSUE TITLE
embedding models offline loading

### ISSUE THREAD

**Issue by sooditaher** [JohnSnowLabs/spark-nlp#851]
Hi,

## Description

I am trying to do sentence embedding using USE and BERT models and load them offline.
USE can be loaded but BERT model stopping by error
AttributeError: module 'sparknlp.embeddings' has no attribute 'BertEmbeddings'
I am using spark-nlp 2.4.5 , pyspark 2.4.5 and spark 2.4.3
I installed spark-nlp through pip. and add fat jar file "spark-nlp-assembly-2.4.5.jar" in spark and pyspark jars folder. 
## Steps to Reproduce

1.
2.
3.
4.

## Context

from pyspark.context import SparkContext
from pyspark.conf import SparkConf
from pyspark.sql import  SQLContext

import sparknlp
from sparknlp.annotator import *
from sparknlp.base import *

sparkContext = SparkContext(conf=SparkConf())
sqlContext = SQLContext (sparkContext)
sparknlp.start()

data = [
    ("New York is the greatest city in the world", 0),
    ("The beauty of Paris is vast", 1),
    ("The Centre Pompidou is in Paris", 1)
]

df = sqlContext.createDataFrame(data, ["text","label"])

document_assembler = DocumentAssembler() \
    .setInputCol("text") \
    .setOutputCol("document")

tokenizer = Tokenizer().setInputCols(["document"]) \
    .setOutputCol("token")

word_embeddings = sparknlp.annotator.BertEmbeddings.load("/......../bert_large_uncased_en_2.4.0_2.4_1580581306683/") \
    .setInputCols(["document", "token"]) \
    .setOutputCol("embeddings")

bert_pipeline = Pipeline().setStages(
    [
        document_assembler,
        tokenizer,
        word_embeddings
    ]
)

df_bert = bert_pipeline.fit(df).transform(df)
df_bert.show()
## Your Environment

* Spark NLP version: 2.4.5
* Apache NLP version:
* Java version (java -version): 8
* Setup and installation (Pypi, Conda, Maven, etc.): pip
* Operating System and version:mac
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Could you please fill out the template we provide for issues? We need those information. The more specific you are in that template the easier it is for us to reproduce it step by step and help you.
