### ISSUE TITLE
WordSegmenterModel will change text order

### ISSUE THREAD

**Issue by jacky0218** [JohnSnowLabs/spark-nlp#8530]
## Description

I just found that When I using the BertForTokenClassification(In japanese)(https://nlp.johnsnowlabs.com/2021/09/10/bert_token_classifier_ner_ud_gsd_ja.html), seems like it will change the words automatically

like:
original one: 表面圧縮応力
after fit the model:  '表面', '圧応', '縮', '力',

any idea to slove this problem?
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.4.4
* Apache NLP version `spark.version`: 3.1.2
* Java version `java -version`: 11.0.15
* Setup and installation (Pypi, Conda, Maven, etc.): colab
* Operating System and version: colab
* Link to your project (if any): https://colab.research.google.com/drive/14AFVFvj5jDhqy52XO2dgCALLKMwLp0Jg?usp=sharing

**Comment by maziyarpanahi** [comment]
Could you please fill in the `Environment` completely and provide an end-to-end code snippet? (Google Colab would be the easiest to debug this)

**Comment by jacky0218** [comment]
I give you the colab link (https://colab.research.google.com/drive/14AFVFvj5jDhqy52XO2dgCALLKMwLp0Jg?usp=sharing)
thx for your help!

**Comment by maziyarpanahi** [comment]
Thanks for the notebook @jacky0218 

So the issue is with `WordSegmenterModel` that changes the order of segmented tokens.

@DevinTDHa could you please check to see whether it's the model or `WordSegmenterModel` annotator that causes this issue?
