### ISSUE TITLE
import gpt-2 model into spark nlp.

### ISSUE THREAD

**Issue by leeivan** [JohnSnowLabs/spark-nlp#8532]
I trained a gpt-2 model fine-tuned by huggingface. How could I import this model into spark nlp? please give some idea, appreciate it.

**Comment by maziyarpanahi** [comment]
Hi,

Only the architectures mentioned here are supported: https://github.com/JohnSnowLabs/spark-nlp/discussions/5669
Some are very hard, some are impossible so you have the table there for the current situation.
