### ISSUE TITLE
Do we supply the method that convert spark sql dataframe to tensorflow-java ByteNdArray object ?

### ISSUE THREAD

**Issue by mullerhai** [JohnSnowLabs/spark-nlp#8556]
Hi :
        Now I etl the raw data use spark sql generate the dataframe , I want to convert the spark dataframe object to ByteNdArray object for tensorflow model input with spark -nlp

**Comment by maziyarpanahi** [comment]
Hi,

Spark NLP is not meant to be used as a TF engine. Everything related to TensorFlow is internal and the user has no way of interacting with the internals of TF in Spark NLP. 

There are many libraries that are meant for general use of TF in Scala and Spark, I suggest looking into those.
