### ISSUE TITLE
Do we have make the LSTM Layer  with Tensorflow-java  to the real  in spark-nlp project?

### ISSUE THREAD

**Issue by mullerhai** [JohnSnowLabs/spark-nlp#8557]
HI:  
     I know  spark-nlp is best project for spark combine tensorflow,  I want to use the Tensorflow-Java BlockLSTM  class  to make Lstm Layer like  python keras layer  real in scala ,but   I not know  how to use BlockLSTM? if our project  could do  that ,I think  it will be great for  spark-scala  to deal with  time-series data build  tensorflow model.
     and  I have found our contributor @[danilojsl](https://github.com/danilojsl)  has report some relate issue :https://github.com/tensorflow/java/issues/270
     and  do some base test :https://github.com/danilojsl/tensorflow-java-spikes/blob/main/src/main/java/LSTMSpike.java
     thank you,

**Comment by maziyarpanahi** [comment]
sorry you are in a wrong project, this is library is intended to be used for distributed NLP (not TensorFlow, we use TF internally and will not expose any APIs)

There are other libraries for Spark/TensorFlow

**Comment by mullerhai** [comment]
> sorry you are in a wrong project, this is library is intended to be used for distributed NLP (not TensorFlow, we use TF internally and will not expose any APIs)
> 
> There are other libraries for Spark/TensorFlow
Sorry, anyway, I want to know  
in our project how to build lstm model for nlp task?

**Comment by maziyarpanahi** [comment]
> in our project how to build lstm model for nlp task?

All the code is open-source, please have a look. We do not support the use of TensorFlow in Spark NLP.
