### ISSUE TITLE
Change the copyright year in all html pages

### ISSUE THREAD

**Issue by anju-jsl** [JohnSnowLabs/spark-nlp#86]
## Description
All HTML pages for nlp.johsnowlabs.com should have "© 2017-2018" in the footer

**Comment by maziyarpanahi** [comment]
I can do this, if this is the right format and I am allowed to touch the HTML on the pages?
`last time I did update the HTML it was rejected`

**Comment by anju-jsl** [comment]
Thank you @maziyarpanahi for providing the help
I had to make another change in the footer and alongside changed this one also. 
Hope thats ok, and please do keep checking the spark-nlp repo and keep providing the suggestions for further improvements.
Thanks
Anju
