### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by noahberhe** [JohnSnowLabs/spark-nlp#868]
I'm running the below code in Jupyter notebook, and I keep getting TypeError: 'JavaPackage' object is not callable

```
import sparknlp 
from sparknlp.pretrained import PretrainedPipeline

spark = sparknlp.start()

pipeline = PretrainedPipeline('recognize_entities_dl', 'en')
result = pipeline.annotate('Harry Potter is a great movie')
```
yielding error:

```
recognize_entities_dl download started this may take some time.
 TypeError: 'JavaPackage' object is not callable 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-37-da3074291435> in <module>
----> 1 pipeline = PretrainedPipeline('recognize_entities_dl', 'en')
      2 result = pipeline.annotate('Harry Potter is a good book')
```

I have Java 8 installed on my mac (looked at the Java About... menu)
Looking at my virtual env, I have spark-nlp 2.4.5, pyspark 2.4.5.

I have also tried with replacing the:
```
spark = sparknlp.start()

```

with:
```
spark = SparkSession.builder \
    .appName("Spark NLP")\
    .master("local[4]")\
    .config("spark.driver.memory","16G")\
    .config("spark.driver.maxResultSize", "2G") \
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.4.5")\
    .config("spark.kryoserializer.buffer.max", "1000M")\
    .getOrCreate()
```

to no avail.

Any advice please?

**Comment by noahberhe** [comment]
Hello Maziyar, thanks for getting back to me.

I ran the code in python shell, and after some time downloading the relevant packages it returns what you'd expect:
ie. 
print(result['entities']) 
gives
['Harry Potter']

As you said, it appears to be a Jupyter issue? 
What would you suggest please?

Regards

**Comment by maziyarpanahi** [comment]
I do have Jupyter via Anaconda on macOS, there is no issue with that, as long as you create a new  Python3 kernel not anything else. Sometimes users use some third-party kernels for their Apache Spark and it starts the SparkSession before you start it and it cannot pass the config. (just make sure, your Jupyter doesn't do anything with PySpark and it's just for Pyrhon3, the rest will be handled by `spark = sparknlp.start()`

**Comment by noahberhe** [comment]
I was just about to reply to you, so I restarted my kernel and made sure the only spark related imports were:
```
import sparknlp 
spark = sparknlp.start()
import pyspark as ps
```
I was able to run spark normally on my notebook, including Spark NLP functions. So hopefully that's right. I didn't realise that sparknlp.start() was all I needed to create a spark session.

Thanks

**Comment by freemedom** [comment]
i find that if i run spark = sparknlp.start(). it's ok.
but if i run 
spark = SparkSession.builder \
    .appName("namename") \
    .getOrCreate()
i will get the "[TypeError: 'JavaPackage' object is not callable](https://github.com/JohnSnowLabs/spark-nlp/issues/868#top)"

**Comment by freemedom** [comment]
i know the reason. it's because 
```
        if params.get("spark.jars.packages") is None:
            builder.config("spark.jars.packages", spark_jars_packages)
```
sparknlp add some jars but the default SparkSession didn't add them.

**Comment by freemedom** [comment]
In addition, it seems that the jar packages under the SPARK_HOME path in the environment variable in Windows is preferred by the jar packages that comes with pyspark(site-packages\pyspark\jars). so if the jar in these two paths is different version, there also will be this JavaPackage' object is not callable
