### ISSUE TITLE
LightPipeline with metadata

### ISSUE THREAD

**Issue by lorenz-nlp** [JohnSnowLabs/spark-nlp#873]
**Is your feature request related to a problem? Please describe.**
The LightPipeline is terrific to parse text quickly without the overhead introduced by Spark Pipelines. However, if metadata needs to be passed for the pipeline to work, the LightPipeline is not usable anymore due to the missing interface.

**Describe the solution you'd like**
Within `com.johnsnowlabs.nlp.LightPipeline`, an empty Map is passed within the method "fullAnnotate" to the DocumentAssembler. If the interface offers to set the metadata map, the LightPipeline could be used with pipelines that require metadata. If the default value is set to an empty map, no compile error occur for user who use the old interface:

```
def fullAnnotate(target: String, startWith: Map[String, Seq[Annotation]] = Map.empty[String, Seq[Annotation]], metadata: Map[String, String] = Map.empty): Map[String, Seq[Annotation]] = {
   getStages.foldLeft(startWith)((annotations, transformer) => {
      transformer match {
         case documentAssembler: DocumentAssembler =>
            annotations.updated(documentAssembler.getOutputCol, documentAssembler.assemble(target, metadata))
    ...
}
```

**Comment by maziyarpanahi** [comment]
Thanks for the feature request, could you please provide a snippet code that portraits the issue as an example? I would like to understand the exact need for this in `fullAnnotate()` with an actual example.
Many thanks

**Comment by lorenz-nlp** [comment]
Thanks for your quick response. Here is a code snipped that illustrates the problem:

```
/**
 * Email with metadata
 */
val emailText = "actual email text for document assembler"
val metadata = Map(
	"name"-> "Lorenz",
	"email" -> "email@domain.com"
)

/*
Spark dataframe with metadata column
 */
val dataFrame = Seq((emailText, metadata)).toDF("emailTextColumn", "metadataColumn")

val documentAssember = new DocumentAssembler()
  .setInputCol("emailTextColumn")
  .setMetadataCol("metadataColumn")

/*
Spark Pipeline
 */
val pipeline = new Pipeline().setStages(Array(documentAssember))
val pipelineModel = pipeline.fit(dataFrame)

val transformed = pipelineModel.transform(dataFrame) // document assembler uses metadata column to assemle a document with metadata

/*
Spark NLP LightPipeline
 */
val lightPipeline = new LightPipeline(pipelineModel)
lightPipeline.annotate(emailText, metadata) // compile error, as metadata cannot be passed currently. Document assembler only creates a document with no metadata
```

Please let me know if you need further clarification.

**Comment by maziyarpanahi** [comment]
Thanks for the example, so the `metadata` is not a Spark NLP metadata, it's just an extra column that is not used in the Spark NLP Pipeline. What is the exact point of having a customized Map object without being used in the pipeline inside LightPipeline? (I am trying to understand the end result of the feature request)
Thank you again.

**Comment by lorenz-nlp** [comment]
Nono, the metadataColumn is used by the DocumentAssembler, as I set it on  `.setMetadataCol("metadataColumn")`. Later in my Spark NLP Pipeline I have own AnnotatorModels which have a Document as input type, and access and use the corresponding metadata then as well.

I hope I could provide a detailed picture about my usecase - if not, please let me know :)

**Comment by maziyarpanahi** [comment]
It's perfectly explained. I totally forgot about `setMetadataCol` param so that was my initial confusion. Everything is cleared now and thank you very much.
