### ISSUE TITLE
Using BioBert 

### ISSUE THREAD

**Issue by jamshaidsohail5** [JohnSnowLabs/spark-nlp#876]
**Is your feature request related to a problem? Please describe.**
I wanted to use BioBert for generating an embedding of words belonging to the medical domain. I wanted to use the spark NLP BioBert as [here](https://github.com/JohnSnowLabs/spark-nlp-models#licensed-enterprise).  The thing which is confusing to me is that they are made available to download as you can see from the link above.  Are they available for research or commercial use ? Are they yet to be incorporated in the sparkNLP ? Also is there a link on the usage of them ?

**Describe the solution you'd like**
I want to use BioBert in one of my recent problems for generating embeddings for words from medical domain and will take it to the next level to incorporate it in one of our app for question-answering.

**Describe alternatives you've considered**
One Option we were having was to use the [BioBert official repo](https://github.com/dmis-lab/biobert). But we wanted to explore the capabilities of spark so decided to use it.

Any detailed response would be highly appreciated.

**Comment by maziyarpanahi** [comment]
Hi @jamshaidsohail5 

Any model listed under `Licensed Enterprise` is only available to download and used in the Enterprise edition of Spark NLP Healthcare which is shipped with AWS keys and License keys. 

Here we manage anything and everything related to the open-source Spark NLP which is this repo and every other model/pipeline available for download and use by the open-source library.

**Comment by maziyarpanahi** [comment]
BioBERT and ClinicalBERT models (6) are now available on 2.5.x releases!
https://github.com/JohnSnowLabs/spark-nlp/releases/tag/2.5.1
