### ISSUE TITLE
Tensorflow "table not initialized" using pretrained model

### ISSUE THREAD

**Issue by davinro** [JohnSnowLabs/spark-nlp#877]
## Description
In the example ClassifierDL_Train_multi_class_news_category_classifier.ipynb an exception is thrown in the cell which applies the model to the training data.

## Expected Behavior
The cell

`pipelineModel = pipeline.fit(trainDataset)`

should complete without error.

## Current Behavior

An Tensorflow exception is thrown, reporting "table not initialized".

## Possible Solution

The code invoked by ClassifierDLApproach does seem to add an "init_all_tables" target, so it is not clear why the exception is thrown. As a workaround in TensorflowWrapper.scala I changed a line in readObject to

`val tf = TensorflowWrapper.read(file.toString, zipped = true, initAllTables = true)`

which allowed the cell to run.

## Steps to Reproduce

Run a current version of the above-named jupyter notebook.

## Your Environment

* Spark-NLP version: 2.4.5
* Apache Spark version: 2.4.5
* Operating System and version: Mint Linux, compatible with Ubuntu 18.04.
* Deployment (Docker, Jupyter, Scala, pip, conda, etc.): Jupyter

**Comment by maziyarpanahi** [comment]
Thanks for opening this issue, the example has been tested in most environments. 
Could you please share how you start your SparkSession, how you installed Spark NLP and provide the full snippet code?

**Comment by davinro** [comment]
Please see the info given in https://github.com/JohnSnowLabs/spark-nlp/issues/878.

Here is my version of TensorflowWrapper.scala with the workarounds for these two issues.

[TensorflowWrapper.zip](https://github.com/JohnSnowLabs/spark-nlp/files/4558741/TensorflowWrapper.zip)

**Comment by maziyarpanahi** [comment]
Instructions to resolve this issue is not to change anything in the code but adding the missing spark.config to allow serialization of such large TF model like USE.
https://github.com/JohnSnowLabs/spark-nlp/issues/878
