### ISSUE TITLE
Incorrect Tensorflow serialization in ClassifierDLApproach

### ISSUE THREAD

**Issue by davinro** [JohnSnowLabs/spark-nlp#878]
## Description

In the examples notebook ClassifierDL_Train_multi_class_news_category_classifier.ipynb the pipeline on the driver serializes the Tensorflow data into a structure which the executors are unable to read.

## Expected Behavior

The executors expect the unzipped tensor as received from the driver to be in a file structure containing files

`saved_model.pb`
`variables.index`
`variables.data-00000-of-00001`

## Current Behavior
The driver serializes the tensor into a structure such as

`saved_model.pb`
`variables_temp_eb55ff6cf0c14fd28bc824f1bf25f9f7/part-00000-of-00001.index`
`variables_temp_eb55ff6cf0c14fd28bc824f1bf25f9f7/part-00000-of-00001.data-00000-of-00001`

which causes the executors to throw an error when they attempt to read it.

## Possible Solution

The structure is produced by native Tensorflow code so a workaround is to modify TensorflowWrapper.scala to correct the structure after it is made. I added code to the saveToFile method which examples the temporary directory and changes the paths. This code is placed between the creation of the file structure and the zip operation.

## Steps to Reproduce

Run the jupyter notebook.

## Your Environment

* Spark-NLP version: 2.4.5
* Apache Spark version: 2.4.5
* Operating System and version: Mint Linux, compatible with Ubuntu 18.04.
* Deployment (Docker, Jupyter, Scala, pip, conda, etc.): Jupyter

**Comment by maziyarpanahi** [comment]
As in the other issue, this one requires the full details of how the library was installed and how you are starting your SparkSession with the full code to be reproduced.

This could be the Mint Linux or your OS setup permission on File System as all the tests have passed on all the TF related annotators including ClassifierDL on Ubuntu, Red Hat, Debian, macOS, Windows, Google Colab, Databricks on Azure, Databricks on AWS, and Cloudera with YARN)

The more details you are in how we can reproduce this the better. 

PS: There must be an actual error here as well, the Driver broadcast the TF graph/model to all the executors so they all only access the broadcasted TF session.

**Comment by davinro** [comment]
Attached are the spark-defaults.conf and the kernel.json for jupyterlab.

[spark-config.zip](https://github.com/JohnSnowLabs/spark-nlp/files/4557927/spark-config.zip)

The Spark version is 'spark-2.4.5-bin-without-hadoop'. The Hadoop version is from HDP 3.1.4. Environment variables for Jupyterlab are

```

export JAVA_HOME=/opt/jdk1.8.0_172/
export PATH=$JAVA_HOME/bin:$PATH

export HADOOP_HOME=/usr/hdp/3.1.4.0-315/hadoop
export PATH=$HADOOP_HOME/bin:$PATH
export HADOOP_CONF_DIR=$HADOOP_HOME/conf

export SPARK_HOME=/ssd/opt/spark-2.4.5-bin-without-hadoop
export PATH=$SPARK_HOME/bin:$PATH
export SPARK_CONF_DIR=/ssd/opt/spark-2.4.1-bin-hadoop2.7/conf
export SPARK_DIST_CLASSPATH=$(hadoop classpath)

export PATH=/ssd/opt/anaconda3/bin:$PATH
export PATH=$SPARK_HOME/bin:$SPARK_HOME/sbin:$PATH
export PYSPARK_DRIVER_PYTHON=jupyter
export PYSPARK_DRIVER_PYTHON_OPTS='notebook'
export PYSPARK_PYTHON=python3
export PYTHONPATH=$SPARK_HOME/python:$PYTHONPATH
```


The commit ID of the spark-nlp source is 'f99e21d96631c33a95e75f9415359b4a63e504c1', which is from April 20. The build.sbt has the lines

```
val sparkVer = "2.4.5"
val scalaVer = "2.11.12"
val scalaTestVersion = "3.0.0"
…
version := "2.4.5"
```

and otherwise unchanged. The only source file modified is TensorflowWrapper.scala.

I noticed that 'sbt assembly' gives the error

```
Compiling /home/tdh/source/spark-nlp/python/tensorflow/ner/create_models.py ...
  File "/home/tdh/source/spark-nlp/python/tensorflow/ner/create_models.py", line 12
    raise Exception(f'Spark NLP is compiled with TensorFlow 1.15.0. Please use such version and not {tf.__version__}.')

```

even though

```

$ python -c "exec(\"import tensorflow\nprint(tensorflow.__version__)\")"
1.15.0
$ python2.7 -c "exec(\"import tensorflow\nprint(tensorflow.__version__)\")"
1.15.0
$ python3 -c "exec(\"import tensorflow\nprint(tensorflow.__version__)\")"
1.15.0
```

The Anaconda tensorflow library is 

`-rwxrwxr-x 1 tdh tdh 37025728 Apr 24 06:11 /ssd/opt/anaconda3/lib/python3.6/site-packages/tensorflow_core/libtensorflow_framework.so.1
`

In case this get used the system python tensorflow library is

`-rwxr-xr-x 1 root staff 37025728 Apr 30 08:30 /usr/local/lib/python3.6/dist-packages/tensorflow_core/libtensorflow_framework.so.1
`

This is evidently the tensorflow library that spark-nlp uses

`
-rw-rw-r-- 1 tdh tdh 35226832 Oct 22  2019 '/home/tdh/source/spark-nlp/target/streams/.../libtensorflow_framework.so.1'
`

I don't know why it has a slightly different size.

The data nodes are running HDP 3.1.4 on Centos 7. Tensorflow is not installed on them.

**Comment by davinro** [comment]
The model being downloaded is 

```
$ hdfs dfs -ls /user/tdh/cache_pretrained
Found 1 items
drwxr-xr-x   - tdh hdfs          0 2020-04-30 12:46 /user/tdh/cache_pretrained/tfhub_use_en_2.4.0_2.4_1587136330099
```

Stopping the driver in a debugger, I could see that the spark-nlp-assembly jar is listed first among the java native library paths. I went ahead and checked all the other paths, and there is no tensorflow installed in any of therm.

In the sbt cache all of the org.tensorflow versions are 1.15.0. So the driver is evidently using the correct version of tensorflow.

The format of the serialization produced by TensorflowWrapper.saveToFile is that of a checkpoint for the result of the cell 

`pipelineModel = pipeline.fit(trainDataset)`

in ClassifierDL_Train_multi_class_news_category_classifier.ipynb.

For the cell previous to that TensorflowWrapper.saveToFile is also called at some point, and in that case serializes the tensor in the expected format.

**Comment by maziyarpanahi** [comment]
Thanks for the information, the most important parts are still missing. Before jumping into finding files in tmp or changing code, I need to know how did you install the Spark NLP and how do you start SparkSession?

PS: Spark NLP comes with TensorFlow, there is no need to have external TensorFlow

**Comment by maziyarpanahi** [comment]
I think you should revert every change you have made, and follow the instructions here which is the same exact error: https://github.com/JohnSnowLabs/spark-nlp/issues/850#issuecomment-614168275

(That is why I’ve been asking how you are starting your SparkSession)

**Comment by davinro** [comment]
That solved the "table not initialized" problem, but I am still getting from the executor

`Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /hadoop/yarn/local/usercache/tdh/appcache/application_1588252714560_0014/container_e64_1588252714560_0014_01_000002/tmp/29ab0872f545_ner224534386356310955/variables`

so I believe the serialization structure is still wrong in the driver. Though TensorflowWrapper is clearly specifying a directory name of 'variables', the invocation of the native tensorflow code results in a different name, as described in the original issue.

Since I am running a notebook in Jupyter Lab, the Jupyter Lab server is starting the spark session, in client mode. It is using command line arguments as shown in the kernel.json file attached in an earlier comment, and Spark settings as shown in the spark-defaults.conf included there.

Spark NLP was installed using pip3 in the environment in which Jupyter Lab is running.

The spark-nlp-assembly jar file is sent to the executors at runtime, using the spark.yarn.archive setting in which that jar and the default Spark client jars are placed in a zip file and sent to the executors. Alternatively, the spark.jars setting can be used.

Please let me know if there is any other information you need.

**Comment by davinro** [comment]
Tried the workaround of rewriting pipelineModel given in https://github.com/JohnSnowLabs/spark-nlp/issues/850, but the same error was returned.

Also tried starting Jupyter Lab with "--packages com.johnsnowlabs.nlp:spark-nlp_2.11:2.4.5" instead of using the spark.jars setting, but the same error was returned.

**Comment by maziyarpanahi** [comment]
I am sorry I am lost in all the extra information. Let’s break this down

- the table not initialized was resolved by adding the extra configs into the SparkSession? 

- the other error is new so I need more information on how this cluster is setup, how do you start the SparkSession, what are the operating systems.

- I also need to know the new error happens where exactly in the code?

**Comment by davinro** [comment]
Yes, the 'table not initialized' was resolved by adding the extra configs into the SparkSession.

Running the example with pyspark-shell and the --packages option did work, so the issue arose when trying to providing jar files via other mechanisms supported by Spark. It should be possible to make the spark.jars or spark.yarn.archive setting in spark-defaults.conf work as an alternative to --packages on the command line.

By default the Spark driver creates a .sparkStaging directory in the user's home directory on hdfs and copies into it all of the jars from the Spark client, and also the jars specified with spark.jars. Using spark.yarn.archive allows placing all those jars in a zip file on hdfs once. It avoids the step of copying all Spark jars every time. The driver in client mode doesn't access them, so it may be necessary to set spark.driver.extraClassPath as well.

I created such a zip file including the spark-nlp-assembly-2.4.5.jar from the link you provided and was able to run the example.

The same procedure did not work when using the spark-nlp-assembly-2.4.5.jar produced by sbt, even when no alterations to the source code had been made. So the problem seems to come from the build.

I thought that by checking out the 2.4.5 tag I could build the same binary as is released publicly. That is, I have

```
$ git log --oneline
dc8b6552 (HEAD, tag: 2.4.5) Merge pull request #844 from JohnSnowLabs/245-release-candidate
...
```

which shows the desired tag. 

It would be nice to be able to run spark-nlp from a build. Any suggestions?

Thanks for your inputs in helping me resolve this.

**Comment by maziyarpanahi** [comment]
> Yes, the 'table not initialized' was resolved by adding the extra configs into the SparkSession.
> 
This is good, so this is resolved.
> Running the example with pyspark-shell and the --packages option did work, so the issue arose when trying to providing jar files via other mechanisms supported by Spark. It should be possible to make the spark.jars or spark.yarn.archive setting in spark-defaults.conf work as an alternative to --packages on the command line.

I don't think the issue is the jar itself rather how it's being distributed so probably you will be able to do the same from pyspark-shell even with spark.jars or --jars pointing to the Fat JAR.

> By default the Spark driver creates a .sparkStaging directory in the user's home directory on hdfs and copies into it all of the jars from the Spark client, and also the jars specified with spark.jars. Using spark.yarn.archive allows placing all those jars in a zip file on hdfs once. It avoids the step of copying all Spark jars every time. The driver in client mode doesn't access them, so it may be necessary to set spark.driver.extraClassPath as well.

That's not true only for archive. If your JARs are on HDFS (hdfs:///), using spark.jars or --jars if you look closely to the logs of YARN you can see it will list them one by one and saying it's already on the HDFS so no need to copy and it skips it. 

> I created such a zip file including the spark-nlp-assembly-2.4.5.jar from the link you provided and was able to run the example.
> 
> The same procedure did not work when using the spark-nlp-assembly-2.4.5.jar produced by sbt, even when no alterations to the source code had been made. So the problem seems to come from the build.
> 
> I thought that by checking out the 2.4.5 tag I could build the same binary as is released publicly. That is, I have
> 
> ```
> $ git log --oneline
> dc8b6552 (HEAD, tag: 2.4.5) Merge pull request #844 from JohnSnowLabs/245-release-candidate
> ...
> ```
> 
> which shows the desired tag.
> 
> It would be nice to be able to run spark-nlp from a build. Any suggestions?
> 
> Thanks for your inputs in helping me resolve this.

You can simply check out anywhere in the repo and do a smile `sbt assembly` to get a Fat JAR. The one on S3 is not different than the one you get from `245-release-candidate` branch. The reason I said to use the S3 because I was sure there won't be any doubt in whether or not:
* You have made some changes in the code and forgot to revert
* You made the revert but by mistake using the jar made previously

I suggest:

* you remove the clone, remove all the jars and archives you made
* once you are sure there is nothing left please clone again
* Check out 245-release-candidate branch
* do `sbt assembly` to get a Fat JAR
* try using that jar with --jars or spark.jars from pyspark-shell 
* then try to do the same with Jupyter Lab (--jars or spark.jars)
* --jars or spark.jars as I said won't copy anything anywhere if it starts with hdfs:///
* Do not forget the related spark.config for the session

I am suspecting changes in the code were not reverted correctly or they were but the JAR was used was not the correct/clean jar right from the branch.
