### ISSUE TITLE
'Tokenizer' object has no attribute 'transform'

### ISSUE THREAD

**Issue by gourav-sg** [JohnSnowLabs/spark-nlp#881]
I started the spark context by using the following method:

Downloaded the FAT jar from  https://github.com/JohnSnowLabs/spark-nlp/releases for spark 2.4.4

prod_jar = "s3://mys3bucket/jars/spark-nlp-assembly-2.4.4.jar"
spark = SparkSession.builder.master("yarn") \
                                .config("spark.jars", pre_prod_jar)\
                                .getOrCreate()
spark.sparkContext.addPyFile(pre_prod_jar)

import sparknlp
import tensorflow

import sparknlp

## Description
Everything is working fine including the SentenceDetector annotator, but when I try to use the Tokenizer then I get the above error

## Expected Behavior
The tokenizer should have a method called as transform

## Current Behavior
Tokenizer does not have the method transform

## Possible Solution
no clues

## Steps to Reproduce
mentioned above

## Context
cannot use the tokenizer annotator

## Your Environment
* Spark NLP version: 2.4.4
* Apache NLP version:
* Java version (java -version): 1.8
* Setup and installation (Pypi, Conda, Maven, etc.): direct fat jar file addition to SPARK session
* Operating System and version: AWS EMR 
* Link to your project (if any): sorry running in client VPC

**Comment by maziyarpanahi** [comment]
Could you please provide your full code and the full trace stack of the error?

**Comment by maziyarpanahi** [comment]
PS: Tokenizer is a model, it needs a .fit() before being able to have .transform()
PS: Spark NLP does need a separate TensorFlow, it’s bundle inside, so if you are importing TensorFlow for Spark NLP you can remove it from your app.

**Comment by gourav-sg** [comment]
Superb, thanks a ton :) 

The following worked now:

`
from sparknlp.annotator import Tokenizer

tokenizer_ = Tokenizer()\
    .setInputCols(['sentences'])\
    .setOutputCol('tokens')

tokenizer.fit(sentences).transform(sentences).limit(5).toPandas()
`
