### ISSUE TITLE
last stage of pipeline taking too long

### ISSUE THREAD

**Issue by subhashiniy** [JohnSnowLabs/spark-nlp#896]
After loading about ~1GB data to sparkNLP, in the last part of the processing, the code doesn't move forward and also uses only one core. 

## Description
We are trying to load ~1GB data to the pipeline code attached below. After multiple tries, using .collect() and .toPandas() it gets stuck at the last stage. 
`[OK!]20/05/08 12:56:35 WARN TaskSetManager: Stage 12 contains a task of very large size (9810 KB). The maximum recommended task size is 100 KB.
20/05/08 12:56:37 WARN TaskSetManager: Stage 21 contains a task of very large size (6642 KB). The maximum recommended task size is 100 KB.
[Stage 21:===================================================>    (11 + 1) / 12]^C`
It does not move past this stage at all and only one core in the system. 

## Expected Behavior
The pipeline should end and produce results. 

## Current Behavior
It gets stuck and doesn't move past the stage. 

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version: 2.4.5
* Apache NLP version: 2.4.5 
* Java version (java -version): java  "1.8.0_252"
* Setup and installation (Pypi, Conda, Maven, etc.): python, pyspark
* Operating System and version: Ubuntu 18.04
* Link to your project (if any):

Code : 
`	sparkDF = spark.createDataFrame(data, StringType()).toDF("text")

    document_assembler = DocumentAssembler()\
        .setInputCol("text")\
        .setOutputCol("document")\
        .setCleanupMode("shrink_full")

    sentence_detector = SentenceDetector() \
        .setInputCols(["document"]) \
        .setOutputCol("sentence")

    tokenizer = Tokenizer() \
        .setInputCols(["sentence"]) \
        .setOutputCol("token") \

    stop_words_cleaner = StopWordsCleaner() \
                        .setInputCols(["token"]) \
                        .setOutputCol("cleanTokens") \
                        .setCaseSensitive(False) \
                        .setStopWords(customStopwords)

    normalizer = Normalizer() \
        .setInputCols(["cleanTokens"]) \
        .setOutputCol("normalized")

    pos_tagger = PerceptronModel().pretrained() \
        .setInputCols(["normalized", "sentence"]) \
        .setOutputCol("pos")

    chunker = Chunker() \
        .setInputCols(["sentence","pos"]) \
        .setOutputCol("pos_chunked") \
        .setRegexParsers(posRules)

    chunk2tok = Chunk2Doc()\
                    .setInputCols(["pos_chunked"]) \
                    .setOutputCol("tokens_chunk")

    tokenizer1 = Tokenizer() \
            .setInputCols(["tokens_chunk"]) \
            .setOutputCol("tokenizer1") 

    stop_words_cleaner_tok = StopWordsCleaner() \
                        .setInputCols(["tokenizer1"]) \
                        .setOutputCol("cleanStop") \
                        .setCaseSensitive(False) \
                        .setStopWords(customStopwords)

    stemmer = Stemmer() \
            .setInputCols(["cleanStop"]) \
            .setOutputCol("stem") 

    ngrams = NGramGenerator() \
                .setInputCols(["stem"]) \
                .setOutputCol("ngrams") \
                .setN(3) \
                .setEnableCumulative(True) \
                .setDelimiter("_")

    finisher = Finisher() \
        .setInputCols(["ngrams","pos_chunked","stem","cleanStop"]) \
        .setIncludeMetadata(True)
    
    pipeline = Pipeline(stages=[ 
        document_assembler,
        sentence_detector,
        tokenizer,
        stop_words_cleaner,
        normalizer,
        pos_tagger,
        chunker,
        chunk2tok,
        tokenizer1,
        stop_words_cleaner_tok,
        stemmer,
        ngrams,
        finisher
    ])

    model = pipeline.fit(sparkDF)
    savePath = modelSavePath  + version
    model.save(savePath)
    prediction = model.transform(sparkDF)
    finished_token_list = prediction.select(['finished_ngrams','finished_cleanStop'])
    nGramsData = []
    stopWordRemData = []
    collectedData = finished_token_list.collect() 
    for row in collectedData:
         nGramsData.append(row.finished_ngrams)
        stopWordRemData.append(row.finished_cleanStop)`

**Comment by maziyarpanahi** [comment]
Hi, 
Thanks for opening this issue, it's easier here than in the Slack. 

**Question 1:** I would like to know what is `data` which is being converted into DataFrame. Not just the size, how many rows, the average size of the documents, etc.

**Question 2:** I would like to know the size of your machine (I think this is not a cluster)? How do you start the SparkSession? (in there you assign memory to the driver - if it's sparknlp.start() then it's by default 16G)

Also, I would like you to do the experiment of taking out the .collect and other operations which are not related to Spark NLP out just for testing. Let's first break your pipeline into two pipelines.

```python
document_assembler = DocumentAssembler()\
    .setInputCol("text")\
    .setOutputCol("document")\
    .setCleanupMode("shrink_full")

sentence_detector = SentenceDetector() \
    .setInputCols(["document"]) \
    .setOutputCol("sentence")

tokenizer = Tokenizer() \
    .setInputCols(["sentence"]) \
    .setOutputCol("token") \

stop_words_cleaner = StopWordsCleaner() \
                    .setInputCols(["token"]) \
                    .setOutputCol("cleanTokens") \
                    .setCaseSensitive(False) \
                    .setStopWords(customStopwords)

normalizer = Normalizer() \
    .setInputCols(["cleanTokens"]) \
    .setOutputCol("normalized")

pos_tagger = PerceptronModel().pretrained() \
    .setInputCols(["normalized", "sentence"]) \
    .setOutputCol("pos")

chunker = Chunker() \
    .setInputCols(["sentence","pos"]) \
    .setOutputCol("pos_chunked") \
    .setRegexParsers(posRules)

preProcessingPipeline = Pipeline(stages=[ 
    document_assembler,
    sentence_detector,
    tokenizer,
    stop_words_cleaner,
    normalizer,
    pos_tagger,
    chunker
])

preProcessingPipelineDFF = preProcessingPipeline.fit(sparkDF).transform(sparkDF)

# let's save this on the disk
# It's like a checkpoint
# It helps to run the second pipeline as many times as possible
# But without keep re-calculating this first pipeline.
# When you save on disk, it guarantees it will calculate all the rows (Apache Spark is lazy, so it won't do anything unless there is an action like .show or .count or .save)

preProcessingPipelineDFF.write.parquet("/tmp/preProcessingPipelineDF.parquet")

# let's load it back because we need it in the second pipeline
offlineFirstPipelineDF = spark.read.parquet("/tmp/preProcessingPipelineDF.parquet")

```

**Question 3:** How long this takes. The saving part and loading it back from the disk. 

Now the Second experiment with the second pipeline:

```python

chunk2tok = Chunk2Doc()\
                .setInputCols(["pos_chunked"]) \
                .setOutputCol("tokens_chunk")

tokenizer1 = Tokenizer() \
        .setInputCols(["tokens_chunk"]) \
        .setOutputCol("tokenizer1") 

stop_words_cleaner_tok = StopWordsCleaner() \
                    .setInputCols(["tokenizer1"]) \
                    .setOutputCol("cleanStop") \
                    .setCaseSensitive(False) \
                    .setStopWords(customStopwords)

stemmer = Stemmer() \
        .setInputCols(["cleanStop"]) \
        .setOutputCol("stem") 

ngrams = NGramGenerator() \
            .setInputCols(["stem"]) \
            .setOutputCol("ngrams") \
            .setN(3) \
            .setEnableCumulative(True) \
            .setDelimiter("_")

finisher = Finisher() \
    .setInputCols(["ngrams","pos_chunked","stem","cleanStop"]) \
    .setIncludeMetadata(True)

pipeline = Pipeline(stages=[ 
    chunk2tok,
    tokenizer1,
    stop_words_cleaner_tok,
    stemmer,
    ngrams,
    finisher
])

# We use offlineFirstPipelineDF which comes from the disk
model = pipeline.fit(offlineFirstPipelineDF)
prediction = model.transform(offlineFirstPipelineDF)

# Let's save it on the disk to calculate all the rows
prediction.write.parquet("/tmp/final_prediction.parquet")
final_prediction = spark.read.parquet("/tmp/final_prediction.parquet")
```

**Question 4:** How long this takes? The saving part and loading it back from the disk. 

**Question 5:** How long it takes if you prefer your .collect, toPandas, etc. on `final_prediction` now?

With the answer to these questions I can have a better understanding since I don't have the `data` to do experiments myself.

**Comment by subhashiniy** [comment]
Hi Maziyar, 
    Here are the answers to your queries. Also the experiment's results are after removing the Chunker(). With the Chunker() as a part of the pipeline, it just would not end.  The first pipeline is stuck again at the last stage.
```
    chunker = Chunker() \
    .setInputCols(["sentence","pos"]) \
    .setOutputCol("pos_chunked") \
    .setRegexParsers(posRules)
```
After multiple experiments I am positive that the chunker causes the pipeline to freeze. Without this, it runs smoothly. 

Question 1: I would like to know what is data which is being converted into DataFrame. Not just the size, how many rows, the average size of the documents, etc.
    - The data has around 100K rows. It terminated with connection errors at 100k, so we fed a chunk of 10k rows when it froze at the last stage. The average size of docucemts of is about 9 KB, but the sizes are varying going as much as 5 MB to  1 KB. 

Question 2: I would like to know the size of your machine (I think this is not a cluster)? How do you start the SparkSession? (in there you assign memory to the driver - if it's sparknlp.start() then it's by default 16G)
    - It is not a cluster. It is a single instance with 110GB RAM and 12 cores
    spark = SparkSession.builder \
    .appName("Spark NLP")\
    .master("local[*]")\
    .config("spark.driver.memory","25G")\
    .config("spark.driver.maxResultSize", "4G") \
    .config("spark.kryoserializer.buffer.max", "1000M")\
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.4.5")\
    .getOrCreate()

Question 3: What is customStopwords? (how large, how big, etc.)
   - It is list of around 170 words. Ex - ['i', 'me', 'my', 'myself', 'we', 'our',....]. It is not that big
   - The number of "posRules" is around 50. Ex - ["<MD|PRP|PRP$|CC|DT|IN>*<PP>+", "<MD|PRP|PRP$|CC|DT|IN>*<VP>+"]

Question 4: Why is this True .setIncludeMetadata(True). Are you really using the metadata after? I see you only select the actual Array columns for Pandas. (cleaning helps to reduce the size of unnecessary stuff)
   -  No it isnt necessary right now. I will set it to False and re run it for experimenting.  


Question 5 & 6 : How long this takes? The saving part and loading it back from the disk.
  - This first half of the pipeline without the Chunker() takes 140 seconds and the second half takes 103 seconds on 10k documents . 

Question 7: How long it takes if you prefer your .collect, toPandas, etc. on final_prediction now?
   - 510 seconds.  
 
So, I think there is an issue with Chunker() alone. 
Thanks in advance!
