### ISSUE TITLE
Py4JJavaError: An error occurred at COLAB  while callingz:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader

### ISSUE THREAD

**Issue by msklc** [JohnSnowLabs/spark-nlp#916]
**
I run __1.SparkNLP_Basics.ipynb__ notebook on COLAB. But while running the 
`pipeline = PretrainedPipeline('explain_document_ml', lang='en')`;

 I got  this error:
**Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline.
: java.lang.IllegalArgumentException: Unsupported class file major version 55**

I run COLAB set-up code without any problem.

## Environment
Spark NLP version 2.5.1
Apache Spark version: 2.4.4
 
What do you think about this error on COLAB?

**Comment by maziyarpanahi** [comment]
I am not sure where is that notebook so I can take a look at it, but this error is about the JAVA version not being supported by Apache Spark. It has to be 8.

```
import os

# Install java
! apt-get install -y openjdk-8-jdk-headless -qq > /dev/null
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]
! java -version

# Install pyspark
! pip install --ignore-installed -q pyspark==2.4.4

# Install Spark NLP
! pip install --ignore-installed -q spark-nlp==2.5.1
```

**Comment by msklc** [comment]
It is your notebook at 
(https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/1.SparkNLP_Basics.ipynb).

I already shared the pyspark and spark-nlp version before:
**Spark NLP version 2.5.1
Apache Spark version: 2.4.4**

The Java version:
**openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)**

Thanks for fast reply

**Comment by msklc** [comment]
I updated the java. Now version:

**openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)**

**Comment by maziyarpanahi** [comment]
If you restart your kernel and follow the exact code in that notebook that has everything set at the beginning it should be fine.

**Comment by msklc** [comment]
Sorry but i didn't understand "follow the exact code"... I run your notebook on colab several times. But it gave this error: 
__Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline.
: java.lang.IllegalArgumentException: Unsupported class file major version 55__

The notebook also gives the same error in the local. But it is interesting, it is not working on colab. Do you have time try to run the your own notebook (https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/1.SparkNLP_Basics.ipynb) on colab?

Problem not solved...

**Comment by maziyarpanahi** [comment]
Sorry, those notebooks have been updated with some sort of script to prepare the Colab with Java, I wasn’t aware of that.
The usual way of preparing the Colab can be fouund in the first cell of this notebook:

https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/training/english/classification/SentimentDL_train_multiclass_sentiment_classifier.ipynb

I will let the person who made those notebooks to know the error that comes from the script. But the notebook I shared, the first cell is all you need to setup everything before sparknlp.start()

Please let me know if everything works well

**Comment by msklc** [comment]
Thanks for your interest,

Yes, the problem was solved with the first cell of your notebook.
Thanks too much, 
Kind regards

```import os
# Install java
! apt-get install -y openjdk-8-jdk-headless -qq > /dev/null
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]
! java -version

# Install pyspark
! pip install --ignore-installed -q pyspark==2.4.4

# Install Spark NLP
! pip install --ignore-installed -q spark-nlp==2.5.1

**Comment by vkocaman** [comment]
Ok I updated all the notebooks.. looks like installing jdk 1.8 through local script is not working all the time. So I fell back to our original setup commands.
