### ISSUE TITLE
java.lang.NumberFormatException BigDecimal in NerDLApproach regarding includeConfidence

### ISSUE THREAD

**Issue by dukegris** [JohnSnowLabs/spark-nlp#917]
Error in ner train with Bert 

### Description
When i train with NerDLApproach using bert_large_uncased_en_2.4.0_2.4_1580581306683, using Spark-NLP 2.5.1 with Conll2003 Corpus, after 10 epoch the library throw an exception when include confidence is true

### Current Behavior
https://github.com/JohnSnowLabs/spark-nlp/blob/c8ad852c288e73869cdef06dd4f43a142723d4a2/src/main/scala/com/johnsnowlabs/ml/tensorflow/TensorflowNer.scala#L89

java.lang.NumberFormatException
  at java.math.BigDecimal.<init>(BigDecimal.java:497)
  at java.math.BigDecimal.<init>(BigDecimal.java:827)
  at scala.math.BigDecimal$.decimal(BigDecimal.scala:52)
  at scala.math.BigDecimal$.apply(BigDecimal.scala:249)
  at com.johnsnowlabs.ml.tensorflow.TensorflowNer$$anonfun$predict$2$$anonfun$6.apply(TensorflowNer.scala:89)

### Possible Solution
Ensure the division

**Comment by maziyarpanahi** [comment]
Hi @dukegris 

Thanks for reporting this, I think the `setIncludeConfidence` is set to `true` and this line comes from that param. Meanwhile, you can turn that to false until next release when we fix this.

Thanks again!

**Comment by dukegris** [comment]
Thx

**Comment by maziyarpanahi** [comment]
This issue was fixed in 2.5.2 release. Please feel free to reopen it if the issue still exists.
