### ISSUE TITLE
Typo, python code not showing up, and link to eval folder wrong

### ISSUE THREAD

**Issue by erotavlas** [JohnSnowLabs/spark-nlp#922]
**Link to doc page in question (if any):**

https://nlp.johnsnowlabs.com/docs/en/evaluation#evaluating-ner-dl

**Name of the Spark NLP feature whose docs need improvement:**

Licensed Content > Evaluation

**What you think the docs should say:**

![image](https://user-images.githubusercontent.com/10454265/83889090-b7078b00-a718-11ea-90e4-6c90422ee477.png)

First paragraph last sentence typo on the word 'with'

Code samples for python are blank

![image](https://user-images.githubusercontent.com/10454265/83889289-f7ff9f80-a718-11ea-85e8-3961f47f07a2.png)

Browsers tested - Microsoft Edge and Firefox

Also link to eval folder is pointing here
![image](https://user-images.githubusercontent.com/10454265/83890998-8a547300-a71a-11ea-9b4f-0194177f0f0f.png)

https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/jupyter

But there is no eval folder at this location.

**Comment by maziyarpanahi** [comment]
This issue was fixed in 2.5.2 release. Please feel free to reopen it if the issue still exists.
