### ISSUE TITLE
How to run SparkNLP across multiple GPUs

### ISSUE THREAD

**Issue by Bassie1** [JohnSnowLabs/spark-nlp#9266]
I am running a pyspark Logistic Regression model on a virtual machine with Ampere 6000 GPU x2. I am using SparkNLP to process text data. 
Here is the spark config to start the Spark Session, in a python script called mf:
```
def start(gpu=False, spark23=False):
    current_version="3.4.4"
    maven_spark24 = "com.johnsnowlabs.nlp:spark-nlp_2.11:{}".format(current_version)
    maven_gpu_spark24 = "com.johnsnowlabs.nlp:spark-nlp-gpu_2.11:{}".format(current_version)
    maven_spark23 = "com.johnsnowlabs.nlp:spark-nlp-spark23_2.11:{}".format(current_version)
    maven_gpu_spark23 = "com.johnsnowlabs.nlp:spark-nlp-gpu-spark23_2.11:{}".format(current_version)
    builder = SparkSession.builder \
    .appName("sparknlp") \
        .config("spark.jars.packages","com.johnsnowlabs.nlp:spark-nlp_2.12:3.4.0")\
        .config("spark.pyspark.python","python3") \
        .config('spark.driver.memory','64G') \
        .config("spark.executor.memory", "32g") \
        .config('spark.memory.offHeap.enabled', True) \
        .config('spark.memory.offHeap.size', '12g')\
        .config('spark.ui.showConsoleProgress', True) \
        .config('spark.dynamicAllocation.enabled', True)\
        .config('spark.python.worker.memory', "32g")\
        .config('spark.rapids.sql.enabled', True)
    if gpu and spark23:
        builder.config("spark.jars.packages", maven_gpu_spark23)
    elif spark23:
        builder.config("spark.jars.packages", maven_spark23)
    elif gpu:
        builder.config("spark.jars.packages", maven_gpu_spark24)
    else:
        builder.config("spark.jars.packages", maven_spark24)
    return builder.getOrCreate()
```
I call this function in another notebook

```
from numba import cuda
import findspark
findspark.init('spark-3.1.3-bin-hadoop3.2')

import pyspark
from pyspark.sql import SparkSession

cuda.select_device(1)
spark= mf.start(gpu= True)
```

It seems that I am using 1 GPU. Here is the output of nvidia-smi:
-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:00:05.0 Off |                  Off |
| 30%   33C    P8    26W / 300W |    259MiB / 48685MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000    On   | 00000000:00:06.0 Off |                  Off |
| 30%   31C    P8    28W / 300W |    265MiB / 48685MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1463      G   /usr/lib/xorg/Xorg                127MiB |
|    0   N/A  N/A      1926      G   /usr/bin/gnome-shell               49MiB |
|    0   N/A  N/A      2223      G   ...bexec/gnome-initial-setup       77MiB |
|    1   N/A  N/A      1463      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A      3192      C   /bin/python3                      257MiB |
+-----------------------------------------------------------------------------+

Is there a way to utilize both GPUs, or more if I would use a machine with x4 or x6 GPUs?

**Comment by maziyarpanahi** [comment]
Hi,

- training in Spark NLP happens inside Driver and only on 1 GPU
- prediction/inference also uses 1 GPU device, however, if you are in a cluster mode (multiple executors) then each machine can have 1 GPU device and that way you can distribute and parallelize the computation over multiple GPU

Currently, due to TensorFlow limitations especially available APIs in Java only 1 GPU per machine is possible
