### ISSUE TITLE
Unable to retrieve storage under Embeddings in pretrained pipelines within Kubernetes environment

### ISSUE THREAD

**Issue by kvanlieshout** [JohnSnowLabs/spark-nlp#937]
## Description

I am a configured K8's cluster where we are mounting volumes and not using the tmp directory. I upload my recognize_entities model into these volumes which are mounted into the executors. This is the best path for us to be configured. I can run the model and its recognized by my executors but when I try to run .show(), .collect(), etc, it cannot find the storage for the embeddings that were indexed after a .transform on text data with the pipeline. 

My question is how can I override this storage setting for the embedding component to this pipeline? Should I be configuring the application.conf file in order to redirect this embedding storage to a path where my volumes are. For instance, we mount volumes in a directory called  /spark_nlp/tmp and this is where my model is, so how can I override the application.conf in order to have the embedding storage look to this file, rather than the /tmp/ directory where I am sure its defaulted to. This is in a Kubernetes setting. 

This is how we are setting up our config. 

conf = SparkConf()
...
conf.set('spark.files','file:///spark_nlp/tmp/application.conf')
conf.set('spark.driver.extraJavaOptions','-Dconfig.file=file:///spark_nlp/tmp/application.conf')
conf.set('spark.executor.extraJavaOptions','-Dconfig.file=file:///spark_nlp/tmp/application.conf')

application.conf setup is 

sparknlp {

  settings {

    overrideConfigPath = "./application.conf"
    annotatorSerializationFormat = "object"
    useBroadcastForFeatures = true

    storage {
      cluster_tmp_dir = "/spark_nlp/tmp/"
    }

    pretrained {
      s3_bucket = "auxdata.johnsnowlabs.com"
      s3_path = ""
      s3_socket_timeout = 3600000
      // Override as required. Defaults to home/cache_pretrained folder.
      // cache_folder = "/home/robert/models"
      credentials {}
    }

    annotator {
      // log_folder = "/home/robert/logs"
    }
  }
}

I changed the cluster_tmp_dir directory since I thought this was the cluster embedding place to change a directory of where embeddings will be indexed to. But im not sure if this is how it should be done. I was following https://github.com/JohnSnowLabs/spark-nlp/issues/723 to set up the config and application.conf file. Just not sure if its different on a S3 basis vs Kubernetes. 

Further down the code base I call:

        pipeline = PipelineModel.load("/spark_nlp/tmp/recognize_entities_dl_en_2.4.3_2.4_1584626752821/")
        results = pipeline.transform(df)
        entities = results.select("entities.result")

And this results in my storage error 

## Expected Behavior

Hope to successfully run the transform and be able to collect results after a transform to extract entities. 

## Current Behavior

Caused by: java.lang.IllegalArgumentException: requirement failed: Storage not found under given ref: EMBEDDINGS_glove_100d
 This usually means:
1. You have not loaded any storage under such ref or one of your Storage based annotators has `includeStorage` set to false and must be loaded manually
2. You are trying to use cluster mode without a proper shared filesystem.
3. source was not provided to Storage creation
4. If you are trying to utilize Storage defined elsewhere, make sure it has the appropriate ref.

## Possible Solution

Find a way to redirect the storage path for the word embeddings component to my pipeline. 

## Steps to Reproduce

1. Mount the model with the volumes and see if its possible to redirect the storage of the embedding part of the pipeline to this same place so it can be retrieved when a .show() or a .collect() is called on the entity extraction. Reproduce in a kubernetes setting. THANKS!!
2.
3.
4.

## Context

Getting Spark NLP running in our K8's environment 

## Your Environment

* Spark NLP version: 2.4.5
* Apache NLP version:
* Java version (java -version): 1.8
* Setup and installation (Pypi, Conda, Maven, etc.):
* Operating System and version: Centos
* Link to your project (if any):

**Comment by kozlovit** [comment]
Hi @kvanlieshout, were you able to resolve the issue? I'm facing the same problem in the Kubernetes environment and can't seem to find a solution.

**Comment by ShindeAkshay** [comment]
@kvanlieshout @kozlovit Do you guys find the solution for above problem, I am also facing the similar issue.

**Comment by maziyarpanahi** [comment]
This issue is related to Apache Spark in a cluster mode (or a setup that Driver and Executor are not in a single machine) and not having a distributed file system available or correctly configured for it.

All the machines/executors must have knowledge of HDFS and have access to a single path on HDFS. If your Apache Spark / YARN is correctly configured to discover HDFS and all the nodes have access to it, this won't be an issue. 

Unfortunately, there is no way around this unless you use other annotators providing embeddings as WordEmbeddings must be able to extra its indexes on a path that all machines have access to which by default on all the clusters is HDFS or DBFS: Databricsk, EMR, Glue, Cloudera, Hortonworks, etc. Almost all the clusters work except those who just launch K8 clusters without HDFS which is very common by just relying on isolated Docker volumes.
