### ISSUE TITLE
Apache Spark 3.x support

### ISSUE THREAD

**Issue by maziyarpanahi** [JohnSnowLabs/spark-nlp#940]
Apache Spark 3.0 is finally released. It is important to investigate how we best can support Apache Spark 2.3.x, Apache Spark 2.4.x, and Apache Spark 3.x at the same time as most distributors like Cloudera, Hortonworks, etc. won’t be moving to 3.x anytime soon.

- [x] Before making this possible we need to first make the library compatible with Scala 2.12: https://github.com/JohnSnowLabs/spark-nlp/issues/308
NOTE: All tests have passed for Scala 2.12 in Apache Spark 2.4.x, only pretrained models/pipelines failed: https://github.com/JohnSnowLabs/spark-nlp/pull/2129

~~Which models/pipelines are compatible with Scala 2.12 so we can use the same model/pipeline hopefully regardless of _2.11 or _2.12 in our package~~

~~Which models/pipelines are compatible in Apache Spark 3x. Maintaining over 160 models/pipelines for two different versions will be very hard so we have to have a grace period before moving to 3.x and then discontinuing 2.4.x support. (If models/pipelines are not compatible in 3.x otherwise we just need to find a way to fix metadata.json since it relies on the Apache Spark version to download. We have to make that field multiple versions like 2,4,3.0~~

UPDATE:

~~* It seems we need to train/upload/maintain all 330+ models/pipelines for Apache Spark 3.x/Scala 2.12. For now, I haven't found any way to fix this so the other points will be resolved when we pull the trigger on maintaining over 600+ pretrained models/pipelines for Apache Spark 2.3.x, 2.4.x, and 3.x.~~

This will be an ongoing discussion as we fo forward.

LAST UPDATE: 
* it seems we only have problems with POS models that were compiled and trained on Scala 2.11 and not compatible with Scala 2.12. We will re-train all of them for the Spark NLP that supports Spark 3.0.1
* Most of the work is done but, we have to start testing in many environments yet
* We will start our RC releases from mid-March
* We are aiming to have a final candidate by the end of March/start of April

**Comment by iiLaurens** [comment]
What is the status of this? There is no Databricks 6.x runtime with LTS so we can expect these runtimes to be unavailable relatively soon.

**Comment by maziyarpanahi** [comment]
@iiLaurens 
We are still working on it and hopefully have support for Spark 3.x at the end of Q1 in 2021. However, I highly doubt Databricks deprecates 2.4.x support in their runtimes as it's the most used in both Databricks and the entire enterprise. They already extended this to April 2021 and I am guessing they will do it again: https://docs.databricks.com/release-notes/runtime/releases.html#extended-release

In any case, we are working on it since the only issue right now is our pretrained models saved in Spark 2.4.x cannot be loaded in Spark 3.x. We solve that issue we can start releasing for Spark 3.x, if cannot do that then we start with a handful of models/pipelines but eventually, we need to support over 600 models in 2.4 and 3.x since 99% of the users in the enterprise are still in 2.3.x or 2.4.x.

**Comment by AadhiKat** [comment]
Hi, Is there any way that I can train the model myself? I am using ViveknSentimentModel and I am not able to upgrade my version of spark to 3.0 due to this. Any docs on this ?

**Comment by maziyarpanahi** [comment]
All the notebooks are listed here: https://github.com/JohnSnowLabs/spark-nlp-workshop

Especially this directory for certification: https://github.com/JohnSnowLabs/spark-nlp-workshop/tree/master/tutorials

You can search for `ViveknSentimentModel` but also you can look for `SentimentDL` or `ClassifierDL` which allow you to train a multi-class sentiment detector by using deep learning.

**Comment by icassina** [comment]
It would be indeed be great to have all the necessary information to re-train all the existing pre-trained models. Even more so if in the form of scripts ;)

In particular I'm really interested in re-train the `pos_anc` (and all the other localized POS **PerceptronMode**l models), the **NerCrfModel**s and the **WordEmbeddings**.

Some pre-trained models look like they have been trained from the `Universal Dependencies` datasets, but I'm not 100% exactly how. I have found no information about what dataset was used to train `pos_anc`.

Any help is appreciated!

**Comment by maziyarpanahi** [comment]
The repository I mentioned earlier has over 100s of notebooks to demonstrate the use and training the trainable models. 
There is not a single annotator that can be trained and doesn't have a notebook to show how. 
Please do a search in spark-nlp-workshop repository, you will find at least 1 notebook.
If there is a trainable annotator without an example (we might have missed) please open a new issue in that repository and we will add them.

**Comment by JJorczik** [comment]
> @iiLaurens
> We are still working on it and hopefully have support for Spark 3.x at the end of Q1 in 2021. However, I highly doubt Databricks deprecates 2.4.x support in their runtimes as it's the most used in both Databricks and the entire enterprise. They already extended this to April 2021 and I am guessing they will do it again: https://docs.databricks.com/release-notes/runtime/releases.html#extended-release
> 
> In any case, we are working on it since the only issue right now is our pretrained models saved in Spark 2.4.x cannot be loaded in Spark 3.x. We solve that issue we can start releasing for Spark 3.x, if cannot do that then we start with a handful of models/pipelines but eventually, we need to support over 600 models in 2.4 and 3.x since 99% of the users in the enterprise are still in 2.3.x or 2.4.x.

Is there any status update for Spark 3.x support at the end of Q1 in 2021? Thanks in advance.

**Comment by maziyarpanahi** [comment]
Hi @JJorczik 

Yes, we will start in 3-4 weeks to release a series of RCs until we do a final release by the end of Q1. Most of the work is done.

**Comment by dzlab** [comment]
@maziyarpanahi is there a jira ticket or a github branch to track this effort (getting spark-nlp on spark 3)?

**Comment by maziyarpanahi** [comment]
Yes, there is a pull request open for our first RC1 release on 12th of March. (Starts with 300-release-candidate)

**Comment by maziyarpanahi** [comment]
We have just made a public pre-release for Spark NLP `3.0.0-rc8`:
https://github.com/JohnSnowLabs/spark-nlp/releases/tag/3.0.0-rc8

**Comment by maziyarpanahi** [comment]
Let's close this as Spark NLP 3.x supports Spark 3.x.
