### ISSUE TITLE
DeepSentenceDetector load giving cast error when loading ner_dl_sentence model

### ISSUE THREAD

**Issue by danielpaparo98** [JohnSnowLabs/spark-nlp#943]
## Description
I am attempting to use the DeepSentenceDetector annotator with the model from [ner_dl_sentence](https://github.com/JohnSnowLabs/spark-nlp-models).The `.load(path)` method is giving me a cast error at runtime (cannot cast between NERdlmodel and DeepSentenceDetector).

## Expected Behavior
`DeepSentenceDetector.load(path)` should work in the same way as the other annotators having a premade model loaded into them. At the moment my PerceptronModel, NERDLModel, and BertEmbeddings annotators are working as expected using the same `.load(path)` method.

## Current Behavior
The following runtime error is given when trying to execute the pipeline:
```
Exception in thread "main" java.lang.ClassCastException: com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel cannot be cast to com.johnsnowlabs.nlp.annotators.sbd.deep.DeepSentenceDetector
```

## Possible Solution
I think this could be a problem with the model itself. I have downloaded it a couple of times from the official spark-nlp-models repo, but with no success. I went into the `/metadata/part-00000` file and found that it contains:
```
{"class":"com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel","timestamp":1556666842350,"sparkVersion":"2.4.0","uid":"NerDLModel_823e4d627783","paramMap":{"inputCols":["sentence","token","embeddings"],"batchSize":4,"outputCol":"ner"},"defaultParamMap":{"batchSize":8}}
```
I changed this to the `com.johnsnowlabs.nlp.annotators.ner.dl.NerDLModel` class and the pipeline stopped giving me the runtime error. However, the results of the sentence splitting came out different to what was expected (it didnt seem that they were split as sentences).

## Steps to Reproduce
1. Create a pipeline similar to that found here [here.](https://github.com/JohnSnowLabs/spark-nlp/blob/38328a64884b822044abef7c5150fd17d6b276bd/src/test/scala/com/johnsnowlabs/nlp/annotators/sbd/deep/DeepSentenceDetectorTestSpec.scala)
2. Use the  [ner_dl_sentence](https://github.com/JohnSnowLabs/spark-nlp-models) model.
3. Adding the deep sentence detector using:

```
  val deepSentenceDetector = DeepSentenceDetector.load(path_to_ner_dl_sentence)
    .setInputCols(Array("document", "token", "ner_con"))
    .setOutputCol("seg_sentence")
    .setIncludePragmaticSegmenter(true)
    .setEndPunctuation(Array(".", "?"))
```
4. Error occurs at runtime.

## Context
I am trying to test out the DeepSentenceDetector to see if I should use it in my pipeline. At this point I am unable to do so due to the runtime error.

## Your Environment
* Spark NLP version: 2.5.2
* Apache Spark version: 2.2.0
* Java version (java -version): 1.8.0
* Scala version: 2.11
* Setup and installation (Pypi, Conda, Maven, etc.): Maven, hadoop 2.6.0
* Operating System and version: Ubuntu 18.04
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
We have deprecated this annotator and its models in favor of the much faster and more accurate annotator/models `SentenceDetectorDL`. The annotator is also trainable.

https://nlp.johnsnowlabs.com/models?tag=sentence_detection
