### ISSUE TITLE
How do I select classifierdl_use_trec50 for classifierDLApproach?

### ISSUE THREAD

**Issue by ndolev** [JohnSnowLabs/spark-nlp#944]
```
classsifierdl = ClassifierDLApproach()\
  .setInputCols(["sentence_embeddings"])\
  .setOutputCol("class")\
  .setLabelColumn("label")\
  .setMaxEpochs(5) #classifierdl_use_trec50
```

**Comment by maziyarpanahi** [comment]
`classifierdl_use_trec50` is a pretrained model which can be used by `ClassifierDLModel`:

```python
document = DocumentAssembler()\
    .setInputCol("description")\
    .setOutputCol("document")

use = UniversalSentenceEncoder.pretrained() \
 .setInputCols(["document"])\
 .setOutputCol("sentence_embeddings")

classsifierdl = ClassifierDLModel.pretrained("classifierdl_use_trec50") \
  .setInputCols(["sentence_embeddings"])\
  .setOutputCol("class")

pipeline = Pipeline(
    stages = [
        document,
        use,
        classsifierdl
    ])
```

`ClassifierDLApproach` is for training a new `ClassifierDLModel`. In Spark NLP any annotator with Approach is for training, any annotator with Model is for predicting.

Reference: https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/jupyter/training/english/classification/ClassifierDL_Train_multi_class_news_category_classifier.ipynb

**Comment by ndolev** [comment]
Thanks for the quick explanation! 

Can I do transfer learning using DLApproach? E.g., load classifierdl_use_trec50 and continue training?

**Comment by maziyarpanahi** [comment]
Unfortunately, our models in pure Spark NLP and TensorFlow doesn't accept transfer learning but the ones with embeddings require much fewer data for training as Embeddings itself adds transfer learning.
