### ISSUE TITLE
Use DLApproach for Multi-Label Classification

### ISSUE THREAD

**Issue by ndolev** [JohnSnowLabs/spark-nlp#945]
Is this currently possible in some way?

**Comment by maziyarpanahi** [comment]
`ClassifierDL` only supports multi-class up to 100 classes. The multi-label multi-class classifier is under development currently and hasn't released yet.

**Comment by maziyarpanahi** [comment]
`MultiClassifierDL` also supports multi-label datasets where the text has more than 1 label assigned to it.
