### ISSUE TITLE
RegexMatcher doesn't work in python/pyspark

### ISSUE THREAD

**Issue by YashSinha1996** [JohnSnowLabs/spark-nlp#948]
## Description
As given at [in the docs](https://nlp.johnsnowlabs.com/docs/en/annotators#regexmatcher) `RegexMatcher` seems to support python. However, I can't get it to work as it says that there is no attribute like `setRulesPath`
## Expected Behavior
For this
```
regex_matcher = RegexMatcher() \
    .setStrategy("MATCH_ALL") \
    .setRulesPath('rules.txt', ',') \
    .setOutputCol("regex") \
    .setInputCols(["document"])
```
to work and read rules given in rules.txt

In rules.txt, copy and pasted from the documentation
```
the\\s\\w+,"followed by ‘the’"
```

## Current Behavior
```
regex_matcher = RegexMatcher() \
    .setStrategy("MATCH_ALL") \
    .setRulesPath('rules.txt', ',') \
    .setOutputCol("regex") \
    .setInputCols(["document"])
```
Gives
```
AttributeError                            Traceback (most recent call last)
<ipython-input-35-ef77aee064cc> in <module>
     12 
     13 regex_matcher = RegexMatcher() \
---> 14     .setStrategy("MATCH_ALL") \
     15     .setRulesPath('rules.txt', ',') \
     16     .setOutputCol("regex") \

AttributeError: 'RegexMatcher' object has no attribute 'setRulesPath'
```

## Steps to Reproduce
Run the above snippets in python with spark-nlp

## Context
Trying to see the results from regex extraction from spark-nlp

## Your Environment
* Spark NLP version: 2.4.5
* Apache NLP version: Don't think I have this
* Java version (java -version): 1.8.0_252
* Setup and installation (Pypi, Conda, Maven, etc.): pip install
* Operating System and version: Gcloud Dataproc, ubuntu-1

**Comment by YashSinha1996** [comment]
As defined in the scala [documentation](https://nlp.johnsnowlabs.com/api/index#com.johnsnowlabs.nlp.annotators.RegexMatcher) I tried `setRules` to work.

**Comment by maziyarpanahi** [comment]
It should be working correctly, but I only know the latest release which is 2.5.x: 

```
regex_matcher = RegexMatcher()\
    .setInputCols('document')\
    .setStrategy("MATCH_ALL")\
    .setOutputCol("regex_matches")\
    .setExternalRules(path='./regex_rules.txt', delimiter=',')
```

Reference: https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/2.Text_Preprocessing_with_SparkNLP_Annotators_Transformers.ipynb
