### ISSUE TITLE
Available jars on Maven Central do not include Python API

### ISSUE THREAD

**Issue by sofianeh** [JohnSnowLabs/spark-nlp#95]
I've noticed the the jars [here](https://search.maven.org/#artifactdetails%7Ccom.johnsnowlabs.nlp%7Cspark-nlp_2.11%7C1.3.0%7Cjar) are missing python the api. Is this on purpose?

**Comment by saifjsl** [comment]
Hi @sofianeh Thank you for the feedback! 

The jar won't include python API. Python API for pyspark is meant to be used throughout --packages in Spark-Packages which will download it for you and include it in any spark session. https://spark-packages.org/package/JohnSnowLabs/spark-nlp

Nonetheless, will be working on adding spark-nlp as a python PIP module.

Please close if this answers your comment
Best

**Comment by sofianeh** [comment]
Installing from Maven Central adds also many dependencies artifacts, which is not the case when you install the pyhton jar alone (might be the reason for this error in [Issue 85](https://github.com/JohnSnowLabs/spark-nlp/issues/85)

**Comment by sofianeh** [comment]
Installing yhe library from Maven on Databricks adds all the following artifacts, are those required when using the Python API?
![image](https://user-images.githubusercontent.com/271142/36650016-eb344690-1a6e-11e8-9981-c28185f0b2a7.png)

**Comment by showy** [comment]
Dependencies are actually required.

**Comment by showy** [comment]
As @saifjsl commented, the python API is only planned to be supported using the spark-packages package. Closing this issue.
