### ISSUE TITLE
Problems with various getters and setters in the Python Spark NLP API

### ISSUE THREAD

**Issue by C-K-Loan** [JohnSnowLabs/spark-nlp#952]
The following Spark NLP annotators have buggy behavior when getting and setting certain parameters.

## Steps to Reproduce

1. Open terminal and Python shell
2. Copy Paste the following imports  into your python shell
```
import sparknlp
from sparknlp.pretrained import PretrainedPipeline
from sparknlp.annotator import *
from sparknlp.base import *
```
3.  Create Document Assembler,  getting parameter throws error 
```
spark = sparknlp.start()
document_assembler = DocumentAssembler()
sentence_detector.getInputCols()   # crash
sentence_detector.getOutputCols()    # crash
sentence_detector.getSplitLength() # returns nothing, intended behaviour?
```

4. After using setter method to set input and output columns, the getter returns None
```
sentence_detector = SentenceDetector() \
    .setInputCols(["document"]) \
    .setOutputCol("sentence")
sentence_detector.getInputCols()   #  now returns None
sentence_detector.getOutputCols()    # now returns None  

```
5. The exact same behavior on the getters/setters for InputCols and OutputCols can be seen for the following Annotators and can be reproduced in exactly the same way as demonstrated with the sentence detector : 
- tokenizer, NorvigSweetingApproach, SPellChecker,  ContextSpellChecker, dependencyParser, Typed Dependency Parser, Sentiment Detector, ViveknSentimentDetector, POSTagger, DeepSentenceDetector, SentenceDetector, DateMatcher, NGramGenerator, Chunker, Textmatcher, RegexMatcher, StopWOrdCleaner, Lemmatizer, Stemmer, Normalizer, Tokenizer

6. Alternative buggy behavior: 
- Some annotators don't crash when getting their parameter, but they still return None after setting them.
- elmo : When getting the parameter and it has not been set before it returns None. After setting parameters and getting them None is still being returned
```

elmo = ElmoEmbeddings.pretrained() 
print(elmo.getInputCols())
print(elmo.getOutputCol())
elmo.setInputCols(["token", "document"]).setOutputCol("elmo") 
print(elmo.getInputCols())
print(elmo.getOutputCol())

``` 
   - exactly the same behavior as demonstrated with elmo has been tested and reproduced  with Xlnet, Bert, Albert, UniversalSentenceEncoder, SentenceEmbeddings, chunkEmbeddings, ClassifierDL, SentimentDL, language detector 

# Third alternation behavior alternations : 
- NER CRF Tagger returns None when getting InputCol. Ner CRF Tagger crashed when getting OutputCol.
- NER DL crashes for both, Input and Output Col when getting and returns None even after setting.
I tested every annotator 

## Annotators unaffected by this bug : 
- DocumentAssembler, 
- Not tested on pretrained pipes

## Your Environment

* Spark NLP version: tested on 2.5.1 and 2.5.2
* Java version (java -version): openjdk version "1.8.0_252"
* Setup and installation (Pypi, Conda, Maven, etc.): via pip. Also tested on Databricks
* Operating System and version: Manjaro Linux

**Comment by maziyarpanahi** [comment]
Thanks @C-K-Loan 
I am going to start debugging this. Some annotators are missing the `default` for inputCols and OutputCol. Also, I would like to see what is missing which even after setting them it gets back None or crashes.

**Comment by maziyarpanahi** [comment]
The first issue with not having something set and crashing is because there is no default values. In case for inputCols and OutputCol we should add these to the default of all annotations:

```
setDefault(
    inputCols -> Array("document"),
    outputCol -> "sentence"
  )
```
There are other parameters which won't be having defaults and may crash in case of `.get` which wee should also fix.

However, the second issue of returning None even when it's set, I think the issue might be here:

https://github.com/JohnSnowLabs/spark-nlp/blob/4d53a705e3f09e05f744cf98cee83ea33ff5ce34/python/sparknlp/common.py#L9

I'll try to add default values for input/output to annotators and dig deeper for the None issue.

**Comment by C-K-Loan** [comment]
Found a workaround that makes getting the inputCols and OutputCols for Annotators possible.

The parameters still exist and are properly as on the spark Parameter map.
```python
>>> for k in m.extractParamMap().keys() : k
... 
Param(parent='SentenceDetector_eb6b9af1e6de', name='lazyAnnotator', doc='Whether this AnnotatorModel acts as lazy in RecursivePipelines')
Param(parent='SentenceDetector_eb6b9af1e6de', name='useAbbreviations', doc='whether to apply abbreviations at sentence detection')
Param(parent='SentenceDetector_eb6b9af1e6de', name='detectLists', doc='whether detect lists during sentence detection')
Param(parent='SentenceDetector_eb6b9af1e6de', name='useCustomBoundsOnly', doc='Only utilize custom bounds in sentence detection')
Param(parent='SentenceDetector_eb6b9af1e6de', name='customBounds', doc='characters used to explicitly mark sentence bounds')
Param(parent='SentenceDetector_eb6b9af1e6de', name='explodeSentences', doc='whether to explode each sentence into a different row, for better parallelization. Defaults to false.')
Param(parent='SentenceDetector_eb6b9af1e6de', name='minLength', doc='Set the minimum allowed length for each sentence.')
Param(parent='SentenceDetector_eb6b9af1e6de', name='maxLength', doc='Set the maximum allowed length for each sentence')
Param(parent='SentenceDetector_eb6b9af1e6de', name='inputCols', doc='previous annotations columns, if renamed')
Param(parent='SentenceDetector_eb6b9af1e6de', name='outputCol', doc='output annotation column. can be left default.')
>>> 
```

Thus we can extract any parameters by using the parameter map and its keys. 
Usually, the input/output column keys are last and 2nd last but have to confirm that the case for all models. 
Otherwise getting the right key is not a big problem.

```python
m = SentenceDetector().setInputCols(["some_input",'some_other_input']).setOutputCol("the_output")
k_output =  list(m.extractParamMap().keys())[-2]
k_input =  list(m.extractParamMap().keys())[-1]
print(m.extractParamMap()[k_output])
print(m.extractParamMap()[k_input])
```


Did not test this thoroughly with all Annotators yet. 
Will do very soon when running tests with NLU and report back
