### ISSUE TITLE
Support Apache Spark 2.3.x

### ISSUE THREAD

**Issue by maziyarpanahi** [JohnSnowLabs/spark-nlp#955]
We have many users stuck in Hortonworks and can't/won't move to Apache Spark 2.4.x releases. Since the latest releases of Spark NLP 2.5.x are compatible with Apache Spark 2.3.x, we need to make some adjustment to make these releases compatible with Apache Spark 2.3.x as well as Apache Spark 2.4.x:

* New JAR names for Apache Spark 2.3.x:
  * `spark-nlp-spark23` for CPU and `spark-nlp-gpu-spark23` for GPU
  * These two new JARs/artifacts will be published on Maven alongside the others
* We need to allow users with Apache Spark 2.3.x to use `.pretrained()` so some changes have to be made in ResourceDownloader / metadata.json
* Both `SparkNLP.start()` and `sparknlp.start()` should now accept a param `isSpark23` so it will start SparkSession with the right Apache Spark version.

PS: The PR will be opened soon.

**Comment by rohit-nlp** [comment]
> Both SparkNLP.start() and sparknlp.start() should now accept a param isSpark23 so it will start SparkSession with the right Apache Spark version.
@maziyarpanahi 

Don't understand this? when we start spark session the spark version is automatically set based on what spark is used and we read the same version. Why do we want to send a param isSpark23 while starting spark session?

**Comment by maziyarpanahi** [comment]
In order to support Apache Spark 2.3.x we need to publish two new JARs/Artifacts on Maven. Which they will be named:

* `spark-nlp-spark23` for CPU
* `spark-nlp-gpu-spark23` for GPU

These will become coordinates such as `com.johnsnowlabs.nlp:spark-nlp-spark23_2.11:2.5.2`. Now in `start()` function we have this line:

```
      build.config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.5.2")
```

Since we don't have any SparkSession at this point, we cannot use `spark.version` to decide what Apache Spark the user is using. So the user has to pass a param to let the function know that he/she installed `pip install pyspark==2.3.4` and we need to instead use the following for Apache Spark 2.3.x:
```
      build.config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp-spark23_2.11:2.5.2")
```

Anywhere else after this point, since there is a SparkSession we can rely on `spark.version` and decide what we need to do. But in `start()` function there is no SparkSession and we cannot add anything afterward so we have to rely on the user's input whether they want `gpu` and `spark23`.

Current start function:

```
 val currentVersion = "2.5.2"

  def start(gpu:Boolean = false): SparkSession = {
    val build = SparkSession.builder()
      .appName("Spark NLP")
      .master("local[*]")
      .config("spark.driver.memory", "16G")
      .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
      .config("spark.kryoserializer.buffer.max", "1000M")
      .config("spark.driver.maxResultSize", "0")
    
    if(gpu){
      build.config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp-gpu_2.11:2.5.2")
    }
    else
      build.config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.11:2.5.2")

    build.getOrCreate()
  }

  def version(): String = {
    currentVersion
  }
```
