### ISSUE TITLE
Pretrained POS PerceptronModel offline loading fails on pyspark :  "has no attribute 'annotators'"

### ISSUE THREAD

**Issue by alibell** [JohnSnowLabs/spark-nlp#960]
Pretrained model loading fail on pyspark :  "has no attribute 'annotators'"

## Description
When I attempt to load POS PerceptronModel, pos_ud_gsd_fr_2.0.2_2.4_1556531457346, downloaded from johnsnowlabs website, an AttributeError is returned.

The error code is :

    AttributeError                            Traceback (most recent call last)
    <ipython-input-32-11686b52568d> in <module>
          1 PerceptronModel() \
    ----> 2     .load("file:///export/home/spark-nlp/pos_model/pos_ud_gsd_fr_2.0.2_2.4_1556531457346") \
          3     .setInputCols(["token", "sentence"]) \
          4     .setOutputCol("pos")

    /usr/hdp/current/spark2.4.3-client/python/pyspark/ml/util.py in load(cls, path)
        360     def load(cls, path):
        361         """Reads an ML instance from the input path, a shortcut of `read().load(path)`."""
    --> 362         return cls.read().load(path)
        363 
        364 

    /usr/hdp/current/spark2.4.3-client/python/pyspark/ml/util.py in load(self, path)
        302             raise NotImplementedError("This Java ML type cannot be loaded into Python currently: %r"
        303                                       % self._clazz)
    --> 304         return self._clazz._from_java(java_obj)
        305 
        306     def context(self, sqlContext):

    /usr/hdp/current/spark2.4.3-client/python/pyspark/ml/wrapper.py in _from_java(java_stage)
        225         stage_name = java_stage.getClass().getName().replace("org.apache.spark", "pyspark")
        226         # Generate a default new instance from the stage_name class.
    --> 227         py_type = __get_class(stage_name)
        228         if issubclass(py_type, JavaParams):
        229             # Load information from java_stage to the instance.

    /usr/hdp/current/spark2.4.3-client/python/pyspark/ml/wrapper.py in __get_class(clazz)
        221             m = __import__(module)
        222             for comp in parts[1:]:
    --> 223                 m = getattr(m, comp)
        224             return m
        225         stage_name = java_stage.getClass().getName().replace("org.apache.spark", "pyspark")

    AttributeError: module 'com.johnsnowlabs.nlp' has no attribute 'annotators'

## Expected Behavior
The model should load.

## Current Behavior
The loading fails.

## Steps to Reproduce
1. Download POS PerceptronModel : https://s3.amazonaws.com/auxdata.johnsnowlabs.com/public/models/pos_ud_gsd_fr_2.0.2_2.4_1556531457346.zip
2.Load it with : PerceptronModel().load("file:///export/home/cse190009/spark-nlp/pos_model/toto") from an Pyspark installation

## Your Environment
* Spark NLP version: 2.5.2
* Spark version : 2.4.3
* Pyspark
* Python 3.6
* Java version (java -version): 1.8.0
* Setup and installation (Pypi, Conda, Maven, etc.): conda and --packages com.johnsnowlabs.nlp:spark-nlp_2.11:2.5.2 on my PYSPARK_SUBMIT_ARGS environment variable in kernels.json (jupyterhub)
* Operating System and version: Linux kernel 3.10.0

**Comment by alibell** [comment]
Just upgraded to 2.5.3 and it now works.

**Comment by maziyarpanahi** [comment]
Thanks for the updates.
