### ISSUE TITLE
Unable to load pretrained resources

### ISSUE THREAD

**Issue by pekyntosh** [JohnSnowLabs/spark-nlp#970]
## Description

I have successfully installed PySpark and SparkNLP on my linux box (see specifications below).

I launch pyspark with this command:
`pyspark --packages com.johnsnowlabs.nlp:spark-nlp_2.11:2.5.3`

And I try to execute the following code:

<pre><code>
from sparknlp.base import *
from sparknlp.annotator import *
from sparknlp.pretrained import PretrainedPipeline
import sparknlp

spark = SparkSession.builder\
.master('local[*]')\
.appName('Spark NLP')\
.config('spark.driver.memory', '4G')\
.config('spark.executor.memory', '2G')\
.config('spark.jars.packages', 'JohnSnowLabs:spark-nlp:2.5.3')\
.config('spark.kryoserializer.buffer.max', '600M')\
.getOrCreate()

pipeline = PretrainedPipeline('explain_document_dl', lang='en')
</code></pre>

## Current Behavior
During the execution of the last line of code, I get this error:
<pre><code>                           
Download done! Loading the resource.
[Stage 0:>                                                          (0 + 1) / 1]
[ | ]#                                                                                              
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007f833219eda9, pid=11336, tid=0x00007f83d0a68700
#
# JRE version: OpenJDK Runtime Environment (8.0_262-b10) (build 1.8.0_262-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.262-b10 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtensorflow_framework.so.1+0x744da9]  _GLOBAL__sub_I_loader.cc+0x99
#
# Core dump written. Default location: /vda1/home/pex/core or core.11336
#
# An error report file with more information is saved as:
# /vda1/home/pex/hs_err_pid11336.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
[ / ]ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1159, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 985, in send_command
    response = connection.send_command(command)
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1164, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
[OK!]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pex/anaconda3/envs/sparknlp/lib/python3.6/site-packages/sparknlp/pretrained.py", line 91, in __init__
    self.model = ResourceDownloader().downloadPipeline(name, lang, remote_loc)
  File "/home/pex/anaconda3/envs/sparknlp/lib/python3.6/site-packages/sparknlp/pretrained.py", line 60, in downloadPipeline
    j_obj = _internal._DownloadPipeline(name, language, remote_loc).apply()
  File "/home/pex/anaconda3/envs/sparknlp/lib/python3.6/site-packages/sparknlp/internal.py", line 181, in __init__
    super(_DownloadPipeline, self).__init__("com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline", name, language, remote_loc)
  File "/home/pex/anaconda3/envs/sparknlp/lib/python3.6/site-packages/sparknlp/internal.py", line 129, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "/home/pex/anaconda3/envs/sparknlp/lib/python3.6/site-packages/sparknlp/internal.py", line 139, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "/opt/spark/python/pyspark/ml/wrapper.py", line 67, in _new_java_obj
    return java_obj(*java_args)
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/opt/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 336, in get_return_value
py4j.protocol.Py4JError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadPipeline
</code></pre>

## Context
I'm just trying to run the example in the [Quick Start](https://github.com/JohnSnowLabs/spark-nlp#quick-start) section.

## Your Environment
* Spark NLP version: 2.5.3
* Apache Spark version: 2.4.4
* Java version (java -version): 1.8.0_262
* Setup and installation (Pypi, Conda, Maven, etc.): exactly as suggested in the "Quick install" section

<pre><code>
$ conda create -n sparknlp python=3.6 -y
$ conda activate sparknlp
$ pip install spark-nlp==2.5.3 pyspark==2.4.4
</code></pre>

* Operating System and version: Debian GNU/Linux 10.4 Buster (4.19.0-6-amd64)

**Comment by maziyarpanahi** [comment]
Thanks for reporting this. It seems an issue between TensorFlow and Debian. 

May I ask what else are you adding to your PySpark command and whether or not you installed TensorFlow in your conda environment? (we don't need it and we don't recommend to avoid conflicts)

**Comment by pekyntosh** [comment]
Thanks for your attention.

I've setup the environment on a clean and up to date GNU/Linux Debian Buster o.s.
I got the last version of Anaconda and I didn't install TensorFlow in my conda environment. 
Through the command line I invoke pyspark as:
`pyspark --packages com.johnsnowlabs.nlp:spark-nlp_2.11:2.5.3`

I've tested also Java version 1.8.0_252 and Apache Spark 2.4.6, but the behavior is exactly the same.

Ask me if you need more information or you need to do further tests on my environment.

Thank you!
