### ISSUE TITLE
Tensorflow Error - Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.

### ISSUE THREAD

**Issue by TiGaI** [JohnSnowLabs/spark-nlp#994]
## Description

![image](https://user-images.githubusercontent.com/22779825/89333627-3e16a800-d663-11ea-8085-74cd7cc54df7.png)

`---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
~\Anaconda3\envs\sparknlp\lib\pyspark\sql\utils.py in deco(*a, **kw)
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:

~\Anaconda3\envs\sparknlp\lib\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:

Py4JJavaError: An error occurred while calling o49.load.
: java.lang.IllegalArgumentException: NodeDef mentions attr 'incompatible_shape_error' not in Op<name=Equal; signature=x:T, y:T -> z:bool; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_UINT8, ..., DT_QINT8, DT_QINT32, DT_STRING, DT_BOOL, DT_COMPLEX128]; is_commutative=true>; NodeDef: {{node accuracy/Equal}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	at org.tensorflow.Graph.importGraphDef(Native Method)
	at org.tensorflow.Graph.importGraphDef(Graph.java:131)
	at org.tensorflow.Graph.importGraphDef(Graph.java:115)
	at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.readGraph(TensorflowWrapper.scala:209)
	at com.johnsnowlabs.ml.tensorflow.TensorflowWrapper$.readChkPoints(TensorflowWrapper.scala:384)
	at com.johnsnowlabs.ml.tensorflow.ReadTensorflowModel$class.readTensorflowChkPoints(TensorflowSerializeModel.scala:128)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.SentimentDLModel$.readTensorflowChkPoints(SentimentDLModel.scala:157)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.ReadSentimentDLTensorflowModel$class.readTensorflow(SentimentDLModel.scala:147)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.SentimentDLModel$.readTensorflow(SentimentDLModel.scala:157)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.ReadSentimentDLTensorflowModel$$anonfun$4.apply(SentimentDLModel.scala:154)
	at com.johnsnowlabs.nlp.annotators.classifier.dl.ReadSentimentDLTensorflowModel$$anonfun$4.apply(SentimentDLModel.scala:154)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:31)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead$1.apply(ParamsAndFeaturesReadable.scala:30)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$class.com$johnsnowlabs$nlp$ParamsAndFeaturesReadable$$onRead(ParamsAndFeaturesReadable.scala:30)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.ParamsAndFeaturesReadable$$anonfun$read$1.apply(ParamsAndFeaturesReadable.scala:41)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:19)
	at com.johnsnowlabs.nlp.FeaturesReader.load(ParamsAndFeaturesReadable.scala:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

During handling of the above exception, another exception occurred:

IllegalArgumentException                  Traceback (most recent call last)
<ipython-input-2-0e17e77cef8d> in <module>
----> 1 ner = SentimentDLModel.load("sentimentdl_use_twitter_en_2.5.0_2.4_1589108892106")

~\Anaconda3\envs\sparknlp\lib\pyspark\ml\util.py in load(cls, path)
    360     def load(cls, path):
    361         """Reads an ML instance from the input path, a shortcut of `read().load(path)`."""
--> 362         return cls.read().load(path)
    363 
    364 

~\Anaconda3\envs\sparknlp\lib\pyspark\ml\util.py in load(self, path)
    298         if not isinstance(path, basestring):
    299             raise TypeError("path should be a basestring, got type %s" % type(path))
--> 300         java_obj = self._jread.load(path)
    301         if not hasattr(self._clazz, "_from_java"):
    302             raise NotImplementedError("This Java ML type cannot be loaded into Python currently: %r"

~\Anaconda3\envs\sparknlp\lib\py4j\java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

~\Anaconda3\envs\sparknlp\lib\pyspark\sql\utils.py in deco(*a, **kw)
     77                 raise QueryExecutionException(s.split(': ', 1)[1], stackTrace)
     78             if s.startswith('java.lang.IllegalArgumentException: '):
---> 79                 raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
     80             raise
     81     return deco

IllegalArgumentException: "NodeDef mentions attr 'incompatible_shape_error' not in Op<name=Equal; signature=x:T, y:T -> z:bool; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_UINT8, ..., DT_QINT8, DT_QINT32, DT_STRING, DT_BOOL, DT_COMPLEX128]; is_commutative=true>; NodeDef: {{node accuracy/Equal}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.)."`

## Expected Behavior

I try it the online version and the offline version. Both of them give me the same errors. I can download pipeline and use those no problem.

## Steps to Reproduce

1. New environment in window 10, create new conda enviroment
2. Open a spark sections
3. Load the model
4. Error occurs

## Context

Just trying to load the perbuilt model, but the error keep happening.

## Your Environment

* Spark NLP version: 2.5.5
* Apache Spark version: 2.4.6
* Java version (java -version): 1.8.0_251
* Setup and installation (Pypi, Conda, Maven, etc.): conda install
* Operating System and version: window 10
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
Thanks, we'll test this on Windows 10 to reproduce it.

**Comment by TiGaI** [comment]
Keep me updated. It works on Mac OS. So it may be a window issue.

**Comment by TiGaI** [comment]
Any progress? It is definitely a window issue. Linux and Mac OS work using the exact same step.

**Comment by maziyarpanahi** [comment]
I have tested this on Windows 8 Pro, could you please make sure you have followed the steps from here: https://github.com/JohnSnowLabs/spark-nlp/issues/982#issuecomment-670033754

Just to be sure you have the requirements in a Windows environment. But I was planning to install Windows 10 and reproduce this there as well later today/tomorrow.

**Comment by TiGaI** [comment]
I have no problem with PipelineModel.load with explain_document_ml_en_2.4.0_2.4_1580252705962.

![image](https://user-images.githubusercontent.com/22779825/90057413-5cf1eb80-dcae-11ea-9107-19ea4116fb02.png)

The problem arrived when I try to use SentimentDLModel.

Py4JJavaError: An error occurred while calling o444.load.
: java.lang.IllegalArgumentException: NodeDef mentions attr 'incompatible_shape_error' not in Op<name=Equal; signature=x:T, y:T -> z:bool; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_UINT8, ..., DT_QINT8, DT_QINT32, DT_STRING, DT_BOOL, DT_COMPLEX128]; is_commutative=true>; NodeDef: {{node accuracy/Equal}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

**Comment by TiGaI** [comment]
My spark works on most of the functionality. Of course, I can't use the directly download, but I can download the pipeline and load it in, no problem.

Hey Maziyarpanahi,

I am not sure about window 8 PRO, but I follow your step one by one in window 10.
![image](https://user-images.githubusercontent.com/22779825/90053405-7132ea00-dca8-11ea-86bb-148a1ea717d7.png)
![image](https://user-images.githubusercontent.com/22779825/90053558-accdb400-dca8-11ea-9ed9-e6ff390b5a5a.png)
![image](https://user-images.githubusercontent.com/22779825/90053595-b9eaa300-dca8-11ea-810d-b6a34ef98ba2.png)
![image](https://user-images.githubusercontent.com/22779825/90053629-c3740b00-dca8-11ea-9f32-7a2595c19566.png)
![image](https://user-images.githubusercontent.com/22779825/90053754-eacad800-dca8-11ea-866b-6d54c62a923a.png)
![image](https://user-images.githubusercontent.com/22779825/90053883-15b52c00-dca9-11ea-9fc9-48b9fb4af913.png)


But when I load this it gives me the same exact error. Now it is saying a little more.
Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.downloadModel.
: java.lang.UnsupportedOperationException: Spark NLP tried to load a TensorFlow Graph using Contrib module, but failed to load it on this system. If you are on Windows, this operation is not supported. Please try a noncontrib model. If not the case, please report this issue. Original error message:

![image](https://user-images.githubusercontent.com/22779825/90053330-506a9480-dca8-11ea-9a00-cde09bf2ee52.png)

![image](https://user-images.githubusercontent.com/22779825/90053286-4052b500-dca8-11ea-9835-8906eca91e09.png)

**Comment by maziyarpanahi** [comment]
Thanks, a couple of things:

- explain_document_ml has no TensorFlow so it's normal to work
- explain_document_dl has TF so that should fail
- The fact that you cannot download the model means you haven't set up the Apache Spark/Hadoop env correctly. Otherwise, it will download with no problem and one of the things that can cause this is `Microsoft Visual C++` and maybe it is a different version for Windows 10
- Windows don't like having spark under sub-directory. So if you can put your Spark at the root like Hadoop would be better

I am installing Windows 10 and setting the envs right now, so I'll keep you updated today for all this

**Comment by maziyarpanahi** [comment]
OK, this is definitely a bug in TensorFlow supporting Windows 10, not just one model, all the TF related models.

To solve the pretrained, you need the followings:

- Create a C:\temp
- Create a C:\temp\hive
- C:\Users\maz>%HADOOP_HOME%\bin\winutils.exe chmod 777 /tmp/hive
- C:\Users\maz>%HADOOP_HOME%\bin\winutils.exe chmod 777 /tmp/
- have this installed: https://www.microsoft.com/en-us/download/confirmation.aspx?id=14632

This won't solve the TF issue but allows you to use pretrained() without any issue if other params are set correctly.

**Comment by maziyarpanahi** [comment]
@albertoandreottiATgmail The error is `java.lang.NoClassDefFoundError: Could not initialize class org.tensorflow.Graph` which is mentioned here (you can see me also reporting it): https://github.com/tensorflow/tensorflow/issues/30635

This file is supposed to fix that: https://github.com/JohnSnowLabs/spark-nlp/tree/master/src/main/scala/org/tensorflow

Given this works in Windows 8, you think there is another way of overriding this for Windows 10? (or maybe Windows doesn't need it at all)

**Comment by maziyarpanahi** [comment]
This is a great news. Happy it worked out st the end. 
It's a minor warning from TF regarding your CPU having some features not included in the main TF build which is totally fine.

**Comment by TiGaI** [comment]
Thanks!
